### ISSUE TITLE
Cleanup unused Account#isNotifiedForInvoices field

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1003]
As part of #58 we have removed the core functionality inside killbill core, and this has been ported to [email notification plugin](https://github.com/killbill/killbill-email-notifications-plugin/issues/8).

However, the Account ddl and the account models still export this field. The work is to remove it and update dependencies:
* In killbill core, remove any reference to this field
* Regenerate client libraries --  java, python and manually fix ruby
* Update KAUI
* Update slate documentation

**Comment by karser** [comment]
This field hasn't been removed from the php client, here is the issue https://github.com/killbill/killbill-client-php/issues/34

Also there are all search occurrences: https://github.com/search?p=1&q=org%3Akillbill+isNotifiedForInvoices&type=Code
