### ISSUE TITLE
Fix non deterministic test TestEntitlement#testCreateEntitlementsWithAddOnsThenCloseAccountWithItemAdjustment

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1027]
Our `circle-ci` build fails on postresql because of `TestEntitlement#testCreateEntitlementsWithAddOnsThenCloseAccountWithItemAdjustment`. After investigation, the issue is that depending on how events occur, we may or not get the `INVOICE_PAYMENT_FAILED` event. Since we are passing the flag to `itemAdjustUnpaidInvoices`, this operation is competing with the creation of the new invoice (we have moved the clock by one day):

- If we are lucky and the generation of the new invoice was done after we already adjusted the existing unpaid invoice, we are left with a new unpaid invoice, and we attempt to make a payment but because there is no default payment method, this fails and we get `INVOICE_PAYMENT_FAILED`
- If we are not lucky, the generation of the new invoice was done early and we end up adjusting all items for both invoices and we see a message `invoiceId='e2c511a1-405b-4905-8916-19b4967275b8' has already been paid`, and don't get a `INVOICE_PAYMENT_FAILED` event

**Comment by pierre** [comment]
Let's chat - I'm confused why a new invoice is being generated in that scenario.
