### ISSUE TITLE
Invoice, email encoding

### ISSUE THREAD

**Issue by tabbi89** [killbill/killbill#1035]
KillBill 0.20

I have created account with PL na pl_PL language. Added translations for this language to emails and invoices but the result is that:

Do zapÅ‚aty - it should be Do zapłaty.

Non of polish signs are encoded properly in invoices and in emails. In invoices I have even added proper charset:

```
<!DOCTYPE html>
<html lang="pl-PL">
    <head>
        <style type="text/css">
            th {align=left; width=225px; border-bottom: solid 2px black;}
        </style>
        <meta charset="UTF-8">
    </head>
```

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by tabbi89** [comment]
all utf8 signs are converted to ASCII it's not an implementation issue. I'm using killbill/killbill:0.20.1
