### ISSUE TITLE
Api: missing amount when call invoices/pagination 

### ISSUE THREAD

**Issue by developeruz** [killbill/killbill#1048]
When call `GET http://127.0.0.1:8080/1.0/kb/invoices/pagination` [even in documentation](https://killbill.github.io/slate/?shell#invoice-pagination-search) all amount fileds are always 0 (amount, creditAdj, refundAdj etc). Could you please fix that and make API return real amount fields?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
