### ISSUE TITLE
Billing Accounts / Sub Accounts

### ISSUE THREAD

**Issue by martinwesthead** [killbill/killbill#105]
Basic requirement

This is a new feature to meet the billing requirements of large corporations. Suppose we have a service provider Foo and a customer of theirs Bar. Bar is a big company with many departments. Departments A, B and C in Bar decide to purchase subscriptions from Foo. The finance team at Bar now receive multiple invoices every month from Foo. In order to simplify their operations Foo asks Bar to bill all the subscriptions on a single invoice, but the individual departments still want their separate, independent views of their subscriptions, upgrades, downgrades etc.

To meet this need we add a new account X that belongs to the Finance team at Foo. The accounts A B and C reference X as their "Billing account" and all the subscriptions on accounts A, B and C are rolled up and invoiced together on X.

Transitions

Note that A, B and C may have invoices and payments already associated with them. To handle the we propose adding an end-stop billing event. Once this has been inserted into the subscription (must be inserted at the CTD) all billing that has occurred before this is ignored. In this way A, B and C will continue to be responsible for payments against anything that has already been billed but X will be responsible for bills moving forward.

The inverse transition should also be possible A, B and C can return to do their own billing in which case another end-stop is added at the current CTD. In this case X is responsible for things billed to it and A, B and C are responsible for things billed after that.

Funds transfer

In order to make the transitions manageable with these hard billing stops it should be possible to move credit from the parent to the children and visa versa. 

Discussion

Accounts which have a parents should not be allowed to engage in any activities that involve the creation or modification of invoices. Payments, refunds and chargebacks against existing invoices are still possible 

Overdue enforcement should probably be modified to consider X overdue in the event that any of A, B or C are overdue and to cancel subscriptions on A, B and C if subscriptions need to be cancelled on X.

**Comment by pierre** [comment]
See related https://github.com/killbill/killbill/issues/339.
