### ISSUE TITLE
Running multiple instances of Kill Bill

### ISSUE THREAD

**Issue by eladtamary** [killbill/killbill#1051]
Hi, 
I read this user guide deployment document: http://docs.killbill.io/0.20/userguide_deployment.html
It states that is it recommended to run multiple instances in front of a load-balancer.  
Is there any special configuration needed to run Kill Bill in HA mode? 
Is it enough to run multiple instances and connect them to the same DB?

Thanks,
Elad

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
