### ISSUE TITLE
Janitor UNKNOWN transition may not correctly update invoice balance

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1061]
The issue was reported on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/janitor%7Csort:date/killbilling-users/w1YNtBJ7Vxo/yf9GSTF7CAAJ).

By reading the code it looks like this may be a bug but this requires more investigation.

**Comment by sbrossie** [comment]
Also, what seems like another issue related to Janitor not making transition through state machines [mailing list thread](https://groups.google.com/forum/#!topic/killbilling-users/Z4FEkZymPzk)

**Comment by sbrossie** [comment]
For this original issue, it looks like we should keep the `attemptId` -- if any in the notification -- and when processing the notification, if such  `attemptId` exists, recreate a new attempt, therefore calling the various control plugins.

**Comment by meden** [comment]
I can confirm this behavior: when transitioning from `UNKNOWN` to `SUCCESS` the invoice balance is not updated. I managed to nail it down to this patch (against 0.20.10, needs to be rebased):
```
Index: payment/src/main/java/org/killbill/billing/payment/api/DefaultAdminPaymentApi.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- payment/src/main/java/org/killbill/billing/payment/api/DefaultAdminPaymentApi.java	(date 1554364168000)
+++ payment/src/main/java/org/killbill/billing/payment/api/DefaultAdminPaymentApi.java	(date 1562332274224)
@@ -17,6 +17,7 @@
 
 package org.killbill.billing.payment.api;
 
+import java.math.BigDecimal;
 import java.util.List;
 
 import javax.annotation.Nullable;
@@ -116,7 +117,7 @@
                                                            lastSuccessPaymentState,
                                                            paymentTransaction.getId(),
                                                            transactionStatus,
-                                                           paymentTransaction.getProcessedAmount(),
+                                                           paymentSMHelper.isSuccessState(currentPaymentStateName) ? paymentTransaction.getAmount() : BigDecimal.ZERO,
                                                            paymentTransaction.getProcessedCurrency(),
                                                            paymentTransaction.getGatewayErrorCode(),
                                                            paymentTransaction.getGatewayErrorMsg(),

```
I was willing to make a PR, but I had no tests ready (nor I checked the existing ones :disappointed:), so I was quite sure the PR would have been rejected.

**Comment by pierre** [comment]
I've submitted https://github.com/killbill/killbill/pull/1216 to fix the original issue. The second report is tracked by #880.

@meden Your issue is actually unrelated to this bug. In your case, the invoice balance can indeed be incorrect either when calling the `DefaultAdminPaymentApi` via our JAX-RS endpoint or when calling this API from a poorly implemented payment plugin.

In any case, I've submitted a patch to fix this in https://github.com/killbill/killbill/pull/1216 -- could you verify it solves your use-case?

If it doesn't, please reach out to the mailing-list with details on how to reproduce it and I'll open a separate bug if the issue is still there. Thanks!
