### ISSUE TITLE
UK: Making Tax Digital for VAT

### ISSUE THREAD

**Issue by chriscroome** [killbill/killbill#1062]
Are any Kill Bill users or developers looking at or interested in looking at the work that would be necessary to make Kill Bill suitable for use in the UK for VAT registered organisations?

From 1st April 2019 organisations that are VAT registered in the UK will have to comply with new rules for *"Making Tax Digital"*:

>  The regulations will provide that a business is in scope for MTD must use functional compatible software to meet the new requirements.
>
> Functional compatible software means a software program or set of compatible software programs which can connect to HMRC systems via an Application Programming Interface (API). The functions of the compatible software must include:
>
> * keeping records in a digital form as required by the regulations
> * preserving digital records in a digital form as required by the regulations
> * creating a VAT return from the digital records held in functional compatible software and providing HMRC with this information digitally
> * providing HMRC with VAT data on a voluntary basis
> * receiving information from HMRC via the API platform in relation to a relevant entity’s compliance with obligations under the regulations
>
> https://www.gov.uk/government/consultations/making-tax-digital-reforms-affecting-businesses/making-tax-digital-for-vat-legislation-overview

**Comment by pierre** [comment]
Let's use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead to discuss this. We can open tickets when requirements are more defined.

**Comment by chriscroome** [comment]
Thanks, that sounds sensible, we are currently looking at using [https://erpnext.com/ ERPNext], so I don't expect to be raising this issue on the list.
