### ISSUE TITLE
Option to disable auth

### ISSUE THREAD

**Issue by aaabramov** [killbill/killbill#1079]
Today we found out that default value for hash iteration count is 200000 https://github.com/killbill/killbill/blob/499a2d39278decc42f27a8d5dac43890f15126a5/util/src/main/java/org/killbill/billing/util/config/definition/SecurityConfig.java#L33-L35

Is there any reason to keep this value so high? As I understand, Shiro recommends to set this value to 1024.
Because making 200000 iterations of Sha-512 is overhead as for me.

Because we are using KilllBill as a service in our "microservice world", we don't need such protection in our case, KillBill is only available to VPC. 

Any advices how to properly downgrade this value? The only option to properly decrease iteration count is to:
- shutdown (downtime)
- set iterations count to N
- up
- create new tenant
- update old tenant with new api_secret, api_salt.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

See also http://docs.killbill.io/0.20/debugging.html#_tips_and_tricks.

**Comment by aaabramov** [comment]
@pierre done, sorry.
https://groups.google.com/forum/#!topic/killbilling-users/TkpE5sW8uug
