### ISSUE TITLE
Non decimal currency

### ISSUE THREAD

**Issue by agenteDserrano** [killbill/killbill#1080]
Hello team. I need to use CLP currency that dont have decimals.

I try to use but killbill add 2 zeros to al charges. For example if my price is 1 when I see the invoice the price is 100. 

I attach screen shoots

![screenshot_54](https://user-images.githubusercontent.com/2618188/50045008-db763000-006a-11e9-8b10-8fb9ff0ca3b3.png)
![screenshot_53](https://user-images.githubusercontent.com/2618188/50045009-dc0ec680-006a-11e9-8e27-271f3d294c74.png)
![screenshot_52](https://user-images.githubusercontent.com/2618188/50045010-dc0ec680-006a-11e9-829e-6b00a24e07f0.png)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by agenteDserrano** [comment]
> Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

Hello Pierre. Sorry I was think this is a bug.

I have publish this issue on mail list already.
