### ISSUE TITLE
Ability to control whether payment should be retried or not

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1107]
Today our payment (& invoice payment) apis are wired to [disable automatic retries upon failure](https://github.com/killbill/killbill/blob/killbill-0.20.6/payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java#L60) -- i.e we only allow automatic retry when coming from [recurring path](https://github.com/killbill/killbill/blob/killbill-0.20.6/payment/src/main/java/org/killbill/billing/payment/bus/PaymentBusEventHandler.java#L92).

The goal, would be to make it more flexible by allowing caller to specify whether configuration-based retries should be allowed.

**Comment by pierre** [comment]
We've decided we won't support this for now.

If one drives the payment process using our APIs, one can detect failures and schedule future retries as needed (using a custom notification queue in a plugin for instance).
