### ISSUE TITLE
Noisy PaymentRefresher logs for external payments

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1111]
In `PaymentRefresher`, we log when we cannot find the `PaymentTransactionInfoPlugin` for a given `PaymentTransactionModelDao`. This is usually useful to detect misbehaving or mis-implemented plugins.

See https://github.com/killbill/killbill/blob/c26dd4d8c395a3ad89ff27512ee2567aa67feb31/payment/src/main/java/org/killbill/billing/payment/core/PaymentRefresher.java#L140

Unfortunately, this is quite noisy for the (built-in) external payment plugin as it never has the information.

See https://github.com/killbill/killbill/blob/c26dd4d8c395a3ad89ff27512ee2567aa67feb31/payment/src/main/java/org/killbill/billing/payment/provider/ExternalPaymentProviderPlugin.java#L92-L94

**Comment by sbrossie** [comment]
@pierre Is the goal of the task to just move the log line from `warn` to `info` ?


Another more involved solution would be to check if this is the external payment and not print such warn in this case; however this info is not available inside the janitor and requires a little bit of code change.

**Comment by pierre** [comment]
Even if we switch to the `info` level, this is still going to pollute the logs.

Alternatively, we switch to `debug`: the idea for this log line is to ensure plugins are correctly implemented. Plugin implementors could change the log level for this class if needed.
