### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/sql/DataSource

### ISSUE THREAD

**Issue by durmusdeniz** [killbill/killbill#1114]
I am trying to build the code, but getting java.lang.NoClassDefFoundError: javax/sql/DataSource exceptions on tests for killbill-util module. 
Is there any specific version of java I am supposed to use or a different way of building rather than mvn package or install ?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
