### ISSUE TITLE
Custom currency support

### ISSUE THREAD

**Issue by chendo** [killbill/killbill#1121]
We would like to add a custom currency to track a credit/token system that our users can obtain through various means that they can also use to pay for subscriptions. Initial research shows we'd need to modify https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/Currency.java and rebuild but I was hoping there is an easier way.

Alternatively, we were going to look at using hierarchical accounts to track this.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
