### ISSUE TITLE
Error on docker-compose up (killbill container)

### ISSUE THREAD

**Issue by exexzian** [killbill/killbill#1129]
I am getting below error on running docker-compose up

> 
> killbill_1  | PLAY [Deploy Kill Bill] ********************************************************
> killbill_1  |
> killbill_1  | TASK [Gathering Facts] *********************************************************
> killbill_1  | task path: /var/lib/tomcat/.ansible/roles/killbill-cloud/ansible/killbill.yml:2
> killbill_1  | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
> killbill_1  | fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
> killbill_1  |   to retry, use: --limit @/var/lib/tomcat/.ansible/roles/killbill-cloud/ansible/killbill.retry
> killbill_1  |
> killbill_1  | PLAY RECAP *********************************************************************
> killbill_1  | localhost                  : ok=0    changed=0    unreachable=0    failed=1
> killbill_1  |
> killbill_killbill_1 exited with code 2

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
