### ISSUE TITLE
startDate query param from api to fetch invoices is confusing

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1134]
See [email thread](https://groups.google.com/forum/#!topic/killbilling-users/57QwW26DaNg) for the report.

Basically we use the same JARXS query param to mean 2 different things in two apis:
* Invoice#getInvoicesByAccount(.., **startDate**,..)
* Invoice#getUnpaidInvoicesByAccountId(..., **upToDate***,...)

**Comment by pierre** [comment]
Sounds good - we should also make sure Slate is updated.
