### ISSUE TITLE
[QUESTION][HELP] Invoices not shown inside dashboard and api

### ISSUE THREAD

**Issue by aresares** [killbill/killbill#1137]
Hi I'm having some troubles on visualizzing invoices.
I followed all the steps about creating a user account and setted an external payment .
After that I insert an invoice calling this endpoint which give me a 201
_**.../1.0/kb/invoices/migration/{accountId}**_ 

When I go to the dashboard of that specific account under invoices menu I cant see the invoice. I tried also calling this endpoint
_**/1.0/kb/accounts/{accountId}/invoicePayments**_ but nothing change, the invoice is not shown.

Any idea about this or any tutoria on how to create and pay an invoice?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
