### ISSUE TITLE
Add description column in invoice_items

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#114]
We currently add a hard-coded description on the fly to `InvoiceItem`. We should also allow the user to store a real value and use it in the `insertExternalCharge` call.

This would get rid of stacktraces, like:
```
com.ning.billing.catalog.api.CatalogApiException: Could not find any plans named 'Migration charge'
	at com.ning.billing.catalog.StandaloneCatalog.findCurrentPlan(StandaloneCatalog.java:180)
	at com.ning.billing.catalog.VersionedCatalog.findPlan(VersionedCatalog.java:222)
```

**Comment by sbrossie** [comment]
Is that related to #86?

**Comment by sbrossie** [comment]
I believe this has already been fixed: The api is not `insertExternalCharges` and takes a list of `InvoiceItem` and the code extract the description field for each of those.
