### ISSUE TITLE
[FAQ] Integration with Fineract/Mifos

### ISSUE THREAD

**Issue by kirantpatil** [killbill/killbill#1147]
Hello,

I would like to know does it provide any kind of integration with [Fineract/Mifos](https://cwiki.apache.org/confluence/display/FINERACT/Fineract+CN) ?

Thanks,
Kiran.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by kirantpatil** [comment]
Thanks @pierre.
