### ISSUE TITLE
Subscription does not have externalKey

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1157]
Most of our models have an externalKey allowing for passing external ID and also enforcing the idempotency of the requests.

**Comment by sbrossie** [comment]
@pierre Currently the the subscription already exports an `externalKey` but this is [computed from using the one from the bundle](https://github.com/killbill/killbill/blob/killbill-0.21.2/entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java#L140)

**Comment by pierre** [comment]
> @pierre Currently the the subscription already exports an `externalKey` but this is [computed from using the one from the bundle](https://github.com/killbill/killbill/blob/killbill-0.21.2/entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java#L140)

This is `getBundleExternalKey()` though, not `getSubscriptionExternalKey()`?

**Comment by sbrossie** [comment]
@pierre Unfortunately no -- but my link was perhaps not clear. The `EventsStream#getBundleExternalKey` is then called [here]( https://github.com/killbill/killbill/blob/killbill-0.21.2/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java#L238)
