### ISSUE TITLE
Kill bill docker installation stuck

### ISSUE THREAD

**Issue by anuragpathak21** [killbill/killbill#1172]
Kill bill docker installation stuck with error:
Aborted connection 10 to db: 'killbill' user: 'root' host: '172.19.0.3' (Got timeout reading communication packets)

**docker-compose file**

![image](https://user-images.githubusercontent.com/50142570/61850882-bac36200-aef8-11e9-92d9-1e835ea6462f.png)

**Error during docker-compose up**

![image](https://user-images.githubusercontent.com/50142570/61850702-42f53780-aef8-11e9-864b-5363407b91e4.png)

**Comment by sbrossie** [comment]
Not sure how to help here, your log shows almost nothing.. Is your DB
container running? Can you access it?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
