### ISSUE TITLE
Invoice formatter display wrong currency symbol

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#118]
First of all, the code is using the locale to set the currency formatter. For instance in 
DefaultInvoiceFormatter:

```
 public String getFormattedPaidAmount() {
        final NumberFormat number = NumberFormat.getCurrencyInstance(locale);
        return number.format(getPaidAmount().doubleValue());
 }
```

The number format returned is based on the locale which is 'good' so it knows how to display the dots, comma, ... but wrong it comes to display the currency symbol.

**Comment by vp-maguero** [comment]
Supposing a Locale.FRANCE locale and a USD currency, do you want to keep the France number format but replacing the currency code by the one selected by customer?

```
// Locale.FRANCE & Currency.EUR
<td class="amount"><strong>1 499,95 €</strong></td>
```
```
// Locale.FRANCE & Currency.USD
<td class="amount"><strong>1 499,95 $</strong></td>
```

**Comment by pierre** [comment]
> Supposing a Locale.FRANCE locale and a USD currency, do you want to keep the France number format but replacing the currency code by the invoice currency?

Yes ([this](http://stackoverflow.com/questions/7828364/formatting-currencies-in-foreign-locales-in-java) might help).

We should also add more tests to cover various use-cases (see examples [here](https://msdn.microsoft.com/en-us/goglobal/bb688126.aspx) and [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)).

**Comment by vp-maguero** [comment]
Good. Yes, that's how I tried.

It seems that when tries to use a different currency that the Locale has, the format prints the letters instead of the symbol.

Example:
// Locale.US & Currency.USD
**$**1,499.95
// Locale.US & Currency.EUR
**EUR**1,499.95

// Locale.FRANCE & Currency.EUR
1 499,95 **€**
// Locale.FRANCE & Currency.USD
1 499,95 **USD**

Is it the expected behaviour?

**Comment by pierre** [comment]
> Is it the expected behaviour?

It seems [that way](http://stackoverflow.com/questions/15106484/not-getting-currency-symbols-for-specific-locale), to avoid confusions (e.g. `$` can be ambiguous depending on the country).

**Comment by vp-maguero** [comment]
Thanks. This is done.

Do you want to check the commit before I create the pull request? (https://github.com/vp-maguero/killbill/commit/b764b9c60cf24e575adbfc99e7935097dc0c83f9)

**Comment by pierre** [comment]
> Do you want to check the commit before I create the pull request?

Actually, create the pull request and we can comment over there (it's easier for others to follow and jump-in).

**Comment by vp-maguero** [comment]
Done. https://github.com/killbill/killbill/pull/405
