### ISSUE TITLE
NullPointerException on InvoicePluginApi

### ISSUE THREAD

**Issue by hendryluk** [killbill/killbill#1182]
According to the documentation (https://docs.killbill.io/0.20/invoice_plugin.html):

> When returning InvoiceItem objects back to Kill Bill, it is recommended to set the id value to null.

But when you do that, you'll get a NullPointerException on this line: https://github.com/killbill/killbill/blob/e30cdaef205ac51340217679e70dd9d17eb4ae6b/invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java#L217

Perhaps should be replaced with `Objects.equals(originalInvoiceItem.getId(), additionalInvoiceItem.getId())`, which is generally always the safe thing to do anyway?

**Comment by sbrossie** [comment]
@hendryluk I don't really understand why you get an NPE. 

The `UUID#equals` method is defined as -- or maybe this JVM dependent?

```

public final class UUID {
....
 public boolean equals(Object obj) {
        if ((null == obj) || (obj.getClass() != UUID.class))
            return false;
        UUID id = (UUID)obj;
        return (mostSigBits == id.mostSigBits &&
                leastSigBits == id.leastSigBits);
    }
```

-> Which means that `return originalInvoiceItem.getId().equals(additionalInvoiceItem.getId());` should return false.

**Comment by sbrossie** [comment]
@hendryluk Also, in the future please report issues on the mailing list instead of filing GH issues.

**Comment by hendryluk** [comment]
The NPE is because `originalInvoiceItem.getId()` returns null. Somehow the additionalInvoiceItem gets added to that list.

Steps to reproduce:
- write a plugin that returns an additionalInvoiceItem with a null id
- generate an invoice, e.g. dry-run
You'll get an NPE.
