### ISSUE TITLE
subscription: add effective date check on cancellation

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#119]
Make sure we can't specify a cancel date that is prior to the create event.

**Comment by jgomez-vp** [comment]
Created a Pull Request to confirm and close this ticket:
https://github.com/killbill/killbill/pull/403

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill/commit/72f559f30384ab0e492e2d0aa37c257c677f8743 and https://github.com/killbill/killbill/pull/403.
