### ISSUE TITLE
throw errors when trigger add credit and click confirm under account page

### ISSUE THREAD

**Issue by yifanyou** [killbill/killbill#1194]
below is errors:
Error while communicating with the Kill Bill server: Error 400: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 1, column: 1]

**Comment by yifanyou** [comment]
killbill version 0.21.3~4
kaui version 1.0.6

**Comment by pierre** [comment]
We do not provide community support for Kill Bill version 0.21.x.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
