### ISSUE TITLE
throw errors when open install new plugins page

### ISSUE THREAD

**Issue by yifanyou** [killbill/killbill#1195]
below is errors:
2019-08-26T11:36:14,494+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-16', xff='', rId='431e8de3-e4ae-483d-878d-53c4cae26221', tok='c773d1eb-7060-436c-b963-9d0cd3b17db9', aRId='', tRId='2', NoMethodError - private method `load' called for YAML:Module:
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/kpm-0.6.5/lib/kpm/plugins_directory.rb:10:in `all'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/plugins_installer.rb:64:in `all'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/application.rb:18:in `HEAD /plugins/killbill-kpm/plugins'
	org/jruby/RubyMethod.java:116:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1293:in `compile!'
	org/jruby/RubyProc.java:281:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:876:in `route_eval'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:897:in `process_route'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:895:in `process_route'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:859:in `route!'
	org/jruby/RubyArray.java:1613:in `each'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:858:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:963:in `dispatch!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:960:in `dispatch!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `call!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `call!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:780:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/logger.rb:15:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/commonlogger.rb:33:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:161:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:154:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:124:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/killbill-9.4.0/lib/killbill/http_servlet.rb:117:in `rack_service'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/killbill-9.4.0/lib/killbill/http_servlet.rb:65:in `service'
2019-08-26T11:36:14,500+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-16', xff='', rId='431e8de3-e4ae-483d-878d-53c4cae26221', tok='c773d1eb-7060-436c-b963-9d0cd3b17db9', aRId='', tRId='2', - - - [26/Aug/2019:11:36:14 +0000] "GET /plugins/killbill-kpm/plugins?latest=true " 500 30 0.8500

2019-08-26T11:36:14,515+0000 lvl='WARN', log='PluginResource', th='catalina-exec-2', xff='', rId='431e8de3-e4ae-483d-878d-53c4cae26221', tok='c773d1eb-7060-436c-b963-9d0cd3b17db9', aRId='', tRId='2', /plugins/killbill-kpm/plugins responded 500
2019-08-26T11:36:14,515+0000 lvl='INFO', log='LoggingFilter', th='catalina-exec-2', xff='', rId='431e8de3-e4ae-483d-878d-53c4cae26221', tok='c773d1eb-7060-436c-b963-9d0cd3b17db9', aRId='', tRId='2', 475 * Server out-bound response
475 < 500
475 < Content-Type: application/json
475 < 

2019-08-26T11:36:14,721+0000 lvl='INFO', log='LoggingFilter', th='catalina-exec-3', xff='', rId='2eef0933-d668-4e1c-9c45-c659bb5266d0', tok='8be072c5-4e4f-4861-85e7-7dadbcdd8ee5', aRId='', tRId='2', 479 * Server in-bound request
479 > GET http://killbill-svc.77-bill-dev.svc:8080/plugins/killbill-kpm/plugins?latest=false
479 > accept: application/json
479 > user-agent: killbill/2.5.0; jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.191-b12 on 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12 +jit [linux-x86_64]
479 > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
479 > x-killbill-apikey: test
479 > x-killbill-apisecret: ****
479 > cookie: JSESSIONID=903046c1-2fdc-43dd-a339-e80e9fe09182
479 > host: killbill-svc.77-bill-dev.svc:8080
479 > 

2019-08-26T11:36:14,729+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-16', xff='', rId='2eef0933-d668-4e1c-9c45-c659bb5266d0', tok='8be072c5-4e4f-4861-85e7-7dadbcdd8ee5', aRId='', tRId='2', NoMethodError - undefined method `load_file' for YAML:Module:
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/kpm-0.6.5/lib/kpm/plugins_directory.rb:13:in `all'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/plugins_installer.rb:64:in `all'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/application.rb:18:in `HEAD /plugins/killbill-kpm/plugins'
	org/jruby/RubyMethod.java:116:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1293:in `compile!'
	org/jruby/RubyProc.java:281:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:876:in `route_eval'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:897:in `process_route'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:895:in `process_route'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:859:in `route!'
	org/jruby/RubyArray.java:1613:in `each'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:858:in `route!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:963:in `dispatch!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:960:in `dispatch!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `call!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	org/jruby/RubyKernel.java:1242:in `catch'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `call!'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:780:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/logger.rb:15:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/commonlogger.rb:33:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:161:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:154:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:124:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/killbill-9.4.0/lib/killbill/http_servlet.rb:117:in `rack_service'
	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/killbill-9.4.0/lib/killbill/http_servlet.rb:65:in `service'
2019-08-26T11:36:14,735+0000 lvl='WARN', log='PluginResource', th='catalina-exec-3', xff='', rId='2eef0933-d668-4e1c-9c45-c659bb5266d0', tok='8be072c5-4e4f-4861-85e7-7dadbcdd8ee5', aRId='', tRId='2', /plugins/killbill-kpm/plugins responded 500
2019-08-26T11:36:14,735+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-16', xff='', rId='2eef0933-d668-4e1c-9c45-c659bb5266d0', tok='8be072c5-4e4f-4861-85e7-7dadbcdd8ee5', aRId='', tRId='2', - - - [26/Aug/2019:11:36:14 +0000] "GET /plugins/killbill-kpm/plugins?latest=false " 500 30 0.0070

**Comment by yifanyou** [comment]
docker  deploy
killbill version 0.21.3~4
kaui version 1.0.6

**Comment by pierre** [comment]
We do not provide community support for Kill Bill version 0.21.x.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
