### ISSUE TITLE
Build failed with Maven

### ISSUE THREAD

**Issue by ko2in** [killbill/killbill#1198]
I was trying to install killbill on my Ubuntu. When I try to run start-server inside the bin directory. I've got the errors about the failure of building killbill-jaxrs.

![KillBill-Maven](https://user-images.githubusercontent.com/930315/63956212-05ae3780-caac-11e9-90db-bed28d794561.png)

I've also tried to use `mvn clean install` and have the same problem. I'm not Java guy. Do you've any idea what would be the problem?

I can deploy via Docker without any problem. I would like to run within Tomcat which led me to this problem.

**Comment by pierre** [comment]
You are missing a dependency on Bintray, see https://groups.google.com/d/msg/killbilling-users/ESjCqmZaLjo/G6TTbTfmBgAJ.

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead in the future. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
