### ISSUE TITLE
Wrong argument in catalog API client

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1208]
`catalogApi.getCatalogXml` takes a `LocalDate`. It should be a `DateTime` instead.

**Comment by sbrossie** [comment]
This seems like the same issue from #922, and we need to enhance the [ugly fix](https://github.com/killbill/killbill/commit/c6510a6615de13206af7b591b3fcba3359f02318) to include the `catalogApi.getCatalogXml`.
