### ISSUE TITLE
Junction does not collect blocking_states events at the subscription level

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#122]
In BlockingCalculator, we see that we fetch blocking_states events for BUNDLE and ACCOUNT but not for SUBSCRIPTION. So that should be added.

```
  public void insertBlockingEvents(final SortedSet<BillingEvent> billingEvents, final InternalTenantContext context) {
        if (billingEvents.size() <= 0) {
            return;
        }

        final Account account = billingEvents.first().getAccount();

        final Hashtable<UUID, List<SubscriptionBase>> bundleMap = createBundleSubscriptionMap(billingEvents);

        final SortedSet<BillingEvent> billingEventsToAdd = new TreeSet<BillingEvent>();
        final SortedSet<BillingEvent> billingEventsToRemove = new TreeSet<BillingEvent>();

        for (final UUID bundleId : bundleMap.keySet()) {
            final List<BlockingState> blockingEvents = blockingApi.getBlockingAll(bundleId, context);
            blockingEvents.addAll(blockingApi.getBlockingAll(account.getId(),context));
            final List<DisabledDuration> blockingDurations = createBlockingDurations(blockingEvents);

            for (final SubscriptionBase subscription : bundleMap.get(bundleId)) {
                billingEventsToAdd.addAll(createNewEvents(blockingDurations, billingEvents, account, subscription));
                billingEventsToRemove.addAll(eventsToRemove(blockingDurations, billingEvents, subscription));
            }
        }

        for (final BillingEvent eventToAdd : billingEventsToAdd) {
            billingEvents.add(eventToAdd);
        }

        for (final BillingEvent eventToRemove : billingEventsToRemove) {
            billingEvents.remove(eventToRemove);
        }
    }
```

**Comment by jgomez-vp** [comment]
Hi guys, is this issue still Opened?
I've seen that the code has been updated and I'm not sure if this was fixed or not.
If it is still opened, could you add more details so I can give it a try?

Thanks!!!

Javier.

**Comment by pierre** [comment]
You are right! 92042843e38a67f75495b207385e4c1f9ca60990 did indeed fix it, but we don't have tests for it.

That being said, Blocking States are currently set:

* for cancel operations (blocking type `SUBSCRIPTION`, state `ENT_CANCELLED`, service `entitlement-service`, `blockChange` true, `blockEntitlement` true, `blockBilling` false)
* for pause operations (blocking type `SUBSCRIPTION_BUNDLE`, state `ENT_BLOCKED`, service `entitlement-service`, `blockChange` true, `blockEntitlement` true, `blockBilling` true)
* for resume operations (blocking type `SUBSCRIPTION_BUNDLE`, state `ENT_CLEAR`, service `entitlement-service`, `blockChange` false, `blockEntitlement` false, `blockBilling` false)
* during transfers (blocking type `SUBSCRIPTION`, state `ENT_CANCELLED`, service `entitlement-service`, `blockChange` true, `blockEntitlement` true, `blockBilling` false)
* for overdue states (blocking type `ACCOUNT`, service `overdue-service`, state and block changes depend on the configuration)

We currently don't have any use-case where we would have `SUBSCRIPTION` level blocking states with `blockBilling` set, and there is no API to create them. Adding a test for it is not worth it at this point.

**Comment by jgomez-vp** [comment]
Good! Thanks @pierre !
