### ISSUE TITLE
Contents of some table may be trimmed?

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill#1235]
Thinking about tables like audit_log, sessions, ... which might contain a huge number of rows (and take some drive space), but don't store data that is related to business value after some time, are all the contents of those table needed? forever? Is it possible to trim them?

**Comment by pierre** [comment]
Regarding the `sessions` table, unless you are on an old Kill Bill version (< 0.20.3), this table should always be empty, except when there are currently active Kaui users.

While you could try to delete old `audit_log`, history, etc. entries, there will be side effects (e.g. refreshed Analytics data will be incomplete). We do not recommend it.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by GregOriol** [comment]
I understand about the contribution, but I'm also trying to find out if there is a bug (or a feature request) behind this question.

Actually, there might have been a problem in our instance because after your comment and after looking at the contents of `sessions`, there seem to be only very old sessions, ones from before the upgrade to 0.20.x (we were on 0.18.x); no new ones, so they are likely cleared. Maybe the upgrade didn't clear them? We'll try to clear them manually.

**Comment by pierre** [comment]
> I understand about the contribution, but I'm also trying to find out if there is a bug (or a feature request) behind this question.

GitHub's `CONTRIBUTING.md` file might be a misnomer, yet these _guidelines help [users] verify that they're [...] opening useful issues._ (https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).

In any case, we prefer to discuss the issues on the mailing-list and if there is indeed a bug and/or a feature request, we would then take care of documenting the bug ourselves.

Thank you for your understanding!

> Actually, there might have been a problem in our instance because after your comment and after looking at the contents of `sessions`, there seem to be only very old sessions, ones from before the upgrade to 0.20.x (we were on 0.18.x); no new ones, so they are likely cleared. Maybe the upgrade didn't clear them? We'll try to clear them manually.

It sounds like you didn't clear the database upon upgrade. See the 0.20.3 release notes: https://github.com/killbill/killbill/releases/tag/killbill-0.20.3.

**Comment by GregOriol** [comment]
Ok!

Thanks for pointing that DB change out, we missed it when we went from 0.18.x to 0.20.10... Having made that "mistake", I'd like to suggest that those kind of things could be automated in an upgrade process

**Comment by pierre** [comment]
> Thanks for pointing that DB change out, we missed it when we went from 0.18.x to 0.20.10... Having made that "mistake", I'd like to suggest that those kind of things could be automated in an upgrade process

Most of the database changes are automated already (http://docs.killbill.io/0.20/database_migrations.html). This one couldn't very easily unfortunately, as Kaui would need to be offline during the `truncate` (other users could be logged out in the middle of operations).
