### ISSUE TITLE
External charges with future effective dates lead to invoicing too much in the future

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1241]
The scenario is such that:
1. Create an external charge with a future `effectiveDate` -- e.g 1 year in advance
2. Create a subscription -- e.g 1 MONTHLY subscription

Expectation is that in step 2. we should only invoice for a month. Instead the subscription gets invoiced for a year.

**Comment by sbrossie** [comment]
The issue is that we have [some logic in place to adjust the target date](https://github.com/killbill/killbill/blob/killbill-0.20.13/invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java#L125) based on what we previously invoiced.

**Comment by deepcitizen** [comment]
There is a new bug.
Scenario:
Today 01.01.23
1. I have subscription with monthly billing. The plan of subscription has some usages with billing daily period.
2. Change date to 03.01.23
3. I try to trigger generating invoice with grouping at 01.02.23.
4. When method getInvoiceGrouping called in the my invoice plugin I remove all usages from groups.
5. Killbill generating invoice with target date 01.02.23 with only RECURRING item (no usages)
6. Change date to next day. (04.01.23)
6. Killbill will generate invoice for usage but start day is 31.01.23 and end date is 01.02.23

Expected result:
Killbill should generate invoice for usage with start date 03.01.23 and end date 04.01.23
