### ISSUE TITLE
Support for partial payments

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#125]
Today Kill Bill does not support partial payments.

There does not seem to have any real limitation in Kill Bill. The main investigation is to understand if the 1 invoice -> N payments is correctly supported in terms of APIs

**Comment by pierre** [comment]
As part of this work, we should also verify and test the processed currency is correctly handled.

**Comment by pierre** [comment]
> Regarding the actual implementation, it looks like we at least need to create a future notification in case of payment success if the returned paid amount is lower than the submitted payment amount.

We won't implement this: if a system-generated payment is partial, the user will need to trigger manually a follow-up payment.
