### ISSUE TITLE
Swagger: createAccount does not return Account

### ISSUE THREAD

**Issue by mrmstn** [killbill/killbill#1259]
Version: 0.21.9
Hey there. There is something wrong with API Spec.

According to the defined operation `createAccount`, the operation should return a Account Model.
```
      responses:
        201:
          description: "Account created successfully"
          schema:
            $ref: "#/definitions/Account"
        400:
          description: "Invalid account data supplied"
```
But, the response just links the new account with a Header `Location` parameter. As you might expect, this leads to an unusable generated client.

Could you return the created account as specified or at least define the response as `204, no content` while defining the header "Location" parameter in the Spec?

**Comment by pierre** [comment]
> this leads to an unusable generated client

Which language are you trying to generate? For nearly all of the officially supported languages, we had to tweak the generator (e.g. to support our api key/secret authentication mechanism).

**Comment by mrmstn** [comment]
Well, I'm generating an elixir client, but that's not the point of my issue. 
It seems like the definition of the createAccount opperation is wrong since it doesn't return a Account, it just refers to one by the Location header.

**Comment by pierre** [comment]
> Well, I'm generating an elixir client, but that's not the point of my issue.

What I was trying to say was that you should expect to have to modify the templates and/or even the client generation code -- none of the languages worked out of the box for us.

> Could you return the created account as specified or at least define the response as `204, no content` while defining the header "Location" parameter in the Spec?

We cannot change this behavior at this point as we're about to release 0.22 (no more API change is accepted).

Some background on this behavior: https://github.com/killbill/killbill/issues/917#issuecomment-374827684.

> It seems like the definition of the createAccount opperation is wrong since it doesn't return a Account, it just refers to one by the Location header.

The swagger file is autogenerated from the annotations. Can this behavior be expressed by modifying these annotations?

**Comment by Yeuri1271** [comment]
https://github.com/killbill/killbill/blob/8f22312a0cc091affb4ae345fafde7b6a76a20d8/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java#L357

The annotations has a `response = AccountJson.class` This should be removed or we should return an AccountJson in the body.
