### ISSUE TITLE
Enhance validation error message for SimplePlan catalog apis

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1270]
See https://github.com/killbill/killbill-admin-ui/issues/247#issuecomment-580661462: in `CatalogUpdater`, we often `throw new CatalogApiException(ErrorCode.CAT_INVALID_SIMPLE_PLAN_DESCRIPTOR, desc)`, which isn't really helpful for the user.

Instead of passing `desc` to the `ErrorCode`, we should pass useful messages instead.

**Comment by sbrossie** [comment]
It might be tricky, because all we have is the Jaxb exception, so the best we can do, is relay what they tell us.

**Comment by pierre** [comment]
> It might be tricky, because all we have is the Jaxb exception, so the best we can do, is relay what they tell us.

Not in `CatalogUpdater`, take a look at these for example:

https://github.com/killbill/killbill/blob/154c33420788152b58bcfc8af4f7fb792c8946ba/catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java#L110-L113

https://github.com/killbill/killbill/blob/154c33420788152b58bcfc8af4f7fb792c8946ba/catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java#L116-L118

https://github.com/killbill/killbill/blob/154c33420788152b58bcfc8af4f7fb792c8946ba/catalog/src/main/java/org/killbill/billing/catalog/CatalogUpdater.java#L289-L302
