### ISSUE TITLE
installing killbill-paypal-express-plugin on killbill v0.22.5

### ISSUE THREAD

**Issue by spartakb** [killbill/killbill#1291]
Hi, having a lot of issue trying to get killbill-paypal-express-plugin on killbill v0.22.5.
It appears that from the `killbill-paypal-express-plugin` that it's last supported killbill version is 0.20.x?  

Could you please recommend a path for using PayPal with killbill v0.22.5?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
