### ISSUE TITLE
Customized invoices

### ISSUE THREAD

**Issue by jnax09** [killbill/killbill#1300]
I have been trying to create invoices using the external charges api call method. 

Now I have been looking for ways to add custom fields to the invoices generated. I uploaded an invoice template but still when the invoices are generated, the custom fields are not visible.

Is there any particular way to go about it?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
