### ISSUE TITLE
Tenant Module build is getting failed.

### ISSUE THREAD

**Issue by jayulmehta** [killbill/killbill#1301]
Hi,
Tenant module build is not working.
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/kill-bill/billing/killbill-internal-api/0.22.9-SNAPSHOT/killbill-internal-api-0.22.9-SNAPSHOT.jar
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/kill-bill/billing/killbill-util/0.22.9-SNAPSHOT/killbill-util-0.22.9-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.203 s
[INFO] Finished at: 2020-04-27T18:23:11+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project killbill-tenant: Could not resolve dependencies for project org.kill-bill.billing:killbill-tenant:jar:0.22.9-SNAPSHOT: The following artifacts could not be resolved: org.kill-bill.billing:killbill-internal-api:jar:0.22.9-SNAPSHOT, org.kill-bill.billing:killbill-util:jar:0.22.9-SNAPSHOT, org.kill-bill.billing:killbill-util:jar:tests:0.22.9-SNAPSHOT: Could not find artifact org.kill-bill.billing:killbill-internal-api:jar:0.22.9-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
