### ISSUE TITLE
retryDay config being used for past and future transactions

### ISSUE THREAD

**Issue by HeyCenturies** [killbill/killbill#1304]
Hello, sorry if I got this wrong but does this:

https://github.com/killbill/killbill/blob/ab761c1a0572babea2ec3647366682612237b08b/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L540

means we are using `org.killbill.payment.retry.days` every time kb needs to retry a payment? If i change this value, what happens to the transactions created with the property value set before the change?

Consider this example: Let's say I currently have
`org.killbill.payment.retry.days=1,6,10`
now, if i decide to stop using KB's retry i'd set this to:
`org.killbill.payment.retry.days=null`
but that would affect all past transactions that failed and are still under on-going retry, if i had a retry on day 6, it would not retry on day 10 because i changed the value to null (or any number <6).

 Is that the expected behaviour

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
