### ISSUE TITLE
Uploading catalog versions has weird behavior

### ISSUE THREAD

**Issue by aaldredge** [killbill/killbill#1307]
Uploaded a catalog with a future effective date seems to be ignored.  Uploading the catalog with the same future effective date as the existing future catalog causes an error and the catalogs calls fail to work.  The only way to get out of this state is to delete all catalogs. 

Steps: 
1) upload first catalog xml via Kaui (in this case, cat2.xml).  When this issue description was written, this file has a past effective date. 
2) upload future dated catalog via Kaui (cat3.xml). 
3) navigate away and back to the tenant page; only the cat2 catalog is in the drop down of catalog versions. 
4) getCatalogJson API call /1.0/kb/catalog?requestedDate=2020-06-27T00:00:00.000 returns the cat2.xml data.
5) think "maybe I got distracted and didn't upload cat3.xml" 
6) upload cat3.xml via Kaui
7) receive error via Kaui: "Error while communicating with the Kill Bill server: Error 500: java.lang.IllegalStateException: Failed to de-serialize catalog for tenantRecordId='10'".  Kill Bill log says
`killbill_1   | 21:30:27.160 [catalina-exec-5] WARN  org.killbill.billing.catalog.io.VersionedCatalogLoader - xff='', rId='2565df5f-8672-4544-9959-a9a681d058c8', tok='', aRId='', tRId='10', Catalog effective date 'Wed Jun 03 00:00:00 GMT 2020' already exists for a previous version (class org.killbill.billing.catalog.DefaultVersionedCatalog:)
killbill_1   | 
killbill_1   | 21:30:27.162 [catalina-exec-5] WARN  org.killbill.billing.catalog.io.VersionedCatalogLoader - xff='', rId='2565df5f-8672-4544-9959-a9a681d058c8', tok='', aRId='', tRId='10', Catalog effective date 'Wed Jun 03 00:00:00 GMT 2020' already exists for a previous version (class org.killbill.billing.catalog.DefaultVersionedCatalog:)
killbill_1   | 
killbill_1   | 21:30:27.168 [catalina-exec-5] WARN  org.killbill.billing.jaxrs.mappers.LoggingResponse - xff='', rId='2565df5f-8672-4544-9959-a9a681d058c8', tok='', aRId='', tRId='10', Internal error
killbill_1   | java.lang.RuntimeException: java.lang.IllegalStateException: Failed to de-serialize catalog for tenantRecordId='10'
` 
8) Go back to the Kaui tenant page, catalog drop down is blank.  Clicking + to add a catalog results in the 500 error again.  The getCatalogJson and getCatalogVersions API calls also return a 500.  The only way have found to get out of this state is to delete catalog. 

(txt extensions added to be able to upload)
[cat3.xml.txt](https://github.com/killbill/killbill/files/4713560/cat3.xml.txt)
[cat2.xml.txt](https://github.com/killbill/killbill/files/4713561/cat2.xml.txt)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
