### ISSUE TITLE
Bi Monthly billing period 

### ISSUE THREAD

**Issue by Initlipton** [killbill/killbill#1321]
Hey guys, we are currently using Killbill as our billing solution, and we're just trying to figure out if there is any way to create a plan with a Bi Monthly billing date? Of if not is this something that we could try add

**Comment by pierre** [comment]
We support both `BIWEEKLY` (every 2 weeks) and `BIMESTRIAL` (every two months).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
