### ISSUE TITLE
Issue with AUTO_INVOICING_REUSE_DRAFT and target date

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1357]
If an account is in `AUTO_INVOICING_REUSE_DRAFT`, subsequent invoicing runs will re-use the original invoice. The original target date isn't updated though, which can lead to repair issues.

For example:

* Run 1, target date `2020-08-07`: invoice created as DRAFT with 1 item `startDate=2020-08-07, endDate=2020-09-07`
* Run 2, target date `2020-09-07`: invoice re-used with 2 items `startDate=2020-08-07, endDate=2020-09-07` and `startDate=2020-09-07, endDate=2020-10-07`
* Run 3, target date ⚠️ `2020-08-07` ⚠️: only the proposed item `startDate=2020-08-07, endDate=2020-09-07` is generated, so the code generates a `REPAIR_ADJ{startDate='2020-09-07', endDate='2020-10-07'}`

The reason the target date isn't adjusted is because the target date on the `DRAFT` invoice isn't updated (it's still `2020-08-07` after run 2). It seems that we would need to update this date.

**Comment by sbrossie** [comment]
@pierre I believe this issue was fixed https://github.com/killbill/killbill/commit/71d59e0c9d7db02, can we close?
