### ISSUE TITLE
Wrong billing event catalog effective date in some cases

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1373]
Given the following scenario:

* t1: Catalog with effective date `2020-09-16T10:34:25` is uploaded
* t2: Subscription is created on `2020-09-20T12:56:02`
* t3: Catalog with effective date `2020-09-18T11:19:01` is uploaded

When invoicing is re-running at t > t3, the billing event catalog effective date is currently `2020-09-18T11:19:01`, not `2020-09-16T10:34:25`.

**Comment by sbrossie** [comment]
Note that in the scenario above, the versions of the `Plan` were the same (e.g same prices, ...). There is a [test case that verifies that it works](https://github.com/killbill/killbill/blob/killbill-0.22.19/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogEffectiveDate.java#L80) so I am closing the bug.
