### ISSUE TITLE
Ability to specify full datetime when dealing with subscriptions

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1375]
The feature used to exist and for use case simplifications we decided to remove it. 

Now the issue is that our catalog versions are based on their effectiveDate (datetime) and so when catalog versions are close to each other, creating a subscription that will use a certain version of a catalog require a more precise date (instead of the input localdate, have a full datetime and have the system honor it)

**Comment by sbrossie** [comment]
We'd like to create an additional set of api for subscription management where we respect the full `datetime` provided by the user - any quirks they encounter with respect to positioning from `now`, ... will be the user's responsibility to handle.

**Comment by pierre** [comment]
A first attempt on master: https://github.com/killbill/killbill/pull/1574/files

Some of the patch above (e.g. test) can likely be reused when working on this ticket.
