### ISSUE TITLE
usage billing not happening

### ISSUE THREAD

**Issue by kannanchinnakannu** [killbill/killbill#1376]
usage billing not happening for the below case

usage invoice item are not come along with invoice when after plan update
Test case :
Step 1 : catalog(c1 with catalog effective date (2020-10-05T14:47:50Z)) ---> plan p1 has no usages(Daily - recurring -Fixed 10$ and recurring 5 $)
Step 2 : subscription s1 happens on   2020-10-06  for plan p1(invoice are generated  with two invoice item (Fixed and recurring))
Step 3 : catalog has updated (c1 with catalog effective date (2020-10-08T14:47:50Z)) ---> plan p1 update usages for plan p1
step 4 : post usage for s1 on 2020-10-09 with usage date 2020-10-09
step 5 : invoice generated for s1 on 2020-10-10 without usage invoice item(Expect invoice should be generated  along with usage items)
step 6 : subscription s2 happens on 2020-10-10 for plan p1 
step 7 : post usage for s2 on 2020-10-11 with usage date 2020-10-11
step 8 : invoice generated for s2 on 2020-10-12 with usage invoice item

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
