### ISSUE TITLE
Memory leak when retrieving tags with audit logs

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1381]
See [email thread](https://groups.google.com/g/killbilling-users/c/ZZLIAuswcFQ)

**Comment by sbrossie** [comment]
Tried to reproduce the issue, but nothing obvious showed up. I ran the following `cURL` in a row to fetch account tags (with full audit logs):

```
curl -v \
    -u admin:password \
    -H "X-Killbill-ApiKey: bob" \
    -H "X-Killbill-ApiSecret: lazar" \
    -H "Accept: application/json" \
    'http://127.0.0.1:8080/1.0/kb/accounts/21ab8c9d-d86f-4ac1-8fb1-a577d2cefb85/tags?audit=FULL'
```

In between each iteration I check the `main.pool` connections (`/1.0/metrics` endpoint), but I don't see any increment in the # of `TotalConnections`, it remains the same after each iteration (the opposite of what one would expect if there was a leak.)

**Comment by fbleite** [comment]
Have you tried retrieving the tags for an account that does not have any tags associated with it? 
The issue in our case happened after we had already added and removed the `AUTO_INVOICING_OFF` tag from the account, then when we tried to get the account tags for the said account, that at that moment does not have any tags associated with it, then the leak happens.

**Comment by sbrossie** [comment]
@fbleite Ok, yes, that does it... The issue is that we [allocate the iterator for the audit logs](https://github.com/killbill/killbill/blob/killbill-0.22.16/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L207) prior we enter the loop to return tags, and so if there is no tags (got added and then removed), we still end up with an iterator that has audit logs but it is never closed.
