### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by yasharzb** [killbill/killbill#1389]
Hi. I started the server and I got this problem: `Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : (conn=149) Access denied for user 'root'@'localhost'`. I want to change killbill's DB user to an existing one. Where can I do it?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
