### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by shaker-project** [killbill/killbill#1393]
Hello, we are a group of researchers interested in understanding methods to reduce costs associated with Test Flakiness [1]. We developed an approach to detect flaky tests, dubbed Shaker [2]. Shaker spawns stressor tasks in the running environment (e.g., tasks that consume lots of cpu or memory) to identify if perturbations can make tests fail.

We ran Shaker on killbill project and found the following likely flaky tests.

* testAccountLock - failed 5 times in 12 reruns.
* testFailedPaymentWithOneSuccessfulRetry - failed 1 time in 12 reruns.
* testAbortedPayment - failed 3 times in 12 reruns.
* testFailedPaymentWithLastRetrySuccess - failed 1 time in 12 reruns.

We sincerely hope that this can be useful information and look forward to hearing back. 

[Denini](https://github.com/denini08), [Leopoldo](https://github.com/leopoldomt) and [Marcelo](https://github.com/damorim).

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

[2] D. Silva, L. Teixeira and M. d’Amorim, "Shake It! Detecting Flaky Tests Caused by Concurrency with Shaker," 2020 IEEE International Conference on Software Maintenance and Evolution (ICSME), Adelaide, Australia, 2020, pp. 301-311, https://ieeexplore.ieee.org/document/9240694/.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
