### ISSUE TITLE
 Incorrect charset/character when get catalog - PrettyName field

### ISSUE THREAD

**Issue by GustavoFior** [killbill/killbill#1394]
Has anyone else had or has problems related to charset when returning the catalog? More specific in the prettyName field.

it doesn't matter if it is in get by XML or get by JSON, in both the text comes with "?" in accents.
For example: my prettyName= "Plano Olá Fíor", and the return is "Plano Ol? F?or"

I've tried to change the column and table charset in the killbill database, but it still didn't solve

in XML it has the -> `<?xml version="1.0" encoding="utf-8"?>`

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
