### ISSUE TITLE
Changes on the same phase not reflected on the GET subscription API response

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1397]
We need to investigate if `curPlanPhase.getName().equals(currentPhaseName)` is still valid now that we allow changes on the same plan (e.g. to force price changes):

https://github.com/killbill/killbill/blob/9a6f3a4fef5c3fecb637056f6364437f319bc907/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java#L416

**Comment by sbrossie** [comment]
I think the check should be enhanced to also look at the catalog effective date
