### ISSUE TITLE
EventSubscriptionJson should contain the catalog effective date for each event

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1400]
* This blocks https://github.com/killbill/killbill-admin-ui/issues/273
* This would also be useful to track multiple changes on the same plan (related: https://github.com/killbill/killbill/issues/1397). On that note, maybe `PhasePriceJson` should also contain the catalog effective date?

**Comment by sbrossie** [comment]
The suggested work is to enhance the json response to return the effective date for the catalog for each of the subscription events. So, this [model](https://github.com/killbill/killbill/blob/work-for-release-0.23.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java#L85) would now take an additional field `catalogEffectiveDate` (`DateTime`). The computation of the value should be easy as it can be extracted from the Plan obtained [here](https://github.com/killbill/killbill/blob/work-for-release-0.23.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java#L133)

**Comment by sbrossie** [comment]
> On that note, maybe PhasePriceJson should also contain the catalog effective date?

@pierre I am not sure about the comment here though ^^

**Comment by pierre** [comment]
We could populated it here: https://github.com/killbill/killbill/blob/00d9ace820bc7ddf6961a16a2727abe17b198bf9/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java#L426 (`curPlanPhase.getCatalog().getEffectiveDate()`)
