### ISSUE TITLE
Error while communicating with the Kill Bill server: Error 500: No existing versions in the VersionedCatalog catalog for input date 

### ISSUE THREAD

**Issue by markdavieswlt** [killbill/killbill#1401]
I'm getting this error

Error while communicating with the Kill Bill server: Error 500: No existing versions in the VersionedCatalog catalog for input date Wed Jan 20 10:27:43 GMT 2021

When playing around with the cloud sandbox for evaluating killbill

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
