### ISSUE TITLE
KAUI admin panel 

### ISSUE THREAD

**Issue by axnamit** [killbill/killbill#1405]
is the KAUI Admin panel available in Node js we can see that Kaui are available at ruby java as well as PHP but we are not able to find the node one. If there is was a node js version please share documentation for implementing

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
