### ISSUE TITLE
RECURRING negative plan price lead to strange behavior

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1407]
It looks like our [validation layer](https://github.com/killbill/killbill/blob/killbill-0.22.20/catalog/src/main/java/org/killbill/billing/catalog/DefaultRecurring.java#L96) is not checking for negative prices, so we should probably start by adding this.

The behavior reported was that invoices would be generated but with a positive price.

Note that here was no intention to support a model where one can specify a negative recurring price to generate recurring credits.

**Comment by xsalefter** [comment]
@sbrossie Should we start add new test class for testing `DefaultRecurring`? I'm asking because seems like there's no dedicated test for `DefaultRecurring` in `catalog` module. There are tests classes that seems testing `DefaultRecurring` class (`TestRecurringInAdvance`, `TestRecurringInArrear`) but these 2 classes exist in `invoice` module.

**Comment by sbrossie** [comment]
We currently don't have a good set of unit tests (`fast` tests) in the catalog module for the validation layer. There are certainly tests in this module that check some validation, for example [TestStandaloneCatalog](https://github.com/killbill/killbill/blob/master/catalog/src/test/java/org/killbill/billing/catalog/TestStandaloneCatalog.java#L31), but nothing exhaustive.

What we have done recently was testing validation catalog in our integration layer (`beatrix`), but the tests end up being more complex. See for instance recently added [TestCatalogValidation](https://github.com/killbill/killbill/blob/master/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogValidation.java).

@xsalefter  I think it is a good idea to start adding more in the catalog module, and so creating a new test `TestDefaultRecurring` to do that makes sense, so give it a try.

**Comment by sbrossie** [comment]
See https://github.com/killbill/killbill/pull/1540
