### ISSUE TITLE
ChargeThroughDate not getting set

### ISSUE THREAD

**Issue by VJSynthesis** [killbill/killbill#1418]
I am using the below query to set chargeThroughDate for the subscription, however, its not getting set.

`{
  "accountId": "c0ed5088-641c-4554-a829-2bbad08d4873",
  "bundleExternalKey": "Demo_SUB001121977",
  "subscriptionId": "9afbc496-f002-4d34-bd5a-f154339164ce",
  "externalKey": "SUB001121977",
  "startDate": "2019-10-26",
  "planName": "OnlineBillingVVMMA_OLB ",
  "chargedThroughDate": "2021-18-03",
  "billCycleDayLocal": 17
}`

However, the chargethrough date is not getting set and as a result the invoice is not getting generated. Note that we have AUTO_INVOICING_OFF for this account though.

Any clue, what am I doing wrong?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
