### ISSUE TITLE
Error when logging in with kaui dashboard

### ISSUE THREAD

**Issue by MohamedBRH** [killbill/killbill#1430]
I installed killbill using the docker-compose file, the three services started and I can see the log message "INFO: Server startup"
but when accessing the kaui dashboard through http://localhost:9090 -> http://localhost:9090/users/sign_in it says that something went wrong and I can see this error logs in kaui conatiner:

`kaui_1      | {"@timestamp":"2021-04-26T14:10:14.270Z","@version":"1","message":"I, [2021-04-26T14:10:14.270404 #1]  INFO -- : Started GET \"/users/sign_in\" for 172.20.0.1 at 2021-04-26 14:10:14 +0000\n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"6c3d9981-dfb2-4850-8c32-d32d5de64ac1","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.281Z","@version":"1","message":"I, [2021-04-26T14:10:14.280991 #1]  INFO -- : Processing by Kaui::SessionsController#new as HTML\n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"6c3d9981-dfb2-4850-8c32-d32d5de64ac1","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.301Z","@version":"1","message":"I, [2021-04-26T14:10:14.301417 #1]  INFO -- : Completed 500 Internal Server Error in 19ms\n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"ffc52b60-56ab-4124-b9c6-71974a4a44ec","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.306Z","@version":"1","message":"F, [2021-04-26T14:10:14.305843 #1] FATAL -- :   \n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"ffc52b60-56ab-4124-b9c6-71974a4a44ec","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.306Z","@version":"1","message":"F, [2021-04-26T14:10:14.306484 #1] FATAL -- : ActiveRecord::NoDatabaseError (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'kaui'):\n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"ffc52b60-56ab-4124-b9c6-71974a4a44ec","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.307Z","@version":"1","message":"F, [2021-04-26T14:10:14.306896 #1] FATAL -- :   \n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"ffc52b60-56ab-4124-b9c6-71974a4a44ec","rails.actionName":"sessions#new"}
kaui_1      | {"@timestamp":"2021-04-26T14:10:14.307Z","@version":"1","message":"F, [2021-04-26T14:10:14.307303 #1] FATAL -- : arjdbc/jdbc/RubyJdbcConnection.java:551:in `initialize'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/abstract/core.rb:19:in `initialize'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:69:in `initialize'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/abstract/statement_cache.rb:21:in `initialize'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/mysql/adapter.rb:35:in `initialize'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/jdbc/callbacks.rb:12:in `new'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/jdbc/connection_methods.rb:14:in `jdbc_connection'\ngems/gems/activerecord-jdbc-adapter-51.1-java/lib/arjdbc/mysql/connection_methods.rb:91:in `mysql_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_handling.rb:116:in `retrieve_connection'\ngems/gems/activerecord-5.1.0/lib/active_record/connection_handling.rb:88:in `connection'\ngems/gems/activerecord-5.1.0/lib/active_record/model_schema.rb:451:in `load_schema!'\ngems/gems/activerecord-5.1.0/lib/active_record/attributes.rb:233:in `load_schema!'\ngems/gems/activerecord-5.1.0/lib/active_record/attribute_decorators.rb:50:in `load_schema!'\ngems/gems/activerecord-5.1.0/lib/active_record/model_schema.rb:446:in `load_schema'\ngems/gems/activerecord-5.1.0/lib/active_record/model_schema.rb:349:in `attribute_types'\ngems/gems/activerecord-5.1.0/lib/active_record/attribute_methods.rb:179:in `has_attribute?'\ngems/gems/activerecord-5.1.0/lib/active_record/inheritance.rb:55:in `new'\ngems/gems/devise-4.7.1/app/controllers/devise/sessions_controller.rb:11:in `new'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'\ngems/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:186:in `process_action'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/rendering.rb:30:in `process_action'\ngems/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\ngems/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:131:in `run_callbacks'\ngems/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:19:in `process_action'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/rescue.rb:20:in `process_action'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'\ngems/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `block in instrument'\ngems/gems/activesupport-5.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'\ngems/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `instrument'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'\ngems/gems/activerecord-5.1.0/lib/active_record/railties/controller_runtime.rb:22:in `process_action'\ngems/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:124:in `process'\ngems/gems/actionview-5.1.0/lib/action_view/rendering.rb:30:in `process'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal.rb:189:in `dispatch'\ngems/gems/actionpack-5.1.0/lib/action_controller/metal.rb:253:in `dispatch'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:31:in `serve'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:16:in `block in Constraints'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'\norg/jruby/RubyArray.java:1735:in `each'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'\ngems/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'\norg/jruby/RubyKernel.java:1830:in `public_send'\ngems/gems/railties-5.1.0/lib/rails/railtie.rb:185:in `method_missing'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:17:in `block in Constraints'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'\norg/jruby/RubyArray.java:1735:in `each'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'\ngems/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'\norg/jruby/RubyKernel.java:1138:in `catch'\ngems/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'\ngems/gems/rack-2.1.2/lib/rack/etag.rb:27:in `call'\ngems/gems/rack-2.1.2/lib/rack/conditional_get.rb:27:in `call'\ngems/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'\ngems/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:269:in `context'\ngems/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'\ngems/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:97:in `run_callbacks'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:24:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'\ngems/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'\ngems/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'\ngems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'\ngems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'\ngems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'\ngems/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'\ngems/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'\ngems/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'\ngems/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'\ngems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'\ngems/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'\ngems/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'\nuri:classloader:/rack/handler/servlet.rb:22:in `call'\n","logger_name":"jruby.rack","thread_name":"catalina-exec-4","level":"INFO","level_value":20000,"req.requestId":"ffc52b60-56ab-4124-b9c6-71974a4a44ec","rails.actionName":"sessions#new"}`

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
