### ISSUE TITLE
Killbill login does work with domain name.

### ISSUE THREAD

**Issue by iamakashk** [killbill/killbill#1432]
Hi I am working on killbill installation part. I am using following docker compose file. I want to map my domain name to killbill and work only with domain name and not with IP address.

=========================================
version: '3.2'
volumes:
  db:
services:
  killbill:
    image: killbill/killbill:0.22.12
    container_name: dev-killbill
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db_ip:db_port/killbill
      - KILLBILL_DAO_USER=user
      - KILLBILL_DAO_PASSWORD=password
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
  kaui:
    image: killbill/kaui:2.0.5
    container_name: dev-kaui
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db_ip:db_port/killbill
      - KAUI_CONFIG_DAO_USER=user
      - KAUI_CONFIG_DAO_PASSWORD=password
      - KAUI_KILLBILL_URL=http://killbill:8080
      
 ==========================
 
 I have nginx server through which I am routing incoming request to killbill. 
 
 When I am using http://external_IP:9090/ then login works fine but when I am trying with my mapped domain name ( say dev-mykill.somthing.com ) login does not work. 
 
 Here is my configuration for nginx.
=================
 server {
    listen 80;
    listen [::]:80;
    server_name  dev-mykill.somthing.com;
    location / {
          proxy_pass http://external_IP:9090;
    }
}
================
I checked doing inspect and found this. Not sure why is this coming. 
![Killbillscreenshot](https://user-images.githubusercontent.com/19202603/118103237-4fad8d00-b3f7-11eb-9881-98d7c6de6ccf.png)

Is there any else which needs to be done ?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
