### ISSUE TITLE
Seat based pricing

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1434]
Over the years, we had multiple requests for seat-based pricing: The ability to offer `Plans` whose price varies based on the number of seats (e.g users). There are quite a few companies in the industry that offer such pricing models, from [GH](https://github.com/pricing), [Slack](https://slack.com/pricing), [Atlassian](https://www.atlassian.com/software/jira/pricing), ...

In all these use cases, what is being offered is a tower of product (typically 3 products), each of which containing a bundle of features, and priced on a per seat/month (with typically a discount if paid yearly).

Examples of such requests on the mailing list can also be found here:
* https://groups.google.com/g/killbilling-users/c/Rk41l7m0Qqw/m/8GbsoHcoAwAJ
* https://groups.google.com/g/killbilling-users/c/2ptZAdgS7FU/m/rw31r3ZxAgAJ
* https://groups.google.com/g/killbilling-users/c/4eBoJQSIzX4/m/0KxPq4UNAgAJ

**Comment by sbrossie** [comment]
The default XML catalog works well for use cases where there are "slabs" of seats (say, 1, 10, 50, 100); in such cases, we can define 3 `Products` (assuming a 3 tier product tower), and for each product, 1 `Plan` for a given slab of seats.

In case, we want to support a more dynamic set of users, there is always the option to auto-generate a catalog with all possible combinations (an extension of a slab whose size=1), but if we want to support from 1-10,000 users that's a crazy number of `Plan`.

A possible workaround is to use the price override feature, and basically have the 3 Products along 3 Plans defined in the catalog, and override the price of each Plan during the creation of the subscription to reflect the number of seats, i.e pricing. in this model, the  catalog `Plan` is simply used for its 'shape' (trial, no trial, monthly, yearly), and the price computation is left outside of Kill Bill (which is not optimal, hence the workaround solution).

Another option is to leverage our plugin apis and create a plugin (or plugins) that would dynamically create the plans and adjust the incoming request to set the right plan. The plugin(s) would implement both the [entitlement plugin api](https://github.com/killbill/killbill-plugin-api/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/plugin/api/EntitlementPluginApi.java) to intercept the subscription request and the [catalog plugin api](https://github.com/killbill/killbill-plugin-api/blob/master/catalog/src/main/java/org/killbill/billing/catalog/plugin/api/CatalogPluginApi.java):

* Request comes in with plugin properties (e.g nb seats = 13)
* The plan is created dynamically if it does not already exist
* Using the entitlement plugin api the incoming request is updated to refer to the new plan

**Comment by shaun-forgie** [comment]
Another possible partial solution: 1) extend the usage tiers to support in_advance billing  2) define the appropriate number of seating tiers in a structure that groups into pre sized bands and enable the top_tier policy 3) Modify the invoicing plugin to be aware of a specific custom field name called "top_tier_amount" which is attached to the subscription. This would result in the creation of a usage record item on the invoice that is used to match the tier band rate and calculated invoice item charges.

I acknowledge that where seat licenses need to be specified individually the catalog mechanism is in appropriate.

**Comment by sbrossie** [comment]
I am closing this ticket as being a duplicate of https://github.com/killbill/killbill/issues/1651: In order to implement seat-based pricing, introducing the `quantity` field should suffice.
