### ISSUE TITLE
Why KB is supporting only 1 LDAP Group in KillBillJndiLdapRealm

### ISSUE THREAD

**Issue by rickhpdev** [killbill/killbill#1455]
I was taking a look at Kill Bill users mailing-list and I saw this question that is the same as mine
https://groups.google.com/g/killbilling-users/c/CSlxYGAIrP8

Is there a specific reason for it and/or are you guys planning to support multiple groups in the future? 
Thanks

https://github.com/killbill/killbill/blob/309a9ebb99fda08297e09593fb7ce398e2784f8d/util/src/main/java/org/killbill/billing/util/security/shiro/realm/KillBillJndiLdapRealm.java#L192

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
