### ISSUE TITLE
Voiding an invoice doesn't automatically void associated credits

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1464]
1. After voiding an invoice, consumed credits should be un-consumed.
* If account has enough credit, delete the extra credit.
* Otherwise, refuse voiding the invoice. The user must delete the CBA item first (https://killbill.github.io/slate/#invoice-delete-a-cba-item).

2. Make sure no new item can be added onto a voided invoice (credit, but also charge, etc).

**Comment by sbrossie** [comment]
PR https://github.com/killbill/killbill/pull/1499 added some constraints to avoid allowing VOIDing invoices that contained items being repaired on subsequent invoices -- and therefore leading to an inconsistent state.

**Comment by sbrossie** [comment]
The VOID behavior around credit was addressed in `https://github.com/killbill/killbill/pull/1502#issue-991659511`.

API doc was [updated](https://github.com/killbill/slate/pull/145) accordingly to reflect the change.
