### ISSUE TITLE
Usage amount should be a floating point not a long 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1469]
This is a GH consolidation from https://github.com/killbill/killbill-api/issues/76

Our usage models define passing the 'amount' of units as a long, as shown in [RolledUpUnit#amount](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/usage/api/RolledUpUnit.java#L25) and [UsageRecord#amount](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/usage/api/UsageRecord.java#L27). However, there are many cases where we want to define a high granularity unit (e.g GBytes instead of MBytes or even KBytes, ...) for invoice presentation, and as a result the usage quantity should allow for 'decimal' values. 

However, we don't want to use decimal types such as `float` or `double` because of the loss of precision. Instead, we suggest to use `BigDecimal`.

**Comment by sbrossie** [comment]
Also see https://github.com/killbill/killbill/issues/1325

**Comment by sbrossie** [comment]
The work will require changing our public api defined in `https://github.com/killbill/killbill-api/` and `https://github.com/killbill/killbill-plugin-api` (plugin spi), and therefore will need to be done in our next feature branch `work-for-release-0.23.x`.

It will also require updating our schema to store this new type. Instead of using a `bigint` as shown [here](`https://github.com/killbill/killbill/blob/master/usage/src/main/resources/org/killbill/billing/usage/ddl.sql#L10`), we want to use a numeric type that is big enough, e.g `numeric(18,9)`.

**Comment by sbrossie** [comment]
As a first step, I would suggest to just change the [database schema](https://github.com/killbill/killbill/blob/work-for-release-0.23.x/usage/src/main/resources/org/killbill/billing/usage/ddl.sql#L10) in Kill Bill and make sure everything works.

**Comment by xsalefter** [comment]
Just for note: As [discussed in this PR](https://github.com/killbill/killbill/pull/1579#pullrequestreview-871196271), there are other APIs in `Catalog` that need to be updated as well:

```
    TieredBlock#getMax
    TieredBlockPriceOverride#getMax
    Block#getSize
    Block#getMinTopUpCredit
    BlockPriceOverride#getSize
    Limit#getMax
    Limit#getMin
```

**Comment by shaun-forgie** [comment]
Any chance we could also include #1756 into the enhancements for usage API?
