### ISSUE TITLE
Changing a subscription plan that has add-ons with a future date results in a NullPointerException

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1477]
If add-ons with a future date are present in a subscription and if you try to change the subscription plan, this results in a NullPointerException.

Steps to reproduce:

- Create an account through Kaui
- Create a subscription for the account
- Create some add-ons for the subscription bundle with a future date
- Try to change the subscription plan via the [Change Subscription Plan ](https://killbill.github.io/slate/?shell#subscription-change-subscription-plan)endpoint
- This results in a `NullPointerException`

**Comment by sbrossie** [comment]
Note that after change Plan the existing (pending) add-on may not be `available` with the new plan, or conversely may be `included`, and so in both cases, it should be canceled. 

In terms of behavior, there are a few options:
1. Always decline the change Plan and return an error for the user to first cancel the add-on (not the best option)
2. Only decline the change Plan and return an error if we detect that add-on is `included` or not `available` with the new Plan
3. Always allow the change Plan and automatically cancel the add-on if it is `included` or not `available` with the new Plan

Option `3` is the best, `2` is acceptable and `1` should be avoided (unless it brings too much complexity).

**Comment by sbrossie** [comment]
Verified as fixed in 0.22.30
