### ISSUE TITLE
The upload catalog code allows uploading a bad catalog

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1481]
The upload catalog code does not run full versioned catalog validations and allows uploading a bad catalog. For example, if there is a plan with a phase type as `EVERGREEN`, the upload catalog code allows uploading a catalog that changes the phase type of the plan to `FIXEDTERM`.  This should not be allowed, that is it should not be possible to change the phases type of a plan across catalog versions. 

1. Add full validation when the catalog is uploaded
2. Add a test to verify the behavior above

Relevant code:

https://github.com/killbill/killbill/blob/99f7102c83cefe892027f4ac0d1ab4da37dd517b/catalog/src/main/java/org/killbill/billing/catalog/api/user/DefaultCatalogUserApi.java#L97

 https://github.com/killbill/killbill/blob/99f7102c83cefe892027f4ac0d1ab4da37dd517b/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L98

**Comment by sbrossie** [comment]
Fixed as https://github.com/killbill/killbill/pull/1518
