### ISSUE TITLE
Pass InvoiceContext instead of CallContext to getAdditionalInvoiceItems

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1489]
It would be nice to receive `InvoiceContext` instead here, as invoice plugins often need the existing invoices (this would save an expensive call):
```
    @Override
    public List<InvoiceItem> getAdditionalInvoiceItems(final Invoice invoice,
                                                       final boolean dryRun,
                                                       final Iterable<PluginProperty> inputProperties,
                                                       final CallContext context)
```

**Comment by sbrossie** [comment]
Should we also reorder the [fields](https://github.com/killbill/killbill-plugin-api/blob/work-for-release-0.23.x/invoice/src/main/java/org/killbill/billing/invoice/plugin/api/InvoicePluginApi.java#L27) to have consistency, i.e context last as we usually do: `..., Iterable<PluginProperty> properties, InvoiceContext context` ?

@pierre Thoughts?

**Comment by pierre** [comment]
We're not consistent across plugin APIs unfortunately:

* https://github.com/killbill/killbill-plugin-api/blob/b18e44053a38e888b912470cf447a59ee6a6250a/entitlement/src/main/java/org/killbill/billing/entitlement/plugin/api/EntitlementPluginApi.java#L23: context, properties
* https://github.com/killbill/killbill-plugin-api/blob/b18e44053a38e888b912470cf447a59ee6a6250a/payment/src/main/java/org/killbill/billing/payment/plugin/api/PaymentPluginApi.java#L187: properties, context

but we should have been at least consistent within the same API file (and do what `EntitlementPluginApi` does, i.e. context, properties, so have `getAdditionalInvoiceItems` and `getInvoiceGrouping` the other way around).

My vote is to review all that in 0.25.x and leave 0.23.x as is 😄

**Comment by reshmabidikar** [comment]
So are you suggesting modifying `getAdditionalInvoiceItems` and `getInvoiceGrouping` to use `context, properties`? Or are you proposing we leave this as it is for now?

**Comment by pierre** [comment]
Fixed in https://github.com/killbill/killbill-plugin-api/pull/28.
