### ISSUE TITLE
Catalog API does not return current catalog as specified

### ISSUE THREAD

**Issue by fellmann** [killbill/killbill#1523]
Documentation for Catalog Resource says that requesting the catalog using `/1.0/kb/catalog/xml` or `/1.0/kb/catalog` without `requestedDate` set should return the current catalog.

https://killbill.github.io/slate/#catalog-retrieve-the-catalog-as-xml: `A request with no effective date would retrieve the current version`.

This is not true, as both requests return all available catalog versions as a list.

The behavior originates here:
https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L142
https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L224

Only when `requestedDate` is set, catalog versions are filtered, otherwise, all available versions are returned.

**Comment by reshmabidikar** [comment]
Thanks for the report. The docs are now updated in https://github.com/killbill/slate/pull/314. I'm closing this ticket.
