### ISSUE TITLE
Error adding products in a row using /simple Plan endpoint

### ISSUE THREAD

**Issue by j4g3** [killbill/killbill#1564]
@pierre After adding more than 2 products in a row I can't add others and it shows this error, KillBill Version 0.22.28

![Screen Shot 2022-01-18 at 12 18 44](https://user-images.githubusercontent.com/24799031/149965219-5a4358df-9501-4f1b-aecf-82f30ce8a988.png)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
