### ISSUE TITLE
Add missing information in CatalogJsonSimple

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#158]
To make it useful, we need to add at least:

* `BillingPeriod`
* `PriceList`

**Comment by pierre** [comment]
As part of this change, the [Ruby](https://github.com/killbill/killbill-client-ruby) and [Java](https://github.com/killbill/killbill-client-java) clients will need to be updated.

**Comment by sbrossie** [comment]
We have two endpoints to retrieve the catalog:
* [GET /1.0/kb/catalog](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L130)
*  [GET /1.0/kb/catalog/simpleCatalog](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L192)

The first is a bit too complex (returns too many things, looks like a json version of our java implementation class). The second one is too simplistic. Probably we should get rid of the second one and modify the first one to return  a subset of what is returned today.

**Comment by maguero** [comment]
I started working on this issue. Based on last comment, I can remove "simpleCatalog" endpoint and modify the "getCatalogJson" method to only return useful properties.

Does work for you if I start creating a CatalogJson class with these properties? (or modify CatalogJsonSimple)
* effectiveDate
* catalogName
* currencies
* units
* products
* plans
* priceLists

**Comment by maguero** [comment]
I created a new CatalogJson based on CatalogJsonSimple and added some properties.

Do you also want to add "priceList" inside of "products" like "plans"? Otherwise I can add "priceLists" at the same level as "products".

```JSON
{
  "name": "SpyCarAdvanced",
  "effectiveDate": "2013-02-08T00:00:00.000+0000",
  "currencies": [
    "USD",
     ... (more currencies)
  ],
  "products": [
    {
      "type": "BASE",
      "name": "Super",
      "plans": [
        {
          "name": "super-monthly",
          "billingPeriod": "MONTHLY",
          "phases": [
            {
              "type": "TRIAL",
              "prices": []
            },
            {
              "type": "EVERGREEN",
              "prices": [
                {
                  "currency": "GBP",
                  "value": 750
                },
                ... (more prices)
              ]
            }
          ]
        },
        ...  (more plans)
      ],
      "included": [
        "OilSlick"
      ],
      "available": [
        "RemoteControl",
        "Gas"
      ]
    },
    ...  (more products)
  ]
}
```

**Comment by sbrossie** [comment]
I would keep the same structure that we have in the catalog xml, that is keeping a high level section of `PriceList`s which contains (for each `PriceList`) the list of `Plan`s.

**Comment by maguero** [comment]
Sounds good.
It already has PlanJson inside of Product. Do you also want to include PlanJson object in PriceList or only list the plan names for each PriceList?

**Comment by pierre** [comment]
> Do you also want to include PlanJson object in PriceList or only list the plan names for each PriceList?

Just the names as you have it (i.e. similar to the [XML](https://github.com/killbill/killbill/blob/master/catalog/src/test/resources/SpyCarBasic.xml#L179-L187)).

The idea is that these are actually references to previous sections. In case of the XML, we have a [tool](http://docs.killbill.io/0.15/userguide_subscription.html#components-catalog-overview) that can be run against the file to verify its integrity (i.e. it would check that a specified plan was actually defined in the _plans_ section).

**Comment by maguero** [comment]
Great! Thanks.

>Probably we should get rid of the second one and modify the first one to return a subset of what is returned today.

Should I continue with this plan and finally have only one json catalog endpoint?

**Comment by pierre** [comment]
> Should I continue with this plan and finally have only one json catalog endpoint?

Yes. The main issue with the (legacy) [complex endpoint](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L130) is that it doesn't transform the underlying raw Java class into a __Json__ one. This can cause bugs as the JSON library (Jackson) will use reflection to guess the fields to serialize. Returning instead a `CatalogJson` will solve this and also returns enough information to make it useful.

**Comment by maguero** [comment]
Sounds good. I'll post the PR here when I finish.
Thanks.

**Comment by maguero** [comment]
PRs:
* killbill-client-java: https://github.com/killbill/killbill-client-java/pull/22
* killbill: https://github.com/killbill/killbill/pull/440

Note: ruby client is pending.

**Comment by matias-aguero-hs** [comment]
I added missing properties to PlanPhase.

PR:
* killbill-client-java: https://github.com/killbill/killbill-client-java/pull/23
* killbill: https://github.com/killbill/killbill/pull/443

**Comment by maguero** [comment]
I added missing properties to PlanPhase.

PR:
* killbill-client-java: killbill/killbill-client-java#23
* killbill: #443
