### ISSUE TITLE
Fix disabled unit tests

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#16]
An example is testENT_REPAIR_BP_RECREATE_MISSING_AO

**Comment by pierre** [comment]
Disabled tests:

* `TestAccountDao#testOverlyLongPhoneNumber`: MySQL specific test (ran manually)
* `TestBillingAlignment#testTransitonAccountBAToSubscriptionBA`: to investigate
* `TestOverdueIntegration#testOverdueStateAndWRITTEN_OFFTag`: tracked by https://github.com/killbill/killbill/issues/476
* `TestIntegration#stressTest`: stress test (ran manually)
* `TestIntegration#stressTestDebug`: stress test (ran manually)
* `TestDefaultInvoiceUserApi#testOriginalAmountCharged`: to investigate
* `TestProRation#testSinglePlanDoubleProRation`: to investigate
* `TestDefaultInternalBillingApi#testBlockingStatesWithSameEffectiveDate`: stress test (ran manually)
* `TestDateInvestigation#testWithGMTPlus8`: MySQL specific test (ran manually)
* `TestDateInvestigation#testWithGMTMinus20`: MySQL specific test (ran manually)
* `EmailSenderTest#testSendEmail`: SMTP test (ran manually)
* `TestKillBillJndiLdapRealm#testCheckLDAPConnection`: LDAP test (ran manually)

`testENT_REPAIR_BP_RECREATE_MISSING_AO` was deleted as part of https://github.com/killbill/killbill/commit/6de3d1ddab15c51ef59cd36580f1222847cf767b.
