### ISSUE TITLE
first cancel bundle and soon next create subscription use the same bundle key occur error

### ISSUE THREAD

**Issue by wishma2013** [killbill/killbill#1609]
error message like this:
`Subscription bundle xxxxxxx already has a base subscription`

operator steps like this:
cancel the bundle via api :
[/1.0/kb/subscriptions/{subscriptionId}](http://172.16.31.124:8181/api.html#/operations/Subscription/cancelSubscriptionPlan)

and create new subscription soon nextly via api, and use the same bundleExternalKey with the canceled bunlde previously：
[/1.0/kb/subscriptions](http://172.16.31.124:8181/api.html#/operations/Subscription/createSubscription)

then , killbill sometimes product the error  above ,and other time not. 

Any one can help! Sincerely！

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
