### ISSUE TITLE
Catalog name conflict

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#162]
It looks like the catalog system can be confused if one tries to load a catalog from a URI and an existing catalog with the same name exists in the classpath.

Details: https://groups.google.com/forum/#!topic/killbilling-users/BcYNdEQTBT0

**Comment by jgomez-vp** [comment]
@pierre 
What are the expected solutions here? 
- Should we accept anyway the uploaded Catalog but rename it internally to avoid confussions?
- Should we reject the uploaded Catalog and drop an Exception informing the user that already exists a Catalog with the same name?

Thanks!

Javier.

**Comment by pierre** [comment]
Note that this bug happens when loading the catalog from a [XML file](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/DefaultCatalogService.java#L74), not when uploading a multi-tenant catalog.

The issue seems to be in the [VersionedCatalogLoader](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L65-L79): calling `loadDefaultCatalog` with `SpyCarBasic.xml`, `/var/tmp/SpyCarBasic.xml` or `file:///var/tmp/SpyCarBasic.xml` will always result in loading the `SpyCarBasic.xml` catalog from the classpath (the way [we build the URI](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L74) is wrong). Instead:

* `SpyCarBasic.xml` should be loaded from the classpath
* `/var/tmp/SpyCarBasic.xml` should be loaded from the classpath ([package](http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getResourceAsStream%28java.lang.String%29) `var.tmp`)
* `file:///var/tmp/SpyCarBasic.xml` should be loaded from the filesystem

**Comment by jgomez-vp** [comment]
Understood!
What I'm wondering now is how should I test the 3 different options...
All of them should be loaded from the catalina.properties file?

Like this:

Option 1:
org.killbill.catalog.uri=SpyCarCustom.xml

Option 2:
org.killbill.catalog.uri=/var/tmp/SpyCarCustom.xml

Option 3:
org.killbill.catalog.uri=file:///var/tmp/SpyCarCustom.xml

I've tried with #3 and got different errors while trying to get the file from the Filesystem. The path is not being recognized and the file could not be found.

Thanks!

Javier.

**Comment by pierre** [comment]
> What I'm wondering now is how should I test the 3 different options...

It should be easy from `TestVersionedCatalogLoader` to add `fast` (i.e. unit) tests:

* load `SpyCarBasic.xml` (already present in the classpath under `src/test/resources`)
* create a simple catalog `src/test/resources/com/acme/SpyCarCustom.xml` and verify you can load it by specifying `/com/acme/SpyCarCustom.xml`
* verify loading `SpyCarCustom.xml` and `/com/acme2/SpyCarCustom.xml` fail
* to verify the path, you could generate a catalog dynamically by writing to a temporary file

> All of them should be loaded from the catalina.properties file?

Note that this code is in the Kill Bill Java library (i.e. outside the `profiles` sub-modules), so there is no container involved.

If you want to test manually though (by using a container and starting Kill Bill), you can only specify one value at a time.

> I've tried with Option 3 and got different errors while trying to get the file from the Filesystem. The path is not being recognized and the file could not be found.

Odd, this should work today. I would step through `VersionedCatalogLoader#loadDefaultCatalog` to understand what is happening.

**Comment by jgomez-vp** [comment]
Thanks Pierre.
I was able to do some changes to allow uploads of external files (outside the classpath) succesfully.
For the test of this specific case, you said that I can generate a catalog dynamically into a temporary file...could you help me there? Any existing example?
After doing that, I could confirm that we can close this ticket.

**Comment by pierre** [comment]
> I was able to do some changes to allow uploads of external files (outside the classpath) succesfully.

Did you actually have to change code to make `file:///` work? This should already be supported.

> For the test of this specific case, you said that I can generate a catalog dynamically into a temporary file...could you help me there? Any existing example?

The easiest would be to copy at runtime [SpyCarBasic.xml](https://github.com/killbill/killbill/blob/master/catalog/src/test/resources/SpyCarBasic.xml) to a in-memory/temporary file.

**Comment by jgomez-vp** [comment]
>Did you actually have to change code to make file:/// work? This should already be supported.
Yes @pierre, I had to add a validation as soon as the URI es being built:

```
URI uri = new URI(uriString);
if (!uri.toString().startsWith("file:/")) {
    // extracts the fileName and try to load it from the classpath (resources)
}
```
Otherwise, the URI should be loaded without changes so the Catalog could be imported normally:
`final StandaloneCatalog catalog = XMLLoader.getObjectFromUri(u, StandaloneCatalog.class);`

Without that validation, the application is always trying to get the file from the classpath.

Thanks,

Javier.

**Comment by pierre** [comment]
> Without that validation, the application is always trying to get the file from the classpath.

I just tried specifying `org.killbill.catalog.uri=file:///var/tmp/MyAcmeCatalog.xml` and I could verify the catalog is properly loaded (it indeed tries [first](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L74) to load it from the classpath, and we go through the `IllegalArgumentException` catch block, but the [uri](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L79) still points to the actual file):

```
2015-10-06 09:32:50,747 [main] INFO  org.killbill.xmlloader.XMLLoader - Initializing an object of class org.killbill.billing.catalog.StandaloneCatalog from xml file at: file:///var/tmp/MyAcmeCatalog.xml
2015-10-06 09:32:50,819 [main] INFO  org.killbill.xmlloader.XMLLoader - Errors: 0 for file:///var/tmp/MyAcmeCatalog.xml
2015-10-06 09:33:00,196 [main] INFO  o.k.b.catalog.DefaultCatalogService - Successfully loaded the default catalog file:///var/tmp/MyAcmeCatalog.xml
```

Also, regarding the snippet, I would not add explicit checks on the protocol, as the catalog could be loaded from a http or ftp server for instance (whatever protocol `XMLLoader` supports). All you have to do is *probably* to skip this [block](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L68-L77) because the [XMLLoader](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/io/VersionedCatalogLoader.java#L87) should be able to handle the URI.

**Comment by jgomez-vp** [comment]
>Also, regarding the snippet, I would not add explicit checks on the protocol, as the catalog could be loaded from a http or ftp server for instance (whatever protocol XMLLoader supports). All you have to do is probably to skip this block because the XMLLoader should be able to handle the URI.

You are right, I've skipped that block and all the required cases worked fine!

Regarding the Unit Test for the Option 3 (external file), I might need to use the FileUtils library from Apache Commons to copy (temporarily) a file during the Test.
Is that something I'm authorized to do?

Thanks!

Javier.

**Comment by pierre** [comment]
> You are right, I've skipped that block and all the required cases worked fine!

Yay!

> Nevermind, I managed to copy it without the Apache Commons library.

In general, we'd like to avoid introducing new dependencies. [Guava](https://github.com/google/guava/wiki/IOExplained) should give you most utilities you need.

**Comment by jgomez-vp** [comment]
Good to know that!
One more thing: for one of the test cases I had to create a folder "com.acme" inside the src/test/resources folder, and then add my SpyCarCustom.xml.
Is that something I can add or should I try to create it dynamically? 
I've been researching on how to create temp folders inside the classpath but couldn't find a good working example.

Javier.

**Comment by pierre** [comment]
> One more thing: for one of the test cases I had to create a folder "com.acme" inside the src/test/resources folder, and then add my SpyCarCustom.xml.
Is that something I can add or should I try to create it dynamically?

You can check that file in, that's fine.
