### ISSUE TITLE
Plan change with subscription start date results in an error

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1631]
When  a plan is changed with a date equal to the subscription start date, the following error occurs:

```
Error while changing subscription: Requested date 2022-03-14T12:04:58.000Z is not allowed to be prior to the previous transition 2022-03-14T12:05:11.000Z
```
Steps to Reproduce:

1. Set date to `2022-03-14`.
2. Upload attached catalog.
3. Create a subscription corresponding to the `premium-monthly` plan.
4. Move clock by 10 days.
5. Change plan to `standard-monthly`  with date as `2022-03-14` - This results in the above error.

**Expected Behavior: The plan change should take effect immediately.**

[monthly-no-trial.zip](https://github.com/killbill/killbill/files/8281694/monthly-no-trial.zip)

**Comment by sbrossie** [comment]
Verified as fixed in 0.22.30
