### ISSUE TITLE
Metrics changes for 0.24.x

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1639]
Starting with 0.23.x, we are abstracting the [Dropwizard](https://metrics.dropwizard.io/4.2.0/) specific code in Kill Bill (metrics, healthchecks) into a new [metrics](https://github.com/killbill/killbill-platform/tree/2c7f2e53572d0b97853bb59080c878ecc29ef7cd/osgi-bundles/bundles/metrics) OSGI bundle.

With this:
* We remove all dependencies on Dropwizard jars inside Kill Bill. This new bundle is optional, but without it, endpoints such as `/1.0/healthcheck` and `/1.0/metrics` will return no data.
* Plugins can now also expose their own metrics. See https://github.com/killbill/killbill-hello-world-java-plugin/pull/9 for an example.

Implementation notes: the new Kill Bill specific `MetricRegistry` is now exposed by the system bundle as a service, so that OSGI bundles can pull the metrics for the _sinks_ (Graphite, InfluxDB, etc.). The implementation of that interface is `KillbillPluginsMetricRegistry`, which itself is a wrapper around `OSGISingleServiceRegistration<MetricRegistry>` (`MetricRegistryServiceRegistration`), which takes care of discovering the services exported by the bundles (in practice, 0 or 1, the `KillBillCodahaleMetricRegistry` one, exported by the `metrics` bundle).

Related tickets and PRs:

* https://github.com/killbill/killbill/issues/360
* https://github.com/killbill/killbill-oss-parent/issues/37
* https://github.com/killbill/killbill-commons/pull/111
* https://github.com/killbill/killbill-plugin-framework-java/pull/57
* https://github.com/killbill/killbill-platform/pull/85
* https://github.com/killbill/killbill/pull/1618

Testing to be done:

* [x] Compare the output of the `/1.0/healthcheck` and `/1.0/metrics` endpoints between Kill Bill 0.22.28 and `work-for-release-0.23.x` (adding `?pretty=true` pretty-prints the output).
  * The shape of the JSON should be mostly unchanged.
  * Validate the metrics are correct and consistent between both versions by issuing a few API calls. Pay specifically attention to database metrics (the implementation of the metrics inside `jdbi` and `HikariCP` is brand new code)
  * Validate the healthchecks are consistent and correct as well, by putting Kill Bill in and out of rotation, stopping the database, forcing a plugin healthcheck to be unhealthy, etc.
* [x] Compare the output of the JMX metrics and healthcheck beans between Kill Bill 0.22.28 and `work-for-release-0.23.x`.
* [x] Test the new Graphite integration
  * Install the newly optional [Graphite bundle](https://github.com/killbill/killbill-platform/tree/2c7f2e53572d0b97853bb59080c878ecc29ef7cd/osgi-bundles/bundles/graphite) and configure it (you can use a docker image like `ghcr.io/deniszh/graphite-statsd` for testing). Verify the metrics are correctly forwarded from Kill Bill to Graphite.
  * Update the [README](https://github.com/killbill/killbill-platform/blob/2c7f2e53572d0b97853bb59080c878ecc29ef7cd/osgi-bundles/bundles/graphite/README.md) with testing instructions for future reference.
* [x] Test the new InfluxDB integration
  * Install the newly optional [InfluxDB bundle](https://github.com/killbill/killbill-platform/tree/2c7f2e53572d0b97853bb59080c878ecc29ef7cd/osgi-bundles/bundles/influxdb) and configure it (you can use the official InfluxDB docker image for testing). Verify the metrics are correctly forwarded from Kill Bill to InfluxDB.
  * Update the [README](https://github.com/killbill/killbill-platform/blob/2c7f2e53572d0b97853bb59080c878ecc29ef7cd/osgi-bundles/bundles/influxdb/README.md) with testing instructions for future reference.

**Comment by shaun-forgie** [comment]
Any plans to support the Open Telemetry standards? See https://opentelemetry.io/docs/instrumentation/java/getting-started/ for more information. We would be keen to assist in implementing this.

**Comment by pierre** [comment]
@shaun-forgie I just talked to @andrenpaes, who is our resident expert on all things logging, metrics, and tracing.

Going with the OTEL Java agent (the link you sent) is the way to go. It is non intrusive, and gives you great high level visibility into Kill Bill (HTTP requests, SQL queries, etc.). We feel we already have enough support via logging and metrics today to introspect Kill Bill at a finer level when needed.

That being said, there are some opportunities to make it even more user friendly, including adding proper `events` to the logs (with the trace id and the timing for instance). Also, we're hoping to add labels to our metrics this year (that being said, we've been talking about this for 8 years now 😅).

If you think of anything else missing specifically, please reach out to the mailing-list.
