### ISSUE TITLE
Add ability to start a subscription in the past.

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#164]
Intuitively that feature does not make a lot of sense:

Starting a subscription in the past from an entitlement point of view make little to no sense since the past is the past, and starting in the past will not change what already happened.

From a strict billing point of view, this makes sense because customer would get invoiced for that past period as well.

Now question is why would we want to invoice for something in the past for which customer did not receive any service (entitlement in the past)?

It seems there is a potential use case for MANUAL_PAY. Customer sent a check but somehow check did not get processed and account goes overdue and subscriptions get cancelled. Customer calls and subscription is restarted but the intent would be to not ask for a new check, hence restarting the subscription at the exact date it got cancelled.

**Comment by sbrossie** [comment]
I think this has been fixed but we should add a test case to verify this is the case.

**Comment by maguero** [comment]
Hi, I'm trying to add a test case to this issue. Assuming that it's already fix, I found some tests on [TestOverdueWithSubscriptionCancellation] (https://github.com/killbill/killbill/blob/master/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueWithSubscriptionCancellation.java#L68) that reactivate a subscription using "uncancel" method. 
Is it what you are asking for? In this case, should I check that no invoices are generated after uncancel it?

**Comment by pierre** [comment]
@maguero Take a look at [TestDefaultEntitlementApi](https://github.com/killbill/killbill/blob/master/entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java): you can create a subscription using `createBaseEntitlement` (`initialDate` should be in the past compared to the `clock`).

@sbrossie Do you think it's worth also adding a test specifically for the `MANUAL_PAY` scenario you described? The "restart" should really be create a new subscription anyways, no (we cannot re-instate fully cancelled subscriptions)?

**Comment by maguero** [comment]
@pierre Yeap, I have a new test there like this:
``` Java
final LocalDate initialDate = new LocalDate(2013, 8, 7);
final LocalDate clockDate = new LocalDate(2013, 10, 7);
clock.setDay(clockDate);
// ... some code 
final Entitlement entitlement = entitlementApi.createBaseEntitlement(...., initialDate, .....);
assertEquals(initialDate, entitlement.getEffectiveStartDate());
```
but I don't know what other asserts I need to add. (like check if invoices were generated for previous moths)

**Comment by pierre** [comment]
This looks good! For now, you can add similar assertions than the other ones in the test class (i.e. verify the `entitlement` attributes and/or verify what `getAllEntitlementsForBundle` or `getAllEntitlementsForAccountIdAndExternalKey` return).

Because the test is at the entitlement level, you won't be able to do any assertion regarding invoices. If we want to do the `MANUAL_PAY` scenario, we will have to write it in the beatrix module (which installs both the entitlement and invoice modules in the tests). I'll get back to you on that one.

**Comment by pierre** [comment]
@maguero I just checked with @sbrossie, let's skip testing the `MANUAL_PAY` scenario originally described. Adding a pure entitlement test at the API level is good enough.

Thanks!

**Comment by maguero** [comment]
Thank you!

PR: https://github.com/killbill/killbill/pull/417
