### ISSUE TITLE
Send event when scheduling an invoice generation

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#166]
See https://groups.google.com/d/msgid/killbilling-users/cd34d8ee-40f4-4fe4-a902-6667d28b1102%40googlegroups.com

**Comment by pierre** [comment]
@sbrossie: it seems that this has been fixed by https://github.com/killbill/killbill/issues/308?

The property `org.killbill.invoice.dryRunNotificationSchedule` can now be configured to send a `INVOICE_NOTIFICATION` event before the actual invoice is generated.

**Comment by sbrossie** [comment]
yep i think that can be closed.
