### ISSUE TITLE
Change in Plan#effectiveDateForExistingSubscriptions behavior

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1661]
Currently, the `Plan#effectiveDateForExistingSubscriptions` works such that the new plan is effective on the specified date and this results in prorations. There is a request from some customers for this feature to work so that the price change happens in the next period and avoids proration. So, we need to make the  `Plan#effectiveDateForExistingSubscriptions`  configurable so that it works in both situations. 

The desired behavior can be reproduced as follows:

1. Set date to `2022-03-29`
2. Upload `catalog-v1.xml`
3. Upload `catalog-v2.xml`
4. Set date to `2022-03-30`
5. Create a new account/subscription to the `standard-monthly` plan
6. This results in an invoice being generated for  `$0.16` for the period `2022-03-30` to `2022-03-31` (prorated on the basis of the old price of `$5`). 
7. Move the clock to  `2022-03-31` - This results in an invoice being generated for `$5.81` for the period `2022-03-31` to `2022-04-30` (prorated on the basis of the new price of `$6`). 
8. However, customers expect the user to be charged the old price (`$5`) for the current billing period ( `2022-03-30` to  `2022-04-30`) and  and the updated price ($6) for the next billing period ( `2022-04-30` to  `2022-05-30`) 

[catalog-v2.zip](https://github.com/killbill/killbill/files/8493354/catalog-v2.zip)
[catalog-v1.zip](https://github.com/killbill/killbill/files/8493355/catalog-v1.zip)

**Comment by shaun-forgie** [comment]
@sbrossie so the isEffectiveDateForExistingSubscriptionsAlignedToBCD setting as used in subscription/src/main/java/org/killbill/billing/subscription/config/MultiTenantSubscriptionConfig.java can be found by retrieving tenant specific configuration settings as documented here https://docs.killbill.io/latest/plugin_installation.html#per-tenant-configuration ?

**Comment by reshmabidikar** [comment]
Does not seem to work after testing via Kaui. This is what I did:
1. Set the `org.killbill.subscription.align.effectiveDateForExistingSubscriptions=true` property
2. Set date to `2022-03-29`
3. Uploaded catalogs `catalog-v1.xml` and `catalog-v2.xml`
4. Set date to `2022-03-30`
5. Create a new account with `BCD=30` and created a subscription to the `standard-monthly` plan
6. This results in an invoice being generated for `$5` for the period `2022-03-30` to `2022-04-30`. (No proration as expected since  `org.killbill.subscription.align.effectiveDateForExistingSubscriptions=true` is set)
7. Moved the clock to `2022-03-31` - no invoice generated as expected
8. Moved the clock to  `2022-04-30` - Invoice generated for `$5` for the period `2022-04-30` to `2022-05-30`  - I would expect the invoice to be generated as per the new price of `$6` since the new price is effective from `2022-03-31`.

**Comment by reshmabidikar** [comment]
Tested a couple of other scenarios and found them to be working as expected.

## Test scenario 1

- [Catalog v1](https://github.com/killbill/killbill/files/10575635/Insurance-v1.zip) - `effectiveDate=2022-01-01`
- [Catalog v2](https://github.com/killbill/killbill/files/10575637/Insurance-v2.zip) - `effectiveDate=2022-04-01` 

Steps followed:
- Set date to `2022-03-15`
- Create a subscription to `liability-monthly-no-trial`. Invoice generated for `2022-03-15` to `2022-04-15` for `$49.95` as per the price in `v1`
- Move the clock to `2022-04-15`: Invoice generated for `2022-04-15` to `2022-05-15` for `$49.95` as per v1 (Although Catalog v2 effective date is `2022-04-01`, plan effective date is `2022-05-01` so invoice generated as per v1)
- Move the clock to `2022-05-15`: Invoice generated for `2022-05-15` to `2022-06-15` for `$59.95` as per v2 (Sinceplan effective date is `2022-05-01`)
- No prorations occur as expected

## Test scenario 2:

- [Catalog v1](https://github.com/killbill/killbill/files/10575646/Insurance-v1.zip) - `effectiveDate=2022-01-01`
- [Catalog v2](https://github.com/killbill/killbill/files/10575647/Insurance-v2.zip) - `effectiveDate=2022-04-01` 

Steps followed:
- Set date to `2022-03-15`
- Create a subscription to `liability-monthly-no-trial`. Invoice generated for `2022-03-15` to `2022-04-15` for `$49.95` as per `v1`
- Move the clock to `2022-04-15`: Invoice generated for `2022-04-15` to `2022-05-15` for `$59.95` as per v2 (Since the plan effective date is `2022-04-01`, the invoice generated as per v2)
- No prorations occur as expected

Since these scenarios work as expected, parking [this issue](https://github.com/killbill/killbill/issues/1661#issuecomment-1411524697) for now. Can be revisited later on if a bug is reported.
