### ISSUE TITLE
Target phase not taken into account on Dry Run Invoice Generation ( moving customer to a new plan without initial phases )

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill#1748]
Example scenario : A customer is on evergreen phase on plan A, and I wish that on moving this customer to plan B, they automatically be moved to new plan without initial phases.

Current functionality does not support this and would require duplicating all plans in the catalog and also the invoice dry run doesn't take this into calculation. 

Sample PR for dryRun: https://github.com/dawidworobiec/killbill/pull/1

More information about the requested use case :  In case more plans are added to catalog, and use both trial and discount phases with a never go back policy (so no going from discount to trial, from evergreen to trial/discount, etc) it would require creating event more plans. And we want to achieve 1-1 relation between the plan in our system and the plan in Killbill, because otherwise, it would overcomplicate killbill clients' work.  Currently, the only thing that isn't working as intended is dry run. Dry runs support other changes like BCD perfectly fine (API, not the endpoint, that still lacks it).  We just lack the support for phaseChanges that is supported for change plan endpoint but not dry run.

**Comment by sbrossie** [comment]
Fixed in https://github.com/killbill/killbill/pull/1759
