### ISSUE TITLE
more testing needed because of Guice `@Inject(optional=true)` to javax `@Inject` + `@Nullable` migration

### ISSUE THREAD

**Issue by xsalefter** [killbill/killbill#1764]
See [this comment](https://github.com/killbill/killbill/pull/1760#discussion_r954928918).

**Comment by pierre** [comment]
To add more details: `ServiceDiscoveryRegistry` is currently only (optionally) provided by the [Eureka](https://github.com/Netflix/eureka) Kill Bill [OSGI bundle](https://github.com/killbill/killbill-platform/tree/work-for-release-0.23.x/osgi-bundles/bundles/eureka).

Manual testing is required after the above change by installing the bundle and making sure it properly `registers` and `unregisters` Kill Bill in Eureka when the server is put in and out of rotation (https://github.com/killbill/killbill-platform/blob/c58cad42e453d9d5ddeaa2edb7331f76c5cbbaa4/server/src/main/java/org/killbill/billing/server/healthchecks/KillbillHealthcheck.java#L80).
