### ISSUE TITLE
feat(storage): add SQLite support

### ISSUE THREAD

**Issue by petermetz** [killbill/killbill#1828]
This is about the core code support SQLite not the admin GUI (which already supports it from what I could gather based on the docs)

**Pros:**
1. Might make local testing slightly easier
2. Enables deployment scenarios where DR is provided by LiteStream

**Con(s):**
1. The common DDL might have to be changed in ways that make everything a little (or a lot) worse for the other database engines that have 10x the features compared to SQLite
2. If not 1) then another set of DDL instructions have to be maintained separately for SQLite

---

Above are my initial, not-well-researched-at-all thoughts. I have not done any work on this apart from cloning the project and running the tests. Opening this issue to discuss if it's something worth looking into at least or are the maintainers totally against it? (which is cool too - I just need a temperature check)

**Comment by pierre** [comment]
Not opposed to it if it unblocks Pro 2, but for Pro 1, Kill Bill already supports H2 (default for tests).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for such discussions. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
