### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by BirknerAlex** [killbill/killbill#1839]
Hello,

is it possible that the Sentry Integration has been removed? Can't find anything that seems like a Sentry Integration on the source code, even not find any plugins on the GitHub organisation but I found the following documentation: 

https://docs.killbill.io/latest/errors-sentry.html

It seems the code is missing or the documentation has not been removed or it was never been implemented. 

Regards
Alex

**Comment by pierre** [comment]
Hi Alex,

The Sentry integration is only available on our AWS AMIs, which include a closed-source premium version of Kill Bill (with added features, such as out-of-the-box Sentry integration).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead (see [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md)).
