### ISSUE TITLE
Current catalog implementation does not allow catalogs with future dates?

### ISSUE THREAD

**Issue by HeyCenturies** [killbill/killbill#1840]
Hello, we noticed a change on the catalog module from 0.20.x to the current master version of KB. The old version compared the date returned from a plugin with the most recent (but not in the future) cached catalog. 

https://github.com/killbill/killbill/blob/8cbafb015a3ab19f5306350a58492ca41d468e9a/catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultCatalogCache.java#L169

The new version uses a method getCurrentVersion() that assumes there will be no future catalogs loaded in KB.

https://github.com/killbill/killbill/blob/cd7bb94e395efd3207ee933698537b559676f6c2/catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultCatalogCache.java#L164

https://github.com/killbill/killbill/blob/cd7bb94e395efd3207ee933698537b559676f6c2/catalog/src/main/java/org/killbill/billing/catalog/DefaultVersionedCatalog.java#L77

So for a use-case where a product effectiveStart date is in the future (lets say we want it to be active 2023-08-09), if we upload a catalog version containing this product, there will always be a mismatch between what our plugin returns (in this example id 11: 2022-09-30 which is the most recent not in the future catalog that we want to use for this account creation), and what KB understands as current version from .getCurrentVersion() (2023-08-09) 

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/28064555/230422946-9db5562b-9514-436e-8c5c-ffeb6403596c.png">

this causes a ton of unnecessary calls to our catalog plugin's method getVersionedPluginCatalog and causes problems downstream. Is this new implementation correct? Shouldn't it follow the same logic as 0.20.x?

**Comment by KBbitsP** [comment]
Hi @HeyCenturies Closing this here since we responded through the Google group.
