### ISSUE TITLE
Incorrect start and end dates in an invoice

### ISSUE THREAD

**Issue by deepcitizen** [killbill/killbill#1851]
Scenario:
Today 01.01.23
1. I have subscription with monthly billing. The plan of subscription has some usages with billing daily period.
2. Change date to 03.01.23
3. I try to trigger generating invoice with grouping and target date 01.02.23.
4. When method getInvoiceGrouping called in the my invoice plugin I remove all usages from groups.
5. Killbill generating invoice with target date 01.02.23 with only RECURRING item (no usages)
6. Change date to next day. (04.01.23)
6. Killbill will generate invoice for usage but start day is 31.01.23 and end date is 01.02.23

Expected result:
Killbill should generate invoice for usage with start date 03.01.23 and end date 04.01.23

___________
org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java#adjustTargetDate is generating incorrect date

**Comment by reshmabidikar** [comment]
There was a recent bug fix around this (See https://github.com/killbill/killbill/issues/1966). Could you please check if the latest KB version (`0.24.10`) fixes the issue for you? If not, I would request you to reach out via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) with the following details:
1. Your catalog
2. Exact steps to reproduce the issue.
