### ISSUE TITLE
Invoice list not showing the correct invoice amounts both through Kill Bill API and Kaui

### ISSUE THREAD

**Issue by MacdonaldRobinson** [killbill/killbill#1880]
Hey,

I am using the latest versions of the kill bill and kaui docker containers.

I think there is an issue with the account invoices API: **/accounts/{AccountId}/invoices**

I created a couple of invoices with charges and this is how it looks in Kaui ( notice the Amount column is $0 ):
![image](https://github.com/killbill/killbill/assets/18366446/7c8b859c-50aa-46fb-aecc-cc22209c051d)

Here is what I saw when making a call for all the invoices for the account and I saw all the amounts as $0: **/accounts/{AccountId}/invoices**
![image](https://github.com/killbill/killbill/assets/18366446/fb668df4-2c53-4bd8-8c2e-280cd0741d9a)

I then made a request for a specific invoice and was able to see the amount correctly:  **/invoices/{InvoiceId}**
![image](https://github.com/killbill/killbill/assets/18366446/6cde4fe2-c001-45d8-9295-78ec30d69386)

But for some reason the individual invoice amounts are not pulling into the list API or in the Kaui invoices section

If this is not a bug then please let me know how I can have the amounts pulling onto the Kaui Invoice section / List of Invoices

**Update: Looks like the same issue is happening with the balance as well**

Thanks!

**Comment by reshmabidikar** [comment]
@MacdonaldRobinson,  couple of things:

> I created a couple of invoices with charges and this is how it looks in Kaui ( notice the Amount column is $0 ):

This is a known issue in Kaui after the Kill Bill `0.24.x` upgrade. Kill Bill `0.24.x` includes a per-account invoice pagination feature that is not yet implemented on the Kaui side.  Issue  https://github.com/killbill/killbill-admin-ui/issues/329 tracks this.

> Here is what I saw when making a call for all the invoices for the account and I saw all the amounts as $0: /accounts/{AccountId}/invoices

Could you try specifying the `includeInvoiceComponents=true` query parameter? See docs [here](https://killbill.github.io/slate/#account-retrieve-account-invoices).

I'm closing this issue. If you have any further questions, please feel free to get in touch via the [mailing list](https://groups.google.com/g/killbilling-users).
