### ISSUE TITLE
Add ability to automatically refund customer instead of giving credit

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#189]

**Comment by meden** [comment]
Hello,

there is some design choice behind closing this or it's just a clean-up of oldies? Just to know if it's something that wouldn't be accepted even if contributed.

Thanks

**Comment by pierre** [comment]
@meden We haven't had the request for it recently, so it's unlikely to be implemented soon. But if this is something you really need, feel free to reach out to the mailing-list to discuss your options.
