### ISSUE TITLE
Invoice Items table amount, rate numeric overflow

### ISSUE THREAD

**Issue by TaeTaeKim** [killbill/killbill#1896]
When using KRW as the default currency (1$ = 1300KRW) and creating a subscription with a price of 1000$(1,300,000 KRW), an insert error occurs in the _numeric(15,9)_ type of the _invoice_items_ table _amout, rate field_.

This seems to cause a batch job exception with a side effect on the invoice sequence, and the biggest problem is that it is difficult to identify the error.(I found a batch exception when committing to an invoice after creating a dry run.)

**Comment by reshmabidikar** [comment]
Could you please provide the following details via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users):

1. Your catalog
2. Exact steps to reproduce?
