### ISSUE TITLE
Catalog example for capacity/consumable in advance

### ISSUE THREAD

**Issue by arturhefczyc** [killbill/killbill#1906]
I am looking for an example catalog with base product, with some add-ones which are capacity of the main product.
For example, I am renting out, on monthly basis, VM at some recurring price and a customer can select capacity of the VM, like how much RAM, CPU or disk space it should have.
So, for example, the VM base, monthly price would be $10.00 plus:
1. $2/month for each CPU a customer adds
2. $1/month for each GB RAM
3. $1/month for each 10GB of disk space

Or something like this. I can find examples with consumable in arrear, would capacity/consumable in advance be the same, just in advance?

**Comment by reshmabidikar** [comment]
I believe this is also posted on the mailing list here: https://groups.google.com/g/killbilling-users/c/tjDa9Wxw2ws. Closing this issue.
