### ISSUE TITLE
Expiry events not returned while retrieving a subscription

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1913]
For a `FIXEDTERM` subscription,  a subscription event of type `EXPIRED` is inserted into the `subscription_events` table. However, when the subscription is retrieved via the [Retrieve Subscription](https://killbill.github.io/slate/?javascript#subscription-retrieve-a-subscription-by-id) endpoint, this event is not returned.

**Comment by sbrossie** [comment]
See https://github.com/killbill/killbill/pull/1916
