### ISSUE TITLE
Adding currency to the plan results with error

### ISSUE THREAD

**Issue by piotrkochan** [killbill/killbill#1917]
https://docs.killbill.io/latest/userguide_kaui#_add_a_currency_to_a_plan

I created a simple tenant and plan. I'm trying to add currency to this plan and the error shows up:

> Error while creating plan: plan plan1 already exists

**Comment by reshmabidikar** [comment]
Could you please post a query with the exact steps that you followed in the [Kill Bill mailing list](https://groups.google.com/forum/#!forum/killbilling-users)? I'm closing this issue for now.
