### ISSUE TITLE
AWS Fargate Task - Access Denied

### ISSUE THREAD

**Issue by mvrius** [killbill/killbill#1926]
The task definition listed here https://docs.killbill.io/latest/aws-container

```Enter the content of the following JSON file:
https://killbill-amp.s3.amazonaws.com/task.json
```

has some ACL problems. Could you upload the task definition to GitHub please?

Thanks!

**Comment by reshmabidikar** [comment]
Could you please post a query for this in the [Kill Bill mailing list](https://groups.google.com/forum/#!forum/killbilling-users)?
