### ISSUE TITLE
killbill TLS connections to 1.2 to maintain AWS endpoint connectivity

### ISSUE THREAD

**Issue by Veeraops** [killbill/killbill#1940]
Hi Team,
We are running the KillBill service on an AWS Ec2 instance. We are using AWS SES service for mail notification.
We got a mail from AWS team that you need to update your TLS connections to 1.2 to maintain AWS endpoint connectivity.
Please help us for the properties file for upgrade steps for TLS verison
Kill bill version: 0.22.8

**Comment by Veeraops** [comment]
Hi Team,
TLS certificates need to be updated ASAP. Kindly help us to resolve this issue

**Comment by Veeraops** [comment]
@vnandwana  Thanks for the replay and will share the required details shortly

**Comment by Veeraops** [comment]
@vnandwana  Does api calls or SMTP interface to connect sent email notificatoins ?

**Comment by Veeraops** [comment]
@vnandwana  As we checked with AWS, below is the response from them.
**Thank you for your time on chat and over chime call today.
To recap, you received an email notification that TLSv1.0/1.1 connection requests were detected from your SES account to SES SMTP endpoint in us-east-1, thus you needed help with updating your client application to use TLSv1.2 . 
As you are already aware, TLSv1 is gradually being deprecated for all AWS endpoints with target completion date of 31 December 2023; and all our customers are required to update their client applications/software/OS to use TLSv1.2 as minimum protocol[1]. After 31 December 2023, SES endpoints will not accept TLSv1 connection requests from clients.
As discussed and advised, you need to update your SMTP client application to use TLSv1.2 and above. You can refer to the application's documentation guide or reach out again to your application support team for further guidance.
Below are logs snippets of message headers shared with you on the chat for sample messages detected to have been sent using TLSv1;**

**Comment by HanumanthaRAON** [comment]
Thank you for contacting AWS Support. It was a pleasure talking to you.

Based on our conversation, I understand that you wanted information about the SES calls made using KillBill application.

Upon checking the logs, I could see that the application is making SMTP calls to send SES emails. 
Example logs:
---------------------------------------------------
customerIp: X.X.X.X.
deliveryAttempts: 1
dkimSigned: true
eventTime: 1701453695853
eventType: DELIVERY_SUCCESS 
operation: SendSmtpEmail 
recipients: [ [-]
XXXX@hotmail.com
]
remoteMtaIp: X.X.X.X
responseCode: 250
responseMessage: 250 2.6.0 <0100018c268b0333-0b06e512-f6db-425a-8fb9-e2de86b9c8ff-000000@email.amazonses.com> [InternalId=8345121457287, Hostname=PH7PR14MB5945.namprd14.prod.outlook.com] 13614 bytes in 0.318, 41.755 KB/sec Queued mail for delivery -> 250 2.1.5 
sourceAddress: test@gmail.com 
---------------------------------------------------
Please note: SES will only accept connections with TLSv1.2 or higher. The client application needs to be updated to initiate TLSv1.2 or higher connection. There are no changes that can be done on SES side to accepts TLSv1.1 or lower version. 

Please reach out to the application support to make further updates to the sending application. 

Closing the case as discussed. Please feel free to open the case if you have any additional questions/concerns.

**Comment by HanumanthaRAON** [comment]
Please help us to resolve the issue as it will impact our production server

**Comment by HanumanthaRAON** [comment]
Hi @vnandwana ,

We are using Killbill-email-notifications-plugin to trigger email.

**Comment by HanumanthaRAON** [comment]
Hi @vnandwana ,

Currently we are running killbill version 22.8 , does latest version notification supported in Killbill 22.8. we are running notification plugin version 0.6.1.

How can we download latest version of notification plugin  .

![image](https://github.com/killbill/killbill/assets/20111534/cee620eb-8b01-49c5-af64-4748c2d7c5b8)
