### ISSUE TITLE
Stripe DIY example errors: not reachable +  incompatible encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by j2l** [killbill/killbill#1941]
Hello,
On ubuntu 22.04, docker 24.0.5, docker-compose 1.27.4, I setup killbill tenant according to https://docs.killbill.io/latest/stripe_plugin
when I run `docker run -e PUBLISHABLE_KEY=pk_test_XXX -e KB_URL=http://host.docker.internal:8080 -ti -p4567:4567 killbill/stripe-demo` fill info and click, I get an error I understand:
`failed to open TCP connection to host.docker.internal:8080 ...`
![image](https://github.com/killbill/killbill/assets/65325/3f94b4d8-9636-4638-ab16-dfceb0db7413)
This way of calling internal address is not working on linux, containers are isolated, can't call each others until they are on the same network.

But even after settings the demo in the correct docker network, I get the error:
```
Internal Server Error
incompatible encodings: ASCII-8BIT and UTF-8
WEBrick/1.6.1 (Ruby/2.5.8/2021-06-15) at localhost:4567 
````
Is the doc up to date?

**Comment by reshmabidikar** [comment]
Yes, the document at https://docs.killbill.io/latest/stripe_plugin is up to date. However, I'm not sure if the demo has been tested on Linux.  If you were able to get it working on Linux,  could you please let us know what worked so we can update the docs accordingly?  If not, could you check if it works by cloning the code as explained [here](https://docs.killbill.io/latest/stripe_plugin#_manually_by_cloning_the_code) and reach out via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) if you are still facing issues?

**Comment by j2l** [comment]
I can't. It was January, I moved to Django.

**Comment by reshmabidikar** [comment]
Thanks for responding. In order to get quicker responses in the future, I would suggest that you use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users).
