### ISSUE TITLE
New Interception plugin API (routing, custom business logic,...)

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#195]
The goal is to have a 'plugin' layer that could be inserted in between the payment and payment plugins. It could for instance:
* Apply some custom business logic that needs to be shared across multiple plugins
* Perform some routing across different plugins

**Comment by pierre** [comment]
We now have the [PaymentRoutingPluginApi](https://github.com/killbill/killbill-plugin-api/blob/master/routing/src/main/java/org/killbill/billing/routing/plugin/api/PaymentRoutingPluginApi.java), but we should rename it, as it is doing more than just routing payments.

**Comment by sbrossie** [comment]
Renaming has been done, can be closed.
