### ISSUE TITLE
Perf issue when committing an invoice

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1950]
For any code path where `ExistingInvoiceMetadata` is empty, we end up doing a loop to load all the invoice items associated with one - or multiple invoices as shown [here](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L436).

The idea behind `ExistingInvoiceMetadata` was to provide a cache of invoices and items in such a way that we can safely iterate over them without performance issues, but there are paths where the cache is empty.

**Comment by sbrossie** [comment]
We should check all the code paths where we call `DefaultInvoiceDao#createInvoices` with a null `existingInvoiceMetadata` parameter, and either check whether those are:
1.  Already available to the caller - and up to date
2. Not available, but we could do one query to populate the cache, or as an alternative, have more logic in the `ExistingInvoiceMetadata` class to load items on a per invoice basis when we detect there are absent.

**Comment by reshmabidikar** [comment]
From what I understand, `ExistingInvoiceMetadata` represents a cache of invoice and invoice items. Since the invoice items cache is empty, each invoice item is fetched from the DB, causing a performance issue. Does that sound right?

A few questions:

> The idea behind ExistingInvoiceMetadata was to provide a cache of invoices and items.

Does this refer to a cache of existing invoices for a particular account?

**Comment by sbrossie** [comment]
> From what I understand, ExistingInvoiceMetadata represents a cache of invoice and invoice items. Since the invoice items cache is empty, each invoice item is fetched from the DB, causing a performance issue. Does that sound right?

Yes.
