### ISSUE TITLE
Perf issue for computing repair map

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1951]
It was reported that the call `InvoiceItemSqlDao#getRepairMap` that is used when we populate the invoice may take a long time, i.e several seconds - although cardinality is not very large - and may be called multiple times for the same invoice.

1. Do we really need this query - could we compute such repaired invoices based on the invoice items that we have already fetched?
2. If we do, we need to review 1/ performance and indices 2/ code path to understand whether this is called too many times.

Note: The report came from a commit invoice path.

**Comment by reshmabidikar** [comment]
Addressed in #1964. Closing this issue.
