### ISSUE TITLE
Can we get one single invoice for multiple subscription for 1 single account?

### ISSUE THREAD

**Issue by rajivsingh171184** [killbill/killbill#1955]
Hi, 
The use case is that we want our customer to be able to make payment against one single invoice which can consolidate multiple invoices in one.
Is this possible in killbill?

**Comment by shaun-forgie** [comment]
Yes this is possible. But you must have the billing plans and account billing cycle lined up to support a monthly [or mulitple of] cycle. Subscripttions created from a plan with a montly cycle can then be aligned with the account BDC when first created. 

If you are not using a monthly billing cycle then it can still be done but you would have to setup a invoice group and ensure all subscriptions were added to the group.
