### ISSUE TITLE
Same account in multiple tenant possible

### ISSUE THREAD

**Issue by rajivsingh171184** [killbill/killbill#1974]
Hi,
Is this possible to have a same account linked to multiple tenants?

**Comment by KBbitsP** [comment]
Hi @rajivsingh171184 No, the data for each tenant is independent and is not accessible from other tenants.

**Comment by KBbitsP** [comment]
Hi @rajivsingh171184 Please feel free to continue the discussion at killbilling-users@googlegroups.com in case of any further questions. Closing this issue.
