### ISSUE TITLE
Trying the latest release of Killbill core and Kaui in docker-compose .. cannot access KAUI

### ISSUE THREAD

**Issue by jogiji** [killbill/killbill#1977]
Can we get a proper Docker-Compose yaml which runs the latest release of KillBill core and Kaui as the one mentioned below is not working,
# KB stack
version: '3.2'
volumes:
  db:
services:
  killbill:
    image: killbill/killbill:latest
    ports:
      - "8080:8080"
      - "8000:8000"
      - "12345:12345"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_METRICS_INFLUXDB=false
      - KILLBILL_METRICS_INFLUXDB_HOST=host.docker.internal
      - KILLBILL_METRICS_INFLUXDB_PORT=8086
  kaui:
    image: killbill/kaui:latest
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mariadb://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
      - KAUI_KILLBILL_API_KEY=bob
      - KAUI_KILLBILL_API_SECRET=lazar
  db:
    image: killbill/mariadb:0.24
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill

**Comment by reshmabidikar** [comment]
Could you try the docker-compose file documented [here](https://docs.killbill.io/latest/getting_started#_docker_installation)?  If you still face issues after using this file, please feel free to reach out via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users).
