### ISSUE TITLE
Overdue system without utilizing Subscription and catalog feature of KillBill

### ISSUE THREAD

**Issue by rajivsingh171184** [killbill/killbill#1978]
Hi,

My use case is that we generate manual invoice and set a due date on it.
Once the due date is approaching that time I want the system to automatically email the customer a reminder to pay the invoice.
I don't want to use the catalog & subscription feature for this.
Is it possible to achieve this?

**Comment by reshmabidikar** [comment]
The overdue system can be configured irrespective of catalogs and subscriptions. See [overdue doc](https://docs.killbill.io/latest/overdue).  Also, I'm not sure what you mean by `we generate manual invoice and set a due date on it.`, so could you please provide more details via the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) if you need further assistance?
