### ISSUE TITLE
Combo call to create subscriptions with add-ons

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#199]
It would be nice to have a combo call to create in a single transaction a subscription with its add-ons, to minimize the amount of invoices created.

See discussion https://groups.google.com/forum/#!topic/killbilling-users/w0ZAxa9Z0BA. This was also requested by @kevinpostlewaite a while back.

**Comment by pierre** [comment]
At a JAX-RS level, we've had other requests for combo calls (e.g. create account, add a payment method   and trigger a purchase in one go). While we have a long way to go to make that happen transactionally, we could introduce new resources (i.e. Java classes) specifically for these calls. Specifically, we could keep `AccountResource` and add `AccountPaymentResource` (still under `/1.0/kb/accounts`). We could even keep the `POST /1.0/kb/accounts` and have Jersey auto-detect wether it's combo or not based on some hint (content-type header, etc.), hidden in the client libraries.

As part of this work, we should also maybe breakdown the existing resources into multiple classes to remove the hacks in [killpay](https://github.com/killbill/killbill/blob/e768d81593120299f7d0f578f43537466f4d5488/profiles/killpay/src/main/java/org/killbill/billing/server/modules/KillpayServerModule.java#L93) (required for Guice injection) and have real profiles.

**Comment by jgomez-vp** [comment]
Hi @pierre, @kevinpostlewaite and @sbrossie.
We've been trying to find solutions for this ticket and we've realized the following:
- Multiple invoices are being created after the process because for each Subscription creation (Base + add ons) an event is being posted into the Bus inside the [DefaultSubscriptionDao](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java#L496-L506).
To make a modification there, we will have to change also all the intermediate classes (APIs, services, etc.) that are being used between the Resource and the DAO, which we think would be a big refactor.

- In the other hand, we could base our work in the comments of the mailing list discussion and create a new Resource that will execute the following steps:
  - Receive a JSON object with all the information of the Base Subscription and a list of Add Ons (String names) that must be added.
  - Add the AUTO_INVOICING_OFF tag to the Account.
  - Create the Base Subscription
  - Create the Add On Subscriptions (one for each Add On)
  - Remove the AUTO_INVOICING_OFF to the Account.

As a result, we can confirm that only one invoice is being generated with 1 item for the base subscription and N items for the N Add Ons specified in the List.
One of the issues we can face with the last option is (for example) if we are trying to create a Subscription with 2 Add Ons.
Imagine that the Base Subscription is created succesfully and the first Add On too.
What should we do if the second Add On fails during its creation? Rollback the whole process? Remove the AUTO_INVOICING_OFF tag and keep the Subscription and the first Add On created?
This is just an example but we should take it into account.

Thanks!

@vp-maguero @jgomez-vp

**Comment by sbrossie** [comment]
@jgomez-vp What are suggesting works from a functionality point of view in the happy case scenario. You also very correctly pointed out some interesting questions and behavior around partial failures, and this is precisely why we are not too keen with this (simpler) approach.

We should solve this problem by changing the api from top to bottom to end up doing 1 database transaction that either succeeds or fails (completely) and then there is no ambiguity.

If you are interested to pursue we can offer some guidance on what to change and how things would work (this is definitely more involved than the other tasks you addressed so far so i'll leave it up to you to decide if this is something you are interested to dig into).

**Comment by maguero** [comment]
Hi @sbrossie, we are interested to implement this combo call, changing the api from top to bottom as you recommended. We appreciate any guidance that you can provide us.

@jgomez-vp @maguero

**Comment by maguero** [comment]
Hi, I started working on this ticket. My idea to implement this combo call is to create new methods to integrate [entitlementApi.createBaseEntitlement] (https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L123) and [entitlementApi.addEntitlement] (https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L164) and create all subscriptions under the same transaction, and then post the events (to prevent multiple invoices).
The clases where I need to add some new methods are implementing [EntitlementApi] (https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/entitlement/api/EntitlementApi.java) (from killbill-api), SubscriptionBaseInternalApi and SubscriptionDao interfaces. I suppose that I also have to add the new methods to the interface... is that correct?

**Comment by sbrossie** [comment]
@maguero I 'll provide some description of the work, but this requires some time as this is non trivial; i would suggest you guys work on other issues we suggested until i can get to it. I'll make it happen this week.

**Comment by maguero** [comment]
sounds like a plan. Thank you!

**Comment by sbrossie** [comment]
The description below is to implement that feature in an atomic way: In the end, there should be only one database transaction, where either all subscriptions are created or none of them are created. There are two main pieces to implement that:
1. Some API work (SubscriptionResource, EntitlementApi, SubscriptionBaseInternalApi) to be able to pass the info realated to the various subscriptions that should be created in one time
2. Modification of the subscriptionBase module to allow all new state (bundle, subscriptions, subscriptions events) to be created in one GO.

I supsect this is non trivial the explanation below are an overview of the work, but more questions will arise during implementation:

Regarding API work:

[SubscriptionResource](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java) needs to be enhanced to export a new endpoint `createEntitlementWithAddOn`. The body would take a list of `SubscriptionJson`. The call would probably return as a Location the bundleId that was created.


[EntitlementApi](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/entitlement/api/EntitlementApi.java) needs to be modifed to add a new api:
```
   public interface EntitlementSpecifier {
        PlanPhaseSpecifier getPlanPhaseSpecifier();
        String getExternalKey();
        List<PlanPhasePriceOverride> getOverrides();
    }
    
    Entitlement createBaseEntitlementWithAddOns(UUID accountId, Iterable<EntitlementSpecifier> entitlementSpecifier, LocalDate effectiveDate, Iterable<PluginProperty> properties, CallContext context) throws EntitlementApiException;
```


[SubscriptionBaseInternalApi](https://github.com/killbill/killbill/blob/master/api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java) Would also need to be modified in a similar way as `EntitlementApi` was:

```
   public SubscriptionBase createBaseSubscriptionWithAddOns(UUID accountId, Iterable<EntitlementSpecifier> entitlementSpecifier, DateTime requestedDateWithMs,
                                               InternalCallContext context) throws SubscriptionBaseApiException;
```


Regarding core work in [subscription base](https://github.com/killbill/killbill/tree/master/api/src/main/java/org/killbill/billing/subscription) module:


`SubscriptionBaseApiService` and its implementation [DefaultSubscriptionBaseApiService](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java) will need to offer a method `createPlans` similar to the existing `createPlan` to create everything in bulk. Note that the important piece is that before we enter in the [DefaultSubscriptionDao](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/engine/dao/DefaultSubscriptionDao.java), all the subscription events should have been create: See what happens for one subscription [here](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java#L146). And then of course the `SubscriptionDao` will need to be enhanced to allow permitting several subscrition in one go.

**Comment by maguero** [comment]
Thank you! I'll be working on that this week.

**Comment by maguero** [comment]
The code is almost done, but now I need to integrate killbill-api changes by pom files. The PR is: https://github.com/killbill/killbill-api/pull/6.

Will you also update killbill/pom.xml and killbill-oss-parent/pom.xml files to point this changes? ( [DefaultEntitlementApi] (https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L69-69) needs to implement "createBaseEntitlementWithAddOns" method.)

**Comment by maguero** [comment]
@pierre @sbrossie Did you have the chance to review the PR?

I'm done with this combo call, but I don't want to push my changes before resolve killbill-api dependency.

**Comment by pierre** [comment]
Sorry for the slow reply, but we just came back from the [Money20/20 conference](http://www.money2020.com/).

Can you submit a PR, so we can start commenting on it? It's fine to have SNAPSHOT dependencies for now, we're not quite ready to release killbill-api yet. When we're done iterating with this PR, we will release both killbill-oss-parent and killbill-api.

Thanks!

**Comment by maguero** [comment]
wow! it seems it was an amazing conference!

Sure, this is the PR: https://github.com/killbill/killbill/pull/426. Don't worry about time.

Thanks.

**Comment by sbrossie** [comment]
@maguero I think we need to make an api change for `createBaseEntitlementWithAddOns` because the externalKey is at the bundle level and therefore should not be contained in the `EntitlementSpecifier`. So instead we should have the following:

```
   public interface EntitlementSpecifier {
        PlanPhaseSpecifier getPlanPhaseSpecifier();
        List<PlanPhasePriceOverride> getOverrides();
    }

    Entitlement createBaseEntitlementWithAddOns(UUID accountId, String externalKey,
Iterable<EntitlementSpecifier> entitlementSpecifier, LocalDate effectiveDate, Iterable<PluginProperty> properties, CallContext context) throws EntitlementApiException;
```

**Comment by maguero** [comment]
yes, I noticed that fixing #315. Sure, I'll make this change.
Thanks.

**Comment by maguero** [comment]
killbill: #426. 

killbill-api: killbill/killbill-api#6
killbill-client-java: killbill/killbill-client-java#20
killbill-oss-parent: killbill/killbill-oss-parent#3
killbill-plugin-api: killbill/killbill-plugin-api#4
