### ISSUE TITLE
How can you kill this if someone has used all your information and sent this after all my personal accounts I almost broke help please 

### ISSUE THREAD

**Issue by SimmonsServices41** [killbill/killbill#1992]
I need the developer who made this to please contact me asap I loosing money by the minute

**Comment by SimmonsServices41** [comment]
I need someone to help stop all killbill attempts on my personal accounts

**Comment by reshmabidikar** [comment]
Hello, could you please reach out to the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) if you need any help? I'm closing this ticket.
