### ISSUE TITLE
Guice inject should default java annotation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#2]
Ideally, we should be able to swap out Guice for another CDI framework (e.g. if we deploy Kill Bill in JBoss).

**Comment by pierre** [comment]
Swapping Guice would be very difficult at this point:

* We heavily rely on Guice modules
* A lot of third-party dependencies use Guice for wiring, such as Dropwizard, Jersey or Shiro

**Comment by pierre** [comment]
@xsalefter did a lot of work towards this as part of https://github.com/killbill/killbill/issues/1615.

That being said, swapping out Guice for another CDI framework is still a non trivial effort (and not worth it at this point).
