### ISSUE TITLE
Relax invoicing rules around additional items received from plugins

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#2004]
Our [code currently adds some restrictions](https://github.com/killbill/killbill/blob/killbill-0.24.10/invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java#L393) on the fields that can be modified for existing items in the system while doing an invoice run.

There is an ask to relax some of these restrictions to allow setting he following: `quantity`, `rate`,  `amount item_details`, `description`.

A proposal would be to relax this for `EXTERNAL_CHARGE` items as there is no expectation from the system.

**Comment by shaun-forgie** [comment]
What is the usecase for this?

**Comment by sbrossie** [comment]
Re-open as fix does not work.
