### ISSUE TITLE
Daily Usage not getting generated on first day invoice

### ISSUE THREAD

**Issue by Santhoshvenkidusamy** [killbill/killbill#2059]
I have created a account which has a base plan and a add-on. Base Plan billing cycle is monthly and add-on billing cycle is Daily. When I Hit Usage API on the same day I have created the account, the usage gets recorded. But I couldn't see the usage getting invoiced on day 1 or day 2.But after that the usage gets invoiced in the coming days.

**Comment by sbrossie** [comment]
Usage is computed in-arrear at the end of the period, so you won't see any invoice until you hit the end of the period.

Closing is this is expected.
