### ISSUE TITLE
Support Chargeback with multiple currencies

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#212]
The current code does not handle it, need to:
* Fix LeavingState constraint (where we check amount)
* Fix InvoicePayment (Invoice) to allow other currency

**Comment by pierre** [comment]
[This check](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/PaymentAutomatonDAOHelper.java#L92-L94) still prevents the chargeback. I'll fix it while verifying it works with invoice payment.
