### ISSUE TITLE
Upgrade Guava to 17.0

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#218]
Upgrading Guava can be a little bit challenging because of our hack here: https://github.com/killbill/killbill-commons/blob/master/queue/src/main/java/com/google/common/eventbus/EventBusThatThrowsException.java

See also https://github.com/killbill/killbill/issues/28.

**Comment by sbrossie** [comment]
Actually it's time to upgrade to guava 18.0...

**Comment by sbrossie** [comment]
@see 256d2fd287d41b08dd13f011047f9c230b8ce4fe
