### ISSUE TITLE
Multiple SLF4J bindings in Jetty console war

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#222]
The Jetty console plugin adds slf4j-simple automatically for Jetty logging. The issue is that we already bundle logback-classic and logback-core in our war, triggering the warning `SLF4J: Class path contains multiple SLF4J bindings.` when Kill Bill starts. This is somewhat harmless as we know at least one of the two will be used (and the jetty-console war should not be used in production anyways).

Adding an `additionalDependencies` block in the plugin configuration for both logback-classic and logback-core works (i.e. prevents the build from adding slf4j-simple) but the logback configuration file isn't found when Jetty is bootstrapped, resulting in a very verbose DEBUG logging.

To configure logback during the bootstrap process, it looks like we need to fork the plugin. It's not worth it at this point.

**Comment by sbrossie** [comment]
Is it still valid? 
* [platform diff1](https://github.com/killbill/killbill-platform/commit/32825035f24f85810c771e1f4e29cb12e80ab2a3)
* [platform diff2](a9f2ee5908937b0762ed4a24e4707baef3951cbf)

**Comment by pierre** [comment]
Yes, just verified:

```
target > java -jar killbill-profiles-killbill-0.15.7-SNAPSHOT-jetty-console.war
[Thread-2] INFO org.eclipse.jetty.util.log - Logging initialized @3889ms
[Thread-2] INFO org.simplericity.jettyconsole.DefaultJettyManager - Added web application on path / from war killbill/profiles/killbill/target/killbill-profiles-killbill-0.15.7-SNAPSHOT-jetty-console.war
[Thread-2] INFO org.simplericity.jettyconsole.DefaultJettyManager - Starting web application on port 8080
[Thread-2] INFO org.eclipse.jetty.server.Server - jetty-9.2.1.v20140609
[Thread-2] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/private/var/folders/0x/1p8qjl4x03q_vtcp_rqqd0l03m6s2y/T/killbill-profiles-killbill-0.15.7-SNAPSHOT-jetty-console.war_8080/webapp/WEB-INF/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/folders/0x/1p8qjl4x03q_vtcp_rqqd0l03m6s2y/T/killbill-profiles-killbill-0.15.7-SNAPSHOT-jetty-console.war_8080/condi/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```
