### ISSUE TITLE
Move date/datetime code into Clock

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#232]
There numerous places where we do a bunch of date/datetime calculation. It would be really useful to extract all those into Clock so they can be (unit tested once and for all) and reused across places.

* https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java (toLocalDate, ..)
* https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/EntitlementDateHelper.java
* https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBaseApiService.java
* https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/timezone/DateAndTimeZoneContext.java

**Comment by pierre** [comment]
Done!
