### ISSUE TITLE
Rename /1.0/kb/tenants/REGISTER_NOTIFICATION_CALLBACK

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#238]
There is an old typo here: https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TenantResource.java#L166

When we fix it, we should probably support the deprecated path because current clients depend on it (Java, .NET, etc.).

Reported-by @galenp.

**Comment by sbrossie** [comment]
I am wondering if we should not *just* fix it and document it-- and of course update our client libraries.

**Comment by pierre** [comment]
Do you want to squeeze it in 0.13.5?

**Comment by sbrossie** [comment]
Yep... since i need to rebuild client libraries anyways (plus i had already fixed it without knowing about that bug. Just undid my change, but now i am thinking this is the right time...)

**Comment by pierre** [comment]
:+1:
