### ISSUE TITLE
Suggest  you use a set or hashmap for registerCallbackNotificationForTenant

### ISSUE THREAD

**Issue by awcoding** [killbill/killbill#240]
This at the top of my kb code experiments:
client.registerCallbackNotificationForTenant("http://mysite.com", "createdByClient", "notificationReason", "no comment");

I just noticed it has led to me getting a linear growing wave of copycat notifications on my url. This isn't ideal because I can't find a way to unregistertheCallbackNotifications. I suspect at some point in the future you will move to having a light pub/sub system here. A set of frontend servers probably only wish to listen to the subset of billing notifications that concern the customers they are currently serving.

**Comment by sbrossie** [comment]
@awcoding Why would you receive notifications for customers you are not serving? The callback is registered per tenant, and i am assuming all the customers in that tenant are customers you would care about. Or am i missing something?

**Comment by pierre** [comment]
See `TenantResource#deletePushNotificationCallbacks` to remove notifications.
