### ISSUE TITLE
Set content-type when sending HTTP notifications

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#249]
See https://groups.google.com/forum/#!msg/killbilling-users/bdVl7hdV69Y/Wa98SsSbCJ8J.

**Comment by ntherning** [comment]
I've been bitten by this as well. Trying to get Spring MVC to accept the request from KillBill. Spring will assume `application/octet-stream` when no `Content-Type` is set in the request. And the `MappingJackson2HttpMessageConverter` which converts the request body to JSON by default only can read `application/json`. Workaround was to configure Spring MVC with a second `MappingJackson2HttpMessageConverter` which supports `application/octet-stream`.
