### ISSUE TITLE
Usage API

### ISSUE THREAD

**Issue by antoniobruno77** [killbill/killbill#250]
Calling /1.0/kb/usages with a JSON containing not correctly formatted date cause a record with "0000-00-00" value on record_date field  on Database.

Here the json
```
{
	"subscriptionId": "4620a5e9-b43b-49c3-9c46-65cdaca1b0ad",
	"unitUsageRecords": [{"unitType":"bandwith-meg-sec","usageRecords":[{"recordDate":"20150115","amount":"100"}]}	                    ]
}
```

**Comment by sbrossie** [comment]
After some investigation, this actually looks like a bug in Joda library (which is invoked from the json deserialization (`com.fasterxml.jackson.datatype.joda.deser.LocalDateDeserializer.deserialize`)

```
        DateTimeFormatter dateTimeFormatter = ISODateTimeFormat.localDateParser();
        final LocalDate d = dateTimeFormatter.parseLocalDate("20150115");
```

Will succeed to create a (wrong) date:
```
Date = 20150115-01-01
```
There is not a lot we can do on our hand to prevent that (obviously i could add code to detect that specific use case, but i am not sure it would cover other badly formatted dates. 

Closing the issue.
