### ISSUE TITLE
Relax strict ordering of XML configuration files

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#252]
The rational for a strict ordering was to make the configuration deterministic. It turns out to be a pain in practice though because most developers don't configure the XSD in their IDE.

**Comment by sbrossie** [comment]
After talking to Martin, the original intent was to avoid people configuring their catalog sections in all kinds of different orders making it hard to read. If we were to relax these constraints, we should think of a tool that reorders section the way we are used to (to help reading).

**Comment by sbrossie** [comment]
The issue still stands but we would like to accept a catalog XML that is not well ordered, but the code would reorder it before we store it on disk. As a side effect the XML would be correctly ordered when the client fetches it through api.

**Comment by sbrossie** [comment]
This applies for all our XML config (catalog, overdue,...)

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
I can start working on this issue.
Is there any preferred place where you want this "tool" to order the XML files?
Any other help will be much appreciated!

Thanks!!

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
So, I've created a test and tried to upload an XML catalog unordered.
I followed the process and it was succesfully saved in the DB. 
Then I tried to get the Catalog, and for my surprise it is now ordered!
Is that the expected behaviour?
Any help will be much appreciated!

Thanks!!

**Comment by sbrossie** [comment]
@javier-gomez-hs That's good. If you have a test you can submit it, and we can close the bug. If this was just a manual test, don't bother writing a test, i don't think this is worth the effort.

**Comment by javier-gomez-hs** [comment]
@sbrossie 
It was just a manual test, uploading an unordered catalog and getting it from the API.

Thanks.
