### ISSUE TITLE
Add support for multiple partial refunds

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#254]
See https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentRoutingPluginApi.java#L164 and https://github.com/killbill/killbill/blob/master/invoice/src/main/resources/org/killbill/billing/invoice/ddl.sql#L73.

Relaxing both constraints seem to work fine (I have verified it with a new integration test) but more work is required to complete the task:

* Get rid of `InvoiceInternalApi#getInvoicePaymentForRefund` (wrong signature, but only used in one place)
* Add tests to verify multiple refunds with invoice item adjustments (on the same and different items). Verify account and invoice balances are correct

A potential bigger task is to add support for partial payments. Tests to add:
* AUTO_PAY_OFF then partial payment. Verify the state when triggering the tag removal
* Partial refund after partial payment: verify link item ids and cookie ids

**Comment by anthonyp** [comment]
Related to #125

**Comment by pierre** [comment]
Supporting multiple refunds forces a DDL change due to the following index:

```
CREATE UNIQUE INDEX idx_invoice_payments ON invoice_payments(payment_id, type);
```

I'll go ahead with the (backward compatible) code changes for 0.16.3, but _official_ support for this feature won't be technically ready until 0.17.0.
