### ISSUE TITLE
SubscriptionResource does not return EntitlementState (ACTIVE, BLOCKED, CANCELLED)

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#257]
Note that when we fix that, we should take a pass and double check if there are other pieces of info that are missing at that level.

**Comment by pierre** [comment]
Missing information to add:

* `Events` (see https://github.com/killbill/killbill/issues/244)
* `State`
* `SourceType`

Some catalog information for the last active plan is shown, such as `productName`, `productCategory`, `billingPeriod` and `priceList` but we should probably also expose the last active `phaseType`.

`BaseEntitlementId` is also missing but it should match the `id`, so I don't think we should expose it.
