### ISSUE TITLE
Add safety bounds in the system

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#26]
If triggered it will add auto_pay_off tag to account throw alert and drop the payment (without creating a payment attempt) also create an ALERT log message. 

Also need a control tag that can be added to the account that overrides the bound.

**Comment by pierre** [comment]
This could be implemented in a payment control plugin. We could use a special plugin property to avoid false positives (e.g. mass refunds).

**Comment by sbrossie** [comment]
I actually think it would be nice to have that in KB itself (instead of a control plugin): Seems like we need that in several parts of the system (invoice, payment, basically whatever part of the system where there is a big risk if there were a infinite loop (either inside or outside of KB).

At the same i am not sure exactly how that would work but we should first define requirements:
1. Be light and simple (preference would be in memory counters of some sort that we implement or code we reuse 'a la codahale metrics')
2. Rely on KB system properties to change values
3. Can be turned off

Since the main use case we know of is based on some potential loop somewhere, what we probably care most to detect is a *rate of the same request*. Maybe just having a in memory rate counter per *something* would be good enough. Examples for payment system:
* Rate of payment/per given account, AND/OR
* Rate of payment for a given payment externalKey

Also the in-memory solution is less robust with regard to loops that occur outside of the system (where the deployment has multiple instances of KB deployed) but maybe this is good enough.

Another possibility, instead of the rates (or in addition to) would be to have a max dollar amount invoiced, paid, .../ account. This is not possible to implement in-memory only in mutli-node deployments.

**Comment by pierre** [comment]
> I actually think it would be nice to have that in KB itself (instead of a control plugin): Seems like we need that in several parts of the system (invoice, payment, basically whatever part of the system where there is a big risk if there were a infinite loop (either inside or outside of KB).

There may be different types of bounds then. Simple rules to detect things like infinite invoice loops, and more advanced ones to detect an integration bug (charging the same credit card from the checkout flow).
While the former can be built-in, I'm thinking that the latter may be very specific to a given integration (amount limits vary by country/provider/payment method type) and the rules could be trickier. Having a plugin would avoid having to write yet another rules engine in the core :-)

**Comment by pierre** [comment]
> Simple rules to detect things like infinite invoice loops, and more advanced ones to detect an integration bug (charging the same credit card from the checkout flow).

For the simple stuff, we could use Metrics [Meters](https://dropwizard.github.io/metrics/3.1.0/manual/core/#meters), to record the rate of payments per account (with a JMX switch to turn it off)? We need to watch out the memory usage, i.e. keep a LRU of some sorts.

Also, we should check if `AUTO_PAY_OFF` is really respected for direct payments. I'm actually not sure it should, since it's not a "AUTO" payment. Maybe we need a new system tag?

**Comment by pierre** [comment]
Or we could use `TransactionStatus#PAYMENT_SYSTEM_OFF` (we would record the payment, but bypass the plugin)?

**Comment by sbrossie** [comment]
> Also, we should check if AUTO_PAY_OFF is really respected for direct payments. I'm actually not sure it should, since it's not a "AUTO" payment. Maybe we need a new system tag?

Absolutely. AUTO_PAY_OFF is only for invoice related payments.

**Comment by pierre** [comment]
Taking a step back, the main safety bound we really care about is for invoice. If we prevent loops in invoice, payment loops would be prevented too.

I'll implement a per subscription check when we compute the resulting items: if these contain one or more invoice items for a subscription and if the total number of items for that subscription created that day is above a given threshold, the code would bail.

There is a possibility of false positives when the system catches up (e.g. removal of AUTO_INVOICE_OFF tag) but a work-around would be to temporarily bump the config threshold (easily doable at runtime through the per-tenant invoice config).
