### ISSUE TITLE
db schema already outdated in userguide

### ISSUE THREAD

**Issue by pepedocs** [killbill/killbill#266]
The following db schema is already outdated and is still referred at http://killbill.io/userguide/platform-userguide/
 
http://killbill.io/wp-content/uploads/2014/11/killbill-0.12.0.ddl

I've had to deal with this for at least a day to figure out what happened with DB errors, and even when I've get rid of it I realised the catalog data were truncated.  I know there's a better way to not stumble on this problem perhaps deploying killbill with the latest schema from github, but still the userguide can lead some to confusion/frustration.

**Comment by pepedocs** [comment]
Great billing app by the way, and thanks for sharing it!

**Comment by pierre** [comment]
We have currently two release trains: 0.12.x (stable) and 0.13.x (development). Each DDL file can be downloaded from http://killbill.io/downloads/, but the user guide refers to the stable version.

To avoid confusion in the future, I've updated the links in the guide to point to the download page: https://github.com/killbill/killbill-docs/commit/d3aa3aac05adfe10253e6aab7f41b364f5732ead.
