### ISSUE TITLE
CatalogResource.getCatalogJson throwing StackOverflowError

### ISSUE THREAD

**Issue by beccagaspard** [killbill/killbill#272]
Calling the `/1.0/kb/catalog` endpoint is throwing a StackOverflowError. 

I'm using killbill-0.13.3 - the error occurs even with the default SpyCarBasic catalog.

> [qtp1214780453-93] WARN org.eclipse.jetty.server.HttpChannel - /1.0/kb/catalog
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]->org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]->org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]->org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]->org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]->org.killbill.billing.catalog.DefaultPlanPhase["plan"]->org.killbill.billing.catalog.DefaultPlan["initialPhases"]
...

**Comment by sbrossie** [comment]
I just downloaded the embedded war 0.13.3 and tried the endpoint and that seems fine. Could you provide more information on how you started KB, and details about your CURL?

> curl -v \
-u admin:password \
-H "X-Killbill-ApiKey: bob" \
-H "X-Killbill-ApiSecret: lazar" \
-H "Content-Type: application/json" \
http://127.0.0.1:8080/1.0/kb/catalog

< HTTP/1.1 200 OK
< Date: Tue, 10 Feb 2015 04:03:32 GMT
< Set-Cookie: JSESSIONID=5; Path=/; HttpOnly
< Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Mon, 09-Feb-2015 04:03:32 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS
< Access-Control-Allow-Headers: Authorization,Content-Type,X-Killbill-ApiKey,X-Killbill-ApiSecret,X-Killbill-Comment,X-Killbill-CreatedBy,X-Killbill-Pagination-CurrentOffset,X-Killbill-Pagination-MaxNbRecords,X-Killbill-Pagination-NextOffset,X-Killbill-Pagination-NextPageUri,X-Killbill-Pagination-TotalNbRecords,X-Killbill-Reason
< Content-Type: application/xml
< Transfer-Encoding: chunked
* Server Jetty(9.2.1.v20140609) is not blacklisted
< Server: Jetty(9.2.1.v20140609)
< 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<catalog>
    <catalogVersion>
        <effectiveDate>2013-02-08T00:00:00Z</effectiveDate>
        <catalogName>SpyCarBasic</catalogName>
        <recurringBillingMode>IN_ADVANCE</recurringBillingMode>
        <currencies>
            <currency>USD</currency>
            <currency>GBP</currency>
        </currencies>
        <products>
            <product name="Standard" retired="false">
                <category>BASE</category>
                <included/>
                <available/>
                <limits/>
            </product>
            <product name="Sports" retired="false">
                <category>BASE</category>
                <included/>
                <available/>
                <limits/>
            </product>
            <product name="Super" retired="false">
                <category>BASE</category>
                <included/>
                <available/>
                <limits/>
            </product>
        </products>
        <rules>
            <changePolicy>
                <changePolicyCase>
                    <policy>IMMEDIATE</policy>
                </changePolicyCase>
            </changePolicy>
            <changeAlignment>
                <changeAlignmentCase>
                    <alignment>START_OF_BUNDLE</alignment>
                </changeAlignmentCase>
            </changeAlignment>
            <cancelPolicy>
                <cancelPolicyCase>
                    <policy>IMMEDIATE</policy>
                </cancelPolicyCase>
            </cancelPolicy>
            <createAlignment>
                <createAlignmentCase>
                    <alignment>START_OF_BUNDLE</alignment>
                </createAlignmentCase>
            </createAlignment>
            <billingAlignment>
                <billingAlignmentCase>
                    <alignment>ACCOUNT</alignment>
                </billingAlignmentCase>
            </billingAlignment>
            <priceList>
                <priceListCase>
                    <toPriceList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="priceListDefault" name="DEFAULT" retired="false">
                        <plans>
                            <plan>standard-monthly</plan>
                            <plan>sports-monthly</plan>
                            <plan>super-monthly</plan>
                        </plans>
                    </toPriceList>
                </priceListCase>
            </priceList>
        </rules>
        <plans>
            <plan name="standard-monthly" retired="false">
                <product>Standard</product>
                <initialPhases>
                    <phase type="TRIAL">
                        <duration>
                            <unit>DAYS</unit>
                            <number>30</number>
                        </duration>
                        <fixed type="ONE_TIME">
                            <fixedPrice>
<price>
    <currency>USD</currency>
    <value>0</value>
</price>
<price>
    <currency>GBP</currency>
    <value>0</value>
</price>
                            </fixedPrice>
                        </fixed>
                        <usages/>
                    </phase>
                </initialPhases>
                <finalPhase type="EVERGREEN">
                    <duration>
                        <unit>UNLIMITED</unit>
                        <number>-1</number>
                    </duration>
                    <recurring>
                        <billingPeriod>MONTHLY</billingPeriod>
                        <recurringPrice>
                            <price>
<currency>GBP</currency>
<value>75.00</value>
                            </price>
                            <price>
<currency>USD</currency>
<value>100.00</value>
                            </price>
                        </recurringPrice>
                    </recurring>
                    <usages/>
                </finalPhase>
                <plansAllowedInBundle>1</plansAllowedInBundle>
            </plan>
            <plan name="sports-monthly" retired="false">
                <product>Sports</product>
                <initialPhases>
                    <phase type="TRIAL">
                        <duration>
                            <unit>DAYS</unit>
                            <number>30</number>
                        </duration>
                        <fixed type="ONE_TIME">
                            <fixedPrice>
<price>
    <currency>USD</currency>
    <value>0</value>
</price>
<price>
    <currency>GBP</currency>
    <value>0</value>
</price>
                            </fixedPrice>
                        </fixed>
                        <usages/>
                    </phase>
                </initialPhases>
                <finalPhase type="EVERGREEN">
                    <duration>
                        <unit>UNLIMITED</unit>
                        <number>-1</number>
                    </duration>
                    <recurring>
                        <billingPeriod>MONTHLY</billingPeriod>
                        <recurringPrice>
                            <price>
<currency>GBP</currency>
<value>375.00</value>
                            </price>
                            <price>
<currency>USD</currency>
<value>500.00</value>
                            </price>
                        </recurringPrice>
                    </recurring>
                    <usages/>
                </finalPhase>
                <plansAllowedInBundle>1</plansAllowedInBundle>
            </plan>
            <plan name="super-monthly" retired="false">
                <product>Super</product>
                <initialPhases>
                    <phase type="TRIAL">
                        <duration>
                            <unit>DAYS</unit>
                            <number>30</number>
                        </duration>
                        <fixed type="ONE_TIME">
                            <fixedPrice>
<price>
    <currency>USD</currency>
    <value>0</value>
</price>
<price>
    <currency>GBP</currency>
    <value>0</value>
</price>
                            </fixedPrice>
                        </fixed>
                        <usages/>
                    </phase>
                </initialPhases>
                <finalPhase type="EVERGREEN">
                    <duration>
                        <unit>UNLIMITED</unit>
                        <number>-1</number>
                    </duration>
                    <recurring>
                        <billingPeriod>MONTHLY</billingPeriod>
                        <recurringPrice>
                            <price>
<currency>GBP</currency>
<value>750.00</value>
                            </price>
                            <price>
<currency>USD</currency>
<value>1000.00</value>
                            </price>
                        </recurringPrice>
                    </recurring>
                    <usages/>
                </finalPhase>
                <plansAllowedInBundle>1</plansAllowedInBundle>
            </plan>
        </plans>
        <priceLists>
            <defaultPriceList name="DEFAULT" retired="false">
                <plans>
                    <plan>standard-monthly</plan>
                    <plan>sports-monthly</plan>
                    <plan>super-monthly</plan>
                </plans>
            </defaultPriceList>
        </priceLists>
    </catalogVersion>
</catalog>

**Comment by beccagaspard** [comment]
Here's the command I'm using to start killbill: 
> java -jar killbill-profiles-killbill-0.13.3-jetty-console.war

Here's the curl I'm using:
> curl -v \
-u admin:password \
-H "X-Killbill-ApiKey: bob" \
-H "X-Killbill-ApiSecret: lazar" \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
http://127.0.0.1:8080/1.0/kb/catalog

It's the same as yours except for the addition of `-H "Accept: application/json" `.  If I don't add the Accept header, the call succeeds, but returns xml instead of json.

I first noticed the problem using the swagger api ui included in the jetty-console war, so the problem seems to exist there as well.

**Comment by sbrossie** [comment]
Ok got it, i was not using the Accept header.
We have two endpoints, one that returns the catalog in xml and the other in json and so by using the 'Accept' header you are triggering the json one, and there is indeed a bug.

I added that bug in our next release train 0.13.4 so we can fix it soon.

**Comment by pierre** [comment]
Interestingly enough, the error is swallowed by the container when running in embedded mode (tests) or using the Jetty Maven plugin.
