### ISSUE TITLE
New API to retrieve upcoming invoice details

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#279]
The idea is to offer a new API that would return when the customer will be invoiced next and for how much. There is a question on whether we also want to specify the next invoice associated to a given bundle or subscription or if we just export at the account level (which means depending on the billing alignment the next invoice may be just a partial invoice)

It looks like from a plumbing point of view we could use the invoice dryRun API, but the trick is to understand which targetDate to use. One way is to look into the notification table and retrieve the earliest nextBCD notification for the account.

**Comment by RobertoRL** [comment]
Hello guys, can you please point me to the invoice dryRun API you mention above, I'd like to take a look and see how it currently works. Thanks.

**Comment by sbrossie** [comment]
Example of a curl:

> curl -v \
     -X POST \
     -u admin:password \
     -H 'X-Killbill-CreatedBy: admin' \
     -H "X-Killbill-ApiKey: test-api-key1429667045-637777" \
     -H "X-Killbill-ApiSecret: test-api-secret1429667045-637777" \
     -H "Content-Type: application/json" \
'http://127.0.0.1:8080/1.0/kb/invoices/dryRun?targetDate=2013-09-01&accountId=a87eb3ee-7c53-47c9-8617-1a639db9e9c4'
