### ISSUE TITLE
Expose more information to the Mustache engine

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#284]
We could expose tags and custom fields for the account, invoice and invoice items.

See discussion at https://groups.google.com/d/msgid/killbilling-users/14eaa78c-3bf2-4255-9907-96129a5c876f%40googlegroups.com.

Additionally, we should get rid of `DefaultInvoiceTranslator` as the `text` object and use a map instead for flexibility (similar to what the email-notifications plugin is doing).

**Comment by poovarasanvasudevan** [comment]
Is this alive, I am also looking for same, Is their way to add custom field in invoice

**Comment by pierre** [comment]
@poovarasanvasudevan This ticket is about exposing more custom fields to the Mustache engine (when displaying HTML invoices).

You can already add custom fields to invoices via POST /1.0/kb/invoices/`<INVOICE_ID>`/customFields.

Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) in the future for implementation questions.

**Comment by pierre** [comment]
This can be done by using a custom formatter. See https://github.com/SolarNetwork/killbill-invoice-formatter for an example.

**Comment by varunvora** [comment]
The custom formatter is not being maintained. Moreover, I think this would be nice to have in Killbill itself. Is there a plan to include it?

**Comment by pierre** [comment]
Here's the latest documentation regarding how to customize invoice notification emails: https://docs.killbill.io/latest/custom-email-invoice-formatter.html
