### ISSUE TITLE
Retries on push notifications

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#285]
`PushNotificationListener` could use its own notification queue to schedule retries.

See discussion at: https://groups.google.com/d/msgid/killbilling-users/CAJE4nfvdYty4SYyCfe1m94uoJWqaZwLGPCJwAAwCsB4Ht-o50A%40mail.gmail.com

**Comment by matias-aguero-hs** [comment]
@pierre I'm working on this issue. I think we should check fails and only retry when the external server cannot be found. Do you think we can ask for a status = 404 [here](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java#L119)?

Does "retry" means insert this event into notification queue again? In this case, how to know what `serviceName` and `queueName` use.

```Java
    /**
     * Creates a new NotificationQueue for a given associated with the given service and queueName
     *  ...
     */
    NotificationQueue createNotificationQueue(final String svcName, final String queueName, final NotificationQueueHandler handler)
            throws NotificationQueueAlreadyExists;
```

Please correct me if I am not in the same page.

**Comment by pierre** [comment]
> Do you think we can ask for a status = 404 [here](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java#L119)?

I think we should keep the logic as is: if the destination app is down (e.g. connect timeout), or unavailable (e.g. returns 500) or misconfigured (e.g. returns 301), we should assume the notification wasn't received and we should retry later (i.e. send it again).

> Does "retry" means insert this event into notification queue again?

We should create a new queue, independent of the queue of the original event, responsible for these events. The queue would be similar to the one handling [payment retries](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/retry/BaseRetryService.java) and do some sort of [exponential delay retries](https://github.com/killbill/killbill/blob/3e0648aebcac969d7c34ef76987b640b3bf231e2/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L264-L272) over the span of, say, a few days (configurable).

I would also suggest we always insert in this new queue (effective date == `now()`) and attempt to send in the notification queue callback, to [avoid blocking the external bus](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java#L84) (since the HTTP POST can take some time). @sbrossie thoughts?

Does it make sense?

**Comment by pierre** [comment]
> I would also suggest we always insert in this new queue (effective date == `now()`) and attempt to send in the notification queue callback, to [avoid blocking the external bus](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationListener.java#L84) (since the HTTP POST can take some time). 

Scratch that. @sbrossie convinced me that it wasn't worth the added overhead:

* First, the external bus was built specifically to avoid third-party code and systems to block the main bus (the one that really matters)
* Second, no latency guarantee can be made on the external bus, since it invokes third-party code anyways

**Comment by matias-aguero-hs** [comment]
@pierre thanks for clarifications. I think I can start coding the new notification queue. I'll keep you updated.

**Comment by matias-aguero-hs** [comment]
@pierre I created a PR https://github.com/killbill/killbill/pull/589 with this feature implemented.
