### ISSUE TITLE
Duplicate results in payments when refund present

### ISSUE THREAD

**Issue by mkching** [killbill/killbill#289]
The /1.0/kb/invoices/.../payments call is returning the same payment information twice when a refund is present.  Each record had the same paymentId and transaction list.

<pre>
[
    {
        "accountId": "179eb3e8-7b29-427c-8b33-8bfb98fce5c7",
        "auditLogs": null,
        "authAmount": 0,
        "capturedAmount": 0,
        "creditedAmount": 0,
        "currency": "USD",
        "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
        "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
        "paymentMethodId": "46ac78dd-6968-4d4f-9058-84958a2c998b",
        "paymentNumber": "10",
        "purchasedAmount": 17.0,
        "refundedAmount": 3.0,
        "targetInvoiceId": "ded2bce6-d560-4971-ae25-7725e814c721",
        "transactions": [
            {
                "amount": 17.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:07:09.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "19e8072e-d0a4-4f99-8a3b-15e31265aff4",
                "transactionId": "0a1f289a-b04d-4764-9fe4-a70ff629084e",
                "transactionType": "PURCHASE"
            },
            {
                "amount": 2.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:07:53.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "c4661f90-7afc-4b70-86b9-8571155c1763",
                "transactionId": "393e19ec-0041-4888-9a13-483709ec3b44",
                "transactionType": "REFUND"
            },
            {
                "amount": 1.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:08:14.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "a075fd0c-6585-4e90-ba50-20456a9feea4",
                "transactionId": "79c20bdf-9249-420d-9ddd-3770edd22aee",
                "transactionType": "REFUND"
            }
        ]
    },
    {
        "accountId": "179eb3e8-7b29-427c-8b33-8bfb98fce5c7",
        "auditLogs": null,
        "authAmount": 0,
        "capturedAmount": 0,
        "creditedAmount": 0,
        "currency": "USD",
        "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
        "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
        "paymentMethodId": "46ac78dd-6968-4d4f-9058-84958a2c998b",
        "paymentNumber": "10",
        "purchasedAmount": 17.0,
        "refundedAmount": 3.0,
        "targetInvoiceId": "ded2bce6-d560-4971-ae25-7725e814c721",
        "transactions": [
            {
                "amount": 17.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:07:09.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "19e8072e-d0a4-4f99-8a3b-15e31265aff4",
                "transactionId": "0a1f289a-b04d-4764-9fe4-a70ff629084e",
                "transactionType": "PURCHASE"
            },
            {
                "amount": 2.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:07:53.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "c4661f90-7afc-4b70-86b9-8571155c1763",
                "transactionId": "393e19ec-0041-4888-9a13-483709ec3b44",
                "transactionType": "REFUND"
            },
            {
                "amount": 1.0,
                "auditLogs": null,
                "currency": "USD",
                "effectiveDate": "2015-07-09T22:08:14.000Z",
                "firstPaymentReferenceId": null,
                "gatewayErrorCode": null,
                "gatewayErrorMsg": "Transaction approved",
                "paymentExternalKey": "653f164a-40c9-4a60-a9a9-7745478d5b17",
                "paymentId": "68d174f7-24be-4f89-9a01-b6fd92799feb",
                "properties": null,
                "secondPaymentReferenceId": null,
                "status": "SUCCESS",
                "transactionExternalKey": "a075fd0c-6585-4e90-ba50-20456a9feea4",
                "transactionId": "79c20bdf-9249-420d-9ddd-3770edd22aee",
                "transactionType": "REFUND"
            }
        ]
    }
]
</pre>

**Comment by pierre** [comment]
Confirmed. Thanks for the report!

Looking [here](https://github.com/killbill/killbill/blob/a75db153b7013ea05490c8dc78bcf0c5647fa5a3/invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java#L254-L259), `invoicePaymentsForAccount` is a list of invoice payment _transactions_, belonging potentially to the same payment. We should make sure in [JAX-RS](https://github.com/killbill/killbill/blob/a75db153b7013ea05490c8dc78bcf0c5647fa5a3/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L526-L529) to remove duplicates.
