### ISSUE TITLE
Invoice generation through API lacks atomicity

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#29]
Another issues to track in this ticket is that we currently have a possible failure scenario with REST API generation of invoices. Invoice can be generated but failure could happend before charge through date is set.

**Comment by sbrossie** [comment]
We have a few use case, where we would like to i/ have atomicity and ii/ keep our modularity:
* Invoice creation and chargeThroughDate set in subscription
* Payment creation and update invoicePayment table (even more tricky because this is done from a pseudo-plugin)

The first case could be solved by using internal api similar to what we have for bus (by passing a open transaction). It's a bit of a weird api, but this is al;ready what we do.

**Comment by sbrossie** [comment]
> * Payment creation and update invoicePayment table (even more tricky because this is done from a pseudo-plugin)

We created #508 to track that work.

> * Invoice creation and chargeThroughDate set in subscription

We could either use an internal api similar to what we have for bus (by passing a open transaction) as suggested above or have subscription module listen to bus events to update the `chargeThroughDate`

**Comment by pierre** [comment]
See also https://github.com/killbill/killbill/issues/282.
