### ISSUE TITLE
Add Shiro database backend for authentication

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#296]
Similar to what we do for tenants, but to manage users and roles (as an alternative to a static shiro.ini or LDAP). Associated screens to manage these in Kaui would be nice.

**Comment by sbrossie** [comment]
Hum... actually could we have different configs on a per tenant basis? Is that what you meant?

That could be really interesting, but we would still need a global config to bootstrap the process and allow the super admin to upload the per-tenant config?

**Comment by sbrossie** [comment]
Add a new realm backend in both `KillBillShiroModule` and `KillBillShiroWebModule` (one is used for Kill Bill library and one for web version. Currently they support the ini file and LDAP and we want to add a DAO backend.

The work will be similar to what we did in  `TenantFilter` where we add the `KillbillJdbcRealm`.
