### ISSUE TITLE
Optimize push notifications configuration caching

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#297]
Currently, for each bus event, we're going back to the database to look-up the push notification URL. While the tenant query `TenantKVSqlDao.getTenantValueForKey` is fast (tp99 of 6ms in my testing), we end up doing dozens of seconds for nothing.

Note that we already do go through Ehcache, but because we return `null`, we trigger a miss each time. Maybe `TenantKVCacheLoader` should return an empty list instead?

Note that we should also optimize `PushNotificationListener` and bail earlier if there is no push notification configured (instead of preparing the post body for nothing).

**Comment by sbrossie** [comment]
Interesting. Isn't the {k,v} cached with the new cached i introduced for the tenant_kvs table?

**Comment by pierre** [comment]
Nope, because we return `null` (nothing to cache).

**Comment by sbrossie** [comment]
Yes of course. We would to cache some marker to indicate there is nothing.
