### ISSUE TITLE
Review invoice items name and behavior

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#30]
For instance Invoice item type REPAIR_ADJ is not actually an adjustment. It should be renamed to reduce chance of confusion.

**Comment by sbrossie** [comment]
We decided to not change `REPAIR_ADJ` and keep it the way it is.

However for the second piece (REFUND_ADJ and CREDIT_ADJ should also be merged together), the proposal is the following:
* We remove the ability to do invoice ajustement (instead one could credit the invoice), which means `REFUND_ADJ` would not be used
* In the future we remove the enum value `REFUND_ADJ` (and provide a migration query to rename `REFUND_ADJ`  -> `CREDIT_ADJ ` for old data.

**Comment by sbrossie** [comment]
Should we keep the task open for the cleanup piece (when/if we decide one day to remove completely `REFUND_ADJ `) and remove the `Release-0.17.0` milestone or close it?

**Comment by pierre** [comment]
Let's maybe create a different 'future cleanup' task, and consolidate them?

**Comment by sbrossie** [comment]
It seems like we already removed the ability to make invoice adjustment in b7e0697, and deprecated the `RefundAdjInvoiceItem` class. The remaining code is just there for backward compatibility to ensure we still support existing `REFUND_ADJ`.

Should we move forward in `0.17.x` and:
1. Remove all remaining code related to `REFUND_ADJ`
2. Create the migration statement to convert `REFUND_ADJ` into `CREDIT_ADJ` ?
