### ISSUE TITLE
Ability to override prices when creating or updating subscriptions

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#301]
We would like to extend the subscription APIs to be able to specify a custom price when creating a subscription or changing plans. This would fix https://github.com/killbill/killbill/issues/276 for example.

Note that when passing a *price*, we really mean passing an international price (value per currency) per phase and price type (fixed and recurring), for a given plan in a given pricelist. We could skip the override of usage tiers/blocks price for the initial implementation, for simplicity's sake.

## API changes

* Change `EntitlementApi#createBaseEntitlement`, `EntitlementApi#addEntitlement`, `Entitlement#changePlan`, `Entitlement#changePlanWithDate` and `Entitlement#changePlanOverrideBillingPolicy` APIs and add a `PlanOverride` argument (which would only contain the new international prices, per phase and price type, for now)
* Propagate the changes in `Catalog`. Only `findPlan(String productName, BillingPeriod billingPeriod, String priceListName, DateTime requestedDate)` and `findPlan(String productName, BillingPeriod billingPeriod, String priceListName, DateTime subscriptionStartDate)` should be impacted (to be verified) and accept the additional parameter. Regarding the implementation, when the plan for a given override doesn't exist yet, create it on the fly (see below).

## Catalog changes

* Add a new `plan_overrides` table, owned by the catalog module. The table would contain the old plan name, the old phase name, the new fixed and recurring price (one row per currency: the overrides will be flat instead of a N:M mapping) and the `tenant_record_id`
* Change the catalog cache loader `EhCacheCatalogCache` to merge the catalog XML and the overridden prices by generating new plans for these overrides. This makes sure that APIs such as `Catalog#getPlans` will return all plans, including virtual ones
* When a new override needs to be created, invalid the catalog cache

**Comment by sbrossie** [comment]
What is the form of the API (to pass the additional prices when we create the subscription. It seems like we have two choices:
1. We could pass an array of prices, where each entry in the array would match a specific phase; that means if we have a 3 phases plan we need 3 entries ion the array, and if we only want to override the last one, the first two would be set to null -- and of course we actually need two of those, to also take care of fixed prices
2. We could pass a well formed array of object, where the object would be
* phaseName
* overrideFixedPrice
* overridePrice

2/ is cleaner, but requires having to know and specify each phaseName when making the call.

**Comment by sbrossie** [comment]
Closed with 
107daa072ad1b1001fa5ff44282396a4c78dc719
da31a90b118786d4a0c43b9d123e9540b8421e54
cb291df243a417203465387fb033c8e9864597ba
c40dc21c027b253b8ce6294284713e2f16ea7a13
9f729f0e254cc0cb3e7679021deb8fe8dbb9b75d
2a9ed5ff34ea7fc10f404251f3c3fa60e93166d2
91d7d5d23cfab1124521774c53098f8cab863c34
