### ISSUE TITLE
Add an endpoint to invalidate Kill Bill ehcache

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#304]
We have more and more caching in Kill Bill and so this might be handy for 2 cases:
* Production case if/when we suspect any caching issues
* Testing case so we can clear DB state and not have to restart KB

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
I can work on this issue.
Could you add more details please?

Thanks!

**Comment by pierre** [comment]
Kill Bill uses a variety of caches (see [EhCacheCacheManagerProvider](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/cache/EhCacheCacheManagerProvider.java)). They are immutable today though (no invalidation mechanism).

The goal of this task is to add an endpoint to provide invalidation (clear a given cache).

Note that we'd like to upgrade to [Ehcache 3](https://github.com/killbill/killbill/issues/587). Unclear if it's easier to do this, then upgrade and update the code as needed, or instead upgrade first and write the code against the new API. Your call (I've also commented on https://github.com/killbill/killbill/issues/587 with some context).

**Comment by javier-gomez-hs** [comment]
Hi @pierre, I have a few questions about this implementation.

>The goal of this task is to add an endpoint to provide invalidation (clear a given cache).

The **given cache**, will be the name of the cache defined in the [ehcache.xml](https://github.com/javier-gomez-hs/killbill/blob/11beef681757729a3162225bc637f9d7bc71fd2f/util/src/main/resources/ehcache.xml#L48) file? As a String for example?

The main idea is to **invalidate** the cache by calling the [dispose()](https://github.com/javier-gomez-hs/killbill/blob/a21ffe26fadf2386f571f39e0ab42c42d0552bb4/util/src/main/java/org/killbill/billing/util/cache/BaseCacheLoader.java#L81-L81) method and clear / clean / stop using that specific cache until it gets loaded again by the application? Or should I dispose the specified cache and then start it again with the [init()](https://github.com/javier-gomez-hs/killbill/blob/a21ffe26fadf2386f571f39e0ab42c42d0552bb4/util/src/main/java/org/killbill/billing/util/cache/BaseCacheLoader.java#L75-L75) method?

I might need to create a new Resource in the JAX-RS module. Is that right?

Thanks in advance!

**Comment by pierre** [comment]
> The **given cache**, will be the name of the cache defined in the [ehcache.xml](https://github.com/javier-gomez-hs/killbill/blob/11beef681757729a3162225bc637f9d7bc71fd2f/util/src/main/resources/ehcache.xml#L48) file? As a String for example?

Yup, I think using the cache name from the XML would make sense.

A subset of the caches are available through the `org.killbill.billing.util.cache.Cachable.CacheType` enum, but not all of them (e.g. Shiro ones - see `ShiroEhCacheInstrumentor`).

> The main idea is to **invalidate** the cache by calling the [dispose()](https://github.com/javier-gomez-hs/killbill/blob/a21ffe26fadf2386f571f39e0ab42c42d0552bb4/util/src/main/java/org/killbill/billing/util/cache/BaseCacheLoader.java#L81-L81) method and clear / clean / stop using that specific cache until it gets loaded again by the application? Or should I dispose the specified cache and then start it again with the [init()](https://github.com/javier-gomez-hs/killbill/blob/a21ffe26fadf2386f571f39e0ab42c42d0552bb4/util/src/main/java/org/killbill/billing/util/cache/BaseCacheLoader.java#L75-L75) method?

While you could go that way, and re-implement some of the logic of [EhCacheCacheManagerProvider](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/cache/EhCacheCacheManagerProvider.java#L99-L120), I'm afraid of race conditions.

Could you invoke `removeAll()` instead on the `Ehcache` object?

> I might need to create a new Resource in the JAX-RS module. Is that right?

No strong feeling, but maybe we could re-use `TestResource`. @sbrossie, any thought?

**Comment by javier-gomez-hs** [comment]
@pierre 
Thanks for the suggestions and information.
I have successfully added the endpoint and I can confirm that it is clearing the cache.
You can see my new method [here](https://github.com/javier-gomez-hs/killbill/blob/03dde764eaaa3434e35cadb3e28bc3c95a3df766/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TestResource.java#L218-L218).
For the Integration Test case, I've seen that the `killbill-client-java` does not have any call that points to the TestResource endpoints.
Should I add the method in the client to call my new endpoint?

Thanks!

**Comment by pierre** [comment]
> I have successfully added the endpoint and I can confirm that it is clearing the cache.

🎉 

> Should I add the method in the client to call my new endpoint?

Yes, I think that would make sense (it looks like we don't have anything for the clock either -- something we'll want to add eventually, as it can be useful for integration tests).

Thanks!

**Comment by javier-gomez-hs** [comment]
@pierre 
I've created the Pull Requests with my changes in:
- [killbill-core](https://github.com/killbill/killbill/pull/602)
- [killbill-client-java](https://github.com/killbill/killbill-client-java/pull/45)
- [killbill-oss-parent](https://github.com/killbill/killbill-oss-parent/pull/11)

Please feel free to take a look and let me know if I have to add /change anything else.

Thanks!
