### ISSUE TITLE
'retired' option from catalog object does not seem to have been implemented

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#306]
The catalog `Product`,  `Plan` and `Pricelist` can take a `retired` parameter. However by looking through the code, i am not seeing any logic doing filtering on that attribute. However:
* Our main documentation claims this is mandatory to retire plans that way versus remove the entries from the catalog -- which in theory is not supported
 * Also, what should be the relationship between retiring at Product, Plan or Pricelist level. Do we need all of them for instance?
* Finally what should be the semantics associated with it? For e.g, hhould findPlan API return the `retired` entries or not?

**Comment by sbrossie** [comment]
Actually there is some code that checks for that flag @see https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/VersionedCatalog.java#L337

But nobody seems to call that API.

**Comment by maguero** [comment]
Hi @sbrossie, what we need to do for this issue? I was reviewing the code but I'm not sure what and where I need to implement it.

**Comment by sbrossie** [comment]
@maguero We would like the ability to 'retire' plans in a multi-version catalog. Example:
* Customer subscribes to plan 'A' at date T1
* Later we decide to remove plan 'A at date T2
* Customer cannot subscribes to plan 'A' anymore but old subscription should still work as expected.

Initially the catalog code planned for that use case by introducing a `retired` flag but looking though the code it does not seem to be used very much. It also seems that by *just* removing the entry (`plan A` from the next catalog version, things should just work as expected.

So the work is:
1. Verify if today removing entries just produce the right result. We already have multi-version [catalog tests written in ruby](https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/core/test_catalog.rb), but we could also add some at the `beatrix` level in java.
2. If this is the case remove all `retired` code and update catalog doc to remove it; if not implement `retired` correctly

Note: The ability to retire catalog entries should work at the `Product`, `Plan` and `Pricelist` level.

**Comment by maguero** [comment]
@sbrossie I tried your scenario and it is working as spected with Plans.

Steps:
* I setup versioned catalogs (4 "WeaponsHireSmall" catalogs)
* I created a subscription to plan 'Pistol' at date T1
* I move time to T2 (T2 > T1) and last versioned catalog started (without 'Pistol' plan).
* I tried to create a new 'Pistol' subscription and I got the error message "Could not find a plan matching: (product: 'Pistol', billing period: 'MONTHLY'..."
* I finally verified that the previous 'Pistol' subscriptions still working and invoices are generating.

I'm going to create some tests to verify remove Plans, Products and PriceLists.

**Comment by maguero** [comment]
I created some tests at beatrix level with versioned catalogs, removing plan, product and pricelist in the different versions. Plans and Products worked as expected, but it seems that we can't remove a PriceList if there is an active plan that was created over it. It fails when clock moves out a month and a new invoice is generated.

```log
[main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2015-10-05T00:00:02.000Z to 2015-11-05T00:00:02.000Z     ********************
[bus_ext_events-lifecycle-th-1] WARN org.killbill.queue.DBBackedQueue - DBBackedQueue-bus-bus_ext_events: batchClaimEntries see 0 entries 
[bus_events-th] WARN org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi - Failed while getting BillingEvent
{cause={cause=null, code=2013, formattedMsg='Could not find a pricelist with name 'SpecialDiscount''}, code=2013, formattedMsg='Could not find a pricelist with name 'SpecialDiscount''}
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForBundle(DefaultSubscriptionInternalApi.java:271)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.addBillingEventsForBundles(DefaultInternalBillingApi.java:148)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.getBillingEventsForAccountAndUpdateAccountBCD(DefaultInternalBillingApi.java:102)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:235)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:213)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:199)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:174)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:170)
	at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by sbrossie** [comment]
> but it seems that we can't remove a PriceList if there is an active plan that was created over it. 
@maguero Do you mean if you remove a pricelist in a new version for which there are still existing plans (from that pricelist) ? If you remove a pricelist, all the plans from the pricelist should be removed as well, or if not an error should be thrown. Is that what you see? 

Maybe you start a PR against that bug so we can follow your tests more easily.

**Comment by maguero** [comment]
my bad... I refactored my test and I noticed that moving multiple months throws some unexpected exceptions.

```Java
busHandler.pushExpectedEvents(NextEvent.INVOICE, NextEvent.PAYMENT, NextEvent.INVOICE, NextEvent.PAYMENT);
clock.addMonths(2);
assertListenerStatus();
```

Good news is that I was able to verify that Plan, Product and PriceList can ve removed on versioned catalogs and the previous subcriptions created with those removed elements continue working as expected. You can find the tests [here](https://github.com/maguero/killbill/commit/e75d16a380aff936c424f5a37cbabdf8bada9fa0).

**Comment by maguero** [comment]
Summary:
* Tests confirmed that "retired" option is not used and versioned catalogs supply this feature.
* "Retired" option is removed from Plan, Product and PriceList.

PR:
* killbill-api: https://github.com/killbill/killbill-api/pull/7
* killbill: https://github.com/killbill/killbill/pull/437

Note: killbill-oss-parent/pom.xml need to be updated to point killbill-api changes.
