### ISSUE TITLE
Reduce lock names size

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#309]
MySQL 5.7.5 and later enforces a maximum length on lock names of 64 characters. Previously, no limit was enforced.

See discussion: https://groups.google.com/forum/#!msg/killbilling-users/iqB1e5NjWMM/9E8mUSts4I8J

**Comment by sbrossie** [comment]
That should be trivial to fix, just need to rename the Enum `LockerType` field `ACCOUNT_FOR_INVOICE_PAYMENTS` with something smaller such as `ACCNT_INV_PAY`.
