### ISSUE TITLE
Should InvoicePluginDispatcher allow CREDIT_ADJ?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#313]
The use-case would be for invoice plugins to add credits (e.g. coupon plugin).

**Comment by gesterhuizen** [comment]
I'm still ramping up on the domain model. But this sounds like a good thing to have. In general, I would support a model with enough flexibility to accommodate different business rules. Provided, of course, the rules stay consistent, sane and moderately easy to reason about and understand.

**Comment by sbrossie** [comment]
@gesterhuizen Yes this is what we need to consider: being more permissive is OK, as long as this does not create an inconsistent state. I don't see what kind of issues that would trigger in that case (since credit_adj can be generated from AP), so i would be tempted to say that we should add it.
