### ISSUE TITLE
Specifying a bundle external key when adding an AO throws a incorrect exception.

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#315]
See reported issue https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/killbilling-users/LIPQNoCSZQI/SgKiPlWt1ScJ

**Comment by sbrossie** [comment]
We should obviously fix the wrong error code, but also allow users to ONLY specify the bundleExternalKey (in place of of the bundleId, which requires first fetching base subscription of bundle).

**Comment by maguero** [comment]
this is fixed. PR: https://github.com/killbill/killbill/pull/434

**Comment by sbrossie** [comment]
@maguero I think my comment was confusing. By *ONLY* i did not mean we should remove the ability to specify a `bundleId`, i meant that if a user were to *only* specify a `bundleExternalKey` things should work.

**Comment by maguero** [comment]
No problem, I'll add bundleId back.
Thanks.
