### ISSUE TITLE
Implement recurring billing mode IN_ARREAR

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#321]
(See thread: https://groups.google.com/forum/#!msg/killbilling-users/kTKAX38bh10/3a42O50j_k0J)

The main differences, between the IN_ADVANCE and IN_ARREAR are:
* The targetDate of the invoice will be used to compute the past invoice (IN_ARREAR) or the upcoming invoice (IN_ADVANCE). Most of the code that we wrote (BillingIntervalDetail, ...) to deal with the period, targetDate, ... should be reusable . You should not have to write too much code, or then you are probably on the wrong path.
* For IN_ARREAR, the logic should be simpler, because there is no 'REPAIR' since you have all the information at the time you create the invoice, so this is simpler.

In file https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/generator/DefaultInvoiceGenerator.java:
* The 'generateInvoice' method will be modified to NOT call 'generateInAdvanceInvoiceItems', but instead call a more generic method that will look at the current value of the 'recurringBillingMode' in your catalog. Note that we have some abstraction for the billingMode , see 'instantiateBillingMode', but this is not plugged at the right place-- some old implementation. So you will have to reshuffle things a bit.
* The usage sections also have a 'billingMode', so if you want to also do usage InArrear, you will also have to look at what we do in 'generateUsageInvoiceItems. I am unclear if this is something you are interested in.

**Comment by sumit-gupta-sgt** [comment]
+1

**Comment by sbrossie** [comment]
Fixed with 41bfa0aaa3defd77c0d1c91f3cd8befafa16d1f9, 7d8f44cf5d4536d4f99b1635e61b1f5c1e4b2dd6, f1b2815d8afe32656fc857f22ea5c4b21722bbcc

**Comment by sbrossie** [comment]
@sumit-gupta-sgt @beccagaspard I am not sure if you are still interested and looking into that but that should not be available for you.
