### ISSUE TITLE
Review length of plan_name and phase_name in invoice_items table

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#322]
See discussion on the [mailing-list](https://groups.google.com/d/msgid/killbilling-users/bb58bd38-b78d-4b9e-99b4-33bae3983c56%40googlegroups.com).

**Comment by almalki** [comment]
I create a PR for this issue
https://github.com/killbill/killbill/pull/500

**Comment by pierre** [comment]
Columns for catalog entries have been normalized and now match the length in the catalog overrides tables.

**Comment by pierre** [comment]
See https://github.com/killbill/killbill/commit/6353737c2207503bd37f3d111d2fd2a44b268242.
