### ISSUE TITLE
reduce contention introduced by UUID.randomUUID

### ISSUE THREAD

**Issue by kares** [killbill/killbill#323]
since it's using a single `SecureRandom` instance but it's called from many places (threads)

... for a relatively early **30s** snapshot it is called 73 times and contention goes up to `~3.5s`
(it does get a little better over time, but still after 3h for a **60s** snapshot `randomUUID` is called 72 times - contention seems to be around `2.5s`)

could be improved by implementing a "secure" kind of `ThreadLocalRandom` which might introduce the cost of creating `SecureRandom` instances so maybe a "pool" would be better (either way it should be hidden behind a service interface).

![securerandom_contention](https://cloud.githubusercontent.com/assets/45967/7684136/180aecf6-fd84-11e4-818c-81d537675bf5.jpg)

**Comment by pierre** [comment]
> it's called from many places (threads)

Yes! Yes! Yes! My favorite open bug: https://github.com/killbill/killbill/issues/35. It has been on my radar for a very long time...

> could be improved by implementing a "secure" kind of `ThreadLocalRandom` which might introduce the cost of creating `SecureRandom` instances so maybe a "pool" would be better (either way it should be hidden behind a service interface).

https://github.com/cowtowncoder/java-uuid-generator might be able to help? Maybe @cowtowncoder can chime in?

**Comment by kares** [comment]
> https://github.com/cowtowncoder/java-uuid-generator might be able to help?

been looking that way as well, seems fine. 
still for performance reasons we should tune https://github.com/cowtowncoder/java-uuid-generator/blob/3.0/src/main/java/com/fasterxml/uuid/impl/RandomBasedGenerator.java to get a thread-local SecureRandom

**Comment by cowtowncoder** [comment]
Or, perhaps use `ThreadLocal` for passing generator itself?

**Comment by kares** [comment]
been using a thread-local and I can confirm the `SecureRandom` contention is gone :hammer: 

... relevant commit: https://github.com/kares/killbill/commit/5f5f4511da2aae271d4cd298b9d1d0ebecfa8f4f#diff-23f11e4e3fa09763f147823ae98458e1R28

mentioned random instance pooling since lately I have noticed some issues (from the JRuby community) related to slowness due `SecureRandom` initialization (if there's not enough system entropy available from */dev/random* it will wait) ... since I wasn't sure I checked the Sun provider's implementation and can confirm that pooling is irrelevant (it potentially only happens once as a shared seeder generator is created and not for every `new SecureRandom()`).

also this article confirmed the observations http://www.cigital.com/justice-league-blog/2014/01/06/issues-when-using-java-securerandom/ ("BLOCKING" section)

**Comment by cowtowncoder** [comment]
Yes, initialization of `SecureRandom` may take very long time (multiple seconds). So in that sense, even sharing a single instance can often help.

**Comment by kares** [comment]
while the thread-local helped (KB showed major contention in other parts e.g. jruby-openssl) after fixing others it sort of occasionally (does not show always but went it does it's considerable) came back : 

![securerandom_convention_v2](https://cloud.githubusercontent.com/assets/45967/7792611/8f98a750-02b5-11e5-98ed-608a2311aac1.jpg)

![securerandom_convention2_v2](https://cloud.githubusercontent.com/assets/45967/7792636/e30133b2-02b5-11e5-8288-7cb1893664cf.jpg)

... at this point it seems that the only resolution would be using a different `SecureRandom` impl or simply not using v4 type UUIDs (at least on a few places) if that is an option at all.

**Comment by kares** [comment]
wanted to try a second service here with a 'custom' SHA1PRNG implementation, still using Java's `SecureRandom` as a (default) seeder but hopefully avoid any possible contention during `nextBytes` : 

so ended up with a quick prototype (based on bouncy-castle code) https://github.com/kares/killbill/commit/e688bd8a0b59250bb1a3058e7457881978e5d421

... unfortunately tests failed which kind of made no sense how the way UUIDs are generated cause : 

```
[notifications-th] WARN org.killbill.billing.payment.core.sm.RetryOperationCallback - RetryOperationCallback failed for account 250a1fdf-d5f4-470f-b38c-d73d7cd19805
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:202)
	at org.killbill.billing.payment.dispatcher.PluginDispatcher.dispatchWithTimeout(PluginDispatcher.java:52)
	at org.killbill.billing.payment.dispatcher.PluginDispatcher.dispatchWithTimeout(PluginDispatcher.java:45)
	at org.killbill.billing.payment.core.sm.OperationCallbackBase.dispatchWithAccountLockAndTimeout(OperationCallbackBase.java:65)
	at org.killbill.billing.payment.core.sm.RetryOperationCallback.doOperationCallback(RetryOperationCallback.java:78)
	at org.killbill.automaton.DefaultOperation.run(DefaultOperation.java:51)
	at org.killbill.automaton.DefaultState.runOperation(DefaultState.java:80)
	at org.killbill.billing.payment.core.sm.PluginRoutingPaymentAutomatonRunner.run(PluginRoutingPaymentAutomatonRunner.java:106)
	at org.killbill.billing.payment.core.PluginRoutingPaymentProcessor.retryPaymentTransaction(PluginRoutingPaymentProcessor.java:213)
	at org.killbill.billing.payment.retry.DefaultRetryService.retryPaymentTransaction(DefaultRetryService.java:49)
	at org.killbill.billing.payment.retry.BaseRetryService$1.handleReadyNotification(BaseRetryService.java:73)
	at org.killbill.notificationq.MockNotificationQueueService.doProcessEventsForQueue(MockNotificationQueueService.java:85)
	at org.killbill.notificationq.MockNotificationQueueService.doProcessEvents(MockNotificationQueueService.java:64)
	at org.killbill.queue.DefaultQueueLifecycle$1.run(DefaultQueueLifecycle.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.killbill.billing.payment.core.sm.RetryOperationCallback$1.doOperation(RetryOperationCallback.java:117)
	at org.killbill.billing.payment.core.sm.RetryOperationCallback$1.doOperation(RetryOperationCallback.java:78)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:219)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:208)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	... 3 more
```

... but with this change I'm also unable to run the server as it timeouts on contention retrieval :)

**Comment by pierre** [comment]
I ran fast (-Ptravis), slow (-Ph2, -Pmysql) and twice the Ruby integration tests. No issue.
[Travis](https://travis-ci.org/killbill/killbill/builds/66761014) tests are running and I'll try to re-run a flood.io test this week just to confirm.

So, it looks good to me, but I would love to get to the bottom of your issue :crying_cat_face:

**Comment by pierre** [comment]
> So, it looks good to me, but I would love to get to the bottom of your issue :crying_cat_face:

@kares: could it be related to low entropy (see https://github.com/killbill/killbill/issues/336 for details)?

**Comment by kares** [comment]
well (as usual) I'm paranoid so it could, but little sense (for now) ... tests and server always work when using `SecureRandom` per thread (have not seen any failure there yet) - in case of `java.util.Random` or the `LightRandom` the secure random is only used as a seeder. 

did a quick test re-run (failed) ... checked that I had 1556 entropy available (I'm using a Linux box locally)

**Comment by pierre** [comment]
> did a quick test re-run (failed) ... checked that I had 1556 entropy available (I'm using a Linux box locally)

Do you have rng-tools and/or haveged installed? I'm curious if running them would make a difference. 1556 might still be a bit low, making the code slower and triggering the timeouts in the tests.

**Comment by kares** [comment]
seems you were right ... I just run some more tests and it seems related (thus the only reason I can think of it not being triggered when using a thread-local `SecureRandom` would be some internal contention since the seeding ~ the same?)

tried https://github.com/kares/killbill/commit/89ea461b3fc1a87b79cade9391ee29c79002170b ... still failures, than I installed the **rngd** daemon and test now pass fine (as much as I tested ... a few runs) ... `cat /proc/sys/kernel/random/entropy_avail` > 3000

**Comment by pierre** [comment]
> tried https://github.com/kares/killbill/commit/89ea461b3fc1a87b79cade9391ee29c79002170b ... still failures, than I installed the **rngd** daemon and test now pass fine 

Ah, it looks like `SHA1PRNG ` still uses `/dev/random`, but only for seeding: https://github.com/jruby/jruby/issues/1405#issuecomment-32582661. According to the thread, `SHA1PRNG` seems to be the fastest option.

**Comment by pierre** [comment]
Switching to `SHA1PRNG` triggered a Travis build failure: https://travis-ci.org/killbill/killbill/jobs/67156466 :crying_cat_face: 

Relevant: https://github.com/travis-ci/travis-ci/issues/1494 and https://github.com/travis-ci/travis-ci/issues/1495.

**Comment by kares** [comment]
seems like another timeout ... related to low entropy at travis' (likely due `generateSeed`).
as stated in the jruby thread comment, we need to avoid using `generateSeed` to avoid contention completely (and simply use `seeder.nextBytes` as the local RNG seed) ... which sounds just fine to do here, right ?

also, maybe it make sense for travis-ci to have some of the same properties set `-Djava.security.egd` ?

**Comment by pierre** [comment]
I've updated the travis config in b54a7f78e6583ab149cd803135d27d150ea76b7d ([green build](https://travis-ci.org/killbill/killbill/builds/68146936)). I'll merge it into master for 0.15.0, so we can get more testing.
