### ISSUE TITLE
Slow performance of Shiro query

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#326]
Seen on RDS:

```
update sessions set
  start_timestamp = '05/26/2015 15:02:09.000'
, last_access_time = '05/26/2015 15:25:18.063'
, timeout = 3600000
, host = 'X.X.X.X'
, session_data = '<byte[]>'
where record_id = 14
;
 {executed in 30053 msec}
```

**Comment by pierre** [comment]
@sbrossie :warning: That needs to be reverted in master (the initial error was caused by missing I/O credits on EC2).

I had already done the revert in my `kares-uuid` branch, so I think you can just simply merge  `kares-uuid` into master (see https://github.com/killbill/killbill/compare/master...kares-uuid).

**Comment by sbrossie** [comment]
OK i am bit unclear, on whether there is something to change on my side, or if this is something you will take care of. Add in the Todo list to discuss.

**Comment by pierre** [comment]
No worries, I just did the merge.
