### ISSUE TITLE
Add missing API payment control APIs

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#329]
We already have the following payment API (control):
* createAuthorizationWithPaymentControl
* createPurchaseWithPaymentControl
* createRefundWithPaymentControl
* createCreditWithPaymentControl
* createChargebackWithPaymentControl

We are missing the following:
* createCaptureWithPaymentControl
* createVoidWithPaymentControl 
* notifyPendingTransactionOfStateChangedWithPaymentControl (exists but no implemented)

**Comment by pierre** [comment]
We might also need (in `PaymentGatewayApi`):

 * `buildFormDescriptorWithPaymentControl`
 * `processNotificationWithPaymentControl`

**Comment by pierre** [comment]
For `buildFormDescriptorWithPaymentControl`, the adjusted properties returned by `onSuccessCall` should be added to `HostedPaymentPageFormDescriptorJson#properties`.

**Comment by sbrossie** [comment]
We will add the following types to be able to plug the payment control api within the `PaymentGatewayApi`:



 `public enum PaymentApiType {
        PAYMENT_TRANSACTION,
        HPP,
        NOTIFICATION
    }`

And:

    `public enum HPPType {
        BUILD_FORM_DESCRIPTOR
    }`
