### ISSUE TITLE
There are payments where more was captured than authorized

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill#333]
I believe that the capture should have failed.

select
    payment_id
    ,case when incoming_funds > authorized_funds and outgoing_funds > incoming_funds then 'INCOMING>AUTH & OUTGOING>INCOMING'
		  when incoming_funds > authorized_funds then 'INCOMING>AUTH'
          when outgoing_funds > incoming_funds then 'OUTGOING>INCOMING' 
     end as problem_reason
    ,authorized_funds
    ,incoming_funds
    ,outgoing_funds
from (
select 
    pt.payment_id
    ,sum(case when pt.transaction_type in ('AUTHORIZE','PURCHASE') then pt.amount else 0 end) authorized_funds
    ,sum(case when pt.transaction_type in ('PURCHASE','CAPTURE') then pt.amount else 0 end) incoming_funds
    ,sum(case when pt.transaction_type in ('REFUND','CHARGEBACK','VOID') then pt.amount else 0 end) outgoing_funds
from
    payment_transactions pt
where 1=1
    and pt.transaction_status = 'SUCCESS'
group by 1    
) t1
where 1!=1
    or incoming_funds > authorized_funds

**Comment by sbrossie** [comment]
Which gateway were those payments using? I don't believe KB will check amounts, but the gateway/payment processor should. Also, as i write that, i think Payment processor actually allow a capture greater than authorize amounts (for instance to take care of tips in restaurant, ...) Unclear. My point is i am not sure this is a bug. We need more details.

**Comment by kevinpostlewaite** [comment]
This is for killbill-cybersource. If this is not valid case to test, just let me know but that seems a little strange

**Comment by pierre** [comment]
For CyberSource specifically, they return a special error code 235 `The requested capture amount exceeds the originally authorized amount`, see page 351 of [Credit_Cards_SO_API.pdf](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SO_API/Credit_Cards_SO_API.pdf). On that same guide, page 47, you can see that some specific processors require the captured amount to be less than or equal to the authorized amount, but it is unspecified for others.

Finally, this behavior is probably not enforced in the sandbox environment.

**Comment by pierre** [comment]
@kevinpostlewaite Is there something more to be investigated?

**Comment by kevinpostlewaite** [comment]
This can be closed
