### ISSUE TITLE
Payments with more refunded than captured

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill#334]
I believe that the refund should have failed.

select
    payment_id
    ,case when incoming_funds > authorized_funds and outgoing_funds > incoming_funds then 'INCOMING>AUTH & OUTGOING>INCOMING'
		  when incoming_funds > authorized_funds then 'INCOMING>AUTH'
          when outgoing_funds > incoming_funds then 'OUTGOING>INCOMING' 
     end as problem_reason
    ,authorized_funds
    ,incoming_funds
    ,outgoing_funds
from (
select 
    pt.payment_id
    ,sum(case when pt.transaction_type in ('AUTHORIZE','PURCHASE') then pt.amount else 0 end) authorized_funds
    ,sum(case when pt.transaction_type in ('PURCHASE','CAPTURE') then pt.amount else 0 end) incoming_funds
    ,sum(case when pt.transaction_type in ('REFUND','CHARGEBACK','VOID') then pt.amount else 0 end) outgoing_funds
from
    payment_transactions pt
where 1=1
    and pt.transaction_status = 'SUCCESS'
group by 1    
) t1
where 1!=1
   or outgoing_funds > incoming_funds

**Comment by pierre** [comment]
Same remarks as https://github.com/killbill/killbill/issues/333. For CyberSource specifically, see page 59 of  [Credit_Cards_SO_API.pdf](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SO_API/Credit_Cards_SO_API.pdf).

**Comment by kevinpostlewaite** [comment]
This can be closed.
