### ISSUE TITLE
New API to retrieve history info from any objects 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#335]
_See bottom comment for the design proposal_

Note: This task really belong under API, but will be more visible here

In the same way we have an [AuditLog API](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/util/api/AuditUserApi.java), we probably need something for history.

Also, we should thing whether audit and history should be returned at the same time, or are there 2 APIs.  Probably something to look at as we redesign our UI.

**Comment by pierre** [comment]
See also https://github.com/killbill/killbill/issues/247.

**Comment by sbrossie** [comment]
/cc @pierre A few topics for discussion:

1. Do we want streaming - like api -- [see existing audit log implementation](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/audit/dao/DefaultAuditDao.java#L73) ?
2. Do we want to also add some caching similarly to what is being done for [audit logs](https://github.com/killbill/killbill/blob/master/util/src/main/resources/ehcache.xml#L34) ?
3.  Do we want end point for history, or combine history on a per call basis, the way this is done for audit logs -- probably we should revisit the use case ?

**Comment by pierre** [comment]
> 1. Do we want streaming - like api -- [see existing audit log implementation](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/audit/dao/DefaultAuditDao.java#L73) ?

I don't think we stream audit logs today: https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/audit/DefaultAccountAuditLogs.java#L49

In any case, I would offer similar APIs between history and audit logs, for simplicity.

> 2. Do we want to also add some caching similarly to what is being done for [audit logs](https://github.com/killbill/killbill/blob/master/util/src/main/resources/ehcache.xml#L34) ?

I wouldn't bother: the caching for audit logs is mainly to speed up Analytics and Kaui, but I don't expect the history APIs to be as heavily used (mainly for adhoc debugging / investigations and tests).

> 3.  Do we want end point for history, or combine history on a per call basis, the way this is done for audit logs -- probably we should revisit the use case ?

I would just add a new specific endpoint, for simplicity. My thinking is that it will be used as an explicit AJAX call on some Kaui screens (➕ sign -- or similar -- to display history, and I don't even think we would want to extend the billing timeline, as it's already verbose), or as adhoc cURLs.
