### ISSUE TITLE
Janitor test scenarios with popular plugins

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#337]
While we have come up with a generic Janitor framework to guess as much as we can what the plugins are trying to tell us, in practice, we need to take a look at individual implementations, as the behavior of the gateways vary quite a lot (see for example https://github.com/killbill/killbill-cybersource-plugin/issues/4).

We should write a couple of generic tests (maybe in https://github.com/killbill/killbill-integration-tests) that we run manually against the individual plugins, and verify the behavior, such as:

* Bad payment method (old credit card or cvv) and/or values (negative amount, wrong currency, etc.) passed during the payment call
* Trigger a RuntimeException (maybe we can find a flaw in ActiveMerchant, like pass a number where a string is expected)
* Force the Janitor to poll a `PENDING` payment that is unknown by the plugin/gateway

The goal is to cover most of the _classic_ failure use cases that may happen in production.

**Comment by pierre** [comment]
See also https://github.com/killbill/killbill-adyen-plugin/issues/2 and https://github.com/killbill/killbill-plugin-framework-ruby/issues/44.

**Comment by sbrossie** [comment]
:+1:

**Comment by pierre** [comment]
For Ruby plugins, generic ActiveMerchant tests have been written, as well as CyberSource specific ones.

For Java plugins, we should look at Adyen in more details, and write generic tests for our [HttpClient](https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/util/http/HttpClient.java).

**Comment by pierre** [comment]
The work for Adyen was done here: https://github.com/killbill/killbill-adyen-plugin/pull/12 (directly in the plugin, as it doesn't use the base HttpClient).

More work will be required on a per-plugin basis.
