### ISSUE TITLE
Hierarchical accounts

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#339]
# Requirements

* Ability to represent a tree of companies: A _owns_ B,C,D ; B _owns_ a,b,c ; etc.
* Ability to configure a company whether it _owns_ its billing and its payments (if not, this is delegated to its parent, and so on)
* Ability to override the payment method per company (B uses payment method A1, C uses A2, etc.).
* Ability to retrieve invoices at a company level, including the children companies
* Ability for a company to use the payment method of (one of) the parent
* Export the relationship in the Analytics tables

Note that in the data model, the invoices will still belong to a given company, but at the API level, one can retrieve all of the invoices for the children. It is up to the presentation layer to decide which invoices to display. However, all payments belong to the company owning the payment (e.g. the parent).

# Implementation

* A company is represented by an account
* New tree representation in the account sub module
* `InvoiceUserApi#getInvoicesByAccount` change to return the invoices of the children
* Payment sub-module switches account if needed to trigger payments (payment belongs to the parent, but invoices to the child)
* invoice_payments table should point to the child account (invoice table)

# Questions

* How does payment methods management work? Should we introduce the concept of billing record?
* Delegation Model:
  * If a company/user does not delegate its payment/billing, does it make sense to still have it part of the tree? What do we get out of it?
  * Do billing & payment necessarily go hand in hand in delegation model (actually is there such a such a thing as delegating billing since we child would be invoiced)?

**Comment by zsmith928** [comment]
One thing I'd like to see in the API at the Parent Company level would be to get a consolidated Statement or Invoice, that includes all the sub accounts clearly broken out.  This would be different than fetching all the invoices, but would be an ability to have terms/billing and billing "statement" presentment at the Parent Company hierarchy level.

**Comment by pierre** [comment]
@zsmith928 Any thought regarding transfers of subscriptions between (sub-)accounts and/or sub-accounts themselves (in the same or different hierarchy)? Particularly: what should happen regarding the invoices and payments history? I'm thinking they should not transfer (also, an account needs to be _clean_, i.e. $0 balance, before being able to be migrated).

**Comment by sbrossie** [comment]
In a second round of design / requirements gathering with Pierre, it seems like the idea of having a tree with N accounts that could depend on each other makes less sense:

* Payments:
  * One account will end up paying for a child account,
* Reporting:
  * One account will end up showing invoices for a child account
  * One account will end up showing payments for a child account (and we don't see any use case where that parent account would be different)

So, in the end, it looks like all we *really* need is the ability to assign a parent account for a given *child) account; that parent will end up paying the invoices for the child account, and will have the ability to display both invoices and payments for its children.

**Comment by sbrossie** [comment]
Close issue as we created a series of issues to partition the problem. See milestone [Hierarchical Accounts](https://github.com/killbill/killbill/milestones/Hierarchical%20accounts)
