### ISSUE TITLE
Proper exception handling in EntitySqlDaoTransactionalJdbiWrapper

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#34]
In EntitySqlDaoWrapperInvocationHandler, we take extra care of propagating the right exception to the caller.

We should do the same in EntitySqlDaoTransactionalJdbiWrapper#execute. Any BillingExceptionBase exception explicitly thrown in transactions are wrapped in TransactionFailedException. It would be nice to unwrap them, although BillingExceptionBase is a checked exception and #execute doesn't declare any to be thrown.

**Comment by sbrossie** [comment]
/cc @pierre Should we close?  I think somebody quite smart [already fixed it](https://github.com/killbill/killbill/commit/812cfce95594ac5f500885879e6105454ada80fa):

```
add a second execute method in EntitySqlDaoTransactionalJdbiWrapper
    which throws a checked exception
```

We can it used at many places in our code -- e.g [here](https://github.com/killbill/killbill/blob/master/account/src/main/java/org/killbill/billing/account/dao/DefaultAccountDao.java#L191)

**Comment by pierre** [comment]
I think the right™ fix would be to now remove:

```
public <ReturnType> ReturnType execute(final EntitySqlDaoTransactionWrapper<ReturnType> entitySqlDaoTransactionWrapper)
```

in favor of the one which throws an exception (it's a lot of changes though...).

**Comment by sbrossie** [comment]
I can investigate, and i'll report back. Moving to `Release-0-20.0` for investigation.

**Comment by sbrossie** [comment]
/cc @pierre 

I looked at it into more details. The main issues are:
1. Now **all** our DAO methods would need to throw some Exception -- and those be propagated up to the stack; example : [DefaultAccountDao#getByAccountKey](https://github.com/killbill/killbill/blob/master/account/src/main/java/org/killbill/billing/account/dao/DefaultAccountDao.java#L120) would need to throw an exception
2. In some cases, we don't have access to any exception making things even harder : example in [DefaultPaginationSqlDaoHelper#getPagination](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/entity/dao/DefaultPaginationSqlDaoHelper.java#L58)

I actually think keeping the two forms make sense: There are situation where we don't have anything to throw, and others where we have some form of `BillingExceptionBase` to throw.
