### ISSUE TITLE
Janitor lock?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#342]
Should we have a "Janitor lock" to avoid concurrent updates between nodes (i.e. multiple nodes trying to update the same transaction)?

**Comment by sbrossie** [comment]
This is related to my point in https://github.com/killbill/killbill/issues/338

**Comment by pierre** [comment]
Re-opening to keep track of my comments in https://github.com/killbill/killbill/commit/951a7867e9181ca97f9eb879a5403cd472555437.

**Comment by sbrossie** [comment]
I think that can be closed again
