### ISSUE TITLE
Missing PENDING transitions for CREDIT and REFUND

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#347]
The current [PaymentState.xml](https://github.com/killbill/killbill/blob/master/payment/src/main/resources/org/killbill/billing/payment/PaymentStates.xml) is missing the PENDING transitions for both CREDIT and REFUND operations

**Comment by sbrossie** [comment]
The work is to add the missing transitions in the XML, and ideally a test should be written to verify the correct behavior.

**Comment by david-xie** [comment]
I tested it in my ENV, it works perfect!

**Comment by pierre** [comment]
We should re-generate the diagram in the docs too (see https://github.com/killbill/killbill-docs/blob/v3/userguide/assets/payment_states.dot and https://github.com/killbill/killbill/blob/master/payment/src/test/java/org/killbill/billing/payment/TestDefaultStateMachineConfigDOTGenerator.java#L30).

**Comment by david-xie** [comment]
@pierre How to re-generate the diagram?

**Comment by pierre** [comment]
@david-xie Take a look at `TestDefaultStateMachineConfigDOTGenerator`, and uncomment the `Files.write...` part.

**Comment by sbrossie** [comment]
Code issue can be closed (but it would be nice to receive a PR for the new generated diagram (@david-xie  any luck?)

**Comment by david-xie** [comment]
@pierre Thanks, Pierre!
@sbrossie See [#9](https://github.com/killbill/killbill-docs/pull/9)
