### ISSUE TITLE
Bus Event Listener: Exception handling

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#348]
Shouldn't we always throw the exceptions, instead of catching and logging (because then the event gets dispatched and marked as SUCCESS, which is not true). We should revisit all our handlers after we agree.

**Comment by sbrossie** [comment]
Actually we have implemented a way to catch exception and retry. I think we in some cases we should not retry. For instance retrying an NPE is probably useless because this will lead to same result..

**Comment by sbrossie** [comment]
@pierre I am actually not so sure this is what we want to do here. We should talk..

**Comment by sbrossie** [comment]
We have the following handlers today:

* `KillbillEventHandler`
* `BeatrixListener`
* `PushNotificationListener`
* `InvoiceListener`
* `InvoiceTagHandler`
* `OverdueListener`
* `PaymentBusEventHandler`
* `PaymentTagHandler`

1. For invoice, overdue, payment, we want to log any KillBill exception `BillingExceptionBase` as we assume this is something not retryable. This is what the code already does today

2. For `BeatrixListener` we seem to already have the right logic in place (the code in the handler only submit the entry to the external bus and should not fail unless malformatted, etc... in which case we want to log.

3. `PushNotificationListener` would require some more advanced retied logic but this is outside the scope of that issue.

4. `KillbillEventHandler` is just there for providing synchronous response (and ensure operation has co mpleted when call returns).

I am tempted to say there is nothing obvious to do here but we might find some tweaks here and there in specific use case (but nothing generic to do).

@pierre i would be tempted to close that issue.

**Comment by pierre** [comment]
For `PushNotificationListener`, see https://github.com/killbill/killbill/issues/285.

> @pierre i would be tempted to close that issue.

Yup, sounds good.
