### ISSUE TITLE
Payment Control state machine: be consistent when creating external keys

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#349]
By convention, we want to set the external key as the payment id if unspecified (see [PaymentModelDao](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/dao/PaymentModelDao.java#L51) and [PaymentTransactionModelDao](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/dao/PaymentTransactionModelDao.java#L59])).

We don't respect this convention however in case of payment control (see [DefaultControlInitiated](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/control/DefaultControlInitiated.java#L59-L72)). I don't think we need to set it that early: we can instead implement similar logic in [PaymentAttemptModelDao](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/dao/PaymentAttemptModelDao.java#L61) and set it in the context afterwards.

**Comment by pierre** [comment]
See also [PaymentBusEventHandler](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/payment/src/main/java/org/killbill/billing/payment/bus/PaymentBusEventHandler.java#L106-L107).

**Comment by sbrossie** [comment]
@pierre Can this be closed?

**Comment by pierre** [comment]
We never addressed this. On one hand, it's not easy to fix, on the other, invoice payments and payments going through the control state machine look weird/different (the key is different than the id, yet the user didn't specify it explicitly).
