### ISSUE TITLE
Payment Control state machine: don't create attempts for non-retry routing plugins

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#351]
Currently, if any routing plugin is specified for a given payment, we insert a row in `payment_attempts`. Besides the storage and DB roundtrip overhead, a major drawback is that `plugin_properties` are stored by default, including cvv, PAN, etc.

One quick solution would be to only add the row in `DefaultControlCompleted` if an attempt is to be scheduled.

There is still a possibility that a control plugin schedules a retry even if a cvv was passed. This seems like  a bug from the plugin though unless it wants to schedule a retry with cvv check disabled. In which case, it  would need to update the properties (the `OnFailurePaymentRoutingResult` object would need to be extended to contain `getAdjustedPluginProperties`, similar to `PriorPaymentRoutingResult`).

**Comment by sbrossie** [comment]
After review:
* Add `getAdjustedPluginProperties` for 'OnFailurePaymentRoutingResult' and 'OnSuccessPaymentRoutingResult'
* Move serialization of plugin properties in the `enteringState` callback (and look for `getAdjustedProperties`)
* `TestRetryService` refactoring
*  'OnFailurePaymentRoutingResult' and 'OnSuccessPaymentRoutingResult' should always be called even if we bail early See #354

**Comment by sbrossie** [comment]
Also see #195 for renaming of the API.

**Comment by sbrossie** [comment]
We decided to keep creating the attempts in the leavingState callback because this is useful to have a state (payment attempt) before we enter the control plugin. The `InvoicePaymentControlPluginApi` is actually making good use of that to handle the AUTO_PAY_OFF scenario.

However all the items listed above have been fixed, so task can be closed.
