### ISSUE TITLE
Payment state machines: simplify exception handling in OperationCallbackBase

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#352]
After the recent changes regarding exception handling, should [OperationCallbackBase](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/OperationCallbackBase.java#L57) be simplified?

In the Payment state machine, `rewrapExecutionException` and `wrapTimeoutException` do pretty much the same (modulo logging info). However `wrapInterruptedException` doesn't set the `PaymentTransactionInfoPlugin` in the context. Should that be fixed?

In the Payment control state machine, all three handlers delegate to `getOperationResultOnException` to return the right `OperationResult`, which does the right thing, but the logic is duplicated in `executePluginOnFailureCallsAndSetRetryDate`. Should we actually avoid catching any exception in `dispatchWithAccountLockAndTimeout` instead to simplify the wrapping/unwrapping of exceptions? We do something similar in [PaymentOperation](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/payments/PaymentOperation.java#L170) where we simply push the exceptions up.

**Comment by sbrossie** [comment]
> In the Payment state machine, rewrapExecutionException and wrapTimeoutException do pretty much the same (modulo logging info). However wrapInterruptedException doesn't set the PaymentTransactionInfoPlugin in the context. Should that be fixed?

Yes that makes sense.

> In the Payment control state machine, all three handlers delegate to getOperationResultOnException to return the right OperationResult, which does the right thing, but the logic is duplicated in executePluginOnFailureCallsAndSetRetryDate. Should we actually avoid catching any exception in dispatchWithAccountLockAndTimeout instead to simplify the wrapping/unwrapping of exceptions? We do something similar in PaymentOperation where we simply push the exceptions up.

I am not following that part...
