### ISSUE TITLE
Janitor: do we really need IncompletePaymentAttemptTask?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#353]
This Janitor looks for payments stuck in `INIT` state (control state machine), but it should almost be impossible to be stuck in such a state.

If we really want to handle this via code, it seems that we would need to do the same in `IncompletePaymentTransactionTask` for the payment state machine?

**Comment by sbrossie** [comment]
We decided we would keep the task since the code has been written (and there are some scenario where that could happen).

**Comment by pierre** [comment]
> If we really want to handle this via code, it seems that we would need to do the same in `IncompletePaymentTransactionTask` for the payment state machine?

Now that we rely on the notification queue for the payment transactions Janitor, it seems that we need to address this: if the payment transaction state machine never completes and no payment event is sent, the Janitor will miss these transactions (created as [UNKNOWN](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/PaymentAutomatonDAOHelper.java#L167)).

Should we re-introduce a [polling](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L83) for this case specifically? The frequency doesn't need to be aggressive, as these should never happen™. We also need to make sure we don't steal the ones which are handled by the notification queue already (either by using the search API or by waiting the max of the [Janitor retries config value](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L241)).

**Comment by sbrossie** [comment]
> Should we re-introduce a polling for this case specifically? The frequency doesn't need to be aggressive, as these should never happen™. 

Yes i agree, this is a valid case. 

> We also need to make sure we don't steal the ones which are handled by the notification queue already (either by using the search API or by waiting the max of the Janitor retries config value).

That part should be taken care of as we perform the whole operation under account lock.

**Comment by sbrossie** [comment]
Created #364 to track that last remaining issue (which has nothing to do with paymentAttempts).
