### ISSUE TITLE
Payment Control state machine: CompletionControlOperation doesn't respect retry date

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#354]
On failure, plugins are not called and the next retry date isn't set.

Notes:

* this goes away if https://github.com/killbill/killbill/issues/353 is valid
* this goes away if https://github.com/killbill/killbill/issues/352 is fixed

**Comment by sbrossie** [comment]
I am actually unclear on which error are the (control) plugins not called? Could you clarify?

What i noticed on my side is that when we [abort the call](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java#L105), the subsequent callback `onSuccessCall ` and `onFailureCall ` are not called, but actually i think this is correct (not to call them).

**Comment by pierre** [comment]
> I am actually unclear on which error are the (control) plugins not called? Could you clarify?

I was referring to this [comment](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentAttemptTask.java#L134). It looks like we only look for successful transactions and execute `executePluginOnSuccessCalls` if needed. Shouldn't we handle failure cases as well (and invoke `onFailureCall`)?

**Comment by pierre** [comment]
Re-opening to track two issues:

* Handling of multiple transactions (see [comment](https://github.com/killbill/killbill/commit/a0638cb3e16e3577c2e33639f203e99d3ad97fa6#commitcomment-12576917)): in case of retries, we may have multiple transactions with the same external key (e.g. two `PAYMENT_FAILURE` and the last one `SUCCESS`), which would map to different payment attempts
* Potential NPE (see [comment](https://github.com/killbill/killbill/commit/a0638cb3e16e3577c2e33639f203e99d3ad97fa6#commitcomment-12590955))
