### ISSUE TITLE
How to deploy Killbill?

### ISSUE THREAD

**Issue by pate** [killbill/killbill#358]
Please add a clear link to instructions for deployment. I looked around and glossed over the wiki, but all the guides are about using the product with no clear help on deploying it.

If you want to get a lot of buy-in, make it easy to build with CircleCI and deploy with one of the cloud providers, perhaps as a Docker image :). Thanks!

**Comment by sbrossie** [comment]
Petrus,

Have you taken a look at our documentation
<http://docs.killbill.io/0.14/userguide_platform.html#deployment>? If you
like docker, we also support docker
<https://github.com/killbill/killbill-cloud/blob/master/docker/README.md>
deployment.

In the future, for tech, doc related question, could you use our mailing
list <https://groups.google.com/forum/#!forum/killbilling-users> instead?

Stéphane

**Comment by zeigerpuppy** [comment]
I think this is a good question, an "Install" doc clearly visible in the wiki would be helpful!

**Comment by pierre** [comment]
I've created https://github.com/killbill/killbill/wiki/Installation.

**Comment by zeigerpuppy** [comment]
thanks Pierre, that's a logical place for it.

**Comment by kevinemeka** [comment]
Please can anyone help. I'm new to this. I have tried deploying killbill with just about every guide available. I also tried using Pierre's installation guide for AWS but after creating my machine, I was barred from sshin into it. Would it be too much to ask for help in deploying it, maybe remotely?

**Comment by 911pcdoc** [comment]
see here is classic example of the documentation assuming far to much you assume i know what a war is other then a battle between 2  and so forth you want people to use the program then a clear guid on how to install on common platforms like Ubuntu red hat or other Linux loads or even on a mac should be published and dont assume anyone knows any thing i have 2 techs with over 30 uears of it background and niether of them nor my self have any idea as to how to install this!

**Comment by pierre** [comment]
This issue is quite old: our current documentation provides detailed installation instructions for various platforms. See http://docs.killbill.io/.

If anything is unclear, feel free to reach out to our mailing-list: https://groups.google.com/forum/#!forum/killbilling-users.
