### ISSUE TITLE
Separation of concern between visible invoice items and internal ledger

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#359]
Today Kill Bill invoices are used to track product related items (recurring, fixed, ...) but also internal bookkeeping items (cba, ...). It would make sense to introduce a lower level ledger and abstract such concepts from the api (i.e hide those items from invoice).

However those bookkeeping items also need to be returned in some specific scenario (analytics, accounting,...).

**Comment by pierre** [comment]
Related: https://developer.squareup.com/blog/books-an-immutable-double-entry-accounting-database-service/
