### ISSUE TITLE
Ability for plugins to export metrics (JMX, ...)

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#360]
The Kill Bill OSGI layer should register and export a new service type where plugins can register metrics. The following metrics types could be supported based on [dropwizard metrics package](http://metrics.dropwizard.io/3.1.0/manual/core/):
- Gauges
- Counters
- Histograms
- Meters
- Timers

**Comment by sbrossie** [comment]
OSGI layer would export a new service `OSGIMetrics` with an api to register a certain type of metric, and then later plugin would be able to record points. The exact form of the api needs to be defined, but potentially something as simple as `record(long value)` may work.

Then at the OSGI level, those plugin specific metrics would be registered in the existing metrics registry, and exported through JMX.

**Comment by sbrossie** [comment]
More thoughts about the API: We need *only* 3 types of metrics, one for requestTime (`Histogram`), one for rate (`Meter`) and one for counts (`Counter`). We could have one api for each:
* requestTime:  `recordHistogramValue(String metricName, long value)`
* rate: `updateMeterValue(String metricName)`
* count: `updateCounter(String metricName, int positiveOrNegativeValue)`

Questions: Do we need to pass plugin name or can we extract it auto-magically?

**Comment by sbrossie** [comment]
Platform work:
* Registration of the new service
* Implementation to keep track of plugin metrics and make sure they are exporter through JMX (and HTTP `/1.0/metrics`)


Java platform framework:
Provide wrapper layer around the apis that need to be instrumented (some method that take a Callable<T> and automatically call the api described above.

Ruby platform framework:
Same idea, where we can pass a small `Proc` that will be executed and automatically call the api described above.

**Comment by andrenpaes** [comment]
So the idea is exposing an API, where dropwizard Metrics would be an implementation detail.

**Comment by sbrossie** [comment]
Some pointers on the code:
* Kill Bill registers OSGI services [here](https://github.com/killbill/killbill-platform/blob/killbill-platform-0.8/osgi/src/main/java/org/killbill/billing/osgi/KillbillActivator.java#L149). So the idea will be to register/unregister the new `OSGIMetrics` service similarly.
* KB provides a `MetricsRegistry` that we will be able to reuse on the OSGI layer to keep track of the plugin metrics:
  * The creation of the MetricsRegistry can be found [here](https://github.com/killbill/killbill-commons/blob/master/skeleton/src/main/java/org/killbill/commons/skeleton/modules/StatsModule.java#L72)
  * The `MetricsRegistry` can be injected using Guice in any CTOR e.g [PersistentBus CTOR](https://github.com/killbill/killbill-commons/blob/master/queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java#L83)
* All the metrics from the registry will be available on `/1.0/metrics` using the [AdminServletModule](https://github.com/killbill/killbill-commons/blob/master/skeleton/src/main/java/org/killbill/commons/skeleton/modules/StatsModule.java#L80)

**Comment by pierre** [comment]
7 years later, this has been done 😅 

The Kill Bill `MetricRegistry` is now exposed by the system bundle as a service, so that OSGI bundles can pull the metrics for the _sinks_ (Graphite, InfluxDB, etc.). The implementation of that interface is `KillbillPluginsMetricRegistry`, which itself is a wrapper around `OSGISingleServiceRegistration<MetricRegistry>` (`MetricRegistryServiceRegistration`), which takes care of discovering the services exported by the bundles (in practice, 0 or 1, the `KillBillCodahaleMetricRegistry` one, exported by the `metrics` bundle).

Plugins can now also expose their own metrics. See https://github.com/killbill/killbill-hello-world-java-plugin/pull/9 for an example.
