### ISSUE TITLE
Janitor: could we optimize the PENDING case?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#373]
In [IncompletePaymentTransactionTask](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L180), when the new state is PENDING, we update the transaction, send an event on the bus, catch the event via [processPaymentEvent](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L145) and insert the notification entry.

In most cases, when nothing changed on the plugin side, this is suboptimal and we could directly call [insertNewNotificationForUnresolvedTransactionIfNeeded](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L261) instead. This is only useful if [some state changed](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L213-L214) in the plugin, for example to track Adyen sub-states via the `gatewayError` field (e.g. Adyen `REFUND_RECEIVED` vs `REFUND_PENDING` states).

Can we optimize the general use-case? Is it worth it?

**Comment by sbrossie** [comment]
Closed with commit 9178b21aaa27712897f7e5e32d7a77c7c19d6d6f
