### ISSUE TITLE
Janitor: why we insert a notification for PLUGIN_FAILURE?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#374]
See [IncompletePaymentTransactionTask](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L188): isn't it a terminal state?

**Comment by sbrossie** [comment]
After discussion, we agreed that `CANCEL` state returned by plugin and which maps to `PLUGIN_FAILURE` should be related to the payment call (and not the `getPaymentInfo` which is used by the janitor to return the known state).

As such we propose to handle `PLUGIN_FAILURE`, the same way we do for other state and transition to a terminal state (as opposed to defaulting to 'UNKNOWN' and doing nothing).
