### ISSUE TITLE
Allow for re-entrant lock in payment system

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#380]
Routing plugins cannot perform certain operations today (such as adding a payment method), because the lock is already taken.

**Comment by sbrossie** [comment]
Closed with:
7a0a5c97a2c6dbae50a5a99b5a2c2228f70b13f0
https://github.com/killbill/killbill-commons/commit/61afe7c1f7ab3424ebffd53d3a21c1b029d85b8c
https://github.com/killbill/killbill-commons/commit/b2d9aaab3dd04652eaafa2c12fce7fb8598bf229
