### ISSUE TITLE
Payment: review state machine transitions

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#383]
Today, we support these use-cases. Should we allow them?

* Multiple transactions (different external keys) for the same payment, in state PENDING
* Multiple AUTH transactions (different external keys) for the same payment, in state SUCCESS (disallowed for PURCHASE)

**Comment by sbrossie** [comment]
> * Multiple transactions (different external keys) for the same payment, in state PENDING

Yes, needed for Adyen for instance.

> * Multiple AUTH transactions (different external keys) for the same payment, in state SUCCESS (disallowed for PURCHASE)

I am unclear if partial auth is a real use case. For now leave it the way it is.

Closing issue.

**Comment by sbrossie** [comment]
Reopening the issue for 0.16.4. We decided that we should actually not allow to have multiple initial transactions (`AUTH`, `PURCHASE`, `CREDIT`) for the same paymentId in either `SUCCESS` or `PENDING` state. For instance having multiple `AUTH` (for same payment) would make it impossible to know which one to match for the `CAPTURE`.

**Comment by sbrossie** [comment]
Closed by 3952d7d3
