### ISSUE TITLE
Link failed payments to invoices

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#393]
Invoice payments that are not successful will not appear in `invoice_payments`, so Kaui cannot display them in the invoice details page.

We should somehow surface them, as well the next scheduled retry date (information in `payment_attempts`).

**Comment by sbrossie** [comment]
Let's recap how payment retries (through `PaymentAttempt`) work:
* Payment attempts are created and keep track of `paymentExternalKey`, `transactionExternalKey`
* Upon retry:
  * We reuse the same `Payment`
  * We reuse the same transaction for when the state is `PENDING` [see PaymentLeavingStateCallback](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/payments/PaymentLeavingStateCallback.java#L81)  (By the way, does it really make sense, or should we not handle it as a UNKNOWN, that is, not allow retry and only have janitor handle it; can't remember why we decided that way, maybe 3DS?)
  * We create a NEW transaction for other states (`PAYMENT_FAILURE`, `PLUGIN_FAILURE`) (and `UNKNOWN` are not retried)

=> So `PENDING` case apart, it seems like we could have multiple payment retries for the same `Payment` at a given time, and so in essence payment retries are more like payment transaction retries (e.g we could have 2 retries for two partial captures at a given time). Each payment retry will therefore end up being a new `PaymentTransaction`  for that Payment **and will therefore be visible when retrieving the Payment**.

So, then coming back to invoices: Today returning the `Payment` associated to an invoice is a 2 steps process:
1. The `Invoice` contains a list of `InvoicePayment`
2. By extracting the paymentIds for the list of `InvoicePayment`, we know which list of `Payment` to fetch.

In case of `Payment` failure there is no entry in the `invoice_payments` table, and so nothing is returned.

=>  So, it seems like we need to change the `invoice_payments` table to have a new column `success`, and change the [InvoiceControlPluginApi onFailureCall](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L201) to update the invoice module about failed attempt.

Finally regarding the retryDate of a `Payment` (or actually more precisely `PaymentTransaction`), we need to change the API for `Payment` to be able to bubble up that info as part of the `Payment` object.

**Comment by sbrossie** [comment]
We decided to not tackle exposing the payment retry date as part of this bug, so this is closed as of commit f9d03a75bdb318936c830e14dbdac96c2d8dca5b.
