### ISSUE TITLE
PaymentMethod not consistent

### ISSUE THREAD

**Issue by akley** [killbill/killbill#395]
With killbill 0.14 it is possible to set the default payment method on the account, although the accountId of the payment method points to another account.
The server should prevent this.

**Comment by sbrossie** [comment]
I did not verify the bug yet. This is probably something we will fix for 0.16

**Comment by maguero** [comment]
This is fixed.
PR:
* killbill-api: https://github.com/killbill/killbill-api/pull/8
* killbill: https://github.com/killbill/killbill/pull/438

**Comment by pierre** [comment]
Thanks!
