### ISSUE TITLE
missing Logback dependency while using conditional processing

### ISSUE THREAD

**Issue by akley** [killbill/killbill#400]
If conditional processing (e.q. during filtering log messages) is used, the janino.jar (org.codehaus.janino) is missing on killbill by default.

Additionally have to define which version will be used. 2.5.16 seems to be fine in killbill 0.14

Maven:
<dependency>
  <groupId>org.codehaus.janino</groupId>
  <artifactId>janino</artifactId>
  <version>2.5.16</version>
</dependency>

**Comment by pierre** [comment]
> Additionally have to define which version will be used. 2.5.16 seems to be fine in killbill 0.14

Thanks for trying it out. I had done some testing with 2.5.10, but I'm glad we can upgrade.
