### ISSUE TITLE
Allow to trigger invoice payments with a non-default payment method

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#407]
See [JaxRsResourceBase](https://github.com/killbill/killbill/blob/ab2ba000a10fbe94f3384a34f58f9712f0ee7cb2/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L403).

**Comment by sbrossie** [comment]
@pierre Can you elaborate a bit?

**Comment by pierre** [comment]
Today, when [triggering a payment for an invoice](https://github.com/killbill/killbill/blob/9013abf3487bca6744fa41078d0de2fec76848dc/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L583-L612), we can either trigger an external payment or use the default payment method. We should respect `InvoicePaymentJson#paymentMethodId`.
