### ISSUE TITLE
Enhance logging by print context user token

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#409]
To enhance https://github.com/killbill/killbill/pull/406, we should print the user token when calling the plugins.

We should also make sure the context token is set using the request id, if set in JaxRs.

**Comment by sbrossie** [comment]
Work it to at least add the context user token into the payment api log line.

**Comment by sbrossie** [comment]
I am wondering if we should not make the remaining of that task more generic and make sure every log line prints the X-Request-Id (maybe part of structured logging work).

**Comment by pierre** [comment]
Fixed in enhanced-logging branch.
