### ISSUE TITLE
Wrong error message when try to uncancel an active subscription.

### ISSUE THREAD

**Issue by maguero** [killbill/killbill#416]
When tries to uncancel an "Active" subscription gets this error message:

``` Json
{
  "className": "org.killbill.billing.entitlement.api.EntitlementApiException",
  "code": 1031,
  "message": "Subscription ef4434fe-2ec9-4999-92ca-97410263b9da is in state CANCELLED: Failed to cancel",
  "causeClassName": null,
  "causeMessage": null,
  "stackTrace": []
}
```
But the subscription is "state": "ACTIVE".

The issue seems to be [here] (https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java#L329-329).

**Comment by maguero** [comment]
@pierre: should I use this msg instead ?

``` Java
SUB_UNCANCEL_BAD_STATE(1070, "Subscription %s was not in a cancelled state: Failed to uncancel plan")
```

**Comment by pierre** [comment]
Yup, that sounds good as it is what `DefaultSubscriptionBaseApiService` will [throw](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java#L335).

Could you also fix [this](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java#L309)?

**Comment by maguero** [comment]
Thank you!

PR: https://github.com/killbill/killbill/pull/417
