### ISSUE TITLE
Pause operation is allowed for requested date in the past/future but implementation is incorrect

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#428]
The code retrieves the current `BlockingState` for the `EntitlementService.ENTITLEMENT_SERVICE_NAME` for the present time which is incorrect.

See [DefaultEntitlementApiBase](https://github.com/killbill/killbill/blob/killbill-0.15.7/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java#L175)

**Comment by sbrossie** [comment]
I created that bug a few months back and now i don't understand what is incorrect:

@pierre : Can you confirm:

`pause` operations consist in inserting a blockingState for the `ENTITLEMENT_SERVICE_NAME`. The [code](https://github.com/killbill/killbill/blob/killbill-0.16.0/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java#L169)  first retrieves any blocking state for `ENTITLEMENT_SERVICE_NAME` and if they (already) exist it throws an exception. That seems correct...

Note that if another service had inserted a blocking state that would work independently of the pause operation (which is specific for entitlement service).

**Comment by pierre** [comment]
Shouldn't `blockingStateDao.getBlockingStateForService` take into account the effective time?

For example, if the bundle is currently paused between 2015-01-01 and 2015-01-15, and we want to future pause it again at 2015-02-01, the code would throw `ErrorCode.ENT_ALREADY_BLOCKED` since it's currently blocked (but it is not yet blocked as of 2015-02-01).

**Comment by sbrossie** [comment]
Ah of course. I did not read the end of my description "... for the present time which is incorrect."

**Comment by sbrossie** [comment]
@pierre Actually, i implemented the fix and then realized the code is correct:

When we pause the bundle in the future, we don't insert a `BlockingState` in the future; instead we post a [notification for the future date](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java#L179), that will kick in when the time comes and then pause in what is now the present time... So the assertion for the [currentState](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementApiBase.java#L169) makes sense as we only have to deal with present time.

We could still decide to harden the code and verify there is indeed no `BlockingState` in the future (i have the code written), but do we?

**Comment by sbrossie** [comment]
Also note we already have a [test](https://github.com/killbill/killbill/blob/master/entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlementApi.java#L361) to verify pause/unpause operations in the future.

We could keep the check and only do it when the date provided is the present day to ensure that we don't end up with multiple same event for the same day although the [logic in the dao](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/dao/DefaultBlockingStateDao.java#L204) should remove such duplicate.

**Comment by pierre** [comment]
>  So the assertion for the currentState makes sense as we only have to deal with present time.

Should we actually remove the check?

* The DAO logic will remove duplicates
* There is still the issue I mentioned above (future un-paused entitlement that we want to re-pause in the future: the code would prevent it, no?)
