### ISSUE TITLE
Timeout exception on Payment module when run "mvn clean install" on Linux

### ISSUE THREAD

**Issue by maguero** [killbill/killbill#435]
There is an exception when run "mvn clean install" in a linux environment.

Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-32-generic", arch: "amd64", family: "unix"

Please see [group discussion](https://groups.google.com/forum/#!topic/killbilling-users/ehQhseveDcg) for more details.

**Comment by sbrossie** [comment]
@maguero do you still see this issue. Any idea how we could reproduce?

**Comment by matias-aguero-hs** [comment]
@sbrossie I moved from linux to mac a month ago. The only way that I found to reproduce it was running `mvn clean install` in a linux environment.
