### ISSUE TITLE
Invoices changes to support Hierarchical Account

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#459]
* New invoice listener to catch children invoices and populate the parent summary invoice
* New invoice tables to manage parent invoice and invoice items
* Modification of the child invoice to mark it as such (and for instance making sure invoice child balance is 0)
* Notification handler to transition DRAFT invoice to COMMITTED invoice at the end of the day.
* Api implementation called from payment to notify invoice about payment needs to be modified to propagate the payment to all children included in that summary invoice. For scalability purpose and to avoid locking issues the propagation would happen asynchronously (new notificationQ).

Mapping between the parent invoice id and the list of invoice ids used for the computation:

parent_invoice_id - child1_invoice_id1
parent_invoice_id - child1_invoice_id2
parent_invoice_id - child2_invoice_id3

This mapping will be used for the (new) GET invoice item details API (summary invoices will never have details, only at most one entry per child, even if there are several invoices for the same child for the day).

**Comment by matias-aguero-hs** [comment]
> New invoice tables to manage parent invoice and invoice items

What is your plan for this? Do you mean to create only a mapping table (parent-child relation) or you want to create new invoice and invoice-item tables to attend new parent invoices?

**Comment by pierre** [comment]
Parent invoices and invoice items should be in a new set of tables because:

* the data is different: while the children will continue to have entries in the original tables, the new tables will only contain summaries (one line per child per day).
* we probably need to support updating the rows in these new tables (in case a child goes through multiple changes in the same day for example), something that is not allowed in the original tables

Additionally, we need a mapping table parent invoice to child invoices, as described above.

**Comment by matias-aguero-hs** [comment]
Guys, I just pushed several changes to address this story. I'm still have pending a couple of things:

- Payment for ParentInvoice is not made after set it as COMMITTED status.
- Post a NotificationQ after create ParentInvoice in InvoiceListener. (is there any example about how to do it?)
- Refactor Invoice.getBalance() to return 0 when its a child invoice and payment is delegated to parent. (Should add a ImmutableAccountData object to Invoice?)
- Fix TestIntegrationInvoice
- Complete InvoiceListener tests.

**Comment by sbrossie** [comment]
@matias-aguero-hs Did you submit a PR already?

Also, i expect that task to be quite long, we will probably need a lot of back and forth, as this is the bulk of the work, and is quite complicated (and also i am sure we will discover things we did not think of as yet as we go through the code). I wish we had cut that task in smaller pieces, but in the end this does not matter too much.

Regarding your questions:

> Payment for ParentInvoice is not made after set it as COMMITTED status.

Yes, at the end of the day, the invoice gets `COMMITTED` and then payment will happen automatically in payment module

> Post a NotificationQ after create ParentInvoice in InvoiceListener. (is there any example about how to do it?)

The invoicing code [already creates a notificationQ](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDateNotifier.java#L70) to handle all the recurring aspects. You will need to create a new notificationQ with the handler that will be in charge of transitioning invoices to 'COMMITTED' state. Note that notificationQ needs to be created during `LifecycleLevel.INIT_SERVICE` phase and need to be stopped/deleted in the [LifecycleLevel.STOP_SERVICE phase ](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/engine/core/DefaultSubscriptionBaseService.java#L137).

Then once the queue exists, the code can use it to post future notification, for instance in invoice, we post the [next recurring billing date](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/notification/DefaultNextBillingDatePoster.java#L92).


> Refactor Invoice.getBalance() to return 0 when its a child invoice and payment is delegated to parent. (Should I add an ImmutableAccountData object to Invoice?)

I will need to check with Pierre on that point. I think we went back and forth with regard to the child (delegated to parent) invoice balance . Regarding immutability, i would defer for now as this is related to the design with un-parenting children which we postponed.

**Comment by matias-aguero-hs** [comment]
@sbrossie No, I didn't submit a PR yet, but you can find all those changes in this commit: https://github.com/matias-aguero-hs/killbill/commit/c3c7cc9b3d2f47f9db78bc6a80cf3cd09d119493

Thank you for NotificationQ info, I'm going to work on that today. I missing to `post future notification` after move invoice to COMMITTED, thats why I'm not getting the payment automatically. :+1: 

> I will need to check with Pierre on that point. I think we went back and forth with regard to the child (delegated to parent) invoice balance 

Ok, let me know then. We need to do something because now the child account invoice is paid anyway, and we have the invoice paid by the child and the parent too.

**Comment by sbrossie** [comment]
@matias-aguero-hs 

Regarding child `Invoice.getBalance() `, the proposal is the following: 
1. The payment system is modified to ignore child delegated invoices, [similar to what you did for non COMMITTED invoices](https://github.com/killbill/killbill/blob/hierarchical-accounts/payment/src/main/java/org/killbill/billing/payment/invoice/InvoicePaymentControlPluginApi.java#L261)
2. The computation of the child invoice balance will follow a slightly different logic: Instead of simply summing all items and substracting payments, the child balance will depend on the parent invoice balance:
* If parent balance is > 0 =>  normal child balance calculation
* is parent balance == 0 => child balance = 0

Note that it means that when constructing a child delegated invoice, the code will also need to compute the parent balance (i.e pulling all invoice items, invoice_payments, tags,...) and ideally all part of the same transaction.

Obviously in a first iteration, get something that works, and then when we hit performance milestone, we may revisit implementation.

**Comment by matias-aguero-hs** [comment]
@sbrossie 
I pushed new changes that include new NotificationQ and ParentInvoice payment actions.
Do you want that I create a PR? So you can check the code better.

I need to work now in child invoice balance proposal.

**Comment by sbrossie** [comment]
@matias-aguero-hs Yes please start a PR and we can iterate from there.

**Comment by matias-aguero-hs** [comment]
Done:
* killbill-api : https://github.com/killbill/killbill-api/pull/12
* killbill-client-java: https://github.com/killbill/killbill-client-java/pull/27
* killbill: https://github.com/killbill/killbill/pull/491

**Comment by matias-aguero-hs** [comment]
> 2 . The computation of the child invoice balance will follow a slightly different logic: Instead of simply summing all items and substracting payments, the child balance will depend on the parent invoice balance:

Getting back to `childInvoice.gelBalance()` refactor, I'm not sure what do you expect.

> Note that it means that when constructing a child delegated invoice, the code will also need to compute the parent balance (i.e pulling all invoice items, invoice_payments, tags,...) and ideally all part of the same transaction.

I assume you expect that I use `invoiceApi.getAccountBalance(parentAccount.getId(), tenantContext)` when `InvoiceDispacher` is creating the parent item invoice from the child total invoice. But I need more details on what do you expect to do with the original child invoice.

**Comment by matias-aguero-hs** [comment]
@sbrossie @pierre Hi guys, I just returned from my vacations. Did you have the chance to review my last questions?

**Comment by sbrossie** [comment]
@matias-aguero-hs 

> Getting back to childInvoice.gelBalance() refactor, I'm not sure what do you expect.

This is what i described above, but let me reformulate and add come context: The child invoice balance depends on the parent invoice balance, in such a way that if parent invoice balance is 0, then child balance automatically becomes 0. On the other hand if parent invoice balance is > 0 (unpaid), then child balance calculation should default to normal computation. To summarize:

* If parent balance is > 0 => normal child balance calculation (i.e will result in being the child invoice amount since there is no payment against child)
* if parent balance == 0 => child balance = 0

**Comment by matias-aguero-hs** [comment]
Sure, I understand what the feature is. Ohh sorry, I think I forgot to include the other question.

I'm confused about if I need to change the DefaultInvoice.java object (getBalance()) to have the feature reflected in each invoice or if I have to change the Account getBalance method when the account is [retrieved] (https://github.com/matias-aguero-hs/killbill/blob/d99b2211fa4843cbd53fca3bd52facbd450b3859/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AccountResource.java#L305-L305). The second option is the one I know how to implement.

> Note that it means that when constructing a child delegated invoice, the code will also need to compute the parent balance (i.e pulling all invoice items, invoice_payments, tags,...) and ideally all part of the same transaction.

For the first option, if the parent account balance is > 0, Should the original child invoice be created with the calculated amount? What happen if the parent pay all invoices and the balance is now = 0? (the child invoices need to be updated to return 0)

**Comment by sbrossie** [comment]
> I'm confused about if I need to change the DefaultInvoice.java object (getBalance()) to have the feature reflected in each invoice or if I have to change the Account getBalance method when the account is retrieved. The second option is the one I know how to implement.

You need to change implementation of the [invoice balance](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java#L68) for the children invoices to reflect the logic i mentioned above. Since the account balance is [computed by summing the invoice balance](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L373), this will also have the desired effect for the account balance. 

> For the first option, if the parent account balance is > 0, Should the original child invoice be created with the calculated amount? What happen if the parent pay all invoices and the balance is now = 0? (the child invoices need to be updated to return 0)


Note that both invoice balance and account balance are computed in the fly (not store on disk). 
* If the parent invoice (not account) balance is > 0 => all the children invoice balance will also be positive
* If the parent pay all invoices and the balance is now = 0 => all the children invoice balance are now 0.

**Comment by pierre** [comment]
Note that this probably means that a child invoice needs a pointer (just private) to the parent invoice. The implementation now simply becomes:

```
@Override
public BigDecimal getBalance() {
    final BigDecimal parentInvoiceBalance = parentInvoice.getBalance();
    return isWrittenOff ? BigDecimal.ZERO : (parentInvoiceBalance.compareTo(BigDecimal.ZERO) > 0 ? InvoiceCalculatorUtils.computeInvoiceBalance(currency, invoiceItems, payments) : BigDecimal.ZERO);
}
```

**Comment by matias-aguero-hs** [comment]
thank you guys for clarifications. I'll try something similar what Pierre suggested. First iteration may not contemplate performance.

**Comment by matias-aguero-hs** [comment]
Guys, I pushed the changes related to gelBalance feature.
