### ISSUE TITLE
Catalog translation upload does not seem to take effect

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#461]
I created the following catalog translation:
```
shotgun-monthly = Fusil de chasse mensuel
shotgun-annual = Fusil de chasse annuel
reserved-metal-monthly-bp-evergreen = Metal reserve reconductible
reserved-metal-monthly-bp = Metal reserve
```

I uploaded the file for my tenant:

```
curl -v -u admin:password -H "X-Killbill-ApiKey: bob2" -H "X-Killbill-ApiSecret: lazar" -H 'X-Killbill-CreatedBy: admin' -H "Content-Type: text/plain" -X POST --data-binary @/tmp/CatalogTranslation_fr_FR.properties http://127.0.0.1:8080/1.0/kb/invoices/catalogTranslation/fr_FR
```

The upload worked the first time and the entries in the html invoices were not translated:

```
curl -v \
-u admin:password \
-H 'X-Killbill-ApiKey: bob2' \
-H 'X-Killbill-ApiSecret: lazar' \
-H "Content-Type: application/json" \
-H 'X-Killbill-CreatedBy: stephane' \
"http://127.0.0.1:8080/1.0/kb/invoices/1785b3d5-24b3-4d17-94ce-310aeb74bc63/html"
```

I could see:
```
...
  <tr>
                <td>reserved-metal-monthly-bp-evergreen</td>
                <td>reserved-metal-monthly-bp</td>
                <td>1 sept. 2015 - 1 oct. 2015</td>
                <td>EUR 88.000000000</td>
            </tr>
...
```

**Also trying to upload another version fails with a 400 (no stack trace, and no reason)**

**Comment by pierre** [comment]
> The upload worked the first time and the entries in the html invoices were not translated:

I couldn't reproduce it. Was the account locale `fr_FR`?

Note that in the output, only the plan name (`reserved-metal-monthly-bp`) will be translated. `reserved-metal-monthly-bp-evergreen` maps to the invoice item description that is not translated today (maybe we should fix this, although it's unclear which translator to use - `CATALOG_TRANSLATION`, `INVOICE_TRANSLATION` or both?).

> Also trying to upload another version fails with a 400 (no stack trace, and no reason)

Did you pass `deleteIfExists=true`? See https://github.com/killbill/killbill/blob/614ba1e2e8e336233438000c5f8db185454845e3/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L826.

**Comment by sbrossie** [comment]
@pierre You are correct, i just retried and it actually works.

However we should fix the plan name (which is not translated), as it does not make any sense to allow for product translation and not for plan name.

Another glitch i found is that uploading twice the config fails:
* First attempt: 201
* second attempt: 400 (with no sign of why)

**Comment by sbrossie** [comment]
There is actually no issue with the translation of the phase name. The real issue is that our template uses the `description` and:
1. Our invoicing system adds the phase name into the description for some items (e.g `FIXED` items)
2. Currently there is [no translation for the description](https://github.com/killbill/killbill/blob/fix-for-451/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceItemFormatter.java#L92)

We could easily fix it (i tried) by calling the `translator` for the description (and ensuring the translation resource includes the phase name).

**Comment by sbrossie** [comment]
As for the other issue where we get 400 after retrying to upload resource, this is because we need to specify the `deleteIfExists` query param. Retried and it works as expected.
