### ISSUE TITLE
Catalog api lack an api for retrieving priceList

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#464]
Most catalog api have two versions of the api: For e.g `findPlan`:
*  `findPlan(final String name, final DateTime requestedDate)`
* `findPlan(final String name, final DateTime requestedDate, final DateTime subscriptionStartDate)`

The first one is for instance used when creating a new subscription (we just need to find if the current catalog has the plan requested and what his attributes are.

The second one is used for instance when extracting catalog info based on an subscription event (the date of the event select a list of possible catalog and the startDate allows to find the right match depending on how the catalog was configured -- see [findPlan logic](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/VersionedCatalog.java#L152)

The issue comes with `findPricelist` which only has one version, and then it seems like because of that the code is incorrect [here](https://github.com/killbill/killbill/blob/killbill-0.16.0/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java#L634).

The issue came up during [this test](https://github.com/killbill/killbill/blob/killbill-0.16.0/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogRetireElements.java#L165)

**Comment by sbrossie** [comment]
Added in milestone-0.17.0 because it needs to add new api (technically the change is not backward compatible so could fall on 0.16)

**Comment by pierre** [comment]
This [API](https://github.com/killbill/killbill-api/commit/e47155b0327188a1faa6e47e46183612c580b992) change triggers a recursive loop (stackoverflow) when trying to retrieve the catalog from Ruby plugins 😞
