### ISSUE TITLE
Mapping currency -> locale is not unique

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#474]
See https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatterFactory.java#L43.

**Comment by sbrossie** [comment]
@pierre But the reverse is `locale` -> 1 `currency`. Can we just implement a reverse map?

**Comment by pierre** [comment]
I refreshed my memory on this issue:

* This code is used to find the _default_ symbol for a currency: this technically depends on the locale of the user, but it's more user-friendly to print £ than GBP by default
* This reverse lookup is a hack and needed [here](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java#L244-L245) -- that's why we need a mapping Currency -> Locale

Now, the mapping isn't deterministic:

* `currency.getSymbol(locale)` yields `US$` for `USD` / `es_US`
* `currency.getSymbol(locale)` yields `$` for `USD` / `es_PR`

What we really need is the user-friendly currency symbol per currency. Maybe we should just hardcode a list: https://en.wikipedia.org/wiki/Currency_symbol?

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I've started with this issue.
Currently, the Currency Symbol comes from the `java.util.*` library, which could be causing that the mapping is not as deterministic as expected.
If the idea is to hardcode the list, we can re-use the [Currency](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/catalog/api/Currency.java#L22) enum in `killbill-api` but adding to each Currency its respective Symbol.
Do you guys agree?

Please let me know so I can move forward with this.

Thanks!

**Comment by pierre** [comment]
> If the idea is to hardcode the list, we can re-use the Currency enum in `killbill-api` but adding to each Currency its respective Symbol.

Oh I see, maybe just adding a `String getSymbol()` method? This should work indeed, even for code generated for Ruby plugins (we already have enums with methods, like [BillingPeriod](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/catalog/api/BillingPeriod.java)).

@sbrossie Any objection?

**Comment by javier-gomez-github** [comment]
@pierre 
Sure, I've been working on that following that idea.
One question, what should I do in the case of those symbols like the one for United Arab Emirates:
AED --> د.إ

Should I use the original symbol or just try to find / use the Latin value? (sometimes it is the same as the Currency Code -> AED).

I was thinking that we can have some encoding / decoding issues in the future with some symbols.
What do you think about this?

Thanks!

**Comment by pierre** [comment]
> Should I use the original symbol or just try to find / use the Latin value?

I'm not sure what you mean by Latin value?

The goal of this ticket is to have a quick look-up AED -> د.إ, Euro -> €, etc. to remove the non deterministic lookup mentioned and simplify [that](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java#L244-L245) code.

The wikipedia article linked above seems to be a good source for these.

> I was thinking that we can have some encoding / decoding issues in the future with some symbols.

Indeed, let's make sure the source file is properly saved as utf-8. Maybe `-encoding UTF8` needs also to be passed to `javac` in the pom.xml? Some investigation is need here.

**Comment by javier-gomez-github** [comment]
@pierre 
What I wanted to say is that, we can have one of these values:

![screen shot 2016-10-03 at 1 51 02 pm](https://cloud.githubusercontent.com/assets/13949662/19045689/8fa175ea-8970-11e6-8016-6099fcfa3d73.png)

And as you can see, we have the original symbol and also the `Latin form` which is more legible BTW.

Should I use the symbol?

Thanks.

**Comment by pierre** [comment]
> Should I use the symbol?

Yes: `DefaultInvoiceFormatterFactory` is the code that will pretty-print (HTML, PDF) an invoice to the user. The symbol will most likely always be more user-friendly, rather than any other option, regardless of the locale (10€ is nicer than 10 EUR).

Let's just make sure to use variations when a symbol is shared across several currencies (e.g. `A$` for AUD), to avoid any confusion.

**Comment by javier-gomez-github** [comment]
@pierre 
I've pushed my first approach with the symbols of each Currency defined in the Currency class in `killbill-api`.
I still have to write some Integration tests to verify this new behavior but just wanted you to take a look at the symbols:

PR is -> https://github.com/killbill/killbill-api/pull/23

That said, I have a few cases where I didn't know which one I should use as the symbol:
- Hong Kong -> HK$ or 元/圓
- Japanese yen -> ¥ or 円/圓
- Sri Lankan -> SLRs or රු or ரூ
- Nepalese -> N₨ or रू.
- SPL(Seborgan Luigino) -> not considered as an official currency
- Taiwanese -> NT$ or 元/圓

Hope you can help me clarifying those cases.

Thanks!

**Comment by pierre** [comment]
> Hong Kong -> HK$ or 元/圓
> Taiwanese -> NT$ or 元/圓

Looks like the second symbol is shared? I would use HK$ (https://en.wikipedia.org/wiki/Hong_Kong_dollar) and NT$ (https://en.wikipedia.org/wiki/New_Taiwan_dollar) as it's consistent with other dollar symbols.

> Japanese yen -> ¥ or 円/圓

¥, as it's the international version (see https://en.wikipedia.org/wiki/Japanese_yen and https://en.wikipedia.org/wiki/%C2%A5).

> Sri Lankan -> SLRs or රු or ரூ

රු, see https://en.wikipedia.org/wiki/Sri_Lankan_rupee.

> Nepalese -> N₨ or रू.

रू, see https://en.wikipedia.org/wiki/Nepalese_rupee.

> SPL(Seborgan Luigino) -> not considered as an official currency

Keeping SPL is fine in that case, I doubt it will get much use anyways! 😸

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I've made the changes requested during code review and added changes to the core in order to use the new Currency class defined in `killbill-api`.
I've also updated the Integration tests that verifies the behavior.

The PRs are:

- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/15
- killbill-api: https://github.com/killbill/killbill-api/pull/23
- killbill-core: https://github.com/killbill/killbill/pull/623

Please feel free to review them and let me know if I have to change anything else.

Thanks!
