### ISSUE TITLE
Add support for chargeback reversals

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#477]
The current chargeback state machine looks as follows:

![image](https://cloud.githubusercontent.com/assets/51940/12681562/fa189852-c663-11e5-9573-777121ab264b.png)

To support reversals, we need to:

* introduce a new state `CHARGEBACK_REVERSED` from `CHARGEBACK_SUCCESS`
* add links from `CHARGEBACK_FAILED`, `CHARGEBACK_ERRORED` and `CHARGEBACK_REVERSED` to `REFUND_INIT`
* make sure the balance of the payment is correctly reflected in these states
* introduce new APIs `createChargebackReversal` and `createChargebackWithPaymentControlReversal` to transition the chargeback to `CHARGEBACK_REVERSED` from `CHARGEBACK_SUCCESS`

**Comment by sbrossie** [comment]
@pierre All this work should be feasible in 0.16.x as we just add new things?

**Comment by pierre** [comment]
Probably, yes.

What worries me:

* Non-trivial change of behavior of the chargeback state machine (and overall payment balance / state)
* Unknown implications in the plugins (base gem / jar might need to be rebuilt?)
* Analytics?

**Comment by pierre** [comment]
Could we more simply treat these as `CHARGEBACK_FAILED`?

**Comment by pierre** [comment]
One drawback of using `fixPaymentTransactionState` to transition from `CHARGEBACK_SUCCESS` to `CHARGEBACK_FAILED` suggests that something unusual/unexpected happened.

Receiving a chargeback_reversed after chargeback however, is what happens in a normal lifecycle of disputes. It's not like receiving refund_failed after refund_success, because those are a result of shortcomings of the gateway integration with acquirers. For refunds the latter notification is meant to replace he previous one. With chargebacks it's a normal process of receiving a chargeback and later reversing it after it has been successfully defended.

**Comment by pierre** [comment]
For reference, the chargeback process is as follows (simplified):

1. Cardholder contacts Issuer Bank to dispute a charge
2. Issuer Bank credits Cardholder for the charge while the issue is being investigated, then
initiates the chargeback process by submitting a request to the appropriate Card Association (MasterCard, Visa, etc.)
3. Merchant's Acquirer issues credit to the Issuer Bank from the Merchant's account (first chargeback)
4. If Merchant provides sufficient proof that the original charge was valid, the money moves back to the Merchant’s account and the Issuer Bank charges the Cardholder (first reversal)
5. Cardholder can submit a second chargeback
6. If Merchant responds back, Acquirer requests arbitration from the Association (decision is final)

Before step 1., a Request For Information can also be sent to the Merchant, who needs to provide documentation to support the transaction (this could help prevent a chargeback).

Keeping track of the full lifecycle of the chargeback seems out of scope inside Kill Bill. First of all, the gateway / processor may not offer APIs to retrieve this information. Second, chargeback representment may be handled by a third-party (which may not offer APIs either).

However, here is what should happen:

* At step 3., i.e. first chargeback, a chargeback transaction should be created in state `CHARGEBACK_SUCCESS`
* At step 4., i.e. first reversal, the chargeback transaction state should be updated to `CHARGEBACK_FAILED`
* At step 5., i.e. second chargeback, the chargeback transaction state should be updated back to `CHARGEBACK_SUCCESS`
* At step 6., in case of a second reversal, the chargeback transaction state should be updated to `CHARGEBACK_FAILED`

By default:

* We shouldn't need pending nor errored states
* We should prevent further refunds after `CHARGEBACK_SUCCESS` (but not after `CHARGEBACK_FAILED`)
* The payment amount should be 0 after `CHARGEBACK_SUCCESS`

![image](https://cloud.githubusercontent.com/assets/51940/15473354/6851e3d2-20b4-11e6-9cdb-6f0431c98ca1.png)

**Comment by sbrossie** [comment]
@pierre Should that be closed (for `0.17.0`) ?

**Comment by pierre** [comment]
Yup, I think we should be good.
