### ISSUE TITLE
Catalog effectiveDateForExistingSubscriptons is not correctly implemeted

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#481]
The `effectiveDateForExistingSubscriptons` (typo on purpose, this is the name of the variable), is used to decide when **existing subscriptions** should be affected by the price change of the plan.

Unfortunately, this feature does not work as expected because i/ junction pulls the billing events  by using the effectiveDate of the event, which is used to decide which version of the catalog to use and ii/ there is no trigger for that specific date (as indicated by `effectiveDateForExistingSubscriptons`) to generate an invoice and apply the new price change

**Comment by sbrossie** [comment]
A suggestion for that fix would be the following (requires more thinking to look at other possible implementations):

1. When the new catalog is uploaded, we insert a future notification (a new type) for the `effectiveDate` of that catalog
2. When we reach the `effectiveDate` of that new catalog (version) we compute a lit of [plan, `effectiveDateForExistingSubscriptons `], and for each of those entries, we look for all subscriptions currently on that plan, and insert a future notification for the distinct set of account at those dates. The goal is to create the invoice trigger for all these accounts
3. We modify junction to insert a new CHANGE event when those notifications kick-in in such a way that we now insert a new billingEvent in the stream which includes the new price for the plan.

=> As a result the customer would be pro-rated with the new price up to his next BCD, and then on the next cycle a full period at the new price would be invoiced.

**Comment by sbrossie** [comment]
Let's use the picture below to go through scenarios, product questions, and possible implementations:

![issue 481](https://cloud.githubusercontent.com/assets/246910/13537240/c6cacdde-e1f8-11e5-80e8-5f4ceebaa8d5.png)

* A subscription `S1` for plan `P` was created when catalog `v1` was in effect (`t` < `T1`)
* At `T1` we upload a new catalog version `v2` (and we assume it still contains the plan `P` attached to `S1` and has a `effectiveDateForExistingSubscriptons` set for `T3` (`T3` > `T2`)
* At  `T1` < `t` < `T2`, a new subscription `S2`  for plan `P` is created when catalog `v1` is *still* effect (`t` < `T2`)
* At `T2`, the new catalog `v2` becomes effective; All new subscriptions for plan `P` would use new price
* At `T3`, all old subscriptions attached to plan `P` must move to new price

There are 2 use cases, the use case for `S1` and `S2`:
* `S1` was created before the catalog `v2` got uploaded so the information about the  `effectiveDateForExistingSubscriptons` for `P` did not exist in the system. Therefore, the **only way** to trigger the transition to the new price at time `T3` is to follow the proposal above where all unique accounts attached to existing subscriptions started before `T2` in the system for plan `P` need to be invoiced again (by inserting a new invoice notification).
* `S2` was created after the catalog `v2` got uploaded so the information about the  `effectiveDateForExistingSubscriptons` for `P` does exist in the system. For those it would be possible to insert additional future notification for `T3` (this requires real work but this is possible).

In any case, there is a decision to make about product requirement and implementation complexity (and associated issues around scalability):
1. Proposal 1: We go with suggested implementation (potentially we need to re-invoice all accounts in the system on `T3`, which could be millions of accounts for large companies (e.g a company like Netflix has about 45 millions subscribers in the US)
2. Proposal 2: We only do that for plans that are long enough. For smaller plans such as monthly, we use the existing `chargedThroughDate` trigger to make the price correction. For large plans such as monthly we roll with the proposal
3. Proposal 3: We drop the feature

**Comment by sbrossie** [comment]
Today the feature is not implemented at all, that is, this date is not used because the code keeps looking at the old version of the catalog. That part is not too difficult to change.

The other aspect, is the 'trigger' that is required to pro-rate the portion from `T3`=`effectiveDateForExistingSubscriptons ` to the CTD of the subscription. One proposal could be to not implement that piece which means new price would occur but only when it is time to re-invoice the subscription.

**Comment by sbrossie** [comment]
@pierre Should we also fix the typo in the name `effectiveDateForExistingSubscriptons ` (-> `effectiveDateForExistingSubscriptions `) ?

**Comment by pierre** [comment]
> Should we also fix the typo in the name effectiveDateForExistingSubscriptons (-> effectiveDateForExistingSubscriptions) ?

I think so, yes (impact should be minimal since it wasn't implemented).

**Comment by sbrossie** [comment]
@pierre The tricky piece is although it was not implemented, a lot of our xml catalogs had that filed defined (with the typo) and so whoever copied our catalog to implement theirs (i am guessing most folks) will now end up with an invalid catalog (either statically configured or part of their tenant config).

I also agree we should fix it (this is now or never) but not so sure impact is minimal...

**Comment by pierre** [comment]
If that's the case, that would be annoying indeed. But the only place I could find it referenced is in the versioned catalog tests (`WeaponsHireSmall-*.xml`). Is it referenced elsewhere?

**Comment by sbrossie** [comment]
I think that's it (and our main subscription [doc](http://docs.killbill.io/0.16/userguide_subscription.html#_deferred_price_change)
