### ISSUE TITLE
Cleanup/review of date manipulation functions

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#487]
Our Kill Bill code makes a lot of manipulation around dates:
* Given a timezone, conversion from DateTime -> LocalDate. 
* Given a LocalDate to be interpreted in a specific timezone, and a reference time -> DateTime

There are several things we should review/enhance/document:

First, our date manipulation function are spread in multiple places, it would be nice to have one documented  class that embeds all that (along with unit tests and some of which already exist)
* In jaxrs [functions toLocalDate](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L301)
* In entitlement [EntitlementDateHelper](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/EntitlementDateHelper.java)
* In commons [ClockUtil](https://github.com/killbill/killbill-commons/blob/master/clock/src/main/java/org/killbill/clock/ClockUtil.java)

(Those would now become available anywhere in the code)

Second, the `AccountDateAndTimeZoneContext` could probably be cached so it becomes cheap to retrieve and use all over for conversions. That would also eliminate the [hack in junction](https://github.com/killbill/killbill/blob/master/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultBillingEventSet.java#L72) where we set the `DefaultAccountDateAndTimeZoneContext`.

Third, we should review the current strategy for the date computation especially the one we introduced for [Daylight Saving issue](https://github.com/killbill/killbill/issues/445), and think whether similar fix would apply for leap second.

At this stage we would be ready to have a review with date experts.

**Comment by pierre** [comment]
Regarding leap seconds: http://joda-time.sourceforge.net/faq.html#leapseconds

**Comment by pierre** [comment]
> Third, we should review the current strategy for the date computation especially the one we introduced for Daylight Saving issue

Instead of adding a fixed offset, could we simply ignore Daylight Saving Time (e.g. always use PST, never PDT)?

**Comment by pierre** [comment]
Here is the proposed new function:

```
// Create a LocalDate object using the specified timezone (usually, the one on the account), respecting the offset at the time of the referenceDateTime
public LocalDate toLocalDate(final DateTime dateTime, final DateTime referenceDateTime, final DateTimeZone accountTimeZone) {
    // Check if DST was in effect at the reference date time
    final boolean shouldUseDST = !accountTimeZone.isStandardOffset(referenceDateTime.getMillis());
    if (shouldUseDST) {
        final DateTimeZone accountTimezoneWithDST = DateTimeZone.forOffsetMillis(accountTimeZone.getOffset(referenceDateTime.getMillis()));
        return toLocalDate(dateTime, accountTimezoneWithDST);
    } else {
        final DateTimeZone accountTimezoneNoDST = DateTimeZone.forOffsetMillis(accountTimeZone.getStandardOffset(referenceDateTime.getMillis()));
        return toLocalDate(dateTime, accountTimezoneNoDST);
    }
}
```

and associated tests:

```
@Test(groups = "fast")
public void testComputeTargetDateWithDayLightSaving() {
    final DateTime dateTime1 = new DateTime("2015-01-01T08:01:01.000Z");
    final DateTime dateTime2 = new DateTime("2015-09-01T08:01:01.000Z");
    final DateTime dateTime3 = new DateTime("2015-12-01T08:01:01.000Z");

    // Alaska Standard Time
    final DateTimeZone tz = DateTimeZone.forID("America/Juneau");

    // Time zone is AKDT (UTC-8h) between March and November
    final DateTime referenceDateTimeWithDST = new DateTime("2015-09-01T08:01:01.000Z");
    final AccountDateAndTimeZoneContext tzContextWithDST = new DefaultAccountDateAndTimeZoneContext(referenceDateTimeWithDST, tz, internalCallContext);
    assertEquals(tzContextWithDST.computeLocalDateFromFixedAccountOffset(dateTime1), new LocalDate("2015-01-01"));
    assertEquals(tzContextWithDST.computeLocalDateFromFixedAccountOffset(dateTime2), new LocalDate("2015-09-01"));
    assertEquals(tzContextWithDST.computeLocalDateFromFixedAccountOffset(dateTime3), new LocalDate("2015-12-01"));

    // Time zone is AKST (UTC-9h) otherwise
    final DateTime referenceDateTimeWithoutDST = new DateTime("2015-02-01T08:01:01.000Z");
    final AccountDateAndTimeZoneContext tzContextWithoutDST = new DefaultAccountDateAndTimeZoneContext(referenceDateTimeWithoutDST, tz, internalCallContext);
    assertEquals(tzContextWithoutDST.computeLocalDateFromFixedAccountOffset(dateTime1), new LocalDate("2014-12-31"));
    assertEquals(tzContextWithoutDST.computeLocalDateFromFixedAccountOffset(dateTime2), new LocalDate("2015-08-31"));
    assertEquals(tzContextWithoutDST.computeLocalDateFromFixedAccountOffset(dateTime3), new LocalDate("2015-11-30"));
}
```

**Comment by pierre** [comment]
Work has been done in both 0.16.3 and 0.17.0 branches.

**Comment by sbrossie** [comment]
:sunglasses:
