### ISSUE TITLE
Passing 0.999 as a payment amount results inconsistant rounding

### ISSUE THREAD

**Issue by kevinsharpjr** [killbill/killbill#494]
For cyber source and orbital a value of 1.00 is returned where as with the external payment plugin a value of .99 is returned.

**Comment by sbrossie** [comment]
I don't think this is really a bug since USD only supports 3 decimals. The reason behind it has to do with the ruby `monetize` gem which [we use in our ruby plugin](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/payment_plugin.rb#L460) and which does the rounding:

```
2.1.1 :006 > amount = BigDecimal.new("0.999")
 => #<BigDecimal:102a4d5f0,'0.999E0',9(18)> 
2.1.1 :007 > ::Monetize.from_numeric(amount, :USD).cents.to_i
 => 100 
```

**Comment by pierre** [comment]
Not suggesting any change but here are some thoughts:

* Having the rounding logic outside of Kill Bill gives more flexibility to plugins. The `processedAmount` value gives enough information on how the value was actually rounded by the plugin
* The flip side is that each plugin needs to do the rounding. I've just fixed an issue in the [Adyen plugin](https://github.com/killbill/killbill-adyen-plugin/commit/d27729714114bbb7ad122354ae4f8a7aadef100e) about this. Code has also been extracted in the [Java framework](https://github.com/killbill/killbill-plugin-framework-java/commit/14b3a2962d2290d0a34093484ad03a64cb85ed04) for future use (it's already taken care of in the Ruby framework)
* This behavior could silently swallow errors if the client submits bogus data by mistake and doesn't check  `processedAmount`. This could be a great use-case for returning a [Warning header](https://tools.ietf.org/html/rfc7234#section-5.5) which would be logged on the client side

**Comment by sbrossie** [comment]
We now have same behavior in ruby and java. Bug can be closed.
