### ISSUE TITLE
Payment completion endpoint shouldn't create new transactions

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#496]
When completing a payment (via payment and transaction external keys for example), JAX-RS should retrieve first the payment transaction to ensure it exists (otherwise, Kill Bill will silently create a new one).

**Comment by pierre** [comment]
As part of this, let's verify we cannot create a second transaction for initial operations (e.g. we cannot have `PURCHASE_PENDING` and then a `PURCHASE_SUCCESS`).

**Comment by sbrossie** [comment]
There are 2 different things to look at (as described by Pierre, but to make it clear):
* Fix JAXRS to not allow completion of payment for which there is not already a `PENDING` transaction
* Verify that for each initial transaction (`AUTH`, `PURCHASE`) we don't end up with 2 rows if the api is called multiple times after there is already a row in `PENDING`

**Comment by sbrossie** [comment]
> When completing a payment (via payment and transaction external keys for example), JAX-RS should retrieve first the payment transaction to ensure it exists (otherwise, Kill Bill will silently create a new one).

On this first part of the bug description, it looks like we already have a [check in JARS](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java#L319)
