### ISSUE TITLE
Add migrated flag for subscriptions

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#497]
In the same way we already have a `migrated` status for account and invoices, we would like to add one for the subscriptions. However the semantics attached to those flags would be a bit different depending on the type of object:

* **account**: `migrated` is just there for info purpose. System ignores it, and sees this account as any other account in the system
* **subscription**: `migrated` is also just there for info purpose. entitlement and billing associated to this migrated subscription is driven the normal way independently of that `migrated` flag
* **invoice**: `migrated` is interpreted by the system to ignore those invoices (also such invoices are static, no repair, no adjustment and balance of $0). See #495 for this specific task.

**Comment by sbrossie** [comment]
@pierre : Is it acceptable to have different semantics around same flag for different objects?

**Comment by pierre** [comment]
It seems that the behavior is the same for both account and subscription. It's really invoice which is different. Doesn't really shock me - that's something we can document.
