### ISSUE TITLE
BlockingState Ordering logic in entitlement

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#498]
We have a lot of code that is doing ordering inside `entitlement` module:

1. `BlockingStateOrdering` (`insertSorted`) and  `SubscriptionEventOrdering` (`sortedCopy`): Used to order `SubscriptionEvent` for the bundle timeline 
2. `DefaultBlockingState` (`compareTo`) and `ProxyBlockingStateDao` (`sortedCopy`) are used to order `BlockingState`
3. `DefaultBlockingStateDao` (`BLOCKING_STATE_MODEL_DAO_ORDERING`) is used to order `BlockingStateModelDao` for a particular service so as to remove duplicates
4. `DefaultSubscriptionApi` (`SUBSCRIPTION_BUNDLE_COMPARATOR`) is used to order a list of `SubscriptionBundle` (e.g `getSubscriptionBundlesForAccount`).

The original idea was to refactor the sorting in a more unified place, but since they order different things and for different purpose, it does not necessarily make sense. 

However by reviewing the code i'd like to get more understanding for `2.`

**Comment by sbrossie** [comment]
Focusing on bullet `2.`,  DefaultBlockingState (compareTo) and ProxyBlockingStateDao (sortedCopy):

1. I am unclear on the [ordering strategy](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java#L87) we are using
2. There is a comment in [DefaultBlockingState](https://github.com/killbill/killbill/blob/master/api/src/main/java/org/killbill/billing/junction/DefaultBlockingState.java#L135) that does not quite make sense to me
3. There is comment in [](https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java#L67) that says ordering is critical to junction but looks like [junction is using the  `compareTo` method from `DefaultBlockingState`](https://github.com/killbill/killbill/blob/master/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BlockingCalculator.java#L151)

**Comment by pierre** [comment]
A few thoughts:

> I am unclear on the ordering strategy we are using

When we arrive line 87, we have two blocking states for the same date, the same blockable id but different services. We need some form of stable ordering in that case and by convention, we decided to respect block billing transitions first, then block entitlement transitions and finally block changes transitions (so if one event for service A is block billing and another for service B is block changes, the former has higher precedence, in that day).

> There is a comment in DefaultBlockingState that does not quite make sense to me

`BLOCKING_STATE_MODEL_DAO_ORDERING` determines the ordering on disk when creating the blocking states. For consistency, we want the same ordering for blocking states not yet on disk for add-ons (impacted by future changes or cancellations). See https://github.com/killbill/killbill/blob/master/api/src/main/java/org/killbill/billing/junction/DefaultBlockingState.java#L146-L148.

> There is comment in that says ordering is critical to junction but looks like junction is using the compareTo method from DefaultBlockingState

Junction relies on it via this call chain:

* https://github.com/killbill/killbill/blob/master/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BlockingCalculator.java#L107
* https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultInternalBlockingApi.java#L55
* https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java#L234
* https://github.com/killbill/killbill/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/dao/ProxyBlockingStateDao.java#L327

**Comment by pierre** [comment]
I think most of the complexity comes from the fact that we have events on disk, and some that are constructed on-the-fly. Maybe always writing to disk would simplify this?

**Comment by sbrossie** [comment]
Closed as a duplicate for #269 (although there is good info in that issue).
