### ISSUE TITLE
Usage API idempotency

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#502]
The goal is to have the user pass an identifier (called `tracking_id`) when recording usage. Subsequent requests with that tracking id should not result in duplicated usage being recorded.

Tasks:

- Add a `tracking_id varchar(128) NOT NULL` column to `rolled_up_usage`.
- Index: `CREATE INDEX rolled_up_usage_tracking_id_subscription_id_tenant_record_id ON rolled_up_usage(tracking_id, subscription_id, tenant_record_id);`.
- Update `RolledUpUsageModelDao`, `UsageRecord` and `SubscriptionUsageRecordJson` (as well as the java client library model) to allow passing the tracking id when recording usage (the key won't be returned in the GET APIs, as current APIs aggregate usage rows). If the id isn't set, a random UUID should be generated using the `UUIDs` helper class. Note that all `RolledUpUsageModelDao` rows will share the same id from `SubscriptionUsageRecordJson`.
- Add a transactional bulk API to `DefaultRolledUpUsageDao` and `RolledUpUsageDao` **to record all row transactionally**. For performance reasons, we should use the `@SqlBatch` annotation in `RolledUpUsageDao` (see example in [QueueSqlDao](https://github.com/killbill/killbill-commons/blob/master/queue/src/main/java/org/killbill/queue/dao/QueueSqlDao.java#L107-L109)).
- Add a check in `DefaultUsageUserApi` when recording usage if we have (at least) one row with the supplied tracking id. If so, a checked exception should be thrown (similar to [DefaultAccountUserApi](https://github.com/killbill/killbill/blob/master/account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountUserApi.java#L84), let's introduce a new `UsageApiException` and `ErrorCode`).

Due to the API and DDL changes, work should be done against the `work-for-release-0.17.0` branch.

**Comment by sbrossie** [comment]
I am wondering if we should call it `external_key`. Usually our apis include a `getByExternalKey` and as you mentioned this will not be returned by GET (aggregation). Maybe a `tracking_id` (to make it clear this is simply used to avoid dups) ?

**Comment by pierre** [comment]
Sure, :+1: for `tracking_id`.

**Comment by sbrossie** [comment]
Note that initial description has been updated with comments below.

**Comment by almalki** [comment]
Hi pierre,

I have few questions:

> Index: CREATE INDEX rolled_up_usage_tracking_id_subscription_id_tenant_record_id ON rolled_up_usage(tracking_id, subscription_id, tenant_record_id);.

shouldn't this be UNIQUE index to prevent duplicates at the db level?

> Update RolledUpUsageModelDao, UsageRecord and SubscriptionUsageRecordJson (as well as the java client library model) to allow passing the tracking id when recording usage

So this means the API caller will send only one tracking_id for all records(UsageRecordJson)?
i.e SubscriptionUsageRecordJson will have one attribute `private String trackingId`?

> If the id isn't set, a random UUID should be generated using the UUIDs helper class.

I did this in SubscriptionUsageRecordJson constructor, is it ok?

> Note that all RolledUpUsageModelDao rows will share the same id from SubscriptionUsageRecordJson.

I used toSubscriptionUsageRecord to set the tracking ID in all UsageRecord

> Add a transactional bulk API to DefaultRolledUpUsageDao and RolledUpUsageDao to record all row transactionally. For performance reasons, we should use the @SqlBatch annotation in RolledUpUsageDao (see example in QueueSqlDao).

did you mean to add the `@SqlBatch` annotation to `RolledUpUsageSqlDao`?

Also, should I keep the old single record method `create` in `RolledUpUsageSqlDao` or should I replace it?

**Comment by pierre** [comment]
> shouldn't this be UNIQUE index to prevent duplicates at the db level?

It actually won't be unique: multiple rows are inserted at the same time (batch API), and the user will provide a unique tracking id per API call. It will be unique "by batch" however (written once, by a single DB transaction) -- you cannot capture that in the index unfortunately.

We need the index to speed up detecting duplicates (when we check if that tracking id already exists).

> So this means the API caller will send only one tracking_id for all records(UsageRecordJson)? i.e SubscriptionUsageRecordJson will have one attribute `private String trackingId`?

Correct.

> if this is the case, then we should change `SubscriptionUsageRecord` to have tracking ID not `UsageRecord`, right?

`SubscriptionUsageRecord` will have the new tracking ID (passed at the API level from the JAX-RS model). You are correct that `UsageRecord` doesn't need to change (but `RolledUpUsageModelDao` will) -- this was a leftover from the original ticket.

> I did this in `SubscriptionUsageRecordJson` constructor, is it ok?

We actually prefer doing it at the DAO level (i.e. in `RolledUpUsageModelDao`) -- see how we do it in [AccountModelDao](https://github.com/killbill/killbill/blob/master/account/src/main/java/org/killbill/billing/account/dao/AccountModelDao.java#L70) for example. The reason for it is that some of our users embed Kill Bill as a library, so we don't want to duplicate logic in JAX-RS and in the library (usage module).

> I used toSubscriptionUsageRecord to set the tracking ID in all UsageRecord

As discussed above, `UsageRecord` doesn't need it.

> did you mean to add the `@SqlBatch` annotation to `RolledUpUsageSqlDao`?

The annotation needs to be added on a new bulk DAO API, e.g. `void record(@BindBean Iterable<RolledUpUsageModelDao> rolledUpUsages, @InternalTenantContextBinder final InternalCallContext context)`

> Also, should I keep the old single record method `record` in `RolledUpUsageDao` or should I replace it?

You can replace it with something more appropriate (e.g. `void record(final Iterable<RolledUpUsageModelDao> rolledUpUsages, final InternalCallContext context)`). Note that some tests will need to be updated (see `TestDefaultRolledUpUsageDao`).

**Comment by sbrossie** [comment]
I think this can be closed. PR was merged.
