### ISSUE TITLE
Overdue Killbill API 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#51]
Overdue Apis are not public anymore. Should we re-export them in public Apis?
How does that play with a potential overdue module?

**Comment by sbrossie** [comment]
We need to export a similar API than the one we have in OverdueInternalApi to retrieve the OverdueState for the account.

**Comment by pierre** [comment]
We now have:

* `getOverdueAccount` in `AccountResource`, which returns `OverdueStateJson`
* `getBlockingStates` in `DefaultSubscriptionApi`, which needs to be exported in JAX-RS

**Comment by pierre** [comment]
`AccountResource` still uses `OverdueInternalApi`. It should use a public API instead (see https://github.com/killbill/killbill/issues/53).
