### ISSUE TITLE
Wrong redirect url after create any entity when killbill is deployed as non-root

### ISSUE THREAD

**Issue by matias-aguero-hs** [killbill/killbill#510]
The killbill as non-root issue was fixed #221, but when killbill is deployed as non-root, there is an issue after create any entity like account, subscription, etc. The redirect URL does not contains the correct base url.

Example.
- killbill deployed as: `http://localhost:8080/killbill/api.html`
- account created by: `http://localhost:8080/killbill/1.0/kb/accounts`
- redirect url returned: `http://localhost:8080/1.0/kb/accounts/71caf7a3-e977-4ab0-940e-c8912538c8f7` (it's missing `/killbill/`)

There are two big consequences. First is that KAUI can't show the new entity created and when killbill client is used it can't return the new entity because is not loaded.

**Comment by matias-aguero-hs** [comment]
![screen shot 2016-03-15 at 13 01 42](https://cloud.githubusercontent.com/assets/16122016/13784558/814e2fd0-eaae-11e5-89f6-1d0cf287e61f.png)

**Comment by matias-aguero-hs** [comment]
@sbrossie @pierre this issue is duplicated. #221

**Comment by sbrossie** [comment]
@matias-aguero-hs  Can i close this issue?

**Comment by matias-aguero-hs** [comment]
Yes, you can close this issue.
