### ISSUE TITLE
Usage API accepts null unitType

### ISSUE THREAD

**Issue by almalki** [killbill/killbill#513]

**Comment by sbrossie** [comment]
@almalki Happy to merge a PR if you want or if not we'll address it in our 0.17.1 milestone.

**Comment by almalki** [comment]
@sbrossie a PR should be against 0.16 or 0.17? I think it should be in 0.16 since it is a bug fix and just validation in API

**Comment by sbrossie** [comment]
@almalki Yep you are correct, this can land in 0.16.4 (no api change). Will move the milestone accordingly.
