### ISSUE TITLE
Voided authorization should be a terminal state

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#514]
Now that we support void on captures, the following is allowed by the payment state machine: AUTH, VOID, VOID.

While AUTH, CAPTURE, VOID, VOID is allowed, we should prevent further transactions when the AUTH is voided.

**Comment by sbrossie** [comment]
@pierre I am actually unclear on what we want to verify here. 

> Now that we support void on captures, the following is allowed by the payment state machine: AUTH, VOID, VOID.

What does that second VOID mean?

> While AUTH, CAPTURE, VOID, VOID is allowed,

Is it? If we first AUTH and then CAPTURE, i understand the new desire to VOID the capture but then do we also want to allow to VOID the AUTH. How do we link the VOID to specific transactions?

> we should prevent further transactions when the AUTH is voided.

Yes that part kindda makes sense, but in the details this is not so simple:
1. AUTH + VOID : CAPTURE fail
2. AUTH + VOID : new AUTH fail ? Independently of key used? ( i believe so)
3. AUTH + VOID : CREDIT or PURCHASE fail

Depending on what decide here, might require some substantial changes, so we should also decide what is the minimum we want to test and implement.

**Comment by pierre** [comment]
> What does that second VOID mean?

Nothing: the bug is that it's allowed today. We should prevent it.

> If we first AUTH and then CAPTURE, i understand the new desire to VOID the capture but then do we also want to allow to VOID the AUTH. How do we link the VOID to specific transactions?

Yes, in certain cases, we actually need to to avoid fees (what CyberSource recommends IIRC), because we need to release the funds. There is no way really today to link these transactions explicitly (the code just link them [implicitly](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/api/DefaultPayment.java#L64-L94), by ordering through time).

> AUTH + VOID : CAPTURE fail

If the auth is voided, captures should be prevented.

> AUTH + VOID : new AUTH fail ? Independently of key used? ( i believe so)

:+1: 

> AUTH + VOID : CREDIT or PURCHASE fail

:+1: (AUTH is an entry point, no other entry point should be allowed)

> Depending on what decide here, might require some substantial changes, so we should also decide what is the minimum we want to test and implement.

Absolutely. One day, this should really be handled by the state machine, in a [configurable way](https://github.com/killbill/killbill/issues/330) since gateways and processors have different behaviors.

**Comment by pierre** [comment]
Closing as won't fix.

AUTH, VOID, VOID is disallowed by default. However, when configuring the state machine to allow VOID on CAPTURE, the transition AUTH, VOID, VOID will be allowed. Fixing it is hard and not worth it at this point (see lengthy discussions on https://github.com/killbill/killbill/issues/330 and https://github.com/killbill/killbill/issues/504).

Users who might be affected are encouraged to make sure the payment plugin is well behaved and returns `CANCELED ` when trying to void an already voided auth.
