### ISSUE TITLE
Use Flyway to manage database schema migrations

### ISSUE THREAD

**Issue by almalki** [killbill/killbill#521]
[Flyway ](https://flywaydb.org/)would be a great addition to kill bill to manage and track database migrations instead of keeping changing ddl.sql files and wiki pages.

**Comment by pierre** [comment]
Good timing!

I've just published a proposal on how database migrations would work with Kill Bill and its plugins: https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/database_migrations.adoc (starting with 0.16.4).

The proposal is currently under review by a few users, feel free to share your feedback as well.

**Comment by pierre** [comment]
Done. Schema files for 0.17.x still need to be written though (see https://github.com/killbill/killbill/wiki/Kill-Bill-Migration-0.16.x-to-0.18.x).
