### ISSUE TITLE
Ability to specify a hierarchical ADD_ON products in the catalog

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#539]
The feature originated from the following [killbill-user mailing discussion](https://groups.google.com/forum/#!topic/killbilling-users/wqcaT53PzYY). 

**Overview:**

The feature is to enhance catalog and Kill Bill behavior to support a hierarchy of AOs: Given a product BASE `Medium` with two AOs `A` and `B`, then also allow those AOs to specify their own AOs `APlus` and `BPlus`, leading to the following catalog definition

```
 <products>
    <product name="Medium">
      <category>BASE</category>
      <available>
        <addonProduct>A</addonProduct>
        <addonProduct>B</addonProduct>
      </available>
    </product>
    <product name="A">
      <category>ADD_ON</category>
      <available>
        <addonProduct>APlus</addonProduct>
      </available>
    </product>
    <product name="B">
      <category>ADD_ON</category>
      <available>
        <addonProduct>BPlus</addonProduct>
      </available>
    </product>
    <product name="APlus">
      <category>ADD_ON</category>
    </product>
    <product name="BPlus">
      <category>ADD_ON</category>
    </product>
  </products>
```

**Behavior:**
- Catalog
  - Fetching catalog, returns the hierarchy defined in the xml
  - Listing available AOs: There is a question on whether we want to list all AOs associated to the tree below the BP or only the first level (and then allow to list each level). The former is the simpler option (considering what we already have)
- Subscription Lifecycle
  - When creating associated subscriptions, all subscriptions end up into one bundle (and not N bundles associated with each level).  So, the feature does not transform AOs into BPs, but enhance AOs to be hierarchical and the concept of a BP attached to a bundle still remain.
  - When canceling BP all AOs subscriptions get cancelled (or when changing the plan associated to the BP and where some AO are not available or already included, similar behavior happens)
  - When canceling AO subscription, all AO subscriptions that were available because of that subscription would get cancelled (similarly for change of Plan)

**Comment by GiulianoGrassi** [comment]
Q: There is a question on whether we want to list all AOs associated to the tree below the BP 
A: From a users perspective, our company thinks, that the product catalogue should contain the whole tree and not just the next level after the BP as you always want to offer as much as possible.

when doing so, there will be a following question IMHO:
we should define what would be best when subscribing to APlus without having A?
1. Throw KillBillError: Couldnt subscribe APlus as the dependency to A is not met
2. Dont Throw KillBillError and successfully subscribe A (or whatever is between APlus till the root node) before subscribing APlus

**Comment by sbrossie** [comment]
**Current Proposal**

1. Catalog would be enhanced to provide the hierarchical AO described above (providing the ability to prompt customers with the right `Plan` choices.
2. Internally, KB would keep its current model based on the fact that a `SubscriptionBundle` is attached to one `BP` subscription and can contain any number of `AO` subscriptions:
  * Those subscriptions would not show the hierarchical structure of the catalog but would appear as flat in that bundle
  * All the logic that we currently have when canceling (or changing `Plan`) the `BP` subscription would need to also be applied to the `AO` subscription

**Details on the work**

_**Subscription/entitlement Layers:**_

CREATE BP -> nothing different than today

CREATE AO 
1. Verify if AO can be created -> plan P
1.a If any subscription include P => NO
1.b If there is **not** at least one subscription allowing P => NO

2. Verify if some AOs need to be cancelled
If P include any plans, for each Pi, we should cancel the subscription on Pi

CHANGE BP
1. Verify if some AOs need to be cancelled (current logic)

CHANGE AO
1. Verify if AO can be changed -> plan P'
1.a If any subscription include P' => cancel AO
1.b If there is **not** at least one subscription allowing P' => Fail operation

2. Verify if some AOs need to be cancelled

CANCEL BP
1. Cancel all AOs (current logic)

CANCEL AO
1. Verify if some AOs need to be cancelled

_**Catalog:**_

* Add catalog validation
* Verify correct info is returned when hitting catalog endpoints

**Comment by sbrossie** [comment]
Also related see #545
