### ISSUE TITLE
Catalog endpoint does not return usage info.

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#543]

**Comment by sbrossie** [comment]
See mailing [thread](https://groups.google.com/forum/#!topic/killbilling-users/5S0dF_zal8A)

**Comment by javier-gomez-hs** [comment]
@sbrossie 
I can start working on this one.
Would you be able to tell me more details about this specific issue?

Thanks!

**Comment by javier-gomez-hs** [comment]
@pierre @sbrossie 
I've made some changes in the code to allow the usage info. I've also modified an integration test to verify the usage info added.
These are the PR:
- KB Core: https://github.com/killbill/killbill/pull/588
- KB Client Java: https://github.com/killbill/killbill-client-java/pull/43
- KB OSS Parent: https://github.com/killbill/killbill-oss-parent/pull/9

Please, feel free to take a look at them and let me know if I have to change anything else.

Thanks!
