### ISSUE TITLE
Proposal to make transactionStatus Nullable in AdminPaymentApi#fixPaymentTransactionState

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#551]
The new behavior would make Kill Bill transform the passed `PaymentTransactionInfoPlugin#status` into the proper `transactionStatus` if the `transactionStatus` specified is `null`.

This would prevent code like [this](https://github.com/killbill/killbill-adyen-plugin/blob/a5f0bf3e71aabd1dbaee3a0306d7155a3fbfb5b2/src/main/java/org/killbill/billing/plugin/adyen/core/KillbillAdyenNotificationHandler.java#L303-L320) in plugins.

**Comment by sbrossie** [comment]
Not sure i understand the proposal. If we pass a null `PaymentTransactionInfoPlugin#status` how does the Kill Bill know how to compute that status (it does not have access the `PaymentPluginStatus` ?)

**Comment by pierre** [comment]
At least `transactionStatus` or `PaymentTransaction#PaymentTransactionInfoPlugin#status` would need to be specified.
