### ISSUE TITLE
Logging in DefaultPaymentApi can output data associated to the wrong transaction

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#552]
See https://github.com/killbill/killbill/blob/10dd537a8911e413288c38d399c026c9374b6381/payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java#L174 for example. In case of two pending captures,  when completing the first one, the logging output would be wrong.

**Comment by sbrossie** [comment]
So in case we have a non null `paymentTransactionExternalKey`, this is fairly easy to fix, but otherwise, we don't really have the info (look for row with latest `updatedDate`, yack...)

**Comment by pierre** [comment]
Yeah...

For reference: https://github.com/killbill/killbill/blob/fix-for-477/payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentApi.java#L682-L689.

**Comment by sbrossie** [comment]
Also looks like DefaultPaymentApi log trace show an incorrect: `amount='0E-9'`
