### ISSUE TITLE
Revisit the credit story for HA parent

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#553]
In the HA (Hierarchical Account) model, when a child delegates its payment to its parent, the parent must first build a summary invoice (one for all its dependent children on any given day). Today this is built by adding a new `PARENT_SUMMARY` invoice item for each child and the amount is the child invoice amount. 

This model therefore includes any credit that child may have on the parent summary invoice , and this probably does not make sense as we don't want to use a given child's credit at the parent level by default.

The proposal is the following:
* Credits are not by default visible at the parent level
* We have a new api which allow to move a given child credit to the parent level (to support the use case when for instance a child cancels his subscription and is left with some 'recognizable credit'.

**Comment by matias-aguero-hs** [comment]
This issue is because the [parent invoice creation event](https://github.com/killbill/killbill/blob/hierarchical-accounts/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L715) is using ``childInvoice.getChargedAmount()`` to calculate parent item amount, and it contemplates the following item types:

```Java
if (isCharge(invoiceItem) ||
    isInvoiceAdjustmentItem(invoiceItem, otherInvoiceItems) ||
    isInvoiceItemAdjustmentItem(invoiceItem) ||
    isParentSummaryItem(invoiceItem)) {
    amountCharged = amountCharged.add(invoiceItem.getAmount());
}
```
I suggest to create a new method in ``InvoiceCalculatorUtils`` (from ``computeInvoiceAmountCharged()``) and return the correct item amounts:

```Java
public static BigDecimal computeChildInvoiceAmountCharged(final Currency currency, @Nullable final Iterable<InvoiceItem> invoiceItems) {
        BigDecimal amountCharged = BigDecimal.ZERO;
        ...
        for (final InvoiceItem invoiceItem : invoiceItems) {
            ...
            if (isCharge(invoiceItem) ||
                isInvoiceItemAdjustmentItem(invoiceItem)) {
                amountCharged = amountCharged.add(invoiceItem.getAmount());
            }
        }
        return KillBillMoney.of(amountCharged, currency);
    }
     // checks removed
     // isInvoiceAdjustmentItem(invoiceItem, otherInvoiceItems)
     // isParentSummaryItem(invoiceItem)
```

**Comment by matias-aguero-hs** [comment]
I think I need to remove ``isInvoiceItemAdjustmentItem(invoiceItem)``from previous code block because when cancel a subscription a REPAIR_ADJ item is created and it's thrown to the parent.

```Java
    // Item adjustments
    public static boolean isInvoiceItemAdjustmentItem(final InvoiceItem invoiceItem) {
        return InvoiceItemType.ITEM_ADJ.equals(invoiceItem.getInvoiceItemType()) || 
                  InvoiceItemType.REPAIR_ADJ.equals(invoiceItem.getInvoiceItemType());
    }
```

**Comment by sbrossie** [comment]
The short answer is that you correctly identified that the `DefaultInvoice#getChargedAmount()` is not the correct way to compute the amount that should appear in the parent summary invoice. Let me provide a few scenarios to illustrate what should happen (before we even dig into the code change):

**Note:** Each of those scenarii should match with a test case (probably beatrix level)

**Scenario 1: Follow up Invoice Item Adjustment on unpaid invoice**

Let's assume we had a previous invoice with a $20 (`RECURRING`) item (generating also a $20 `PARENT_SUMMARY` item). Parent invoice is left unpaid. Then, administrator issues a $10 `ITEM_ADJ` on the child invoice. Child invoice now contains:

* `RECURRING` : $ 20
* `ITEM_ADJ` : $ -10

Because parent invoice was not paid, there is no `CBA_ADJ` generation by the system and **the parent summary invoice should be adjusted accordingly (i.e the `PARENT_SUMMARY` item should now be $10)**


**Scenario 2: Follow up Invoice Item Adjustment on PAID invoice**

Let's assume we had a previous invoice with a $20 (`RECURRING`) item (generating also a $20 `PARENT_SUMMARY` item). Parent invoice was paid fully. Then, administrator issues a $10 `ITEM_ADJ` on the child invoice. Child invoice now contains:

* `RECURRING` : $ 20
* `ITEM_ADJ` : $ -10
* `CBA_ADJ` : $ +10

This means that child now has a $10 credit on its account for future use. **Nothing should happen at the parent level (i.e the two new items `ITEM_ADJ` and `CBA_ADJ` should be ignored by the parent.)**

**Scenario 3: Repair (early cancellation, plan downgrade) on unpaid invoice**

This scenario is similar to scenario 1 except new items appear on a new (child) invoice. Let's assume we had a previous invoice (Invoice 1) with a $20 (`RECURRING`) item (generating also a $20 `PARENT_SUMMARY` item). Parent invoice is left unpaid. User cancels his subscription early on  generating a `REPAIR_ADJ` item on a new invoice.

Invoice 2:
* `REPAIR_ADJ` $ -15
* `CBA_ADJ` $ 15

Invoice 1:
*  `RECURRING` : $ 20
* `CBA_ADJ` $ -15 # Use of credit generated on invoice 2 and bringing back invoice balance to $5

The parent should **ignore invoice 2** and modify its previous `PARENT_SUMMARY` to become $5. The child is left with no credit.

**Scenario 4: Repair (early cancellation, plan downgrade) on PAID invoice**

This scenario is similar to scenario 2 except new items appear on a new (child) invoice.  Let's assume we had a previous invoice with a $20 (`RECURRING`) item (generating also a $20 `PARENT_SUMMARY` item). Parent invoice is fully PAID. User cancels his subscription early on  generating a `REPAIR_ADJ` item on a new invoice.

Invoice 2:
* `REPAIR_ADJ` $ -15
* `CBA_ADJ` $ 15

Invoice 1: # unchanged
*  `RECURRING` : $ 20

The parent should **ignore invoice 2**. The child is left with a $15 credit

**Scenario 5:  Use of credit**

Imagine a scenario where a child has some existing credit (example from `Scenario 4`) of $5. Let's assume we also have a next invoice with a $20 `RECURRING` item.

*  `RECURRING` : $ 20
* `CBA_ADJ` $ -5

The parent will see a `PARENT_SUMMARY` of $15.

**Comment by sbrossie** [comment]
@maguero I would suggest a test-driven approach here (write scenario for each case) and see what happens with current implementation. I'd like @pierre to also review those use cases (he is off until the end of the week). After that, you can submit a proposal on what is the best course of action to modify the code (i think you are on the track track:we probably need new dedicated methods in `InvoiceCalculatorUtils` but this is probably not enough to achieve the result.

**Comment by matias-aguero-hs** [comment]
Great, thanks for the scenarios. I'm working on those beatrix level tests.
So, the plan is don't include the child 'credit' in parentInvoice if it is already in COMMITTED state, isn't it? (and use it in next invoice)

> Then, administrator issues a $10 ITEM_ADJ on the child invoice.

Is ``InvoiceUserApi.insertInvoiceItemAdjustment(...)`` the right method to do that?

**Comment by sbrossie** [comment]
The plan is to match the scenarii i described above: In short, that means that parent should not 'inherit' from child credit when it exists (although we will also need to add a new api to transfer that credit, but let's ignore that for the time being).

You can see in the scenarii that in some case that means:
* Modify previous parent's `PARENT_SUMMARY ` item (e.g scenario 1, 4)
* Ignore children items `ITEM_ADJ ` and `CBA_ADJ ` (e.g scenario 2)
* Both modify previous parent's `PARENT_SUMMARY ` and ignore children items `ITEM_ADJ ` and `CBA_ADJ `  (e.g scenario 3)
* Take into account the negative `CBA_ADJ ` to compute the amount for the  `PARENT_SUMMARY ` (scenario 5).

**Comment by matias-aguero-hs** [comment]
I ran the first 4 scenarios by beatrix test level and also manually using KAUI. Scenarios 2 and 4 (when invoice is already paid) have the same results as 1 and 3 respectively (1 == 2, and 3 == 4). I also tested a regular account and it's working fine.

Results:

Scenario | Child Invoice | Regular Invoice
------------ | ------------- | -------------
1 | OK | OK
2 | Missing (CBA_ADJ : $ +10) | OK
3 | OK | OK
4 | Additional (CBA_ADJ $ -15) in invoice 1 | OK

I suppose that, when its a child invoice and payment is delegated to parent, no payments are attached to this child invoice and core may have some checks that are asking for payments when decides to add the CBA_ADJ to the existing child invoice. Can you please confirm that?

We need to fix this issue first and then attack credit issue again.

**Comment by sbrossie** [comment]
@matias-aguero-hs I am bit confused by your explanation above, so let's go point by point:

1. It seems like you ran all 4 scenarii with regular invoice (e.g: no child-parent  relationship) and this is working as expected. This is the right (third) column of your table above. Can you confirm?
2. In the table above, i am confused with the middle column. For HA use cases (e.g: child-parent  relationship exists), we need to look at both child invoice items and parent item (`PARENT_SUMMARY `).  I would expect that with **existing code**:
  * child invoice would work as expected (similar to what you call regular invoice),
  * parent invoice would not work as expected (changes that were highlighted in my scenario description above)
Can you confirm?

Now to your question:
> I suppose that, when its a child invoice and payment is delegated to parent, no payments are attached to this child invoice and core may have some checks that are asking for payments when decides to add the CBA_ADJ to the existing child invoice. Can you please confirm that?


The [logic](https://github.com/killbill/killbill/blob/hierarchical-accounts/invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java#L256) you wrote is that payments against a child invoice are inferred by looking at whether the full parent summary invoice was paid:
* If parent fully paid its summary invoice, child assumes its balance is 0
* If parent did not fully paid its summary invoice, child computes its balance by assuming there was no payment and just computing invoice amount.

Does that answer your question?

Also i would suggest to add a test case for the fifth scenario later on.


If this is not clear, we can also have a chat (in which i would probably first need to get my hands on your test cases so i can run them and see exactly what you are seeing). Let me know what you think is best.

**Comment by matias-aguero-hs** [comment]
@sbrossie about first 2 points.
1 - Yes. You are right. Regular invoice (e.g: no child-parent relationship) is working as you described in the scenarios. We are good.

2 - HA use cases (e.g: child-parent relationship exists). I tested the same scenarios and the results for scenario 2 and 4 are different as you described. (Let's now focus on child invoices)
* Scenarios 1 and 3 are working as you described.
* In scenario 2 item ``CBA_ADJ : $ +10`` is missing in child invoice after issue credit.
* In scenario 4 an additional item ``CBA_ADJ $ -15`` is added in ''Invoice 1: # unchanged`` when subscription is early cancelled and parent invoice was already paid.

I'm debugging code to find where is adding ``CBA_ADJ`` items to see if we need to add some validations for child-parent relation.

I want to fix that behaviour now and then move to parent invoices and the fifth test scenario.

I'll be commiting my tests later today after some investigation and you will be able to see if we are recreating scenarios properly.

Thanks.

**Comment by pierre** [comment]
@sbrossie Scenarios look good. Just to confirm, for 1 and 3, when the parent invoice needs the be *modified*, it's either:

* Done transparently at creation time for draft invoices
* Done via item adjustments (one per child) for committed invoices

i.e. the line items aren't updated, correct?

**Comment by sbrossie** [comment]
@pierre  We have a choice to either:
1. Modify parent invoice (update amount) when there is a need for an adjustment
2. Add an `ITEM_ADJ ` in the parent invoice.

Before the parent invoice was COMMITTED (i.e the same day it was created), the code will automatically adjust the amount, and this is what we need. After it has been COMMITTED, it probably makes sense to add an `ITEM_ADJ ` to make it clear things have changed. The drawback is that we then end up with potentially more than one item (`PARENT_SUMMARY `) for a given child on a given invoice.

I would suggest to do that (add `ITEM_ADJ `), and if we realize this is not the correct product behavior we can change it down the road.

 @maguero: Does that make sense?

**Comment by matias-aguero-hs** [comment]
@sbrossie: yes, it makes sense. I'll be working on that.

In the meantime, you can check/run the beatrix test I pushed last friday. https://github.com/matias-aguero-hs/killbill/commit/253cfdb690fa106e41adb169df10521fadd5a872

**Comment by sbrossie** [comment]
@maguero Just reviewed/commented your tests. 

What is the status on your side? Are you blocked on anything from us?

**Comment by matias-aguero-hs** [comment]
@sbrossie: thank you for commit comments.

I just created a PR https://github.com/killbill/killbill/pull/561 for this issue.
Next step is **_the new api which allow to move a given child credit to the parent level_**.

**Comment by matias-aguero-hs** [comment]
> We have a new api which allow to move a given child credit to the parent level (to support the use case when for instance a child cancels his subscription and is left with some 'recognizable credit'.

@sbrossie @pierre do you have any suggestion on how to implement it? I think when the api is call we can create a new parent invoice with the credit, but I don't know how to "mark" the child credit as **used**.

**Comment by pierre** [comment]
Could we use the `deleteCBA` feature (which really just consume the CBA)?

**Comment by sbrossie** [comment]
After talking to @pierre we decided to take a different approach (deleting `CBA` may cause some issues). Instead what we suggest is a new api that would:
1. On one side add an external charge on the child account (that would consume the child `CBA`)
2. Add a credit on the parent  (that would create the parent `CBA`)

The api could be of the form: `transferChildCreditToParent(childAccountId, parentAccountId, callContext)` and it would result into one DAO transaction so operation is atomic.  Also we would set a sane description when creating the charge on the child side (to make it clear this is a charge to consume the credit). Maybe something like "child credit transfer to parent"

**Comment by matias-aguero-hs** [comment]
@sbrossie @pierre 
You can find last changes pushed. Those changes includes issue fixed, new transfer api and killbill-client-java module updated.

PRs:
- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/38
- killbill-api: https://github.com/killbill/killbill-api/pull/14
- killbill: https://github.com/killbill/killbill/pull/561

**Comment by sbrossie** [comment]
@maguero I wrote a test and it seems like Scenario 1 (Follow up Invoice Item Adjustment on unpaid invoice) [does not work as expected](https://github.com/killbill/killbill-integration-tests/blob/work-for-release-0.17.x/killbill-integration-tests/core/test_ha.rb#L550) (or i got my test wrong...). Could you double check?

**Comment by matias-aguero-hs** [comment]
> I wrote a test and it seems like Scenario 1 (Follow up Invoice Item Adjustment on unpaid invoice) does not work as expected (or i got my test wrong...). Could you double check?

When you [move 1 day](https://github.com/killbill/killbill-integration-tests/blob/work-for-release-0.17.x/killbill-integration-tests/core/test_ha.rb#L540) with `kb_clock_add_days(1, nil, @options)` the parent invoice is moved to COMMITTED status and paid, so you won't have the parent invoice updated to $400 [here](https://github.com/killbill/killbill-integration-tests/blob/work-for-release-0.17.x/killbill-integration-tests/core/test_ha.rb#L551).
If you want to get current parent invoice adjusted you [shouldn't move one day](https://github.com/killbill/killbill-integration-tests/blob/work-for-release-0.17.x/killbill-integration-tests/core/test_ha.rb#L540).

When a child invoice is generated, a parent invoice is also generated automatically and keep in DRAFT day until next day. Any adjustment in the same day (when parent invoice is still in DRAFT status) will be reflected in that parent invoice, otherwise a new parent invoice will be generated if needed.

**Comment by sbrossie** [comment]
@maguero The scenario i wrote is Scenario 1 (Follow up Invoice Item Adjustment on unpaid invoice). I made sure account had no payment method so no payment could be made, and therefore we end up doing an adjustment on an invoice that was unpaid. (And yes, i moved the clock one day because i wanted the parent invoice to be committed **prior** i do the adjustment.

In this scenario i expect to see what i described above:  "the parent summary invoice should be adjusted accordingly (i.e the PARENT_SUMMARY item should now be $10)". In the end, i see the adjustment on the child invoice but not on the parent invoice. Seems like a bug to me, or am i missing something?

**Comment by matias-aguero-hs** [comment]
> The scenario i wrote is Scenario 1 (Follow up Invoice Item Adjustment on unpaid invoice) ...

Interesting.... I think we have an scenario we didn't discuss. Despite of the parent invoice is unpaid (for any reason), if we move to next day the parent invoice status is now COMMITED and we are not allowing invoices changes when a parent invoice is in this status (correct me if I'm wrong). For that case the adjustment is moving to parent by next child invoice.
Actually, I based my tests on the parent invoice status, and I didn't see the payment status. 

We have now these 3 cases:
- DRAFT and unpaid : [Scenario 1](https://github.com/matias-aguero-hs/killbill/blob/53da86d076045d9413243bbd0a243caf6d5cfbdd/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java#L356-L356)
- COMMITTED and unpaid: Should we update invoice anyway? Should be keep current behaviour?
- COMMITED and paid: [Scenario 2](https://github.com/matias-aguero-hs/killbill/blob/53da86d076045d9413243bbd0a243caf6d5cfbdd/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java#L432)

**Comment by sbrossie** [comment]
Scenario 1 was not specific enough and was referring to both `DRAFT and unpaid` (1.a) and `COMMITTED and unpaid` (1.b). However we did talk about the behavior 1.b in this [comment](https://github.com/killbill/killbill/issues/553#issuecomment-225322061).

To summarize both `1.a` and `1.b` should behave the same way where we add the extra `ADJ` item on the parent invoice. (note that the same thing happens on the child invoice, where although the invoice status is `COMMITTED` additional`ADJ` can occur on this invoice.

Our semantics for `COMMITTED` is a bit lose, but i think we have no choice as there are cases where specific invoices need to be adjusted.

**Comment by matias-aguero-hs** [comment]
No problem, I can [fix it](https://github.com/matias-aguero-hs/killbill/blob/93bff46752f84c9522e8e1d4e8cbd3b9fbcd2a95/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L786-L786).
1. Current process is [updating PARENT_SUMMARY item](https://github.com/matias-aguero-hs/killbill/blob/93bff46752f84c9522e8e1d4e8cbd3b9fbcd2a95/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L813-L814) if parent invoice is DRAFT (not adding items... just updating amount value). Do you want to keep this behaviour? [Test Assert](https://github.com/matias-aguero-hs/killbill/blob/53da86d076045d9413243bbd0a243caf6d5cfbdd/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationParentInvoice.java#L381)
2. Do we have a way to identify to which child account is referred the ADJ item added into Parent Invoice when it's COMMITTED but not paid yet.

**Comment by sbrossie** [comment]
> No problem, I can [fix it](https://github.com/matias-aguero-hs/killbill/blob/93bff46752f84c9522e8e1d4e8cbd3b9fbcd2a95/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L786-L786).

Ah ah, you even had a comment  ;-) 

So proposal is to add an `ADJ` item on the `COMMITTED` invoice (symetric to what happens to child invoice)

> 1. Current process is updating PARENT_SUMMARY item if parent invoice is DRAFT (not adding items... just updating amount value). Do you want to keep this behaviour? Test Assert

Yes

> 2. Do we have a way to identify to which child account is referred the ADJ item added into Parent Invoice when it's COMMITTED but not paid yet.

You should have all the info you need to create the new `ItemAdjInvoiceItem` item (you have access to child account parent account and child invoice) on the parent invoice. However, when you create the `ItemAdjInvoiceItem`, make sure the `linkedItemId` points to the `SUMMARY` item for the child invoice (similar to what happens on the child invoice). Does that answer your question?

**Comment by matias-aguero-hs** [comment]
Adjustment for unpaid COMMITTED parent invoice.
PR: https://github.com/killbill/killbill/pull/574
