### ISSUE TITLE
demo.killbill.io : Login broken

### ISSUE THREAD

**Issue by Gingonic** [killbill/killbill#554]
On the demo.killbill.io the user login seems to be broken. Using the provided user crendentials I get:

> We're sorry, but something went wrong.

Error happend using Chrome on Windows 7  at 11:55 UTC +1

**Comment by sbrossie** [comment]
Hi there,

Yes our demo was down, i just restarted it.

Thanks for reporting the issue.

Stéphane

**Comment by Gingonic** [comment]
All working now, thanks.
