### ISSUE TITLE
Possible DB connection leaks in the plugin

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#556]
See mailing [list thread](https://groups.google.com/forum/#!topic/killbilling-users/cx8WWyqFtxg)

**Comment by pierre** [comment]
When using any pagination API, the caller needs to iterate through all results to close the connection:

```
final Pagination<Account> accounts = accountUserApi.getAccounts(0L, 1L, tenantContext);
for (final Account account : accounts) {
  // Make sure to close the connection!
}
```

This is done automatically in [JAX-RS](https://github.com/killbill/killbill/blob/8130ba66747c43c9dae0bfce0cee47335158556b/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L273-L302) but it is the responsibility of the client to do the same when using the Java API.

The reason for the connection to be left open comes from the fact that we are streaming results out of the database. From http://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-implementation-notes.html:

> By default, ResultSets are completely retrieved and stored in memory. In most cases this is the most efficient way to operate and, due to the design of the MySQL network protocol, is easier to implement. If you are working with ResultSets that have a large number of rows or large values and cannot allocate heap space in your JVM for the memory required, you can tell the driver to stream the results back one row at a time.
>
> [...]
>
> There are some caveats with this approach. You must read all of the rows in the result set (or close it) before you can issue any other queries on the connection, or an exception will be thrown.
