### ISSUE TITLE
Should Pagination offer a close method?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#558]
See [mailing-list](https://groups.google.com/d/msgid/killbilling-users/a91b2f76-d126-4cc1-85c7-1e9eb29aca53%40googlegroups.com) thread.

**Comment by sbrossie** [comment]
@pierre Should we?

**Comment by pierre** [comment]
I think so - it would make it obvious. FYI this might impact [Ruby plugins](https://github.com/killbill/killbill-plugin-framework-ruby/blob/d2281db5e90d8272b494585f3045657de6b20254/lib/killbill/helpers/active_merchant/active_record/models/payment_method.rb#L125).
