### ISSUE TITLE
Failed Payments do not show up in the invoice_payment table

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#560]
The issue was reported from the [Kill Bill user mailing] list(https://groups.google.com/forum/#!topic/killbilling-users/EJHLqujQl8s).

A quick assessment seems to indicate that commit d6c0af83 is the cause of the issue.

**Comment by sbrossie** [comment]
Fix have been released to master, but we need another round of testing prior release on `0.16.6`.

Note that the bug fix resulted in two different fixes:
1. Avoid throwing any NPE when some `invoice_payments` row exist with a null `payment_id`.
2. Allow to record failed payment attempts in the `invoice_payments` table

If issue arose on a production system, underlying data needs to be fixed and we provided some queries below.

**IF YOU NEED TO APPLY SUCH QUERY ON A PRODUCTION SYSTEM, PLEASE REVIEW THE QUERIES AND RUN THEM FIRST IN A TESTING ENVIRONMENT. THOSE ARE PROVIDED "AS A IS" BUT WE YOU ARE RESPONSIBLE TO VERIFY THEIR CORRECTNESS PRIOR RUNNING THEM**

Identify rows that need to be fixed:

```
select
count(*)
from invoice_payments ip
join payment_transactions pt
where
1=1
and ip.type = 'ATTEMPT'
and ip.amount > 0
and ip.payment_id IS NULL
and ip.payment_cookie_id = pt.transaction_external_key
and pt.transaction_status in ('PAYMENT_FAILURE','PLUGIN_FAILURE')
and pt.transaction_type = 'PURCHASE'
;
```

Perform updates to fix data:

```
update invoice_payments ip
join payment_transactions pt
set ip.payment_id = pt.payment_id
, ip.success = 0
where
1=1
and ip.type = 'ATTEMPT'
and ip.amount > 0
and ip.payment_id IS NULL
and ip.payment_cookie_id = pt.transaction_external_key
and pt.transaction_status in ('PAYMENT_FAILURE','PLUGIN_FAILURE')
and pt.transaction_type = 'PURCHASE'
;
```

**Comment by nkuzmina** [comment]
Seems that on the queries above it should be 
`pt.amount > 0` 
instead of
`ip.amount > 0`

Since the amount on a failed payment_transaction is above zero, but the amount on a failed invoice_payment is equal to 0.

**Comment by sbrossie** [comment]
@nkuzmina Yep, that makes sense.
