### ISSUE TITLE
Create a role with an empty permission returns a "null permission" error

### ISSUE THREAD

**Issue by daliwei** [killbill/killbill#562]
Send the following curl for creating a read-only role, 
```
curl -v \
-u "admin:password"  \
-H "X-Killbill-CreatedBy: Dali" \
-H "Content-Type: application/json" \
-X POST \
--data-binary '{ "role": "customer_support", "permissions":[]}' \
'http://killbill.local:8080/1.0/kb/security/roles'
```

it will return the following error:

```
{"className":"org.killbill.billing.security.SecurityApiException","code":40005,"message":"The permission null is invalid","causeClassName":null,"causeMessage":null,"stackTrace":[]}
```

**Comment by sbrossie** [comment]
@daliwei Did you create the permission  first?

**Comment by daliwei** [comment]
@sbrossie Do I need to create the permissions? I looked through [here](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/security/Permission.java), and I don't want the user to have any of these permissions. So I left the permission to `[]` in the curl. I followed this [doc](http://docs.killbill.io/0.16/user_management.html).

**Comment by sbrossie** [comment]
You need to first create a role (that will include some permissions, probably read-only in your case) and then create the user, specifying the roles this user has.

**Comment by daliwei** [comment]
@sbrossie Maybe I did not explain it clear. That curl above **is** to create a role with empty permission. Is that an expected behavior if it returns an error?

**Comment by sbrossie** [comment]
Yes this is expected. Permissions cannot be null. Otherwise what is the role about?

**Comment by pierre** [comment]
I think @daliwei wants to create a pure read-only role (no permission - which are all r/w - we don't have explicit r/o permissions today).

**Comment by sbrossie** [comment]
I see. That makes sense. We should add that in our Permission list or support the empty permission list. In the meantime why not adding [this one](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/security/Permission.java#L91) ?

**Comment by daliwei** [comment]
Yes. [That](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/security/Permission.java#L91) should work.

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill/commit/467c52853161b8a5003d4e1115a6ec37043ca67c.
