### ISSUE TITLE
Advanced product

### ISSUE THREAD

**Issue by AndriySvirin** [killbill/killbill#563]
Please give advice how to realise:

Product is an entity with properties those influence on product price by multiplication. 

Product = 20*Servers with 6*cores and on 10 years.
There 1 server costs 1 apple and 2 cores multiplies on 2.

**Comment by pierre** [comment]
@AndriySvirin, please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for implementation questions.
