### ISSUE TITLE
Review handling of Location header

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#566]
- What should be the default, relative or full URI?
- When configured for full URI, should we translate the port and protocol by looking at the X-Forwarded headers (see https://github.com/killbill/killbill/pull/559#issuecomment-229168475)?

**Comment by pierre** [comment]
We've decided to:

* Default to showing the full URI in the `Location` header
* Not change the code to look at X-Forwarded headers, as it seems this logic belongs in the application server. However, @andrenpaes will look at if we can change our Tomcat configuration by default in our Docker images to support SSL termination out of the box

**Comment by pierre** [comment]
Work for 0.16.7 done. Keeping the issue open to track the Docker work.

**Comment by sbrossie** [comment]
@pierre What needs to be done for docker?

**Comment by pierre** [comment]
Change our Tomcat configuration to support SSL termination out of the box otherwise _refresh_ calls from the clients [may not work](https://groups.google.com/forum/#!topic/killbilling-users/Ofs6J0oGZpI).

**Comment by sbrossie** [comment]
Issues should be tracked in `killbill-cloud` for docker module.

**Comment by pierre** [comment]
@beccagaspard I've just pushed a patch which should help with load balancer SSL termination. Documentation on how it works can be found [here](https://github.com/killbill/killbill-cloud/tree/master/docker#x-forwarded-headers-support). If you get the chance, could you give it a try in your AWS elastic load balancing environment? Hopefully, you won't need to hardcode the scheme and port anymore!
