### ISSUE TITLE
Un-parenting feature

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#567]
- What happens with `ImmutableAccountData`?

**Comment by sbrossie** [comment]
If we don't support un-parenting then we can easily cache the parenting id. If we support un-parenting, then caching becomes a problem since we have no good way to invalidate caches in a distributed system.

**Comment by sbrossie** [comment]
This is not clear we have a use case for that and so we will close the issue

**Comment by pierre** [comment]
Fixed by 860348345f37ad2a8ecf6c0aead871d6f37e3ebd.

Created https://github.com/killbill/killbill-api/issues/31 to track the clean-up work.
