### ISSUE TITLE
Create new API to retrieve invoice items details associated to SUMMARY item.

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#572]
We started the work where the [DAO cal](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L1062)l has been implemented, but we need the new java apis, JAXRS api, java client, profile tests.

**Comment by matias-aguero-hs** [comment]
@sbrossie I'll be working on this issue this week. (if nobody already started)
What parameters the api (resource) should receive? and what information it should return?

**Comment by sbrossie** [comment]
@matias-aguero-hs Sounds good. Will reply with an API proposal. Also don't forget [this remaining issue](https://github.com/killbill/killbill/issues/457#issuecomment-233027870) (Or let me know if this has already been addressed).

**Comment by sbrossie** [comment]
I am thinking we could just enhance our existing endpoint to retrieve invoice [by ID](https://github.com/killbill/killbill/blob/killbill-0.17.1/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L175) or [number](https://github.com/killbill/killbill/blob/killbill-0.17.1/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L197) so they support a new query param `QUERY_INVOICE_WITH_CHILDREN_ITEMS` (similar to existing `QUERY_INVOICE_WITH_ITEMS`):

* For a child invoice that new param would be ignored
* For the parent invoice the following could happen:
  * Neither `QUERY_INVOICE_WITH_CHILDREN_ITEMS` and `QUERY_INVOICE_WITH_ITEMS` => just return invoice with no items (same for child invoice)
  * Only `QUERY_INVOICE_WITH_ITEMS` => returns invoice with its `SUMMARY` items (similar to child behavior, with their own specific items)
  * `QUERY_INVOICE_WITH_CHILDREN_ITEMS` is specified (regardless of `QUERY_INVOICE_WITH_ITEMS`), return all parent and children items.

In that last case, the output would need to be modified (new json model) to have different sections per child:
* SUMMARY_ITEM (child1)
  * ITEM1 (child1)
  * ITEM2 (child1)
  * ...
* SUMMARY_ITEM (child2)
  * ITEM1 (child2)
  * ITEM2 (child2)

**Comment by sbrossie** [comment]
@pierre Any thoughts?

**Comment by pierre** [comment]
> In that last case, the output would need to be modified (new json model) to have different sections per child

⚠️ The output cannot be different depending on the query parameters (otherwise, it breaks the clients). So, it seems we need a new attribute in `InvoiceItemJson` (e.g. `childItems`)?

**Comment by sbrossie** [comment]
That makes sense.

I suggest to keep proposal above but with the difference that json returned should always have the same fields (to not breaks the clients). In practice, what that means is that we should add the new field `childItems` in `InvoiceItemJson` which would be null in regular case and get populated with children items when  `QUERY_INVOICE_WITH_CHILDREN_ITEMS` is set.

@matias-aguero-hs Let us know if this is not clear.

**Comment by matias-aguero-hs** [comment]
@sbrossie @pierre It's clear. Thanks.

**Comment by matias-aguero-hs** [comment]
@sbrossie You can find this feature implemented in next PRs.

- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/42
- killbill-api: https://github.com/killbill/killbill-api/pull/18
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/8
- killbill: https://github.com/killbill/killbill/pull/586
