### ISSUE TITLE
Email service

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#58]

**Comment by pierre** [comment]
Functionality has been moved to https://github.com/killbill/killbill-email-notifications-plugin.

Is there anything left to be done here?

**Comment by sbrossie** [comment]
What would be nice is to cleanup our code (get rid of all these classes) and verify the original isNotifyForInvoice can be supported with the plugin (and also fix kaui to only work when plugin is available).

**Comment by sbrossie** [comment]
What happens to core functionality `isNotifiedForInvoices` ?

**Comment by sbrossie** [comment]
Reaping the code out is not too difficult, but there are some product question to solve:

1. Currently we export all the way to the UI the `isNotifiedForInvoices ` capability. It might make sense to export more than that to match all the events that the `killbill-email-notifications-plugin` plugin currently send.
2. Should this configuration still live as part of core data (or should it be extracted from `accounts` table). There are several choices:
* Remove the per-account config (if plugin exists and is configured correctly, at the tenant level, automatically send emails to all users)
* Move the per-account config in the `killbill-email-notifications-plugin`
* Keep it in core in account table

Depending on those choices, we might need to KAUI component for the  `killbill-email-notifications-plugin`

**Comment by pierre** [comment]
FYI, solving this would let us get rid of this dependency (released 01-Nov-2009):

```
[INFO] +- org.apache.commons:commons-email:jar:1.2:compile
[INFO] |  +- javax.mail:mail:jar:1.4.1:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
```
