### ISSUE TITLE
Catalog CHANGE_OF_PRICELIST has not been implemented

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#583]
One interesting use case that we should at least implement is the scenario where a user has two similar `Plan` but one with trial and one without trial. Because of the current limitation where we can have only plan with a given {`Product`, `BillingPeriod`, `PriceList` } (See #303), it is necessary to configure those two plans in 2 different pricelists. Then, if a user currently in trial needs to be skipped to a non trial phase, we could change the plan but then we would need that policy to be implemented.

**Comment by javier-gomez-hs** [comment]
@sbrossie 
Would you be able to clarify a little bit more the expected behaviour on this ticket?
When you say:
>
a user has two similar Plan but one with trial and one without trial
>

Do you mean with the same Plan Name / Product, but different phase?

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs First of all i fixed #303 so this bug becomes less important, but nonetheless we should fix it.

The goal of that bug is to implement [that piece ](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java#L286). So the test to make is two have two plans that are defined in different pricelists and make a change of plan between the two and verify operations succeeds and behavior is as expected.

I 'll think of a good test case to write and will get back to you (you can familiarize yourself with that code in the meantime)

**Comment by sbrossie** [comment]
Let me provide some more background: Pricelists were introduced to support things like 'discounted' products. The idea was the following:

You sell 3 products, 'Gold', 'Silver' , 'Bronze' and you want to offer a discounted set of prices for a certain class of customers. You can define two pricelists in your catalog, the `DEFAULT` and the `discount` one, where the same plans appear but with different price range.

Let's assume a customer was provided with a discounted `Gold` product. Later on, he decides to downgrade to `Silver`. The choice is to keep him in the discounted pricelist or move him to regular price. If the business logic defines to move him to the regular price, and we have alignment rules in the catalog to define what happens when moving from `DEFAULT` to `discount` pricelist we hit that `CHANGE_OF_PRICELIST` [unimplemented code](https://github.com/killbill/killbill/blob/master/subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java#L286).

The original idea was based on the fact that both `Plan`, the regular one and the discounted one look the same (i.e have similar `PlanPhase`) and only the price differs. For such use cases, it seems like we should align on the subscription `startDate`. For other use cases (maybe one `Plan` has a trial and the other does not, i am unclear what we should do, and i would suggest to just detect such case and throw an exception as this goes beyond what was originally intended.

**Comment by sbrossie** [comment]
@javier-gomez-hs I would hold off on that one (#611 is more interesting)

**Comment by javier-gomez-hs** [comment]
@sbrossie 
If you think #611 is ready, should I continue on this issue?

**Comment by sbrossie** [comment]
@javier-gomez-hs I would hold off, because based on our [doc definition](http://docs.killbill.io/0.16/userguide_subscription.html#_plan_change_phase_alignment) , which says `CHANGE_OF_PRICELIST - The plan phases start at the time of the last change of price list` i am confused on what should really be implemented...

**Comment by sbrossie** [comment]
Closing the issue, as it seems we don't really know what to implement.
