### ISSUE TITLE
Upgrade to Ehcache 3

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#587]
This would reduce the size of the war (ehcache2.jar is 9MB!). Also the new off-heap store could be useful.

**Comment by pierre** [comment]
We currently use [Ehcache 2.9.1](https://github.com/killbill/killbill-oss-parent/blob/master/pom.xml#L91). The goal is to upgrade to [Ehcache 3.1.1](https://github.com/ehcache/ehcache3). Besides adapting the APIs calls, this task mainly requires testing of:

* The [shiro-ehcache](https://github.com/killbill/killbill-oss-parent/blob/master/pom.xml#L539) implementation
* The [metrics-ehcache](https://github.com/killbill/killbill-oss-parent/blob/master/pom.xml#L317) implementation

Both can be checked via JMX stats.

**Comment by javier-gomez-hs** [comment]
@pierre @sbrossie 
I've started working with this issue before #304.
After upgrading to the new version (v3.1.1), I've been trying to fix some inconsistences in the killbill-platform project. More specifically [here](https://github.com/killbill/killbill-platform/blob/549987399562e3c570df9d45d39f8a80a064ba71/server/src/main/java/org/killbill/billing/server/listeners/KillbillPlatformGuiceListener.java#L251-L251).
The main issue is that EhCache v3.1.1 does not include the MBean integration (for now) so the `ManagementService` used in the previous versions, is not present anymore.
I've asked for help in the **ehcache-users** mailing list, and some of the guys suggested me to use **JCache API**, which has the [MBeanServerRegistrationUtility](https://docs.oracle.com/middleware/12211/coherence/java-reference/com/tangosol/coherence/jcache/common/MBeanServerRegistrationUtility.html) that could help us in this case.
I just wanted you to know about this.
What do you think about it? Any thoughts?

Any help / suggestion will be much appreciated!

Thanks!

**Comment by pierre** [comment]
Is there a bug upstream to track the feature?

The main things we cared about in the MBeans were:

1. The statistics
2. The display of the current configuration

For 1., if we successfully upgrade `metrics-ehcache`, we should be fine not having any direct MBean integration (let's not try to pull JCache for now).

Out of curiosity, do you know why it is not exposed anymore?

**Comment by javier-gomez-hs** [comment]
@pierre 
>Is there a bug upstream to track the feature?

Not really, it's really hard to find information about this missing feature.

>if we successfully upgrade metrics-ehcache, we should be fine not having any direct MBean integration (let's not try to pull JCache for now).

I'll try to upgrade `metrics-ehcache` and avoid the `JCache` integration. 

>Out of curiosity, do you know why it is not exposed anymore?

Nope, as I said before it has been very hard for me to find any information about this. Maybe there is something in the Release Notes, but I'm not sure.

**Comment by pierre** [comment]
> I'll try to upgrade `metrics-ehcache` and avoid the `JCache` integration. 

👍 

> Nope, as I said before it has been very hard for me to find any information about this. Maybe there is something in the Release Notes, but I'm not sure.

No worries - since you have a [thread open](https://groups.google.com/forum/#!category-topic/ehcache-users/UFRXilVykyE), maybe that's something we can eventually follow-up with @ljacomet.

**Comment by javier-gomez-hs** [comment]
Yes!
About the `metrics-ehcache`, I've just confirmed that we are using one of the latest versions available ([3.1.1](https://github.com/javier-gomez-hs/killbill-oss-parent/blob/50e2eb7db23660ade558dbc29e352ecb2613e136/pom.xml#L105-L105)).
So, how should I avoid the MBean integration [here](https://github.com/killbill/killbill-platform/blob/549987399562e3c570df9d45d39f8a80a064ba71/server/src/main/java/org/killbill/billing/server/listeners/KillbillPlatformGuiceListener.java#L251-L251)?

Thanks!

**Comment by pierre** [comment]
> About the `metrics-ehcache`, I've just confirmed that we are using one of the latest versions available

Is the current code compatible with the latest version of Ehcache?

If not, maybe we could simply copy over the few classes and adapt them as needed (see https://github.com/dropwizard/metrics/tree/3.2-development/metrics-ehcache/src/main/java/com/codahale/metrics/ehcache).

> So, how should I avoid the MBean integration here?

Simply get rid of the `registerEhcacheMBeans` method 😸

**Comment by ljacomet** [comment]
Hello there,

Given the completely revamped Ehcache 3 API, adoption by third parties is going to take time.
From what I know:
* `metrics-ehcache` is not compatible with Ehcache 3
* `shiro-ehcache` is not compatible with Ehcache 3

Also, for the native exposition of statistics for Ehcache 3 we are still trying to come up with something that makes sense.
But we are very happy to get feedback on what users want to help us prioritise and define features. So do not hesitate to follow up by email on [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) or follow up on the conversation linked above.

**Comment by javier-gomez-hs** [comment]
Hi Louis @ljacomet,

Thanks for the information about the compatibilities with Ehcache 3.
@pierre, knowing this, should we leave this issue and #304 in stand by until we have news?

Thanks.

**Comment by pierre** [comment]
@ljacomet Thanks for reaching out! To give you some background, we are exporting the stats to our [metrics infrastructure](https://engineering.groupon.com/2015/open-source/kill-bill-metrics/) for production monitoring (rate of misses, sizes, etc.).

@javier-gomez-hs While the stats are more of a nice-to-have, no Ehcache 3 support in Shiro is a non-starter. Doing the work ourselves is probably not worth it at this point. However, I still think we should move forward on #304, since it sounds like we'll be stuck on Ehcache 2 for a while (the Shiro project isn't very active these days unfortunately).

**Comment by ljacomet** [comment]
@pierre As an FYI, Ehcache team published a shiro plugin to integrate Ehcache 3 - see [ehcache/ehcache-shiro](https://github.com/ehcache/ehcache-shiro) - version 1.0.0 is available on Maven Central.

**Comment by pierre** [comment]
See https://github.com/dropwizard/metrics/pull/1010 for metrics.

**Comment by pierre** [comment]
Due to the large amount of changes this upgrade requires, the work has been split in two stages:

* 0.18.5 will ship all needed internal changes for the upgrade, while still being on Ehcache 2. This includes:
  * Moving away from the `CacheLoader` pattern
  * `EhCacheBasedCacheController` strongly typed
  * Libraries dependencies updates
* 0.18.6 will ship Ehcache 3 and include the following user-facing changes:
  * Cache metrics are now prefixed with `jcache.statistics` instead of `net.sf.ehcache.Cache`
  * New ehcache.xml syntax (see http://www.ehcache.org/documentation/3.3/xml.html)
