### ISSUE TITLE
Fix payment api to allow retrieving payment transaction tags

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#599]
See [current code](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java#L180) where we can't specify `accountId` based on input transactionId;

**Comment by javier-gomez-hs** [comment]
@sbrossie 
I've started with this one and I wonder if you think is ok to add a new parameter to the method in the [Resource](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java#L174), because in order to get the Tags we need the `accountId`.
If you agree, I can add it and write a test to verify the behaviour.

Thanks!

**Comment by sbrossie** [comment]
The other option is to enhance our PaymentApi to allow retrieving a `PaymentTransaction` from its ID, and then do a similar thing in the resource than we do [here](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java#L886).

@pierre Any thoughts?

**Comment by javier-gomez-hs** [comment]
@sbrossie 
Yes, I agree.
In fact, the `accountId` is needed to get the AccountAuditLogs [here](https://github.com/javier-gomez-hs/killbill/blob/d4ddcc22b75b1e5252e76996f50ee1021a5d6bf2/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L196-L196) and add the audit logs to the Tag and build the response.

**Comment by pierre** [comment]
@sbrossie @javier-gomez-hs I agree about adding the new API, something like:

```
Payment getPaymentByTransactionId(paymentTransactionId, bool, bool, properties, context);
```

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie  
Yes, I've been working on that and added a very similar method.
I had some issues with my other account (that's why I'm commenting from this one) so as soon as I can get my account back, I'll push my changes.

Thanks!

**Comment by javier-gomez-github** [comment]
@sbrossie @pierre 
Guys, I wasn't able to recover my old account so I'll start pushing my changes using this account.
The PRs created for this issue are:
- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/48
- killbill-api: https://github.com/killbill/killbill-api/pull/22
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/14
- killbill: https://github.com/killbill/killbill/pull/620

Please feel free to review them and let me know if I have to change anything else.

Thanks.

**Comment by javier-gomez-github** [comment]
@sbrossie 
I've updated the PRs with the new method.

Thanks.
