### ISSUE TITLE
Entitlement externalKeys over 64 characters allow the creation of duplicates

### ISSUE THREAD

**Issue by silver2k** [killbill/killbill#604]
With KillBill 0.16.7 we've noticed that any entitlement externalKey over 64 characters is silently truncated and inserted into the database. (It should probably fail??)
As a result - the check to confirm if a new entitlements externalKey already exists passes (As it is not truncated to 64 characters) and an additional subscription bundle is created.
I believe this against the intention that externalKeys should imply uniqueness?

**Comment by sbrossie** [comment]
@pierre I am wondering if we should indeed have some code validation for any type of `externalKey` to make sure this matches the size allocated in our DDL (and avoid truncation that would then break client assumption) ?

**Comment by pierre** [comment]
I think it's a MySQL configuration issue (the behavior on PostgreSQL would be different).

From https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict:

> Strict mode controls how MySQL handles invalid or missing values in data-change statements such as INSERT or UPDATE. A value can be invalid for several reasons. For example, it might have the wrong data type for the column, or it might be out of range. A value is missing when a new row to be inserted does not contain a value for a non-NULL column that has no explicit DEFAULT clause in its definition. (For a NULL column, NULL is inserted if the value is missing.) Strict mode also affects DDL statements such as CREATE TABLE.

> If strict mode is not in effect, MySQL inserts adjusted values for invalid or missing values and produces warnings (see Section 14.7.5.40, “SHOW WARNINGS Syntax”). In strict mode, you can produce this behavior by using INSERT IGNORE or UPDATE IGNORE.

**Comment by sbrossie** [comment]
Sure but regardless of the engine or the mode used, preventing keys that are longer than what can be stored in the engine seems like a sane approach?

**Comment by pierre** [comment]
Yeah - I guess I'm just worried about a bunch of validation code all over the place (should we do it for any external key? What about custom fields values, invoice item descriptions, etc.?), no necessarily in sync with the ddl.sql.

**Comment by sbrossie** [comment]
The `externalKey` is very different than anything else: The user specifies ITS key and rely in that to access the resource. If we truncate the key silently, everything breaks on their side

**Comment by silver2k** [comment]
It was worse in my case - as we we so close to the character limit, we encountered what we believed to be completely random behavior. Sometimes keys worked one way - sometimes they didn't!

**Comment by javier-gomez-github** [comment]
@sbrossie @pierre 
I've just started to test this issue and turns out that there is a limitation when you are trying to add a new entitlement using an `externalKey` of more than 64 characters.
The error is this one:

```
{
  "className": "java.lang.RuntimeException",
  "code": null,
  "message": "java.sql.SQLDataException: Data too long for column 'external_key' at row 1",
  "causeClassName": "java.sql.SQLDataException",
  "causeMessage": "Data too long for column 'external_key' at row 1",
  "stackTrace": []
}
```

If I use an equal or less than 64 characters `externalKey`, it works.

Would you like me to write a new test to verify this behavior?

Thanks!

**Comment by javier-gomez-github** [comment]
@sbrossie @pierre 
Any news on this issue?

Thanks!

**Comment by pierre** [comment]
@javier-gomez-github: the behavior actually depends on the configuration of your database unfortunately, hence this bug.

The work is to:

* Make sure all external keys (6 across payment, payment attempt, payment transaction, bundle, account and tenant) have the same length in the DDL (should be 255) and provide DDL migration files as needed
* If a key longer than 255 in specified, throw an exception in each API which accepts an external key (at the Java level, not JAX-RS level) -- this is typically done at the object creation time (tenant creation, new payment, etc.). A new specific ErrorCode would be nice.

Does that make sense?

**Comment by javier-gomez-github** [comment]
@pierre 
Yes, it does make sense.
I'll work on that.

Thanks!!

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I've finished with the changes requested. 
As you can see, I've updated all the `externalKey` fields to 255 characters limit.
I've also added the Exceptions in the API level.

These are the PRs:
- killbill: https://github.com/killbill/killbill/pull/624
- killbill-api: https://github.com/killbill/killbill-api/pull/24
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/16

I'd like to add some Integration tests, but when I tried to write one of them, I've realized that the "virtual" MySQL DB that is using the Tests, is not limiting the number of characters of the `externalKey` fields.
That said, should I move the Exception throwing to any other place just by controlling the provided `externalKey`? Currently I'm waiting for a SQLDataException thrown by the DAOs. Is that the right way?

Thanks!
