### ISSUE TITLE
Add BillingPeriod forthnightly

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#607]
As part of `0.17.x` release we have added a number of new [billing periods](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/catalog/api/BillingPeriod.java#L26), but we recently got a request to add forthnightly.

**Comment by sbrossie** [comment]
Although be aware there is an issue reported for non monthly based plan (so it would be a pre-requisite to fix it). See #598

**Comment by pierre** [comment]
Isn't [fortnightly](https://en.wiktionary.org/wiki/fortnightly#English) the same as [biweekly](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/catalog/api/BillingPeriod.java#L30)? Note that [biweekly](https://en.wiktionary.org/wiki/biweekly#Usage_notes_2) is ambiguous though (in the UK, it means “twice a week”, which we indeed don't support).

**Comment by sbrossie** [comment]
@pierre Yes i think you are correct, we already have some support for [bi-weekly](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/catalog/api/BillingPeriod.java#L30) in `0.17.x`

**Comment by sbrossie** [comment]
Looks like this is already implemented in `0.17.x`.
