### ISSUE TITLE
Implement missing overdue conditions

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#611]
There are a number of possible [overdue conditions](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/overdue/api/OverdueCondition.java) that can be selected but only a few have been implemented.

Recently with the work of #256, we can now specify inclusion or exclusion tags (`ControlTagType`).  The remaining conditions (unimplemented or untested) are:
*  totalUnpaidInvoiceBalanceEqualsOrExceeds
* timeSinceEarliestUnpaidInvoiceEqualsOrExceeds
* responseForLastFailedPaymentIn

**Comment by javier-gomez-hs** [comment]
@sbrossie 
I've been researching a little bit about this issue, and since Matias was the one that fixed #256 I'll need some extra information to fully understand it.
What do you mean with "unimplemented or untested"? 
Aren't they being used yet?

Thanks!

**Comment by sbrossie** [comment]
If you look at the possible set of [overdue conditions](https://github.com/killbill/killbill-api/blob/work-for-release-0.17.x/src/main/java/org/killbill/billing/overdue/api/OverdueCondition.java), only `getTimeSinceEarliestUnpaidInvoiceEqualsOrExceeds` and (because of recent code change in #256) `getInclusionControlTagType`, `getExclusionControlTagType` have been tested.

The other 3 listed above have never been tested (and so i don't even know if logic is fully implemented). The work is to write test cases for each of those (and if needed implement the unimplemented pieces). Does that make sense?

**Comment by javier-gomez-hs** [comment]
@sbrossie 
So, I've been working in the Test Cases for the unimplemented conditions. 
I've made a good progress with 2 of them, except for the one about the Payment Responses.
[This](https://github.com/javier-gomez-hs/killbill/blob/3bcec99cc967a48347db1d9c357e8c8efd7edd46/overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java#L82-L82) is what is being used as `PaymentResponse` every time the Payment fails.
Basically, I'll have to implement the behavior in that line.
Correct me if I'm wrong, but I have to decide which `PaymentResponse` must be assigned to the BillingState according to the [`gatewayErrorCode`](https://github.com/javier-gomez-hs/killbill/blob/055bb10294ee4d22290d78056a9004ef313f177d/payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentTransaction.java#L40-L40) and [`gatewayErrorMsg`](https://github.com/javier-gomez-hs/killbill/blob/055bb10294ee4d22290d78056a9004ef313f177d/payment/src/main/java/org/killbill/billing/payment/api/DefaultPaymentTransaction.java#L41-L41) of the `PaymentTransaction` value in the last failed Payment of the Account, right?
Do I have to decide that using [this](https://github.com/javier-gomez-hs/killbill-api/blob/dead5d261119b96402b00271c8d9207b43d8ef4b/src/main/java/org/killbill/billing/payment/api/PaymentResponse.java#L50-L50) code table?

I hope you can help me clarifying this issue.

Thanks!!!

**Comment by sbrossie** [comment]
@javier-gomez-hs Forget about the `responseForLastFailedPayment` for now, this is a more complicated topic and we are missing some pieces of infrastructure to get that right. I will also ping Joe to understand if they have more requirements from their side for dunning/overdue (since you are working on that, this seems like the right time).

**Comment by javier-gomez-hs** [comment]
@sbrossie 
No problem, I have already made a good progress with the test case of the PaymentResponse, so if you want I can create a separate branch and commit my changes there, so it can be continued in the future.
Regarding the other missing conditions, here is my PR: 
- killbill: https://github.com/killbill/killbill/pull/615

Please feel free to review it and let me know if I have to make any change there.

Thanks!!

**Comment by sbrossie** [comment]
Closing the issue as we will not implement `responseForLastFailedPayment`.
