### ISSUE TITLE
Usage price override

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#614]
Today, we offer a price override capability for fixed and recurring prices (on a per phase basis). The implementation relies on a [separate set of tables](https://github.com/killbill/killbill/blob/master/catalog/src/main/resources/org/killbill/billing/catalog/ddl.sql) owned by the catalog module where such overrides are stored.

Price override for usage hasn't been implemented yet. The implementation would require mirroring the usage data model (from the catalog XML) into similar tables and update the [API](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/PlanPhasePriceOverride.java) accordingly.

**Comment by sbrossie** [comment]
Closing ticket as there is no plan top receive additional PR on that work.

Current status is that basic functionality was implemented to do usage price override (at least consumable in arrear model), and some smoke tests have been run, but nothing extensive. Use with caution.
