### ISSUE TITLE
Missing Transaction ID in executePluginOnFailureCalls 

### ISSUE THREAD

**Issue by daliwei** [killbill/killbill#617]
When [`executePluginOnFailureCalls`](https://github.com/killbill/killbill/blob/1388680aa9efa9828dd42a58886956ffacb64fb2/payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java#L225) is called, it won't pass in transaction ID in the paymentControlContext when `onFailureCall` is invoked at control plugins.

**Comment by sbrossie** [comment]
@daliwei Could you provide more background about the type or errors that lead to the failure: There are probably some use cases where an exception could be thrown prior that `transactionId` exists, but i could also see some [use cases](https://github.com/killbill/killbill/blob/1388680aa9efa9828dd42a58886956ffacb64fb2/payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java#L141) where such `transactionId` should exist. Is that the path you are referring to?

Also for info how do you plan to use that transactionId in your plugin (we have no payment api that can be used by using `transactionId`, everything is at the payment level). Is that to filter list of transactions?

**Comment by daliwei** [comment]
@sbrossie In the use [cases](https://github.com/killbill/killbill/blob/1388680aa9efa9828dd42a58886956ffacb64fb2/payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java#L141) you mentioned above, the transaction ID is not populated either because the call finally ends up [here](https://github.com/killbill/killbill/blob/1388680aa9efa9828dd42a58886956ffacb64fb2/payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java#L225). From what I have tested, both `PAYMENT_FAILURE` and `PLUGIN_FAILURE`, the experiment plugin will not get transaction ID in the context when `onFailureCall` is invoked.

**Comment by daliwei** [comment]
@sbrossie We use the `transactionId` as the `object_id` to save some additional info in the `custom_fields` table.
