### ISSUE TITLE
Cancelling a subscription twice may cause NPE

### ISSUE THREAD

**Issue by marksimu** [killbill/killbill#619]
Suppose a customer wants to cancel their subscription.  We process the request as an end of term cancellation.  The customer views their account and sees the subscription is still active and worries it will continue to bill.  The customer goes to cancel the subscription a second time for assurances.  In this event when the end of term is reached the account will experience NPEs.

**Steps to Recreate**

Create an account.

> curl -v -X POST -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" -d "{\"currency\":\"USD\"}" "http://127.0.0.1:8080/1.0/kb/accounts"

Create a payment method.

> curl -v -X POST -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" -d "{\"pluginName\":\"\_\_EXTERNAL_PAYMENT\_\_\",\"pluginInfo\":{}}" "http://127.0.0.1:8080/1.0/kb/accounts/c38e25df-ed3a-4d76-89e3-521c4a1fee4b/paymentMethods?isDefault=true"

Create a subscription.

> curl -v -X POST -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" -d "{\"accountId\":\"c38e25df-ed3a-4d76-89e3-521c4a1fee4b\",\"productName\":\"Standard\",\"productCategory\":\"BASE\",\"billingPeriod\":\"MONTHLY\",\"priceList\":\"DEFAULT\"}" "http://127.0.0.1:8080/1.0/kb/subscriptions"

Advance the clock to move the subscription into the evergreen phase.

> curl -v -X PUT -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://localhost:8080/1.0/kb/test/clock?days=35&timeoutSec=30"

Cancel the subscription.

> curl -v -X DELETE -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://127.0.0.1:8080/1.0/kb/subscriptions/7ce76c13-a588-4e9f-bf5d-8dd4c82bd323?entitlementPolicy=END_OF_TERM&billingPolicy=END_OF_TERM"

Cancel once more.

> curl -v -X DELETE -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://127.0.0.1:8080/1.0/kb/subscriptions/7ce76c13-a588-4e9f-bf5d-8dd4c82bd323?entitlementPolicy=END_OF_TERM&billingPolicy=END_OF_TERM"

Getting the subscription returns HTTP 200.

> curl -v -X GET -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://127.0.0.1:8080/1.0/kb/subscriptions/7ce76c13-a588-4e9f-bf5d-8dd4c82bd323"

Advance the clock to the end of term.

> curl -v -X PUT -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://localhost:8080/1.0/kb/test/clock?days=35&timeoutSec=30"

Getting the subscription returns HTTP 400.

> curl -v -X GET -u "admin:password" -H "Content-Type: application/json" -H "X-Killbill-CreatedBy: admin" -H "X-Killbill-Reason: admin" -H "X-Killbill-Comment: admin" -H "X-Killbill-ApiKey: bob" -H "X-Killbill-ApiSecret: lazar" "http://127.0.0.1:8080/1.0/kb/subscriptions/7ce76c13-a588-4e9f-bf5d-8dd4c82bd323"

**Exception**

https://github.com/killbill/killbill/blob/killbill-0.17.2/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java#L276

```
java.lang.NullPointerException: null
        at org.killbill.billing.subscription.api.user.DefaultSubscriptionBase.getLastActiveProduct(DefaultSubscriptionBase.java:276)
        at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.createPlanPhaseSpecifier(EventsStreamBuilder.java:372)
        at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForEntitlement(EventsStreamBuilder.java:336)
        at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:220)
        at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:127)
        at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementApiBase.getAllEntitlementsForAccount(DefaultEntitlementApiBase.java:113)
        at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getSubscriptionForEntitlementId(DefaultSubscriptionApi.java:136)
```

**Cause**

The additional CANCEL event causes getLastActiveProduct() to reference an event where the product information is null.

```sql
SELECT `record_id`, `event_type`, `user_type`, `effective_date`, `plan_name`, `phase_name`, `price_list_name`, `is_active`, `created_date` FROM `subscription_events`
WHERE `subscription_id` = '7ce76c13-a588-4e9f-bf5d-8dd4c82bd323'
ORDER BY `record_id`;
```

record_id | event_type | user_type | effective_date | plan_name | phase_name | price_list_name | is_active | created_date
--------- | ---------- | --------- | -------------- | --------- | ---------- | --------------- | --------- | ------------
70 | API_USER | CREATE | 2017-02-10 18:47:37 | standard-monthly | standard-monthly-trial | DEFAULT | 1 | 2017-02-10 18:47:37
71 | PHASE | NULL | 2017-03-12 18:47:37 | NULL | standard-monthly-evergreen | NULL | 1 | 2017-02-10 18:47:37
72 | API_USER | CANCEL | 2017-04-12 18:44:37 | NULL | NULL | NULL | 1 | 2017-03-17 18:50:42
73 | API_USER | CANCEL | 2017-04-12 18:44:37 | NULL | NULL | NULL | 1 | 2017-03-17 18:50:58

**Remedy**

Accounts in this condition can be brought back to normal by clearing out the extra event.

```sql
UPDATE `subscription_events` SET `is_active` = 0 WHERE `record_id` = 73 LIMIT 1;
```

**Comment by sbrossie** [comment]
On Fri, Sep 23, 2016 at 12:56 PM, marksimu <notifications@github.com> wrote:

> Suppose a customer wants to cancel their subscription. We process the
> request as an end of term cancellation. The customer views their account
> and sees the subscription is still active and worries it will continue to
> bill.
>

Kill Bill subscriptions have 2 views:
1. The entitlement (the piece the customer sees)
2. The billing (the piece the customer will be billed for)

You can achieve an IMMEDIATE entitlement cancellation with an EOT billing
cancellation when you make the api calls
<https://github.com/killbill/killbill/blob/work-for-release-0.17.x/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java#L490>.
By doing so, your customer does not see its subscription is still active
(and therefore won't attempt to cancel again), and yet there is no
pro-ration credit because billing is EOT.



> The customer goes to cancel the subscription a second time for assurances.
> In this event when the end of term is reached the account will experience
> NPEs.
>

Ok, regardless of the api use, that part needs hardening from our side...

**Comment by sbrossie** [comment]
The code now includes [some logic to detect](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/subscription/src/main/java/org/killbill/billing/subscription/api/user/DefaultSubscriptionBase.java#L713) duplicate cancel events, but this is unclear whether we want to keep that logic in the future.

We also provide some data queries that could be used to identify if such cases exist and potentially fix the state (replace tenant `XXX` with your `tenant_record_id`):

**Obviously one should review the update query before running it and test it in a testing environment as it might cause some issues**

Find all subscriptions affected by the multiple `CANCEL` data issue:

```
select
e.record_id
, e.subscription_id
, e.user_type
, e.effective_date
from 
subscription_events e
join (select
      distinct(e1.record_id) record_id
      from subscription_events e1
      join subscription_events e2
      on e1.subscription_id = e2.subscription_id
      and e1.account_record_id = e2.account_record_id
      and e1.tenant_record_id = e2.tenant_record_id
      and e1.effective_date = e2.effective_date
      and e1.is_active
      and e2.is_active
      where
      1=1
      and e1.record_id < e2.record_id
      and e1.user_type = 'CANCEL'
      and e1.tenant_record_id = XXX) tmp
on e.record_id = tmp.record_id
;
```

Fix the state, by invalidating such duplicate rows:

```
update
subscription_events e
join (select
      distinct(e1.record_id) record_id
      from subscription_events e1
      join subscription_events e2
      on e1.subscription_id = e2.subscription_id
      and e1.account_record_id = e2.account_record_id
      and e1.tenant_record_id = e2.tenant_record_id
      and e1.effective_date = e2.effective_date
      where
      1=1
      and e1.record_id < e2.record_id
      and e1.user_type = 'CANCEL'
      and e1.tenant_record_id = XXX) tmp
on e.record_id = tmp.record_id
set e.is_active = 0, updated_by='Cancel FIX 12345', updated_date=NOW()
;
```

**Comment by sbrossie** [comment]
\cc @pierre for query review

**Comment by pierre** [comment]
> /cc @pierre for query review

Don't you also need `and e2.user_type = 'CANCEL'` in the select where clause for safety?

Otherwise, the approach looks good to me. As usual though, these queries are hard to review without some problematic data. I just verified I don't get any result in my test db - maybe @marksimu can help us validate it?

**Comment by marksimu** [comment]
Thanks.  This SELECT returns the same list of subscriptions we had independently identified.  We should modify the UPDATE statement though to have the same sub-SELECT.  It does not contain the check regarding is_active.

**Comment by sbrossie** [comment]
@marksimu Yes agreed. Update the `update` accordingly.
