### ISSUE TITLE
Catalog code performance

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#621]
The catalog code implementation  has never been optimized to scale with a large # of plans:
- Lots of `for` loop everywhere (linear searches, computation could become exponential if such looks are nested, to be checked)
- All collections are kept as arrays (in the case of mutable catalog, when adding entries), there is a need to re-alloc for each new entry

**Comment by sbrossie** [comment]
Ran a new experiment with a catalog containing 100k entries. Worst time to find  an entry (with linear search is ~ 5 mSec:

```
    @Test(groups = "fast")
    public void testForIssue621() throws Exception {
        final CatalogUpdater catalogUpdater = new CatalogUpdater("dummy", BillingMode.IN_ADVANCE, clock.getUTCNow(), null);
        int MAX_PLANS = 100000;
        for (int i = 1; i <= MAX_PLANS; i++) {
            final SimplePlanDescriptor desc = new DefaultSimplePlanDescriptor("foo-monthly-" + i , "Foo", ProductCategory.BASE, Currency.EUR, BigDecimal.TEN, BillingPeriod.MONTHLY, 0, TimeUnit.UNLIMITED, ImmutableList.<String>of());
            catalogUpdater.addSimplePlanDescriptor(desc);
        }
        final StandaloneCatalog catalog = catalogUpdater.getCatalog();

        final long timeFirstPlan = findPlanWithTiming(catalog, "foo-monthly-1");
        final long timeLastPlan = findPlanWithTiming(catalog, "foo-monthly-" + MAX_PLANS);

        System.err.println("Time: firstPlan (nanoSec) = " + timeFirstPlan + ", timeLastPlan (nanoSec) = " + timeLastPlan);
    }

    private long findPlanWithTiming(final StandaloneCatalog catalog, final String planName) throws CatalogApiException {
        final long ini = System.nanoTime();
        final Plan plan = catalog.findCurrentPlan(planName);
        assertEquals(plan.getName(), planName);
        final long fini = System.nanoTime();
        return (fini - ini);
    }
```

Results:

```
Time: firstPlan (nanoSec) = 1673000, timeLastPlan (nanoSec) = 5264000
```

**Comment by sbrossie** [comment]
I am re-opening the issue to also address performance in the `StandaloneCatalogMapper` when using catalog plugin api.

**Comment by sbrossie** [comment]
Latest measurement shows that KB can handle a 15K catalog in a reasonable fashion (plugin mapping transformation goes down from 12sec -> 40mSec). Keeping the task opened until we hear confirmation from users.

**Comment by marksimu** [comment]
We are seeing an improvement from 12 seconds to 3.5 seconds.  I have opened https://github.com/killbill/killbill/pull/634 for consideration which improves our time to 1.5 seconds.

**Comment by sbrossie** [comment]
Also see 3f148c74ba3d9383002fc28af39c53a2117724d5

**Comment by sbrossie** [comment]
Closing issue as perf now seems acceptable.
