### ISSUE TITLE
Dry run invoice applies credit to balance without taking into account invoice plugin items

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#637]
We always compute CBA items first, then call the invoice plugins.

In the non-dry-run scenario, [committing](https://github.com/killbill/killbill/blob/6823aa9ecbbb42a153312c0845aee0f8f3837b54/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L378) the invoice and items will result in a re-computation of the CBA (taking into account the items added by the plugins).

In the dry-run scenario, because we don't commit, the CBA is stale. It looks like we should re-run the CBA computation [after calling the plugins](https://github.com/killbill/killbill/blob/6823aa9ecbbb42a153312c0845aee0f8f3837b54/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L358-L362).

**Comment by sbrossie** [comment]
I would suggest something slightly different.

Let's review the steps:
1. Code [calls invoiceGenerator](https://github.com/killbill/killbill/blob/killbill-0.18.2/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L389) to compute `FIXED`, `RECURRING`, `USAGE` items -> At this point balance is **necessarily** >= 0.
2. Today, we then compute `computeCBAOnExistingInvoice` prior calling the plugin 
3. We call the plugin to potentially add items.

I am not convinced about step 2, as the only thing that could happen is that we consume existing credit (but should have no impact in things like `TAX` item generation and such.

So we could now have a step 4. that recomputes again after the plugin the CBA situation (but then we would have to potentially merge multiple `CBA` items if we added one in step 2.

Instead i would suggest to move step 2 into step 4 (one computation of `CBA` after calling plugin). In essence plugin is the continuation of invoiceGenerator and `CBA` items are only added at the very end.

**Comment by pierre** [comment]
> 1. Code [calls invoiceGenerator](https://github.com/killbill/killbill/blob/killbill-0.18.2/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L389) to compute `FIXED`, `RECURRING`, `USAGE` items -> At this point balance is **necessarily** >= 0.

No necessarily in case of repairs? In case of a change plan with pro-ration for instance, the new invoice will have a `RECURRING` and a `REPAIR_ADJ` at this point. Without the CBA item, the plugin would receive an invoice with a negative balance.

This *may* not be an issue to compute `TAX` items, but it feels like a big behavior change for 0.18.x (especially since the bug only affects the dry-run scenario).

Agreed that regardless, we should merge the `CBA` items (probably not the case already today in the non dry-run mode).
