### ISSUE TITLE
Enhance export script

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#646]
We currently have an [import/export script](https://github.com/killbill/killbill/blob/master/bin/import-account) to export data associated to an account, but we would like to enhance it and harden it:

The most important piece is to verify that it works correctly by testing it (maybe a good way would be to create different account (showcasing different use cases),  and then export and re-import the data in the DB and verify that table rows are exactly the same.

In addition:
* scrub data (sensitive info such as names, address,...)
* potentially replace external payment plugin
* potentially allow to change the `account_record_id` and `target_record_id`

**Comment by pierre** [comment]
See https://github.com/killbill/killbill-cloud/issues/71.
