### ISSUE TITLE
Search invoices between start and end date.

### ISSUE THREAD

**Issue by webroboteu** [killbill/killbill#651]
I thinks that is only necessary to update the template of the jbdi framework:

searchQuery(prefix) ::= <<
     <idField(prefix)> = :searchKey
  or <prefix>account_id = :searchKey
  or <prefix>currency = :searchKey
>>

**Comment by pierre** [comment]
Note that [InvoiceUserApi](https://github.com/killbill/killbill-api/blob/e65d422762a210544fe3b38732218ab52a13b6be/src/main/java/org/killbill/billing/invoice/api/InvoiceUserApi.java#L53-L61) already exposes:

```
List<Invoice> getInvoicesByAccount(UUID accountId, LocalDate fromDate, TenantContext context)
```

This is not exposed in JAX-RS today though.

**Comment by pierre** [comment]
I would just expose `getInvoicesByAccount` as-is in JAX-RS, not add anything new.

**Comment by pierre** [comment]
Work to be done is to expose a query parameter `fromDate` in JAX-RS (`AccountResource#getInvoicesForAccount`) and call the right `getInvoicesByAccount` API in the implementation.

* Clients to regenerate and update
* Slate to update

**Comment by pierre** [comment]
I would not change the API but always assume `includesMigrated=true`. Typically, these migrated invoices would be the first ones in the system, so to filter them out, one could simply pass a date post migration.

The main use-case for this API is for display purposes anyways (e.g. show invoices over the last 3 months), so we probably don't need too many bells and whistles 😼
