### ISSUE TITLE
DDL scripts fail on MySQL 5.7.5 or newer

### ISSUE THREAD

**Issue by beccagaspard** [killbill/killbill#652]
DDL scripts are failing for me on MySQL 5.7.15 with error `Unknown system variable 'storage_engine'`.  Looks like it is due to `storage_engine` being [deprecated and removed](http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_storage_engine) in MySQL 5.7.5.  It has been replaced by `default_storage_engine`.

**Comment by pierre** [comment]
It looks like `default_storage_engine` works on older versions? If so, happy to merge a PR with that instead.
