### ISSUE TITLE
Fix missing RECURRING item when item has been fully adjusted

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#654]
Prior the fix, the code would not (re)generate a recurring item for a given period after such item had been item adjusted. Example:

1. Invoice created item for period [2016-08-01 -> 2016-09-01)
2. Admin adjusted item (and probably created a matching refund for payment, and most probably cancelled the subscription).

* With previous behavior: If subscription was not cancelled or cancelled at EOT, item would **not** be regenerated by invoice code, and we would **not** see a new item for [2016-08-01 -> 2016-09-01)
* With new behavior: If subscription was not cancelled or cancelled at EOT, item would **then** be regenerated by invoice code, and we would see a new item for [2016-08-01 -> 2016-09-01).

Note that if admin wants such item to **not** be regenerated, then subscription should be cancelled at SOT (start of term). The new behavior only matters when subscription was not cancelled or cancelled at EOT.

**Comment by alina2016** [comment]
Is there a typo under the second "With previous behavior"? Is this actually a description of the new behavior?

**Comment by sbrossie** [comment]
@alina2016 Yes, sorry, fix the typo!

**Comment by sbrossie** [comment]
Fixed in 93b8b68b62ef3bec51326065feea999cd4e5baf4

**Comment by sbrossie** [comment]
Reopening issue for more explanation on what product behavior should be.

**Comment by sbrossie** [comment]
Let's revisit the behavior of the invoicing system after a subscription was cancelled. For simplicity we will **only consider the billing cancellation date** and not the entitlement cancellation since we care about billing.

Before digging into specific scenarios, it is worth revisiting the basic principle of invoicing a subscription (let's assume a monthly):
*  The subscription starts (`CREATE` billing event)
* Every month the subscription gets invoiced for the current period
* At some point the subscription gets cancelled (`CANCEL` billing event)

The goal of the invoicing system is to match the state of the subscription and in particular, when it comes to cancellation, the following can happen:
* SOT (start of term cancellation): Full credit generated
* IMM (immediate cancellation): Pro-ration credit generated (matching what was not used)
* EOT  (end of term cancellation): No credit generated 

When it comes to **invoice item adjustment**, we made the following **product choice**:
* Any recurring item that has been **fully item adjusted** will remain in that state and this is independent of the cancelation date of the subscription.
* Any recurring item that has been **partially item adjusted** will be invoiced normally, but the amount invoiced will be the original amount - adjustment.

Let's look at the following use cases below:


![issue654](https://cloud.githubusercontent.com/assets/246910/20232815/c07f813e-a81f-11e6-8eca-0d304102966d.JPG)

* Case 1: Normal EOT cancellation. The full period has been invoiced
* Case 2: EOT cancellation followed by full invoice item adjustment. The full period has been invoiced and then fully adjusted. Although the cancellation is EOT, the invoicing system will not re-attempt to invoice for that period.
* Case 3: EOT cancellation followed by partial invoice item adjustment. The full period has been invoiced and then partially adjusted. Because the cancellation is EOT, the period should remain fully charged for (but invoice balance will be lowered by taking into account the partial adjustment)
* Case 4: SOT cancellation. The full period has been invoiced and then `repaired` by the system  by generating a full credit.
* Case 5: IMM cancellation. The full period has been invoiced and then partially `repaired` by the system  by generating a pro-ration credit.

Summary:
1. The choice of the cancellation date will drive the generation of credit
2.  Invoice item adjustments are useful in situation where we want to bring the invoice balance to 0 (or to lower its value) and are often useful when customer payment failed or after a refund. Invoice adjustment are not intended to be used as a replacement of choosing the correct cancellation date (e.g we cancel EOT which does not generate credit, and hen we adjust item to make sure customer does not owe money).
