### ISSUE TITLE
API: Expose user token in ExtBusEvent interface

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#66]
Alternatively, make `ExtBusEvent` extend  `BusEvent`.

This would be useful to trace events received by plugins back to the bus_ext_events tables.

Also, it doesn't seem that the user token is passed from bus_events to bus_ext_events (even though the code looks right).

**Comment by sbrossie** [comment]
`BusEvent` is defined in `commons` repo and `ExtBusEvent` is defined in `plugin-api` repo.  

`BusEvent` contains generic fields:
* `Long getSearchKey1()`
* `Long getSearchKey2()`
* `UUID getUserToken()`

I would suggest to just add the `UUID getUserToken()` in `ExtBusEvent` (and verify this is correctly populated.

**Comment by sbrossie** [comment]
I think there is nothing to do in the code for the UserToken: The [DefaultBusExternalEvent](https://github.com/killbill/killbill/blob/killbill-0.18.13/beatrix/src/main/java/org/killbill/billing/beatrix/extbus/DefaultBusExternalEvent.java#L42) already has a `userToken` and the field seems correctly populated in [the listener](https://github.com/killbill/killbill/blob/killbill-0.18.13/beatrix/src/main/java/org/killbill/billing/beatrix/extbus/BeatrixListener.java#L349).

However the definition of the plugin api `ExtBusEvent` was missing the interface so [i just added it ](https://github.com/killbill/killbill-plugin-api/commit/ea0f8b2965e5b6de5799e3cec421827bb5e7beba);

**Comment by sbrossie** [comment]
\cc @pierre for review

**Comment by pierre** [comment]
👍
