### ISSUE TITLE
Enhance EXT bus events to contain objects externalKey

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#679]
This work is related to a  [thread from the mailing list](https://groups.google.com/forum/#!topic/killbilling-users/bZihq5zIqdE) where user is trying to reconcile different things in a plugin the system based on externalKey. Unfortunately none of our events have the externalKey available which obliges to keep a mapping first between object IDs and external Keys.

**Comment by sbrossie** [comment]
In order to address the issue specified in the mailing list thread, we will first enhance the Subscription event to include the bundle `externalKey` in the [metadata section of the event](https://github.com/killbill/killbill-plugin-api/commit/3876042c912927769f0403bdeb3b4220c3a6a39e#diff-7a56615357737b4a00fba4d95b8ce112R36).

**Comment by mnrasul** [comment]
Thanks 👍 Much appreciated.
