### ISSUE TITLE
Subscription creation exception may leave state on disk

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#684]
When a user creates a new subscription, the creation of the `SubscriptionBundle` and the `Subscription` is not atomic (most operations are but there are a few exceptions). As a result, if the call fails part way through, you may end up with 'empty' bundles.

This can be an issue because then the `externalKey` that was attached to those bundles is not reusable anymore.

**Comment by sbrossie** [comment]
Proposal is to allow subsequent call to be made using same bundle `externalKey` (the code would check if such bundle exists and if it is empty) and if so allow the operation.

**Comment by sbrossie** [comment]
By looking at the code, i realized that in the case of `createBaseEntitlement`, we have a check for the `bundleExternalKey` [here](https://github.com/killbill/killbill/blob/killbill-0.18.2/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L158).

However, in the bulk api, [we don't make the same check](https://github.com/killbill/killbill/blob/killbill-0.18.2/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L225).

The beauty of that check is that it verifies if there is already a bundle with the `externalKey` provided  but will only reject if there are valid `Subscriptions` in that bundle. If the check was in place, then we could replace the `createBundleForAccount` with a `getOrCreateBundleForAccount`

**Comment by sbrossie** [comment]
Ok, i am quite confused with that [test](https://github.com/killbill/killbill/blob/master/subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiCreate.java#L69). The test explicitly asserts that creation another `SubscriptionBundle` with the **same** `externalKey` as the first one **and for the same** `Account` should work ???

**Comment by pierre** [comment]
> /cc @pierre Any thoughts?

👍 for making non-bulk and bulk APIs symmetric (ideally, making non-bulk implementation call bulk implementation).

> Ok, i am quite confused with that [test](https://github.com/killbill/killbill/blob/master/subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiCreate.java#L69). The test explicitly asserts that creation of another `SubscriptionBundle` with the **same** `externalKey` as the first one **and for the same** `Account` should work ???

We [allow](https://github.com/killbill/killbill/blob/killbill-0.18.2/entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/EntitlementUtils.java#L94-L104) non-active bundle external keys to be re-used. In that test, all subscriptions on that bundle have been cancelled (although, without the cancel, the test would still pass since the checks are done higher up).
