### ISSUE TITLE
Resetting account notes does not work

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#685]
Let's assume a given account has some `notes` and user wants to remove them. 

The only way to achieve that is to rely on the `public void updateAccount(Account account, CallContext context)` api; the naive assumption is that setting the `notes` field to null in that input object should reset our notes, but this [is not what happens](https://github.com/killbill/killbill/blob/killbill-0.18.2/account/src/main/java/org/killbill/billing/account/api/DefaultAccount.java#L363).

Instead, the api assumes that if a field is not present, it is because we don't want to update its value. For most fields this might be ok (although we have the same issue to remove any fields like `address`, `phone`, ...), but for `notes` this definitely does not work.

An alternative would be to specify a empty string, but this is not so great

**Comment by sbrossie** [comment]
@pierre Should we change the semantics on our `updateAccount` api and always expect all fields to be passed (so we could use null value to rest value) ? One option would be to deprecate existing `updateAccount`  and create a new one with new behavior.

**Comment by pierre** [comment]
We have 2 forms of the `updateAccount` API: one takes an `Account` object (entity), the other an `AccountData` object (account fields only). Only the second form is in use today (and call `mergeWithDelegate` to populate the `null` values from `AccountData`).

How about we simply use the first form for the new behavior? We could call `accountDao.update` directly on the `Account` object passed. That way, it's backward compatible and we can support both forms with minimal changes.

We probably need a new API in JAX-RS though. Maybe a "set account", e.g. `PUT /1.0/kb/accounts/<ACCOUNT_ID>/set`?
