### ISSUE TITLE
Failed transition to Cancellation Overdue state

### ISSUE THREAD

**Issue by petrkoshkin** [killbill/killbill#687]
killbill version 0.18.2

Following this guide http://docs.killbill.io/0.18/overdue.html I observed transition to WARNING and BLOCKED state as expected. But transition to CANCELLATION state failed with NullPointerException exception. The state remains BLOCKED. This functionality worked in 0.16.12

янв 09 02:26:37 example.com server[2673]: 2017-01-08T23:26:37,494+0000 lvl='WARN', log='OverdueDispatcher', th='notifications-th', xff='', rId='', aRId='3', tRId='1', Error proces
янв 09 02:26:37 example.com server[2673]: org.killbill.billing.overdue.config.api.OverdueException: Entitlement plugin aborted call: null
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.applicator.OverdueStateApplicator.cancelSubscriptionsIfRequired(OverdueStateApplicator.java:336)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.applicator.OverdueStateApplicator.apply(OverdueStateApplicator.java:157)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.wrapper.OverdueWrapper.refreshWithLock(OverdueWrapper.java:109)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.wrapper.OverdueWrapper.refresh(OverdueWrapper.java:91)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.listener.OverdueDispatcher.processOverdue(OverdueDispatcher.java:52)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.listener.OverdueDispatcher.processOverdueForAccount(OverdueDispatcher.java:43)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.notification.OverdueCheckNotifier.handleReadyNotification(OverdueCheckNotifier.java:62)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.notification.DefaultOverdueNotifierBase$1.handleReadyNotification(DefaultOverdueNotifierBase.java:72)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
янв 09 02:26:37 example.com server[2673]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
янв 09 02:26:37 example.com server[2673]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
янв 09 02:26:37 example.com server[2673]: at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
янв 09 02:26:37 example.com server[2673]: at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
янв 09 02:26:37 example.com server[2673]: at java.lang.Thread.run(Thread.java:745)
янв 09 02:26:37 example.com server[2673]: Caused by: org.killbill.billing.entitlement.api.EntitlementApiException: Entitlement plugin aborted call: null
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:86)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementInternalApi.cancel(DefaultEntitlementInternalApi.java:166)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.applicator.OverdueStateApplicator.cancelSubscriptionsIfRequired(OverdueStateApplicator.java:334)
янв 09 02:26:37 example.com server[2673]: ... 18 common frames omitted

The cause exception was missed, so I added logging to the EntitlementPluginExecution.java and got:

java.lang.NullPointerException: null
янв 09 02:26:37 example.com server[2673]: at org.joda.time.base.AbstractInstant.compareTo(AbstractInstant.java:300)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementInternalApi$WithDateOverrideBillingPolicyEntitlementCanceler.doCall(Defaul
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementInternalApi$WithDateOverrideBillingPolicyEntitlementCanceler.doCall(Defaul
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:73)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementInternalApi.cancel(DefaultEntitlementInternalApi.java:166)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.applicator.OverdueStateApplicator.cancelSubscriptionsIfRequired(OverdueStateApplicator.java:334)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.applicator.OverdueStateApplicator.apply(OverdueStateApplicator.java:157)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.wrapper.OverdueWrapper.refreshWithLock(OverdueWrapper.java:109)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.wrapper.OverdueWrapper.refresh(OverdueWrapper.java:91)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.listener.OverdueDispatcher.processOverdue(OverdueDispatcher.java:52)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.listener.OverdueDispatcher.processOverdueForAccount(OverdueDispatcher.java:43)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.notification.OverdueCheckNotifier.handleReadyNotification(OverdueCheckNotifier.java:62)
янв 09 02:26:37 example.com server[2673]: at org.killbill.billing.overdue.notification.DefaultOverdueNotifierBase$1.handleReadyNotification(DefaultOverdueNotifierBase.java:72)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
янв 09 02:26:37 example.com server[2673]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
янв 09 02:26:37 example.com server[2673]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
янв 09 02:26:37 example.com server[2673]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
янв 09 02:26:37 example.com server[2673]: at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
янв 09 02:26:37 example.com server[2673]: at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
янв 09 02:26:37 example.com server[2673]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
янв 09 02:26:37 example.com server[2673]: at java.lang.Thread.run(Thread.java:745)

**Comment by sbrossie** [comment]
Thanks for the report @petrkoshkin . Will investigate and provide a fix on `0.18.3`

**Comment by petrkoshkin** [comment]
Additional comments:

1) It seems there is also a problem with clearing of BLOCKED overdue state after account's balance become positive. 
2) There are no events BUNDLE_PAUSE  after transitioning to BLOCKED overdue state, though disableEntitlementAndChangesBlocked is set to true. Is it expected? If expected then when we can expect firing of BUNDLE_PAUSE event?

**Comment by sbrossie** [comment]
The issue has to do with the fact when we make the date [comparison](https://github.com/killbill/killbill/blob/killbill-0.18.2/entitlement/src/main/java/org/killbill/billing/entitlement/api/svcs/DefaultEntitlementInternalApi.java#L259) the effectiveDate of the `SubscriptionBase` is still null because it has not been refreshed yet.

**Comment by sbrossie** [comment]
@petrkoshkin I will keep this issue to address the NPE you reported. If after this has been fixed, you encounter other issues then please report on the mailing list (or if you are certain those are bugs file reports accordingly).
