### ISSUE TITLE
import-data script does not specify credentials and tenant keys to export data

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#689]
The import script seems to be [missing credentials and tenant/secret keys](https://github.com/killbill/killbill/blob/master/bin/import-account#L87).

We decide if those are ENV variables or additional arguments to the script. 

Also [update doc](https://github.com/killbill/killbill/wiki/Production-troubleshooting#exporting-account-data) when this has ben fixed.

**Comment by sbrossie** [comment]
See a2c7ec497c423ebfc29d560885d8b29704dae234

**Comment by sbrossie** [comment]
I also realized the notification and bus entries data is garbled, so will keep the ticket open to also fix that.

**Comment by sbrossie** [comment]
Unfortunately it looks like we ask `mysql` import script to [use `,`](https://github.com/killbill/killbill/blob/killbill-0.18.2/bin/import-account#L93) to delimit field values but when we have JSON values, that breaks everything.  One road ww could take is to add another pre-processing layer to change those `comma` into something else (except the one from the JSON) and use that new delimiter to do the upload.

/cc @pierre Any thoughts?

**Comment by pierre** [comment]
> when we have JSON values, that breaks everything

I see we use `OPTIONALLY ENCLOSED BY '\"'` when we load. Aren't the JSON columns enclosed by `"`? This would solve the comma issue but the export script still needs to make sure to escape `"` properly inside the JSON.

Could be related to [this](https://github.com/killbill/killbill/blob/killbill-0.18.2/util/src/main/java/org/killbill/billing/util/export/dao/CSVExportOutputStream.java#L67)?
