### ISSUE TITLE
Fatal error in Analytics plugin

### ISSUE THREAD

**Issue by petrkoshkin** [killbill/killbill#693]
killbill 0.18.2
analytics plugin 4.1.0

Steps to reproduce:
1. Start killbill with sample demo catalog, for example with this one: https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/resources/newspaper.xml
2. Create a subscription (with UNLIMITED duration in its final phase)
3. Check logs

Problem is analytics plug-in can not handle  UNLIMITED duration specified in catalog
<duration>
                    <unit>UNLIMITED</unit>
</duration>

янв 14 16:58:02 example.org server[9107]: org.apache.felix.log.LogException: org.killbill.notificationq.NotificationQueueException: java.lang.IllegalStateException: Unexpected duration unit UNL
янв 14 16:58:02 example.org server[9107]: at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:205)
янв 14 16:58:02 example.org server[9107]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
янв 14 16:58:02 example.org server[9107]: at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
янв 14 16:58:02 example.org server[9107]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
янв 14 16:58:02 example.org server[9107]: at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
янв 14 16:58:02 example.org server[9107]: at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
янв 14 16:58:02 example.org server[9107]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
янв 14 16:58:02 example.org server[9107]: at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
янв 14 16:58:02 example.org server[9107]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
янв 14 16:58:02 example.org server[9107]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
янв 14 16:58:02 example.org server[9107]: at java.lang.Thread.run(Thread.java:745)
янв 14 16:58:02 example.org server[9107]: Caused by: java.lang.IllegalStateException: Unexpected duration unit UNLIMITED
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.catalog.DefaultDuration.toJodaPeriod(DefaultDuration.java:160)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.model.BusinessSubscription.<init>(BusinessSubscription.java:139)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.getBusinessSubscriptionFromTransition(BusinessSubscriptionTr
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.getBusinessSubscriptionFromTransition(BusinessSubscriptionTr
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.buildTransitionsForBundle(BusinessSubscriptionTransitionFact
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.buildTransitionsForBundle(BusinessSubscriptionTransitionFact
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.createBusinessSubscriptionTransitions(BusinessSubscriptionTr
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.BusinessSubscriptionTransitionDao.update(BusinessSubscriptionTransitionDao.java:65)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.dao.AllBusinessObjectsDao.update(AllBusinessObjectsDao.java:62)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.AnalyticsListener.handleAnalyticsJob(AnalyticsListener.java:252)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.AnalyticsListener.access$100(AnalyticsListener.java:66)
янв 14 16:58:02 example.org server[9107]: at org.killbill.billing.plugin.analytics.AnalyticsListener$1.handleReadyNotification(AnalyticsListener.java:137)
янв 14 16:58:02 example.org server[9107]: at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)

**Comment by pierre** [comment]
This has been fixed by https://github.com/killbill/killbill-analytics-plugin/commit/2905ae5ef1e55a7f33651cc7bf8bce5f8cf09b43. Please upgrade to version 4.2.0 of the plugin.
