### ISSUE TITLE
Creating Tenants over the HTTP API

### ISSUE THREAD

**Issue by MaxGfeller** [killbill/killbill#697]
I'm trying to create a new tenant using the HTTP API:

```
curl -u admin:password -H "X-Killbill-Apikey: my-api-key" -H 'X-Killbill-Apisecret: my-api-secret' -H "Content-Type: application/json" -H 'X-Killbill-CreatedBy: admin' -X POST -d '{"externalKey": "my-tenant","apiKey":"my-api-key","apiSecret":"my-api-secret"}' "http://127.0.0.1:8080/1.0/kb/tenants"
```

...which works and returns a `201 - Created` status code. However, Kaui somehow does not see this tenant and when i try to retrieve a list using the following curl request:

```
curl -u admin:password -H "X-Killbill-ApiKey: my-api-key" -H 'X-Killbill-ApiSecret: my-api-secret' -H "Content-Type: application/json" -H 
'X-Killbill-CreatedBy: admin' -X GET "http://127.0.0.1:8080/1.0/kb/tenants"
```

...i'm presented with an error: 

```json
{"className":"net.sf.ehcache.CacheException","code":null,"message":"Exception on load for key null","causeClassName":"java.lang.NullPointerException","causeMessage":null,"stackTrace":[]}
```

Any idea on this?

**Comment by sbrossie** [comment]
@MaxGfeller Do you mind using the [user mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for personal questions instead of filing issues. Also please specify which versions of KB and KAUi you are using.

**Comment by MaxGfeller** [comment]
I'm sorry, i assumed this was a bug. I'll post on the mailing list.
