### ISSUE TITLE
Create getInvoiceItem API

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#7]
In `InvoiceUserApi`, add:

```
public Invoice getInvoiceByInvoiceItem(UUID invoiceItemId, TenantContext context) throws InvoiceApiException;
```

In `InvoiceResource`, add `getInvoiceByInvoiceItem` (`@Path("/byInvoiceItem/{invoiceItemId:" + UUID_PATTERN + "}/")`).

* Clients to regenerate (Java, Python) or update (Ruby)
* Slate to update

**Comment by pierre** [comment]
This was indeed for [Kaui](https://github.com/killbill/killbill-admin-ui/blob/1ff391710df1c71a22476b9a45c9440995c76bb4/app/controllers/kaui/invoice_items_controller.rb#L3-L15). Not sure it's really worth the effort though.

**Comment by pierre** [comment]
This could be useful to retrieve linked invoice items as well. See https://groups.google.com/forum/#!msg/killbilling-users/JLIc8qXxjBE/4mHTPMHABQAJ.
