### ISSUE TITLE
Upcoming invoice notification improvements

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#707]
* The event is missing for PHASE transitions
* The event is missing if the `isNotifiedForInvoices` flag isn't set at the time of the previous invoice generation:
1. Create an account (`isNotifiedForInvoices = false`)
2. Create a subscription
3. Move the clock forward to next invoice date - org.killbill.invoice.dryRunNotificationSchedule, observe no UPCOMING_INVOICE event put on the event bus (https://github.com/killbill/killbill/blob/860348345f37ad2a8ecf6c0aead871d6f37e3ebd/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L195)
4. Set` isNotifiedForInvoices = true` on the account 
5. Move the clock forward to next invoice date - org.killbill.invoice.dryRunNotificationSchedule, observe still no UPCOMING_INVOICE event put on the event bus

**Comment by pierre** [comment]
Regarding the PHASE event, there may already be some support for it (see [SubscriptionBaseInternalApi#getFutureNotificationsForAccount](https://github.com/killbill/killbill/blob/master/api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java#L97)).

**Comment by sbrossie** [comment]
This task is related to #58 (we want to deprecate core support to email service and invoice notification) to instead delegate the functionality to the [notification plugin](https://github.com/killbill/killbill-email-notifications-plugin).

**Comment by sbrossie** [comment]
> Regarding the PHASE event, there may already be some support for it (see SubscriptionBaseInternalApi#getFutureNotificationsForAccount).

From reading the code, the api `getFutureNotificationsForAccount` was added implement the dryRun functionality where user specifies a `null` `targetDate` and let the system compute the next invoice for the account (by trying all possible future invoice date and stopping when first non invoice is created). So i think this is orthogonal to this task (and therefore it needs to be verified whether `PHASE` notification would be taken into account for invoice notifications.

**Comment by sbrossie** [comment]
Proposal:

1. Get rid of `isNotifiedForInvoices` in core + email support (#58)
2. Fix (or verify) that `PHASE` events are correctly supported to notify for upcoming invoices (might need to be a different task as this may be more tricky than it looks)
3. Rework notification configuration by adding new endpoint in [notification plugin](https://github.com/killbill/killbill-email-notifications-plugin) that would provide a more granular definition for notifications (e.g user could be notified for upcoming invoices and payments but disable notification for subscription creation). This would need to be coupled with a new KAUI moutable rails app.

**Comment by pierre** [comment]
> > Regarding the PHASE event, there may already be some support for it (see SubscriptionBaseInternalApi#getFutureNotificationsForAccount).
>
> From reading the code, the api `getFutureNotificationsForAccount` was added to implement the dryRun functionality where user specifies a `null` `targetDate` and let the system compute the next invoice for the account (by trying all possible future invoice date and stopping when first non invoice is created). So i think this is orthogonal to this task (and therefore it needs to be verified whether `PHASE` notification would be taken into account for invoice notifications.

Sorry, I meant [getNextFutureEventForSubscriptions](https://github.com/killbill/killbill/blob/cd9502d8ea7b2d00f54c653c0820d21c910c6eb0/api/src/main/java/org/killbill/billing/subscription/api/SubscriptionBaseInternalApi.java#L99) (the one below 😸). See https://github.com/killbill/killbill/issues/311 and [this piece of code](https://github.com/killbill/killbill/blob/cd9502d8ea7b2d00f54c653c0820d21c910c6eb0/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L492-L506).


> 1. Get rid of `isNotifiedForInvoices` in core + email support (#58)

👍 Tracked by #58 for 0.20.0.

> 3. Rework notification configuration by adding new endpoint in [notification plugin](https://github.com/killbill/killbill-email-notifications-plugin) that would provide a more granular definition for notifications (e.g user could be notified for upcoming invoices and payments but disable notification for subscription creation). This would need to be coupled with a new KAUI moutable rails app.

👍 (although our per tenant per plugin config should probably be enough?). Tracked by https://github.com/killbill/killbill-email-notifications-plugin/issues/8.


Now, going back to that specific issue:

> The event is missing if the `isNotifiedForInvoices` flag isn't set at the time of the previous invoice generation

I'm confused about the report since `isNotifiedForInvoices` should be orthogonal to the upcoming notification feature. I'll try to understand better the bug report.
