### ISSUE TITLE
Sensitive plugin properties logged

### ISSUE THREAD

**Issue by daliwei** [killbill/killbill#712]
Sensitive info in Plugin property `ccVerificationValue` is logged. Should we include this in the [pattern list](https://github.com/killbill/killbill/blob/a17f578cc77996befba3413e06c20f412e8dc7a9/profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/PatternObfuscator.java#L30)?

**Comment by pierre** [comment]
> Sensitive info in Plugin property `ccVerificationValue` is logged.

Where is it logged (access log, killbill.out, etc.)?

Note that Tomcat must be configured to not log the query string if these are passed as query parameters. The default pattern is [here](https://github.com/killbill/killbill-cloud/blob/9834b542d92afeee8134691c1ec0ac3b88c334bd/docker/templates/base/latest/server.xml#L102). A more conservative one would be `%h %l %u %t &quot;%m %U&quot; %s %b %D`.

> Should we include this in the [pattern list](https://github.com/killbill/killbill/blob/a17f578cc77996befba3413e06c20f412e8dc7a9/profiles/killbill/src/main/java/org/killbill/billing/server/log/obfuscators/PatternObfuscator.java#L30)?

👍 I would probably include all default plugin properties (see [here](https://github.com/killbill/killbill-plugin-framework-java/blob/47e924295f6e2d276842bcda144f20a404cab013/src/main/java/org/killbill/billing/plugin/api/payment/PluginPaymentPluginApi.java)) that are sensitive (PAN, CVV, PII data, etc.).
