### ISSUE TITLE
Notes for account

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#72]
It would be useful to add a column to accounts where a note can be stored about the account. This would be available in the UI for advo/etc to add details about the account for internal use. Custom fields don't seem to be suited for this as length is limited to 255 characters and I think we would want a higher limit, such as 2k or 4k characters.

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
I've started working with this issue and just made my initial commit.
I still have to add new Integration Tests but I just wanted you to start taking a look at the changes (they are a lot) and tell me if you see anything wrong.

These are the PR:
- killbill-core: https://github.com/killbill/killbill/pull/603
- killbill-api: https://github.com/killbill/killbill-api/pull/20
- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/46
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/12

Thanks!
