### ISSUE TITLE
Catalog simplePlan api needs stronger validation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#722]
There has been reports on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/satish%7Csort:relevance/killbilling-users/eCB2IlclFIc/pAVICgBwAwAJ) that using `CatalogUserApi#addSimplePlan` api (often through KAUI UI) leads to some inconsistent state where catalog entries have to be removed from DB by hand and servers restarted.

Note; While the lack of validation is not a bug per say, it leads to such inconsistent state that i labeled as `bug`

**Comment by pierre** [comment]
Should we simply make `useGlobalDefault=false` the default?

See discussion [here](https://groups.google.com/forum/#!msg/killbilling-users/od1nP_0eEV8/UVynDm-GBAAJ).

**Comment by sbrossie** [comment]
There is another [post on the mailing list](https://groups.google.com/forum/#!topic/killbilling-users/MXmCH2lsv4E) that resurfaces this issue.

I was initially against providing apis that could delete catalog but i think it would be better to actually do that, than leaving all these users in a difficult state to fix. So  a few thoughts:

1. We could/should definitely change the default setting when creating tenant -- comment [above](https://github.com/killbill/killbill/issues/722#issuecomment-301114782)
2. We could provide a `DELETE` catalog endpoint that only works in test mode (that way it is fairly safe to use, as we never expect production environment to be deployed with test mode (`org.killbill.server.test.mode`). We could also plug that endpoint from KAUI and prompt for confirmation. Also note that even if this was done by mistake, the same catalog could be uploaded again and everything would be back to normal.
3. Additionally, for folks tweaking catalog by hand we could offer the cache invalidation endpoint in KAUI to not force people to restart their server

**Comment by sbrossie** [comment]
Note that deleting a catalog by hand from `tenant_kvs` make the default `SpyCar` catalog to be loaded. If we indeed allow to delete catalog, we 'll have to decide on what to do.
