### ISSUE TITLE
Missing MetaData field in push notifications

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#726]
ExtBusEvent now has a [MetaData](https://github.com/killbill/killbill-plugin-api/blob/8828ef32ed4187d89c6fb738b5f5e876b0d30118/notification/src/main/java/org/killbill/billing/notification/plugin/api/ExtBusEvent.java#L43-L49) field, but it is not propagated to [push notifications](https://github.com/killbill/killbill/blob/b2946ee3e1f05de40603c6a2c55b522dadfaf236/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/NotificationJson.java#L30-L35).

The retries mechanism also needs to be [updated](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/java/org/killbill/billing/server/notifications/PushNotificationKey.java).

**Comment by lghamie** [comment]
Hi Pierre, any way of getting a patch for 0.18 with this fix? 

I'd like to get rid of the duplicated notifications.
