### ISSUE TITLE
NPE in DefaultSubscriptionBaseApiService#getEventsOnChangePlan for PENDING subscription

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#733]
If a subscription is started in the future, `PlanAligner#getTimedPhaseOnChange` throws NPE since `subscription.getCurrent*` fields are `null`.

**Comment by sbrossie** [comment]
What was the scenario that triggered that? Was it a changePlan/cancelPlan in the future (after start date) or prior that? Or it does not matter?

**Comment by pierre** [comment]
* Create subscription with (billing) effective date in the future
* Trigger dry-run IMMEDIATE change plan (through the invoice endpoint)

**Comment by sbrossie** [comment]
The NPE is certainly something we should fix, but more importantly we have to define the behavior we want. I would think the dryRun functionality should match the real operation it tries to run, and so stepping back a little bit, i looked at what our code does for normal operation when a subscription is in a `PENDING` state:

1.  A change of `Plan` is not allowed until the {`Entitlement` is active](https://github.com/killbill/killbill/blob/killbill-0.18.6/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlement.java#L574). This is regardless of whether we pass a date (or null) prior the `startDate`, or whether we specify a date on (or after) that `startDate`. From a product point of view i think allowing future changes (that would start on or after `startDate`) seem like the right thing to allow. And then there is a question of whether looking at the entitlement date (v.s billing date) is the right choice (i think both should be taken into consideration).
2. A cancellation of subscription exhibits a different pattern: We allow a future cancellation (and even correctly interpret a  null date to match the startDate and reject any date prior startDate.

My suggestion is to agree on what we want first, fix the normal operation and then mimic that same logic for the dryRun use case.

In that specific scenario, i would reject an `IMMEDIATE` plan change (dryRun or not) on PENDING subscription (in a cleaner manner that throwing an NPE).

**Comment by pierre** [comment]
> The NPE is certainly something we should fix, but more importantly we have to define the behavior we want. I would think the dryRun functionality should match the real operation it tries to run

:+1:

> In that specific scenario, i would reject an `IMMEDIATE` plan change (dryRun or not) on PENDING subscription (in a cleaner manner that throwing an NPE).

Making dryRun behave like the non-dryRun codepath makes sense.

Related to the `PENDING` scenario though (and although this is what triggered originally this bug, we can track this separately), we should fix/ease the migration scenario where the user mirrors subscriptions from an old billing system into Kill Bill, with a billing start date in the future. What happens if the customer changes plan in the old billing system? Specifying `IMMEDIATE` won't work (`PENDING` subscription), so the user would have to pass the right date (unsure if passing the effective start date would even work?). It would maybe be nice to cancel the originally specified subscription event...
