### ISSUE TITLE
Need simple Plan Update and delete and simple plan get

### ISSUE THREAD

**Issue by kannanchinnakannu94** [killbill/killbill#734]
Need Simple plan Get and simple plan with usage based billing parameters

**Comment by sbrossie** [comment]
@kannanchinnakannu94 a PR to implement that would be well appreciated but if it modifies apis in an incompatible way, it would have to land into branch `work-for-release-0.19.x`.

**Comment by kannanchinnakannu94** [comment]
Hi ,
Can i know 0.19.x releasedate

**Comment by kannanchinnakannu94** [comment]
**Requirement Details**
Simple Plan Enhancements:-
1.Tenant Admin should be able to create the Simple plan with Usage Based Billing 
2.Tenant Admin should be able to Update the Particular Simple plan with Usage Based Billing 
3.Tenant Admin should be  able to get the Particular Simple plan with Usage Based Billing
4.Tenant Admin should be  able to delete the Simple plan with Usage Based Billing
