### ISSUE TITLE
Coupons Support in KillBill

### ISSUE THREAD

**Issue by kannanchinnakannu94** [killbill/killbill#737]
**Simple Plan with Coupons**
1.While creating the Simple Plan, We should be able to specify the Coupons code.
2.While subscription, If apply the Coupons, then the Coupons Amount should be detected in the particular subscription.
3.The same should be reflected in Invoice also.

**Comment by ABBAS12MIK** [comment]
Good

**Comment by sbrossie** [comment]
We had in mind to implement coupons in a plugin:
* We started a skeleton [here}(https://github.com/killbill/killbill-coupon-plugin-demo)
* There is a company that open source [theirs](https://github.com/aeq/killbill-coupon-extension) as well
