### ISSUE TITLE
[Site] wrong link to features - 404

### ISSUE THREAD

**Issue by dyorgio** [killbill/killbill#740]
Hi, 

on killbill.io site there is a additional slash '/' on Features (http://docs.killbill.io/latest/features.html/).

If you put site project on github we can adjust it :)

**Comment by pierre** [comment]
Thanks for the report, I've just fixed it.

FWIW, while docs.killbill.io is on GitHub (https://github.com/killbill/killbill-docs), killbill.io isn't.
