### ISSUE TITLE
webconsolebranding stopped status in 0.18.6

### ISSUE THREAD

**Issue by skuda** [killbill/killbill#742]
Hi,

I installed KillBill in a Kubernetes cluster using the docker images, I didn't test thoroughly but everything seems to work fine, everything but the org.kill-bill.billing.killbill-platform-osgi-bundles-webconsolebranding plugin that is in stopped state and I can not start it manually neither.

I am using the Docker image killbill/killbill:0.18.6, this is the log at container start:
https://pastebin.com/cA2V7xT1

This is how I see the state of the plugin from the kpm section of Kaui:
https://gyazo.com/3d116044eec514b5a318ddb1297d88b2

And this is what happens when I try to manually start the plugin:
https://pastebin.com/13ia7J9m

Just in case is related, I installed some plugins using environment variables exposed to kpm, specifically I used:

- KILLBILL_PLUGIN_ANALYTICS
- KILLBILL_PLUGIN_BRAINTREE_BLUE
- KILLBILL_PLUGIN_CURRENCY
- KILLBILL_PLUGIN_EMAIL_NOTIFICATIONS

**Comment by skuda** [comment]
I suppose this is related to this issue too:

When I try to use the OSGI WEB CONSOLE link, from the plug submenu, it doesn't works, the link point to http://killbill:8080/plugins/system/console/bundles but even If I fix ip and port to the real ones I get the error `The page you were looking for doesn't exist.` in the browser.

**Comment by pierre** [comment]
> org.kill-bill.billing.killbill-platform-osgi-bundles-webconsolebranding plugin that is in stopped state and I can not start it manually neither.

This is expected because it is a fragment bundle (the actual code is in the webconsole bundle). 

You can see the related log line in your startup sequence:

```
[killbill-665448191-79gw9] 2017-04-24T12:49:59,141+0000 lvl='INFO', log='FileInstall', th='localhost-startStop-1', xff='', rId='', aRId='', tRId='', Skipping fragment bundle file:/var/lib/killbill/bundles/platform/killbill-platform-osgi-bundles-webconsolebranding-0.36.6.jar
```

> When I try to use the OSGI WEB CONSOLE link, from the plug submenu, it doesn't works, the link point to http://killbill:8080/plugins/system/console/bundles but even If I fix ip and port to the real ones I get the error `The page you were looking for doesn't exist.` in the browser.

This is likely a setup issue -- please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) and attach the Kill Bill logs (killbill.out and access logs) when trying to access that url.

**Comment by skuda** [comment]
Thanks @pierre, It was a bit confusing to have the plugin in stopped state but it's clear now.

I found the second problem, I was using the Kaui port, not the Killbill one, I can see the bundles now, the only issue left is the menu isn't creating the correct url to access externally the killbill instance. 

I know there the problem is, Kaui container is starting with KAUI_KILLBILL_URL=http://killbill:8080 that it's completely valid inside the cluster but not from external clients. I wouldn't like to have all kaui calls pass through our load balancer, there is a env var that allows to define "external_killbill_url"

Should I post to the mailing list? Thanks!

**Comment by pierre** [comment]
> Should I post to the mailing list?

Yes, thanks!
