### ISSUE TITLE
Plugin Properties not extracted from PaymentTransactionJson

### ISSUE THREAD

**Issue by daliwei** [killbill/killbill#746]
Plugin properties in PluginPropertyJson in PaymentTransactionJson is [not extracted](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/PaymentResource.java#L490) from Refund endpoint (looks like that is also the case for capture endpoint), and therefore, are missing from the subsequent operations inside Kill bill and its plugins.

**Comment by sbrossie** [comment]
@daliwei Indeed... do you want to submit a PR?

**Comment by daliwei** [comment]
@sbrossie will do
