### ISSUE TITLE
API POST /tagDefinitions enforces lowercase name?

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill#758]
When sending a POST request to API /tagDefintions in order to create a tag definition, the API doesn't seem to accept uppercase names. The answer is "The tag definition name must be in lowercase ABCDEF".

It seems strange to me as:
1. why not let the user choose?
2. Killbill default tags are uppercase (AUTO_PAY_OFF, ...)

Any reason for this?

**Comment by pierre** [comment]
Upper case tag definition names are by convention reserved for Kill Bill internal use (see https://github.com/killbill/killbill-api/blob/a3188c8710a754d0e5a84a36e70deafa4a7699cd/src/main/java/org/killbill/billing/util/tag/ControlTagType.java#L28-L34). These change the behavior of the system (e.g. disable invoicing) while user-defined tag definitions are ignored.
