### ISSUE TITLE
REST API TransactionResource#notifyStateChanged does not allow passing control plugins

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#764]
The [api](https://github.com/killbill/killbill/blob/killbill-0.18.9/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/TransactionResource.java#L120) does not support the query parameter `controlPluginName` and therefore code is wired to call `notifyPendingTransactionOfStateChanged` instead of `notifyPendingTransactionOfStateChangedWithPaymentControl`.

One issue with that is the case of payment completion (`PENDING` -> `SUCCESS`) as reported in the [mailing list](https://groups.google.com/forum/#!topic/killbilling-users/lj-MumZaHVs).

**Comment by sbrossie** [comment]
However, there is a workaround that would consist in calling the payment completion api and specifying internal control pluguin `__INVOICE_PAYMENT_CONTROL_PLUGIN__` along with the matching `invoiceId` correctly passed as a property `IPCD_INVOICE_ID`:

```
curl -v \
-u'admin:password' \
-H "X-Killbill-ApiKey: bob" \
-H 'X-Killbill-ApiSecret: lazar' \
-H "Content-Type: application/json" \
-H 'X-Killbill-CreatedBy: stephane' \
-X PUT \
--data-binary '{"properties": [ {"key": "IPCD_INVOICE_ID", "value": "<YOUR_INVOICE_ID>"}] }' \
 -v 'http://127.0.0.1:8080/1.0/kb/payments/<YOUR_PAYMENT_ID>?controlPluginName=__INVOICE_PAYMENT_CONTROL_PLUGIN__'     
```

**Comment by sbrossie** [comment]
@pierre In addition to the [fix above](https://github.com/killbill/killbill/commit/0e41cc9e8d3d69da6c2240250425867c7ad6ae75), i am wondering if we should add another convenience api in `InvoiceResource` to not expose any of the KB internals (`controlPluginName=__INVOICE_PAYMENT_CONTROL_PLUGIN__`):

With the fix, the api call becomes:

```
curl -v \
-u'admin:password' \
-H "X-Killbill-ApiKey: bob" \
-H 'X-Killbill-ApiSecret: lazar' \
-H "Content-Type: application/json" \
-H 'X-Killbill-CreatedBy: stephane' \
-X POST \
--data-binary '{"paymentId":"<YOUR_PAYMENT_ID)>", "status":"SUCCESS"}' \
 -v 'http://127.0.0.1:8080/1.0/kb/paymentTransactions/<YOUR_PAYMENT_TRANSACTION_ID>?controlPluginName=__INVOICE_PAYMENT_CONTROL_PLUGIN__'     
```

Note: Unlike the workaround provide above, there is no need to specify the `invoiceId` because the code magically extract it from previous payment attempt.

**Comment by pierre** [comment]
> i am wondering if we should add another convenience api in `InvoiceResource` to not expose any of the KB internals

Agreed, hiding `__INVOICE_PAYMENT_CONTROL_PLUGIN__` would be good.
