### ISSUE TITLE
Built-in support for retry in Kill Bill plugin apis 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#767]
Overview: There are situations where plugins implementing a specific [plugin api](https://github.com/killbill/killbill-plugin-api) will fail to accomplish their task  -- e.g third party system integration returns an error-- and in such a situation, we would like to extend the core Kill Bill system to retry the operation.

Except for plugins implementing the `PaymentPluginApi`, which already offers some [retry options](http://docs.killbill.io/latest/userguide_subscription.html#_payment_retries) through system properties, plugin implementors have 2 options today:
1. Pass any kind of exception back to Kill Bill core which will abort the ongoing operation
2. Catch all exceptions in the plugin -- and possibly handle the retry mechanism on its own

Option 1 is probably sufficient for most operations that are a result of an client api call: The call would fail and the client could retry later when the service -- as a whole -- becomes fully available. However for all operations that are driven through bus/notification events, this is not a good option because the system will abort the call, but this may leave the system in a bad state -- e.g invoice generation fails and from then on, customer is not invoiced anymore.

Option 2 works, but the same kind of retry mechanism possibly needs to happen on all plugins.

The goal of this task is to allow for option 2 to happen with minimum logic inside the plugins.

**Comment by sbrossie** [comment]
See [bug report in avatax-plugin](https://github.com/killbill/killbill-avatax-plugin/issues/3)

**Comment by sbrossie** [comment]
As a workaround until this is fleshed out -- and implemented -- one solution is to implement that logic in the plugin, possibly by leveraging the KB  notificationQ mechanism. See [wiki for direction](https://github.com/killbill/killbill/wiki/Using-NotificationQueue-From-Plugin)

**Comment by pierre** [comment]
We want to retry operations invoking plugins in async threads (bus, notifications), while throwing the exception back to the user for synchronous operations (e.g. API call).

Taking a step back, it sounds like we need to instead implement a retry mechanism to bus handlers. In https://github.com/killbill/killbill/issues/348#issuecomment-225037927, we argued otherwise, because we assumed that if Kill Bill core throws an NPE, there is nothing we can do.

A better approach would actually be to always retry (e.g. 5m, 1hr then every 24hrs) so that next time Kill Bill or the plugin is deployed (or if the third party system goes back online), the state is fixed automagically.

**Comment by pierre** [comment]
An initial generic implementation has been written in the branch https://github.com/killbill/killbill/tree/fix-for-348, but it is more complicated than initially thought:

* It is not clear how we want to handle core exceptions like wrong event class type, null event, event bus exception, etc.
* `EntitlementPluginApi` exceptions aren't well defined (https://github.com/killbill/killbill/issues/669#issuecomment-319384352)
* Code changes are big... 🤗 

We are going to try a similar, yet simpler, approach where only a specific exception (`RetryException`) thrown by the `InvoicePluginApi` is retried. The nice side effect is that the plugin would be able to dictate the retry policy (defined in the exception).

This approach could then be generalized to other sub-systems for other plugin types (e.g. `CatalogPluginApi`) as needed.

**Comment by pierre** [comment]
Changes are in the [fix-for-767](https://github.com/killbill/killbill/compare/work-for-release-0.19.x...fix-for-767) branch. [This test](https://github.com/killbill/killbill/blob/fix-for-767/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestWithInvoicePlugin.java#L96) illustrates the behavior.

See also https://github.com/killbill/killbill-plugin-api/commit/ab81303fc17e1666c7ba920cfdbdfdb347f9c618.

**Comment by pierre** [comment]
In addition to `InvoicePluginApi`, the code has been extended to support retries for notification plugins.

PRs:

* https://github.com/killbill/killbill-api/pull/35
* https://github.com/killbill/killbill-plugin-api/pull/7
* https://github.com/killbill/killbill-commons/pull/23
* https://github.com/killbill/killbill-platform/pull/22
* https://github.com/killbill/killbill/pull/785

Mechanism has been tested with the email notifications plugin (required code change: https://github.com/killbill/killbill-email-notifications-plugin/pull/15).

**Comment by cxzhang2** [comment]
Hi folks, the thread above mentions extending this to the Catalog Plugin but it doesn't look like the work was done?  I'm concerned in particular about the case where the system tries to generate an Invoice, looks up the plan via the catalg plugin, catalog plugin fails and invoice generation is never retried

**Comment by pierre** [comment]
@cxzhang2 Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
