### ISSUE TITLE
Provide Kill Bill hooks for service discovery

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#776]
In some deployments, there is a need for the service (Kill Bill) to register/unregister when it is up or going down. A typical scenario, is one where the Kill Bill instances are not provisioned statically and need to advertise themselves during boot/shutdown sequences.

Today, there is no good way to do that without forking the code to insert logic during the initialization/shutdown phases.

Also, we hooks should allow to interrupt the sequence based on registration status -- if the app cannot unregister itself, probably it should not shutdown and vice versa.

**Comment by pierre** [comment]
See https://github.com/killbill/killbill-platform/pull/33.
