### ISSUE TITLE
Provide a mechanism to encrypt/decrypt sensitive properties

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#777]
Kill Bill system configuration happens through the use of system properties that are then made available to the rest of the system through an 2 interfaces:
* [KillbillConfigSource](https://github.com/killbill/killbill-platform/blob/killbill-platform-0.36.10/platform-api/src/main/java/org/killbill/billing/platform/api/KillbillConfigSource.java): Used by Kill Bill core
* [OSGIConfigProperties](https://github.com/killbill/killbill-platform/blob/killbill-platform-0.36.10/osgi-api/src/main/java/org/killbill/billing/osgi/api/OSGIConfigProperties.java): Used by Kill Bill OSGI plugins

These properties may contain sensitive info such as passwords, and it would be desirable to provide a way to have those properties encrypted and then automatically decrypted at runtime.

There are existing libraries such as [jasypt](http://www.jasypt.org/) that allow to do that.

The work would consist in providing a hook to integrate with such libraries so that such sensitive info can be passed encrypted.

**Comment by sbrossie** [comment]
Note that such properties are provided to the system in the [KillbillGuiceListener](https://github.com/killbill/killbill/blob/killbill-0.18.11/profiles/killbill/src/main/java/org/killbill/billing/server/listeners/KillbillGuiceListener.java#L112)

**Comment by pierre** [comment]
Jasypt has been integrated in 0.20.

**Comment by SquareMike** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉
