### ISSUE TITLE
Provide support for  custom health-check endpoint

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#778]
In many circumstances, users need to offer their own healthcheck endpoints. Both the form of the api  (`GET /mycompany/healhtcheck`) and the code should be customizable.

Also there may be a need for several healthcheck endpoints: `Dropwizard`
  offers a [mechanism](http://metrics.dropwizard.io/3.1.0/manual/healthchecks/) to register different healtchchecks. In our case, this could also even include plugins -- e.g a payment plugin could offer a healthcheck to verify that payment gateway is up.

**Comment by pierre** [comment]
Kill Bill already exports a [default healthcheck](https://github.com/killbill/killbill-platform/blob/master/server/src/main/java/org/killbill/billing/server/healthchecks/KillbillHealthcheck.java). Plugins can also export a [healthcheck service](https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/service/Healthcheck.java).

Work would be to expose these plugin healthchecks to the main Kill Bill healthcheck.

**Comment by pierre** [comment]
The main endpoint (`/1.0/healthcheck?pretty=true`) will now have a global section for plugins under `KillbillPluginsHealthcheck`. `healthy` will be `true` if all plugins are healthy. A detail section will be available for each plugin.

For example, if both Adyen and Analytics are healthy:

```
"org.killbill.billing.server.healthchecks.KillbillPluginsHealthcheck" : {
    "healthy" : true,
    "killbill-adyen" : {
      "message" : "https://pal-test.adyen.com/pal/servlet/Payment/v12 OK"
    },
    "killbill-analytics" : {
      "AnalyticsListener" : true,
      "JobsScheduler" : true
    }
}
```

If the Adyen plugin is unhealthy:

```
"org.killbill.billing.server.healthchecks.KillbillPluginsHealthcheck" : {
    "healthy" : false,
    "killbill-adyen" : {
      "message" : "null java.net.MalformedURLException"
    },
    "killbill-analytics" : {
      "AnalyticsListener" : true,
      "JobsScheduler" : true
    }
}
```
