### ISSUE TITLE
Catalog APIs review

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#784]
* Calling these APIs is difficult and error prone (https://github.com/killbill/killbill/issues/56#issuecomment-135749604, https://github.com/killbill/killbill-analytics-plugin/blob/6c55487b401135a2ec06ca16774f4a3ceac0a1bb/src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java#L381)
* Some APIs are missing dates for grand-fathering (https://github.com/killbill/killbill/blob/4320ce9106e78f9ce533c4d21d214bf77cc070c3/subscription/src/main/java/org/killbill/billing/subscription/alignment/PlanAligner.java#L204)

**Comment by sbrossie** [comment]
The issue has resurfaced recently on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/Changing$20Billing$20Alignment$20From$20Account$20to$20Bundle$2FSubscription%7Csort:date/killbilling-users/bWwQ_049pNw/VuEeLDoCAQAJ).

There are 2 use cases for when fetching catalog information:
1. Given a date, return a given catalog entity (e.g `Plan`). The date is used to find the active version of this catalog. Often the date is NOW, and we return latest version.
2. Given an existing subscription that was started in the past and a date, return the *effective* catalog entity (e.g `Plan` associated to this `Subscription` on that date).  This is based on a complicated logic between subscription startDate and potential `effectiveDateForExistingSubscriptions` catalog attribute

We have all the apis to return catalog entities based on date, use case `1.`, but we only have 4 apis for use case `2.`:
* Retrieve a `Plan` associated to a given subscription: [findPlan](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/Catalog.java#L94) and [createOrFindPlan](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/Catalog.java#L103)
* Retrieve a `PriceList` associated to a given subscription: [findPriceListForPlan](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/Catalog.java#L129)
* Retrieve a `PlanPhase` associated to a given subscription: [findPhase](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/catalog/api/Catalog.java#L140)

For use case `2.`, we are missing all the apis to return catalog alignment info -- as reported in the mailing list thread linked above.


There is a question of whether we want additional apis in `Catalog` or if instead we should only one one such api returning the `Plan`, and allow from `Plan` object to get *effective* the information (`PriceList`, `PlanPhase`, `BillingActionPolicy`, `PlanAlignmentCreate`, `PlanChangeResult`, `PlanAlignmentChange`)

**Comment by sbrossie** [comment]
Issue was again reported on the mailing list [here](https://groups.google.com/forum/#!searchin/killbilling-users/prem%7Csort:date/killbilling-users/OdxKlXDkE8U/s_zf4wF1AAAJ).

Reproducing the scenario, i get:

```
Caused by: org.killbill.billing.catalog.api.CatalogApiException: Could not find any product named 'simple'
	at org.killbill.billing.catalog.StandaloneCatalog.findCurrentProduct(StandaloneCatalog.java:227)
	at org.killbill.billing.catalog.StandaloneCatalogWithPriceOverride.findCurrentProduct(StandaloneCatalogWithPriceOverride.java:99)
	at org.killbill.billing.catalog.rules.DefaultCase.satisfiesCase(DefaultCase.java:68)
	at org.killbill.billing.catalog.rules.DefaultCasePhase.getResult(DefaultCasePhase.java:39)
	at org.killbill.billing.catalog.rules.DefaultCasePhase.getResult(DefaultCasePhase.java:48)
	at org.killbill.billing.catalog.rules.DefaultPlanRules.getBillingAlignment(DefaultPlanRules.java:122)
	at org.killbill.billing.catalog.StandaloneCatalog.billingAlignment(StandaloneCatalog.java:276)
	at org.killbill.billing.catalog.VersionedCatalog.billingAlignment(VersionedCatalog.java:399)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getDefaultBillCycleDayLocal(DefaultSubscriptionInternalApi.java:794)
	... 35 common frames omitted
```

**Comment by pierre** [comment]
Suggested work:

1. We should deprecate (unused):

```
Plan createOrFindPlan(PlanSpecifier spec,
                      PlanPhasePriceOverridesWithCallContext overrides,
                      DateTime requestedDate,
                      DateTime subscriptionStartDate) throws CatalogApiException

BillingActionPolicy planChangePolicy(PlanPhaseSpecifier from,
                                     PlanSpecifier to,
                                     DateTime requestedDate) throws CatalogApiException

boolean canCreatePlan(PlanSpecifier specifier, DateTime requestedDate) throws CatalogApiException;
```
2. For the following APIs, introduce a new `effectiveDate` parameter as suggested by https://github.com/killbill/killbill/commit/09df5ba6c5fbccd3860741adbfaf95f63724ee61 (testing work would be to verify grandfathering works as expected as described in the mailing-list posts above):

```
    public PlanChangeResult planChange(PlanPhaseSpecifier from,
                                       PlanSpecifier to, DateTime requestedDate) throws CatalogApiException;

    public BillingActionPolicy planCancelPolicy(PlanPhaseSpecifier planPhase, DateTime requestedDate) throws CatalogApiException;

    public PlanAlignmentCreate planCreateAlignment(PlanSpecifier specifier, DateTime requestedDate) throws CatalogApiException;

    public BillingAlignment billingAlignment(PlanPhaseSpecifier planPhase, DateTime requestedDate) throws CatalogApiException;

    public PlanAlignmentChange planChangeAlignment(PlanPhaseSpecifier from,
                                                   PlanSpecifier to, DateTime requestedDate) throws CatalogApiException;
```
