### ISSUE TITLE
Kill Bill server starts with 'bad' catalog

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#79]

**Comment by pierre** [comment]
The tricky part is that the `CatalogService` [won't be initialized](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/DefaultCatalogService.java#L68-L82) if a bad default one is specified. Maybe we should not re-throw the `ServiceException` and let the catalog cache load the the built-in default catalog later on?

**Comment by sbrossie** [comment]
Actually i think we should fix the bug and fail to start: The code already allows to not set the default catalog URI:
```
 // In multi-tenant mode, the property is not required
                if (config.getCatalogURI() != null && !config.getCatalogURI().isEmpty()) {
```
So, if this is set, it should be valid and working and if not we should fail to start.

**Comment by pierre** [comment]
> if not we should fail to start

Sounds good but do we want to fail to start the service or `System.exit(1)`?

**Comment by sbrossie** [comment]
Failing to start the service is not enough i would think (user might not realize it first). So unclear is `System.exit(1)` is the right implementation but yes i tempted to have something drastic.
