### ISSUE TITLE
Compile error(metrics-guice:jar:3.2.1 not found) with latest version(0.18.12)

### ISSUE THREAD

**Issue by cocia** [killbill/killbill#790]
Hi,
When compile killbill project, I got this error message:
[ERROR] Failed to execute goal on project killbill-jaxrs: Could not resolve dependencies for project org.kill-bill.billing:killbill-jaxrs:jar:0.18.12: Failure to find com.palominolabs.metrics:metrics-guice:jar:3.2.1 in https://repo.maven.apache.org/maven2

from https://mvnrepository.com/artifact/com.palominolabs.metrics/metrics-guice
there is only a 3.2.2 version but not 3.2.1

metrics-guice says only push 3.2.2 to Maven Central:
https://github.com/palominolabs/metrics-guice/issues/38

**Comment by pierre** [comment]
You need to setup Bintray as described in the [README](https://github.com/killbill/killbill/blob/master/README.md#build).

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead if you still have issues. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md for reporting issues.

**Comment by ruskotron** [comment]
I'm having this problem too … there's nothing in the linked README about Bintray …

I'm trying to build 0.20.10

Thanks :)

**Comment by pierre** [comment]
This in an old issue which has been fixed in latest master (0.22.x). 0.20.10 isn't publicly supported anymore.

**Comment by ivelasquez-rl** [comment]
Now this is not found anywhere.
