### ISSUE TITLE
Is there any validated Test case flow results for the default working of KillBill 

### ISSUE THREAD

**Issue by frostarun** [killbill/killbill#791]
Are there any test case Result list which you have done to test the flow of the default setup of killbill ? 

Because I need to again check all the scenarios which you have done already , It will be time consuming. If I know the test case results I would proceed based on that . Please provide those results.

**Comment by pierre** [comment]
Each Kill Bill submodule has extensive test coverage. The https://github.com/killbill/killbill-integration-tests repository also contains end-to-end scenarii.

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead if you still have questions. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.
