### ISSUE TITLE
Killbill.io seems to be down

### ISSUE THREAD

**Issue by theronic** [killbill/killbill#798]
[killbill.io](http://killbill.io) domain is still active, but site seems to be down. I see nameservers are set to Cloudflare, but registrar responds with noc.afilias-nst.info. Maybe due to non-payment?

**Comment by theronic** [comment]
http://docs.killbill.io is up, though.

**Comment by pierre** [comment]
The site is up but there are widespread [DNS issues](https://news.ycombinator.com/item?id=15293578).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.
