### ISSUE TITLE
 Tag Creation: User created tags should be all lower-case and this should be enforced at creation time

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#80]

**Comment by pierre** [comment]
We should probably throw an exception instead of converting the tags silently, to avoid confusing the user.

**Comment by maguero** [comment]
I'm working on this issue and I'm throwing a TagDefinitionApiException if the tag name is not in lowercase. Should I add a new entry in [ErrorCode] (https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/ErrorCode.java#L156-L159) for this new error message? It involves to modify the killbill-api and oss-parent versions in pom.xml file.

```Java
if (definitionName.matches(".*[A-Z].*")) {
    throw new TagDefinitionApiException(...);
}
```

**Comment by pierre** [comment]
Adding a new ErrorCode makes sense. Just submit a PR for killbill-api and we can take care of killbill-oss-parent.

**Comment by maguero** [comment]
killbill-api PR created: https://github.com/killbill/killbill-api/pull/4

**Comment by maguero** [comment]
killbill-api PR is merged. I'll create a killbill PR to fix this issue when oss-parent and killbill/pom.xml are pointing to killbill-api snapshot version.

**Comment by pierre** [comment]
Kill Bill has been updated to use the latest killbill-api.

**Comment by maguero** [comment]
Thank you!

PR is created: https://github.com/killbill/killbill/pull/410

**Comment by pierre** [comment]
https://github.com/killbill/killbill/pull/410 merged.
