### ISSUE TITLE
we're sorry, but something went wrong

### ISSUE THREAD

**Issue by yonathanhartoko21** [killbill/killbill#806]
I got this error right after i login. I tried to search similar issue in github. But it seems like, nothing solve my problem. Please help!

![image](https://user-images.githubusercontent.com/32639885/31338229-97e4810c-ad28-11e7-8ee5-5ed599b2b8b4.png)

**Comment by sbrossie** [comment]
@yonathanhartoko21  Have you read the [Contributing section](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md) ? Please use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for questions.
