### ISSUE TITLE
How create a one time invoice

### ISSUE THREAD

**Issue by wakashela** [killbill/killbill#808]
Hello killbill is a subscription based billing but i was thinking it might be able to create a one time on demand invoice, so how to achieve this any ideas.

**Comment by sbrossie** [comment]
Patrick,

There is a an api to add charges
<https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L492>
to an account -- creating a new invoice.

Stéphane

**Comment by wakashela** [comment]
Hello Stéphane 

Thank you very much for your promptly contribution i real appreciate.
It took me months and today you have unfold it to me, but i have learned something next time i will read read and re read the documentation.

Cheers.

**Comment by sbrossie** [comment]
@wakashela In the future, please use the [public mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for questions.
