### ISSUE TITLE
demo.killbill.io - We're sorry, but something went wrong

### ISSUE THREAD

**Issue by x011** [killbill/killbill#811]
I cannot login on http://demo.killbill.io using  `demo_ro` / `demo_ro` as stated in http://killbill.io/demo/

Error msg:

`We're sorry, but something went wrong.`

**Comment by pierre** [comment]
The demo is back up (we had a maintenance on our server).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.
