### ISSUE TITLE
oss parent dependency

### ISSUE THREAD

**Issue by anmolsurmountsoft** [killbill/killbill#826]
Hello,i am very new to java and maven thing i am trying deploy killbill and in kill bill directory when i run mvn clean install i get error that mvn couldn't fetch  
`Failed to execute goal on project killbill-internal-api: Could not resolve dependencies for project org.kill-bill.billing:killbill-internal-api:jar:0.18.15-SNAPSHOT: Failed to collect dependencies at org.kill-bill.commons:killbill-clock:jar:0.20.13: Failed to read artifact descriptor for org.kill-bill.commons:killbill-clock:jar:0.20.13: Could not find artifact org.kill-bill.billing:killbill-oss-parent:pom:0.140.43 in central (https://repo.maven.apache.org/maven2)`

https://maven2repo.com/org.kill-bill.billing/killbill-oss-parent and this link of maven seems to be dead.
Am i wrong here ?please help me out

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.
