### ISSUE TITLE
Relax sanity checks for STANDALONE subscriptions

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#840]
https://github.com/killbill/killbill/blob/27fde0808eabca2801b9b3fed6a9cf4b3b58f7cf/entitlement/src/main/java/org/killbill/billing/entitlement/engine/core/DefaultEventsStream.java#L114 throws an NPE when trying to create the subscription.

**Comment by Ramblurr** [comment]
This is unfortunately blocking our killbill evaluation.. is there any workaround? Or is the fix straightforward enough that perhaps I could submit a PR?

**Comment by pierre** [comment]
The fix is indeed straightforward (remove the `baseSubscription` `null` check) but we also need to:

* Add a regression test to catch this moving forward (i.e. ensure `DefaultEventsStream` builds fine for `STANDALONE` subscriptions).
* Add a test to verify that we are not missing a `null` check in `getPendingEntitlementCancellationEvents` for `STANDALONE` subscriptions (i.e. try the `uncancelEntitlement` API on a `STANDALONE` subscription).

If you would like to contribute, [TestDefaultEntitlement](https://github.com/killbill/killbill/blob/27fde0808eabca2801b9b3fed6a9cf4b3b58f7cf/entitlement/src/test/java/org/killbill/billing/entitlement/api/TestDefaultEntitlement.java) is probably a good starting point (lots of test examples).
