### ISSUE TITLE
Cancelling subscription with default EOT catalog policy leads to IMM cancellation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#861]
The issue was reported on the [mailing list](https://groups.google.com/forum/#!topic/killbilling-users/1s_8hDdlVQ8)

**Comment by lghamie** [comment]
Could you reproduce it?

**Comment by sbrossie** [comment]
@lghamie I tried from KAUI but realized the flag `useRequestedDateForBilling` is being passed, so this invalidates the test. This is why i asked you for exact curl you used.

**Comment by sbrossie** [comment]
@lghamie Do you have more info for us to reproduce exact scenario or we should close it?

**Comment by lghamie** [comment]
Hi @sbrossie , I think I have provided everything in the mailing lists.
