### ISSUE TITLE
Failed to execute goal on project killbill-util

### ISSUE THREAD

**Issue by saydulk** [killbill/killbill#872]
Please help me to resolve this problem 

![screenshot from 2018-02-17 15 00 21](https://user-images.githubusercontent.com/1058663/36339583-4e47c5cc-13f3-11e8-9a9e-0969069143ab.png)

**Comment by iwxfer** [comment]
The problem is that `org.testng:testng:jar:6.12` is missing in the maven repo
![tmp](https://user-images.githubusercontent.com/642371/37057571-d2e53976-2155-11e8-87c7-791be7c48308.png)

**Comment by sbrossie** [comment]
Please use [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for questions.
