### ISSUE TITLE
Need invoice Enhancement in killbill 

### ISSUE THREAD

**Issue by kannanchinnakannu94** [killbill/killbill#874]
Hi 
Need a Payment status for Each Invoice and Amount Paid per invoice and Invoice list sorting based on date and amount and other parameters . Due amount of the invoice if payment failed . We are facing Problems to understanding the invoice the above fields are help to understand the invoice clearly

**Comment by sbrossie** [comment]
@kannanchinnakannu94  Please use the public [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) and stop open GH issues.
