### ISSUE TITLE
Question: Volume billing per usage

### ISSUE THREAD

**Issue by robvanpamel** [killbill/killbill#882]
I'm wondering if it would be possible to add a billing with a specific calculation as well.

We have a billing which is divided into 3 tiers 
* the first 500 units are billed at 3% 
* the seconds 1000 units at 2% 
* the rest at 1%

For those 3 tiers we could add 3 different units each with a different price (based upon https://github.com/killbill/killbill/blob/killbill-0.19.0/catalog/src/test/resources/UsageExperimental.xml#L250 )

However the major problem I'm encountering, is that we don't have a fixed price, but it is a variable price. For each account a different price, per subscription period, can be used. 

For example 
* In March the price will be 1%,2% 3% of 15$ for account A
* In March the price will be 1%,2% 3% of 17$ for account B
* In April the price will be 1%,2% 3% of 19$  for account A
* In April the price will be 1%,2% 3% of 20$  for account B

Those pricings are not available up-front so i'm stuck over here. Could you help me out ? 

Kind regards,
  Rob

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
