### ISSUE TITLE
Add missing creditId in CreditJson

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#899]
Test to re-enable: https://github.com/killbill/killbill-integration-tests/pull/18#discussion_r174481356

**Comment by sbrossie** [comment]
@pierre I could fix this in `work-for-release-0.19.x-doc` ?

**Comment by sbrossie** [comment]
Fix has been committed into `work-for-release-0.19.x-doc`

**Comment by pierre** [comment]
Re-opening for the test to be re-enabled (see top comment).

**Comment by wwjfrodriguez** [comment]
@pierre @sbrossie  the `test_find_credit_by_id` was success.

**Comment by pierre** [comment]
Thanks @wwjfrodriguez!
