### ISSUE TITLE
Ordering of arguments in our JAXRS endpoint matters

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#914]
In our attempt to auto-generate client libraries from swagger schema, it becomes important to correctly order arguments on the JAXRS resource api definition. For example `Account#getTags` has the following definition:

```
    public Response getTags(@PathParam(ID_PARAM_NAME) final UUID accountId,
                            @QueryParam(QUERY_AUDIT) @DefaultValue("NONE") final AuditMode auditMode,
                            @QueryParam(QUERY_INCLUDED_DELETED) @DefaultValue("false") final Boolean includedDeleted,
                            @javax.ws.rs.core.Context final HttpServletRequest request) throws TagDefinitionApiException {
        return super.getTags(accountId, accountId, auditMode, includedDeleted, context.createTenantContextWithAccountId(accountId, request));
    }
```

Code generation would lead to:

```
    public Tags getTags(final UUID accountId, final AuditLevel audit, final Boolean includedDeleted,  final RequestOptions inputOptions) throws KillBillClientException {
```

For consistency, we would like to swap the `includedDeleted` param and the `audit`, to end up with:

```
    public Tags getTags(final UUID accountId, final Boolean includedDeleted,  final AuditLevel audit,  final RequestOptions inputOptions) throws KillBillClientException {
```

**Comment by sbrossie** [comment]
Note: This should not impact existing client and user of the api -- since query params can be passed in arbitrary orders.

**Comment by sbrossie** [comment]
I started to reorder things so our client code generation methods look  consistent

The current scheme is to have the following -- of course when such argument s are applicable.

* `PathParam` in the order specified
* `body`(comes right after PathParam`)
* ....
* `controlPluginName`
* `pluginProperty`
* `audit` 
* `Context`

Of course if would be nice to one step further and have some ordering consistency in various query params across endpoints.

**Comment by pierre** [comment]
Agreed - maybe inside the Swagger codegen repository?

**Comment by sbrossie** [comment]
See [SCHEMA_RULES](https://github.com/killbill/killbill-swagger-coden/blob/master/SCHEMA_RULES.md)
