### ISSUE TITLE
CustomField and Tags apis are problematic 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#916]
`CustomField` and `Tag` apis are relying on passing  a string as a query parameter to identify the list of tags of custom fields. For instance for `Account` -- but all resources have the same pattern:

* `Account#getCustomFields` : OK
* `Account#createCustomFields` : OK
* `Account#modifyCustomFields` : OK
* `Account#deleteCustomFields` : Takes a query param `customFieldList` to indicate a list of custom fields; shouldn't we instead send a body, or at the very list, a list of fields instead of a String ?

* `Account#createTags` : Takes a query param tagList; shouldn't we instead send a body, or at the very list, a list of fields instead of a String ?
* `Account#deleteTags` :  Same remark

Note that passing a String as a query param to send a list of Ids breaks auto-generated clients -- pushed the responsibility on  the client to understand this String is actually a list of comma separated value.

**Comment by sbrossie** [comment]
Proposal:   Change server definition to have a `List` -- both for `POST` and `DELETE`, so for instance we would get:

`@QueryParam(QUERY_TAGS) final List<String> tagList` instead of `@QueryParam(QUERY_TAGS) final String tagList`. Also rename `QUERY_TAGS` (`tagList`) with `QUERY_TAG` (`tag`).

**Comment by sbrossie** [comment]
@pierre Made the code change we discussed above. However i realized that the create call for custom filed and tags is different. Custom fields are passed using a body and tags using query params. Should we change the way we pass tags to also use a body -- although tags are simpler to pass since they are just Strings?

**Comment by pierre** [comment]
> Custom fields are passed using a body and tags using query params. Should we change the way we pass tags to also use a body -- although tags are simpler to pass since they are just Strings?

Might as well, it would be more consistent. Also, it would be aligned with the idea of not requiring query parameters.
