### ISSUE TITLE
Create unique name for endpoints

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#931]
Client code generation relies on method name in our resources and some have non unique names. For instance `getPayments` is defined 3 times:

* `Account#getPayments`
* `InvoiceApi#getPayments`
* `PaymentApi#getPayments`

The following have duplicates:
- "getPayments" is defined 3 times 
- "createTags" is defined 8 times 
- "deleteCustomFields" is defined 9 times 
- "modifyCustomFields" is defined 9 times 
- "deleteTags" is defined 8 times 
- "getPaymentMethods" is defined 2 times 
- "getInvoices" is defined 2 times 
- "createCustomFields" is defined 9 times 
- "getTags" is defined 9 times 
- "getCustomFields" is defined 10 times

**Comment by sbrossie** [comment]
Note that current model for client swagger generation is to have one [api per resource](https://github.com/killbill/killbill-client-java/tree/swagger-gen/src/main/java/org/killbill/billing/client/api/gen) and so as such, this this not really a problem. But of course any attempt to create on large api file across resources would require some logic in the code generation.

**Comment by fieryorc** [comment]
Agreed. By disabling validation, go-swagger was able to generate the models. However, I had to turn off validation completely which is annoying.

**Comment by sbrossie** [comment]
The [swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) states that `The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.`
