### ISSUE TITLE
Swagger: delete API return schema missing

### ISSUE THREAD

**Issue by fieryorc** [killbill/killbill#941]
Swagger specification for delete APIs need improvement. 

Delete APIs return 200 upon success and return empty object. But in swagger, they are not specified resulting in client generating getting confused. It would be nice to add empty object type and return for delete APIs. (Similar example is protobuf has built-in type google.protobuf.Empty).

Something like this:
```
"delete": {
        "tags": [
          "Account"
        ],
        "summary": "Remove tags from account",
        "description": "",
"responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Empty"
            }
          },
          "400": {
            "description": "Invalid account id supplied or account does not have a default payment method (AUTO_PAY_OFF tag only)"
          }
        },
```

**Comment by sbrossie** [comment]
Maybe we could improve our swagger definition, but i also think this behavior is specific to your client generator: I generated a a full java client and did not see such issues -- e.g [deleteAccountTag](https://github.com/killbill/killbill-client-java/blob/work-for-release-0.19.x-doc/src/main/java/org/killbill/billing/client/api/gen/AccountApi.java#L272)


@fieryorc  Are you saying any api that does not return a result should instead return an empty result ?

**Comment by fieryorc** [comment]
That would be ideal. It seems the go client generator follows the swagger spec strictly. I looked up at the spec, and it does specify that response is must. 

> The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responsesObject

**Comment by sbrossie** [comment]
@fieryorc I 'll work on adding successful response code on all resources. If empty response is not mandatory i'd rather avoid it then.

**Comment by fieryorc** [comment]
Sounds good. I verified that generator has no issue with missing schema. The original reason I added EmptyJson was, the java framework was ignoring response code unless response object is set. I am guessing you will know how to fix them.
