### ISSUE TITLE
Invoice apis (id and invoice number) share same path

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#954]
Both [this api](https://github.com/killbill/killbill/blob/killbill-0.19.10/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L173) and this [api](https://github.com/killbill/killbill/blob/killbill-0.19.10/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L197) share same JAXRS `Path`. This seems to work as the pattern is different and Jersey is smart enough to route to correct endpoint. However from a swagger point of view this seems to break and only one of the 2 api gets documented (and for client code generation this is an issue).

**Comment by pierre** [comment]
Maybe `/1.0/kb/invoices/byNumber/<1234>` to be more explicit?
