### ISSUE TITLE
api.html missing information for /1.0/kb/invoices/{invoiceId}/payments

### ISSUE THREAD

**Issue by Inkata** [killbill/killbill#966]
The HTML does not allow for the invoiceId field to be populated.

POSTing vía cURL does work correctly. 

Setup:

KB installed vía KPM. /1.0/kb/nodesInfo replies with 

`
{

 [..]
  "kbVersion": "0.18.19",
 [..]

`

**Comment by sbrossie** [comment]
@Inkata Please report issues on the [mailing list](killbilling-users@googlegroups.com) instead of logging GK issues.
