### ISSUE TITLE
'CatalogSchema.xsd' is nowhere to be found

### ISSUE THREAD

**Issue by unserializable** [killbill/killbill#987]
The KillBill catalogs are defined with opening
```xml
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="CatalogSchema.xsd">
...
</catalog>
```

However, the ```CatalogSchema.xsd``` does not appear to be present nowhere (intuitive) in KillBill project(s). It should be simply accessible for verification and IDE support.

For the record, I did NOT encounter `CatalogSchema.xsd` in: 

```
killbill
killbill-admin-ui
killbill-admin-ui-standalone
killbill-api
killbill-catalog-plugin-test
killbill-client-java
killbill-cloud
killbill-commons
killbill-docs
killbill-java-parser
killbill-platform
killbill-plugin-api
killbill-plugin-framework-java
```

**Comment by unserializable** [comment]
Also for the record, I have now found a reference to the tool for generating the schema from `killbill-docs` subscription guide section. It says the following:

```
# Download the tool from maven central:
curl -L -O 'http://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-catalog/x.y.z/killbill-catalog-x.y.z-xsd-tool.jar'
# Run the command
java -jar killbill-catalog-*-xsd-tool.jar schema.xsd
```

Is there any good reason for this schema `.xsd` generation via tool, instead of just including corresponding version of it in the artifact '.jar' (e.g. `killbill-catalog`)? If there is, it probably could use some documentation, to understand benefits of the approach.

 Even if there are benefits, I suspect it might be better to include the latest 'default' schema in artifact '.jar' -- quick start guide makes more sense with schema present already in the system. Note that the reference for schema generation tool really comes late in documentation, long after catalog samples have been presented & discussed.

**Comment by ruskotron** [comment]
I think this might be what you're looking for http://docs.killbill.io/latest/catalog.xsd

**Comment by bvisonl** [comment]
@unserializable did you ever find the CustomField.xsd? I want to modify the schema but I am unable to, it always uses the catalog.xsd
